#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
imgGCSBlack32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbDQ0sEAKnUgAABs5JREFUWMPll11sFNcV"
    "x393dta7ptiOzayNnV1jQ3CdNgEbYwguX0rjKBUPEKAfFqiVS5pSVIUofWlQMDKkRfQRpUhO"
    "X4hUV4VWFAERSmmiBKEiaFwDNWCK7XiNIxw2+GvXnt2dmXv7sLuTNRjVTvrWka7+c0Yzc//3"
    "nP8951z4f7/ETF/87r59B4CKrzjf0T+1tr6f/UCf6ZdKqcqjLS3bHMdBAVIpd2RslX2f+iiF"
    "QDKZ5PXDh8XWlhb+vH+/S0KbBQGk45BMJkkmEi4mEgnipkncNDEnJ5mcmGByYoKJWIxYLEYs"
    "GiUajTI4OMjx1tZtSqnmLXv3Nn4ZApoQgszQAE3T8AiBpmlo2Zge7vtALBYjCbTv379NKdW8"
    "+Y03GmdHQEpXNF+GxMjICEkgCRw9cKBJSdn84p49jbPRgMhMjlIgUvrVlAJNAykfxvQl0xr4"
    "bVub+2xFeXnTO2fOGDMmIKVMrVoIJHCho4OSQIChe/coNgwXP4tEWL506UMkGhoacBwH27Zx"
    "HAdd1/njuXP27D0AaEKwpq4OpRRPhEIuSmBhKISj1LSeEB4PHk1DKcXcvDzKFy0an40HBFkh"
    "GPz0U67evIlpmvj8fpY9/TQlgYA76eXOToaHh3nu2WcfCkdGS1JKMSsRZhQduX+fdz/4gEnT"
    "pKK8nPvDw1y4dAkpJROxGB9euMC/e3oYHR9/pDARAiXloxPR1q1bVwFL0ua1mJSuCG/39QGw"
    "duVKcv1+AvPmoWkaUinuDw+DEBQbBsOjo2iPEGbGA1MIbNq0qUEIsVQpdcpxnJpjx44dsSyL"
    "7du371Lx+OC5997j8VAIy3EAyPF66envp7OrC9txePGFF1hYUUHlggWcO38eRkfxCDHt7tCE"
    "mBqCDRs2fKuqqup7bW1tRwoLC39kWZb2+ecRxsZGsSxLe8y2q1bW1/NJby+OaabccuMGlcEg"
    "VQsXppcl3DzhZrpH5AmRCqvmesC27WW7du3aHQ738+abB37V2XmlR8pUJt+5c+er1dXVT4TD"
    "/dTV1nL5449Z8uSTXL91i+6+PrxeL9+sqqKooMAVqchOtdPkCZH2gEt13bp1QcMwftzSsrdV"
    "KUV+fj66rmfIMT4+jhCCrhs3Wb12LYZhYDsOlmXhy8lBpevFWDyeKkrpQuTep4ff50NKiT83"
    "lx+89tpfPADPPPPMOinl89Fo1AoGg4uCwWBRR0dH986dPzve3v6Hf1RWVuaVlpYat2/fJp5I"
    "0t/Xx/DYGI7XS3d/PwnH4XpvLwnbpjccBqA3HEYAfWk7g0UFBSAEuq5z/OzZW3q6VK58++22"
    "Q9FoFL/fj5SKgwcPnezq6nod4ODBQwfb23//y7KyMuLxOHl5efzzylVq6+sJFBWhgPmGgVKK"
    "+YHAFCwJBFCQQqXcXZERoQ6QSCQ88XgC23ZwHIkQOh6PbmXC4/HolhA6jiOxbYd4PEE8kaC7"
    "t5f8/Hzu3rtHiWEwFIlQYhjT2+m03VBbC2khSsdJaWDx4sWNSqmVALt3v7pj9er1FXfuDF1p"
    "bd1zAmDfvl9vDoXm11y92sH4+BgK+MZTT7G0vh6plNsvuE1IdvyzdQDM9flQSpHj8/Gdl18+"
    "7YowFApVBALFP3/rrbZfmKZJMFhJQcE8AMbG7jM4+Am5ubn8/eJ5tmzZzKhl4dF17qZXOfQA"
    "ZnshU6xKDINF6dqRk5PD8y+9dMYlUFxcvP/kyb/ujUTuUVhYxLVrneEVK1YtALh8+WJ4yZLa"
    "BSMjwwQCxXz40Vl++sorbuuVWeFMPDHX50MBXq+X55qb3/VkCOTk5Phv3rzO5s1NS5qbv3/4"
    "9OkTHU1NzWukhB07mo58dPmi54dNzaG/vX+aurplaHPmcDscRghBz8AACEFPxs7shIEBgC/s"
    "cJjy0tKUrnSdoydO9LiJaGRk5OzFixfE+vV1d2zb/p2u6z8pLDSwbQvLsjRZ9FjvqVPtDatW"
    "raKxsZER0/xC+YYxZSdUBYMpDIUgYwNVoVCqaZ2mFujAPNM0w8BnQKGUsrumpuI36VLcnYzH"
    "12zcuBGv18vQ0BD/GhggWFrK3UiE+YYxBdfW1KQ6JqVQ6bTrdlFKoaXzn3QcNxVLYAJQmVbd"
    "sqy7wDl3K/p8zaWlpWgeD1+bM4dvL1+OpmlUp1eXwa+nMXvCR5GwbVtkE4ilx7SXo2lOWVlZ"
    "SmhZPb/IniRrggfxIRKAaZr6jBuS+OSkZ8pxKvPDTJf8QDWcDslq00X6nzMmkIjH9YfOdF+R"
    "RCIe12fcEyYTCc+0B8tMbX/gmXogVFNyBCA0jWQi4flvBBYA84HHE2NjEX919aX/5clYmWbk"
    "Pwp4zZM5V2+pAAAAAElFTkSuQmCC")
getimgGCSBlack32x32Data = imgGCSBlack32x32.GetData
getimgGCSBlack32x32Image = imgGCSBlack32x32.GetImage
getimgGCSBlack32x32Bitmap = imgGCSBlack32x32.GetBitmap

