#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

imgGCSG0CogBlack = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QITCQknIQE77QAAAS5JREFUWMPtVrsRwjAM"
    "faalgJIxMkLYxBs6I6SDhgsrQENpjgVMEzjjKJY/yqXh3bmxfdLLk/UigIcrXAOAPQTg1ibh"
    "1ibh1iYRBislXEyCIjC3hyWUkFKgmERMASSoU01CWoEfEioxoA817qnIWSquCvLIIYBN5Ex7"
    "culEmavQBImGoF4+sUbQ2L7J7bhhARjiognuNDNBkeAXEwK6wF61tLPajOSWCQzCL0gC/iPs"
    "g4sdgOO4uuCsJ4Iqb/ltyUIHD+5T7xCGMBI9U/NYW05KQElMvfI20nqOSZhUghoo5uvd0iWY"
    "4Hx/7k43u83pAkOQaMdyGIYg5wOcN4i0YZUP1BrR5Osuj9chxwlrrVjECWt+RqlTUdaAowV8"
    "n1VgiYEka2ApGclEscHK+BN4AzpihyilXivdAAAAAElFTkSuQmCC")
getimgGCSBlackData = imgGCSBlack.GetData
getimgGCSBlackImage = imgGCSBlack.GetImage
getimgGCSBlackBitmap = imgGCSBlack.GetBitmap

