#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
imgPlay = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJCTaOBTPwAAAA2klEQVQoz33Rv0oDQRDH8e+G"
    "80+TxlJSKUj6rW1TBZ/Ah7gXEbdNv5BGsMgjBAKC14QkCGIpguAl3e3EMWtxFsde4jS/5sMP"
    "ZsZE/p+sjnvMiKl6RRCEuxT8gMUCPm3o1KEoQ6t5vD0ABGHDjd22SANULPeQBvim4olBQv5A"
    "IFDyTsmMayt5a80AVHSASyaFcXtBJKPHY2HciW+BLQDnPBTGHfmP9iUFOGZcGLfxL3w2gKl/"
    "ccXFM6zdm/8CIKYNr6fdlcyXC/oEAmskaTAZZ2TsUBQlRE3A4fkFDI1aCaBdI4gAAAAASUVO"
    "RK5CYII=")
getimgPlayColorData = imgPlayColor.GetData
getimgPlayColorImage = imgPlayColor.GetImage
getimgPlayColorBitmap = imgPlayColor.GetBitmap

#----------------------------------------------------------------------
imgStep = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJFwCV/pm2AAABG0lEQVQoz33Ov0oDQRDH8e/o"
    "JQQL8QEUhICN5ZIHsLGQ4BOktz2fxGtTWXiFkCKlYCtWcoVoAhZWQRDz18Lc7mYva5HLJWky"
    "xRS/+TAz4tleAcAN0uTJxQ6hDEgTReKvrpcgA4UCYs0ugDpXj/mGHQCHo65c6BswxeFIcbgV"
    "MBgG1JUNfUNjMCz6BjB0uFQ29I10AwQLABlz3rhQ7dAjfOXjHGjA8MMfPc7UQwgOvf6kRjNk"
    "inBKOzGRJkPnpABzAk5oJSaysc6z4oQFhGPuE4lKcQoIdv0HA+xxl0g0iQdUWWYFeKbGbTKO"
    "PuMh8E0NsLyswOiw37Wv7x2qjMlGB/2PFpPu6IgeiAdknxJlwJDiqVBBmDHzvznYVv8FwISP"
    "Lb8SGwAAAABJRU5ErkJggg==")
getimgStepData = imgStep.GetData
getimgStepImage = imgStep.GetImage
getimgStepBitmap = imgStep.GetBitmap

#----------------------------------------------------------------------
imgStop = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJGge+NHJYAAAAsklEQVQoz6XRMU7DUBCE4e/F"
    "oQAhKm7iS3ATak5CTckpkLhDOrgCJcIKSvxsy0sRR8mzJSjYcvef0exuCr/X6o+5NY/Sk3ox"
    "2cT9wwEYqO/qfurHpHs9OXTYawr5te4EtGhtQS8bjG61JdBpfdvKjludATvsfeiRJDDYlQ6N"
    "UXWWIeYOo4siZJo7RKGfZchYuRLG6Q6B7PMIvFT12/PikF/vm7WBFFLlxuWCyJo4AP/85g/B"
    "20B5o42C/AAAAABJRU5ErkJggg==")
getimgStopData = imgStop.GetData
getimgStopImage = imgStop.GetImage
getimgStopBitmap = imgStop.GetBitmap

#----------------------------------------------------------------------
imgBreak = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMCBqjDay5AAABDklEQVQoz6WRr07DYBTFf+1G"
    "m5AiNtGEYCo2BAIB9QuW8AxD8CJ9EQSTOARYMj8aDAgGSRUZDenYaNZ+XdeLYCmfAsG98pzc"
    "e/4Ywu9j/oHTBOgAPY8+Pi4xIwbDCJ4BMATo0Duyg86u27KsonibvjypYHirEc486+LwoOGs"
    "1l+L9D5cnp5HtQbpe93MmZGSkjKncHa60tc0iL/Z/gSWKHJKVmy1xdcJrliKBTnfpg2Wlrg6"
    "IZ4XM7vCwFibKwuJtRxklCQm+qpERnpQg2RM2qjhKs3GDDTCVZQF7+FiIsoUUdnkI8yDy4if"
    "HI432G7u2yfmHi2m1aO6Lh94vclrkVTMyrsy1CrIKLUL/2rzC/+ddkCtau6CAAAAAElFTkSu"
    "QmCC")
getimgBreakData = imgBreak.GetData
getimgBreakImage = imgBreak.GetImage
getimgBreakBitmap = imgBreak.GetBitmap

#----------------------------------------------------------------------
imgMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJAP4nK08AAABKUlEQVQoz13Rz0sCQRTA8e+u"
    "C4lll0js0E3skD+wvHbw2N8g9I907h/pliIs+B8YgQgGebVYwUWDTJbVWTOcmQ5ugvMu83jv"
    "w7wZnqUBuIIT7iiT5Ic3Hvl+ZRtOfJ7xcFO8vjhIrxf9y+ci90y3DTsG9VqlVA3TX4TpUrVW"
    "oR7Xd6BcyAk8XvAQFHKU2R+hk1ZK8c4vEedYKZ00blDLIJBkWJNBEgRqaYJub+SQ55Y8Dr2R"
    "6hpAtwa+CCUSiQgHvm6ZYKbcztBB4tAZKlfPDLBBNrzxZC6ZzL2xbGww34ASqtkfW/THqqmE"
    "MoFGo9u+2OAL3dZEJvggQi10QqITahExMQFMWaFtibZX/2vYAzZHnxnQwGeW490Sd4nNIaeR"
    "+0TkkmXGmvgjf7x4ikuV35bbAAAAAElFTkSuQmCC")
getimgMapPinData = imgMapPin.GetData
getimgMapPinImage = imgMapPin.GetImage
getimgMapPinBitmap = imgMapPin.GetBitmap

#----------------------------------------------------------------------
imgGotoMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJC/KRMHfAAABaElEQVQoz12RvUsCcRzGP5dH"
    "ilhBgWQUKEQthtTNDkIEQUE1W3PQ4hg0twRBa2sFQS9g9B8UhQinVDRUloKHNpRIeldX/e7X"
    "0Ate3/F5PjwPfB8F1432sEAMH29csJV/BsVlh1iNj2jD3g67od+cXrGSr3pagdBiYiI6Znot"
    "bG9/X0Ap8Xje5mqIRQdNipxRxCQ6SAzUVl/6FL9DgXcsBlD80geuBKdZrwuC2AQR1OtO8z+Q"
    "yZZUhphkCJVsycn8A+ThpWG+CAQC8+XSkIctwPrmevL6yUmf3KkIVE7unPT1Uwtga3ZqNSn2"
    "iuVKTVCpFctiD0Bd3lQ0gAbz2nZqjoN9PTLerZed/YIJoDa1Re2ZD6DClLabkglj6RPDVI6/"
    "k9WmvvZTMq1t6W0b942IRyA9Dw33SszkZvX4AkA4uyzD2V/975PGhXOa2yGAHyRALxYWn39j"
    "VY6qeTx0EWyXt51W2qwieEV8Ab3lml4I+uMeAAAAAElFTkSuQmCC")
getimgGotoMapPinData = imgGotoMapPin.GetData
getimgGotoMapPinImage = imgGotoMapPin.GetImage
getimgGotoMapPinBitmap = imgGotoMapPin.GetBitmap

#----------------------------------------------------------------------
imgMachine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsKGSg8jqKbAAABp0lEQVQoz32RPWhTUQCFv/ty"
    "i+FBIKAQLTEN+AaRohlctIOgiyLRrUKJFOrPUKxLwZ+hdPSHLkbJogWpZurQoEgEURDBLFkU"
    "sYKN7UscLJa2NHlp9L57r8NDR89wpjOc8x1h+b8knMahD4GleYSDwMdMTWBRGF4go9zyUXHI"
    "PhO5yyXN7PhyU5yxH9LvARwAfyg1XCi5o9rpsI123NFCKTXsDwEIy0m+TxSKbZI0l/Z60Fra"
    "4wUkeHo1ff8lDmyhFuanJW36PYul3+shmZ9WC1tRydVjHN4MWo2Bfd++VN/AqePp/X5jM+Dc"
    "ap23wjJw7fydHn3s4NHtHzdh962LN36hiPPkun9XQhhTGAzgqMjBYFCEMZAQ1h9PwYkLXvZs"
    "/rmCfN7QWnk9C9RBQvxV+2viSiYbkMpN5GCbDTLZeLL9ILECDvQIx0YmO0gW/XXWWfQlHUYm"
    "w7FeBEqha5VykrlipWwwVMpzxSSVsq6paOYGstoQMy39MHbJxaCdtXszXfPOVrsRSSHZyS7i"
    "EBsUB8B+1p+A3/xkzYbCIhxc3L+3/ZMmoGvNH8TKrfqjhKcGAAAAAElFTkSuQmCC")
getimgMachineData = imgMachine.GetData
getimgMachineImage = imgMachine.GetImage
getimgMachineBitmap = imgMachine.GetBitmap

#----------------------------------------------------------------------
imgAbort = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMBh9N5HW4AAABdElEQVQoz32Rv0tbURzFP/e+"
    "++J7FhyeBTU0pWCW4CJ0U4xrl7dkFRw6VenSFAqFDqmgo/4nWd7iWoOunSRLMrQBK9qmVXm5"
    "eb/y7ZAgdOk54/lwhnOU8H8ZWEWh2CrTYIPnwHcuaHeuBKGPElZR1MNS80V1OZj3hNH4evit"
    "lx6fRY9APXzSellz/GJW65DZr924dRb10VAvl5rrtcTfxc68S+qv1dxmvQwaaDyrjvw3wD4W"
    "yz6wR+IvVWmABtlcCB74AKS8ZocrrtmjTxHI5hSoKK/A4y0D/pCiOEAzIfGkAgYgxxIDGgcX"
    "gwZgAkwbBvfjGHg/ix0O0WjysQymwPnwl+EdDi6HfMbB4QhFMpTzKdC+62t7gssRLi6fgI+I"
    "TXrSBiVU2A6dVlArfDMbKgd71y1aX6IBSlDMEYal5nzVD4wH+dgOR730OIoSBCW8Mizy1F12"
    "t8yaWgH5kV9mneyGW36e5gaYECPZ76z7z88FMRP4CxsClib1AuxPAAAAAElFTkSuQmCC")
getimgAbortData = imgAbort.GetData
getimgAbortImage = imgAbort.GetImage
getimgAbortBitmap = imgAbort.GetBitmap

#----------------------------------------------------------------------
imgMove = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsLAhXMEk8nAAABbUlEQVQoz1WRv0pcQRyFv7l3"
    "diNmQbOYOqBYWM8KxsI/KWQgkLD4DhHyAjZbzisEub6AhcKiEBkQFCy2umMeQG6RMiiKG4l4"
    "//0sVhdzqsPhK87hqI9EaCwKTWxx9CpfInhKagboJZo0AcBW7pM5dYCHFXJyIOJFtnRr5p41"
    "UzrsOH0B7si6GUl4QxIysu7dGNAAYnW3tXUPaQHQaaET6eOfAbGFg5hJ/lEAk8QUBiPgQYst"
    "3GfzM5BGNPZvjhtTUVpRsW7OnIBX39Mv5pZpSoYU28Pk7aocCsI1s5yHHx2d9/bdpjkIAFwt"
    "LwzmCAAdcxJUD7T4gj0HcQeqVEweRm4QVK/hRyV9Dt0SRYTwSI2gA/3maMUvZpj2pa8TZSqg"
    "gFSCbGn+cA3oC+A987T7Yr6aB6w5Cqp/wyVX/Kc2i3Yj3ZGNdNG2x6mgiGnxjik0zJkP337v"
    "ZgEoGXLLX6kUEU0mmHh1G0DNIw/kUj8B2jqZwW6x6egAAAAASUVORK5CYII=")
getimgMoveData = imgMove.GetData
getimgMoveImage = imgMove.GetImage
getimgMoveBitmap = imgMove.GetBitmap

#----------------------------------------------------------------------
imgSave = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMBDTTbu56AAAAwUlEQVQoz32RsQ3CMBBF39mO"
    "oAkJC7AAYgcqekRBRc0MNCBmocoKTEFDxwwgFIoIJTFFTIA44aSTTv5fT993YvlfIiR7xuHR"
    "l9IZ5+XOAJNoPlj4BsVdgaLq9lJgAGWBZhbBgiNoX3YvuiLoTsLbADmmYch/CY/2kB/Cs0Xt"
    "1QYDMKxTCDc0BZViAFOFvAJxvRbB1oZAEEq0+0uJAAIQgLLYbXopM+9IgA0tkoyImbKRw9eS"
    "Vm44sZYkoo/uuEVB9gKxpS8I36iG/wAAAABJRU5ErkJggg==")
getimgSaveData = imgSave.GetData
getimgSaveImage = imgSave.GetImage
getimgSaveBitmap = imgSave.GetBitmap

