#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
imgPlay = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAXhJREFUeNpi/P//PwMlgAWZ4zDvJQMjI+NMIPPwnz9/lvz5"
    "/Zvh98+fYPzrxw+G6w2m+A34+/cviDKGYhBYQsgFTMgckI0gHOstZQykCxj+/48hyQCYc9+/"
    "/8MQ7ydv/PvXL4KGYDXg+/c/DJcvf2KI9VMBG/IfjyEoBoACCoR///4HNOQHw/HjjxiCXIEu"
    "+fkTpyFYDXjz7gPD46dPgfQ7hsNH7zC428qCDSEYjb++fwfTr379Z/jAzg1m6ygJMqzddP4s"
    "MHonEDYAaDsIvGTlZnjJzcagK8nBsG3lfrBmVnb2JYS9AEowQPyClYdBXFqQ4diiHWeBgTgB"
    "6P8lP59cIpwSQTEAFmRnYbg+cwnE2e9uL/lyaS3D7+dXgDIlGAYwIucFVu0ABiYNvzMg9v83"
    "Nyf8u7F5yd9X1+Hy2PINigv+XNvIwSSgco3hx4dL/87NBVmpAcQ/oPg9EP/E6wKgk0EGCkEN"
    "/gcyEwn/AKr9g9cAcgBAgAEACsnYjGRDfAUAAAAASUVORK5CYII=")
getimgPlayData = imgPlay.GetData
getimgPlayImage = imgPlay.GetImage
getimgPlayBitmap = imgPlay.GetBitmap

#----------------------------------------------------------------------
imgPause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAU1JREFUeNrEk79OwzAQxs/ELQkRUiUGhu5dGDMysMErwAoD"
    "DwCPAQ/AAG/AMyAGRhYWpM6obcjfpjRpnETmnDRWraRl6MAnnc73i/PpcrEJ5xy20Q5sKVov"
    "Tp5sIIQ84NJaonfs7rqNvV4eNg2KPBfJujjrW4xxeH4Z1Y+s89O+lWUKaxpkaVrm+TyHIMhl"
    "LTSb5RBFKmsYsMWizHEsNjNZC7nuFMbjH4U1DNIkqYyY6CCUtZDnTcFxAmQbhpjGcZknfggj"
    "P5C1UFL0INMosujvDjzeAd/Yx9qWm3zNQEYUtrYDm+6BY3YgX+lg0jXBNXWFre3AQQNf57C7"
    "MoNvakKog8IaJ1H8IhGFpoFpUFmLYPj9Wrdi6deHYkDqu4AnjmrHN49wMDiqhjEcFm/3t8ju"
    "kA2W7BPZFb7DWg0w9TC6G45+gRG0GvzbbfwVYACMcsm3y4uD/AAAAABJRU5ErkJggg==")
getimgPauseData = imgPause.GetData
getimgPauseImage = imgPause.GetImage
getimgPauseBitmap = imgPause.GetBitmap

#----------------------------------------------------------------------
imgStep = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAeNJREFUeNqkUztLA0EQnou5i29sVPAVRBAtrK4XLUWxULBK"
    "GhvbVP6OVIrgowmiIFZiWkHExgODGBTLENSLUSImub1H1pnl9vSQWOjAx+7Ot/PtzOyuwjmH"
    "/1hUTmZ2n0FRlC2cnruum3EdByKKAmosJnif0xEGHrp2ttov/BEp4HkeYKCOSOEyQT5mWcIv"
    "ueXZPuJ1WksLBOhEQnJ+QMcxBZwLEataDbhazQvmPwQcxgRKJRuSCyO6Y9tCxMYsJGdZbjBv"
    "KsCYBzc3FUgujgkRrDfBajVfwGsuQCfZomYOjQaHXK4MK3MowlgKhUQmxeJjsO/HLUgnYw6Y"
    "pglVrL1Q4LAwG9ePs/cpkaXjhYLDGdTrAsW3dzCZC9VoDManRuDg+NpwLCtN3AeeJ/c1LeEl"
    "EoNyezfEJwfh6PDSwBLSWEJGcGr7LyX4jSlpHRAf7YLs3omBjyetalqGmkhmImd/a2BIQHY2"
    "2tkGFxv7IhheHzL15zy0TCwK7lXtCN2AMPoLhEjvBGhLO1cEdXo90dI3+VWnz3Wdck4jrWVc"
    "kEGjdDfkPuXzwCq5hrF9i64xxBu9cuR6kLt3N/E7lB/yuB5Gf0H8EfkbMeVuHFSE5mtSrtRu"
    "2tDqQ6FqCRhXCQn81T4FGAAo72Xu5YvuhAAAAABJRU5ErkJggg==")
getimgPlayStepData = imgPlayStep.GetData
getimgPlayStepImage = imgPlayStep.GetImage
getimgPlayStepBitmap = imgPlayStep.GetBitmap

#----------------------------------------------------------------------
imgStop = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAT1JREFUeNrEUztSwzAQfUIGjBNomAwFPRWdSwpKzpAWCg7A"
    "OThACug5AxUFJSUFVFAwJGRgxrHxR5Il1nZw0GCHzKRAM/qs9PbpaXfFjDFYpq1gyeYUw+Hl"
    "CIyxAS39BXzuSPXpzfHOjCBXqpj8/tGuL6X9pJ8vdByGq+uX3wpklpVGHOcIAtV6dbfLa6xF"
    "INK0NNJUYTIR9aGUElkmoJSE1hq9XqfGWgRZkpSGEJpIJKIoQhiG5JzBzpKosTZBHJdGlKR4"
    "eh1C0M1VjrgFTvQM26jg+VNg6Li06zYHga/NVzDiHsad1dYginU+X8Gb4+HDba9MQdyyScF3"
    "agzn2PQAbaYd1Wym9SBZhdXjB9rplz6siDJVIecHZxfY3tv/sw7fH+/z2/MT8lMWAa23qG8s"
    "UMqF3MAi+Nff+CXAADjrrYLxZ/nIAAAAAElFTkSuQmCC")
getimgStopData = imgStop.GetData
getimgStopImage = imgStop.GetImage
getimgStopBitmap = imgStop.GetBitmap

#----------------------------------------------------------------------
imgBreak = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNrEU01Lw0AQnU2TWGItpAexB6FVrF+oIC14VY/6"
    "DxT9K8V/ouhP8NCTRy9BD6Jgi6FoqWJbA9pskk2ycWKtBJOePLjwyGwy8/J25i0JggD+sgT4"
    "4xKHwRkhX2wpgAIBOMCwjJhEvCI01HniAzQ5bvYiqsVfhJuSolTnK5XSVLGoyooiO5SyF12v"
    "3Gvatk9pFXMuogVk2INTQgppRTne2NlZDyQp43neT1IqlQLfsvparXblWNbhfhA0YwpclL24"
    "tjZnmGbGdd3YWZEkk19YmGtcX4fHO4oR4P/KaVXNdXq9ASFjQCkFaprAMA4V5fC7N+gNJCmY"
    "9DiXUSKYhgE2Fg6PJ34jsG3ZHTQ2TsCw2x/dLmPt9pjo+5BJGFngOIwNppJIoHVbrXIOIM9H"
    "zPyZ0rcwL9FIKO2k3uk0OCH9LHpiAt9F4ft+/9G2G2Fe4hi3sCiPPpgVhOpyOl2akSR1XBBk"
    "k3Omu65xa9v1B86rl+gDPWKkHwJCiISP/DTA6grAbhZgCV2povuMd4C7G4DzJ4BbzGljjZ1E"
    "gPlfvVPC7Yg2WIgPrPFiBP92Gz8FGAAZJMfQcW0emQAAAABJRU5ErkJggg==")
getimgBreakData = imgBreak.GetData
getimgBreakImage = imgBreak.GetImage
getimgBreakBitmap = imgBreak.GetBitmap

#----------------------------------------------------------------------
imgMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAa9JREFUeNqMUz1Lw1AUvUljK9F2ET9nwUGKWpSOXVy69A+I"
    "Lv4MZycF/4NjRBQdHJzsJIWCOhRBC4V+Do1IkpqmNnnekyhE1MYHh8M5l3fefZf3JCEEfa2W"
    "LIOmGDuMFcY4o8+4Zxwz9AXPo/BS6PuaZ+xP5vPpiVxuKZZIJF3HMXs3N8vW1VWaa3uM9qiA"
    "rWShsJbMZFaFrhN6456SqWx2XRobU8yLiy22DsMb5LBwuW11Y2PRM03SOGC3VvMZGr4bXIv+"
    "DBjwnSVZVoXr0lmnQ23D8Bka/iCYyd8BDpHl6PorNmyqKsm27TM0fNRHBvC4bzvFYk3E47Qz"
    "O0tn6bTP0PBRjwo4bZfLjTfLMnDqF6Dhoz4ygIfUtYU4f76+fiJFIW84JDA0fNRHBhj8qPpC"
    "aK1qta43my84HQwN3wg9ul8D7AA9bvXksVSqkyQRGBq+TURRM/DB075sNho9l68AhoZ/FxWw"
    "zXgIQkzeFBMcAIaGvx8VgHXAqDDeuYYZgCufPv0jAHryiGgG4xL888Cs55hSv/ydHwYCJhjT"
    "3PI5aRr5HAR0g/HQMLzhQ4ABAFZU8nO4cMZ1AAAAAElFTkSuQmCC")
getimgMapPinData = imgMapPin.GetData
getimgMapPinImage = imgMapPin.GetImage
getimgMapPinBitmap = imgMapPin.GetBitmap

#----------------------------------------------------------------------
imgGotoMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCC4PCgdjqgAAAk1JREFUOMuFk0FIU3Ec"
    "xz/v+ZzydF0kVuihg9Bpaa5hYCiBInaQuoQw2yUiqkOeuohHC6KDEBgjL0l4GIjDQJGdXCEi"
    "TDIvhS4Wbm6QT2Tvub033nv/DmtgpesHv8uP7+/z+/5+8JOoEVlJagHCQAfQCJjAFjDbKoQG"
    "INVovghMNg8N+Zv6+i7XNTR4HcvSj1dXvxnLy9vAeKsQOaWGgZB3ePiqt6urU2gaApDBe667"
    "+5pUX6/oi4sh4JV8VrcDHWow2O7qOlFN4346TVTTcHUdNRhsdyprcSagDI2SLKvCcVjI58kV"
    "Cizk8wjHQZJltVy5ydkACwxL046E49CvqsilEv2qinAcLE07ssCoCTBhPZ9IpIXHQ9jnY8Hv"
    "J+zzITwe8olE2oT1/wHmc8lkpmgYBeE4VLNoGIVcMpkxYf5UQO9MLtI7kxvtEeKgJERsNx7f"
    "QVFwbRsUhd14fKckRKxHiINTAWXTDJRNc6z79fdRU4jofiq1p2Wzh8Jx0LLZw/1Uas8UIlrV"
    "S/7JzxFJlgMnIY/C/sCb2e2kcN2pifFOt6Wt7dn1wcGO9ZWVLS2TeXkX5qpapWjogaePbwS+"
    "FkC3K8W1Axi44w/E3n0as+BmNpN54tg22UzmWIIPJ4cpRd1IPn+x9Mcal0K3AvHIUlKS5al7"
    "oL+FOmHbWFD3APRa/4M3NLfpHZ1LNg1MhKu1adg4GhkR07Dxt/6fXyj92NzCtT/aa1PvgWZA"
    "FYBwXURFcgEo/k5bqmFGAVqA8w9h+Arc/gKxCCwBB8BPwPoFY48c81fKVnwAAAAASUVORK5C"
    "YII=")
getimgGotoMapPinData = imgGotoMapPin.GetData
getimgGotoMapPinImage = imgGotoMapPin.GetImage
getimgGotoMapPinBitmap = imgGotoMapPin.GetBitmap

#----------------------------------------------------------------------
imgPlugConnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NCNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NBNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8++VdpNwAAAYdJREFUeNqc0kFLAkEU"
    "AOC3lhlLS0SK2CWwpEOuf8EQhC10rSSlbQsiyFB/QH+hW/+ibhJ1CoSkg6eKCBFviyAs0UFR"
    "VklzehNjyJK2OPCxb2ffG2beDsDkQ0JPkxZvome2iOWCF/Ycji2NLfSayWQIfTK/xbYxRW/M"
    "RSqVCui6DqqqBlgNN0jkRhRr2Wy2ZBgGtFotaLfb0Ol0gBACgiBALpcrYY5/1JbL6XSabnc9"
    "kUgQv18kHo+HOJ0uIooinS+jyLgzVyKRKJFlmSYng8EN4vWuEJ9vjb5XzMXmHkTpXL3eBE2r"
    "QTgsXRcKD/tu9xLw/Nwg/27UAjK6TCYPVvt9Dmw2OzQaBoRC0lWx+CjyvPBn04ebqKnq8bKu"
    "f2DDPn8mHA47cByHzQPI52/pH/Cim1Fnj6GqopwQSdoj8fghPXN1SOy/C7ODapSinBIWb1u9"
    "bXH0jnaZQWxpHKEmOkMutIgW0DyinePRLJpB02jKfBO76Bzdoy/UY3M9U9xl3wf6dIFvAQYA"
    "XFKD1NmwcssAAAAASUVORK5CYII=")
getimgPlugConnectData = imgPlugConnect.GetData
getimgPlugConnectImage = imgPlugConnect.GetImage
getimgPlugConnectBitmap = imgPlugConnect.GetBitmap

#----------------------------------------------------------------------
imgPlugDisconnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NGNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NFNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+phlpSgAAAbVJREFUeNqU089LAkEU"
    "B/BnpkYQEUUIXQo6SBRmJB07xWo/UA9GYFJoehMh6xB16Fin/guhg3jI6OzJixCWdYjshxJo"
    "IHoINXSdviNTCGVbAx9m9u3u27dvZ9X0v2GBU8jCuFj/eVjhMhgMMj4L1i6FmxbhSjgOBALT"
    "xWKRvF7vNI7VoFIpJLgJhUITlUqFqtVqS61WI1mWSafTUSQSuVUrJMgmEolZs9k8WCqViCeq"
    "1+uk1WopGo3e4fyuUgJ+0XMymZwzmUwDvAIVio7FYg+Ib0OsUw8mYV+sz/jF4XA4y5/MGO8h"
    "dYv49y7DFhyIJO3DAXlJkniG/E9PTfn9fn4yBb4Ola1CVczfRtpmszOnc5UnScOSiE/BYacm"
    "fTZxGSS9fmTo5SVPRqNxOJO5n0FMhjmIwOtPCXgTV+DE7d40NBoMXe6mcvmN5ucXDIiHoADX"
    "nSrgG+nR4/GN5nIFbJT3VlCj4U1m1GwyiscvnnAw9tu3tkPO5fIyi8XJHI513oNcG7vST+IS"
    "ZRbW1nxMrDegH/qgF3pAK76/WlT+9Qo12GvVTHQEO3AODaHeNsttmjzBhwADANJmm8jvUXkB"
    "AAAAAElFTkSuQmCC")
getimgPlugDisconnectData = imgPlugDisconnect.GetData
getimgPlugDisconnectImage = imgPlugDisconnect.GetImage
getimgPlugDisconnectBitmap = imgPlugDisconnect.GetBitmap

#----------------------------------------------------------------------
imgProgram = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg86069mBAAAAdlJREFUOMuNk79OG0EQ"
    "h7/Zu4OzhXEKhOR0KdLAWzh1iiiK8gp5BiRkAU0eIFKokaiS1ChCyivgIqlIDaKxMXfHnW//"
    "pfDdBmILZaTVrnZnvp3f7KzQ2LvR6DUw4Gn78eXg4PfDjbhdOOeen4xGx7W1aGvRzmG9x3sP"
    "wHg85uT8/MPb/X35dnR02capALBWnHNYrbFaU1cVZVGQ5zlZlpHnOV8PD4+dta/e7O29XAJY"
    "a0UAJUISRaRJwlocEyuFiDCZTPh0espwZ+fzz4uL98sSrFVKBCUCQBJFf4Uaw3A4xHtPr9fj"
    "+3g8vTw7ewww1oo0gGfdboi9ns14sbUFwK+rq+C7lIE1RgTY7HS4K0uc92Fcz2YM+v0gxxqz"
    "EqDa9JUIm50OAJOiCHLW4phoAVBLRTTGqBarlCKvqgBrwWmSkEQR5gEgfgAQEWFuDOtx2H5U"
    "k0G/z3Q+x6yUoLVqn3FuDL6tgXNMi3s8i4aKRLBar8xAiQiJCmdUWtNNU/KqYiNNAcjq+gkJ"
    "i5bG+cV9znsqrXHek1cVznuUyGoJZVHEbQH/tWxe02syuNc6+LaADtCbTafrQPg8vlm3c20t"
    "zntEKRrfbSBrAdt3Nze3G7u7H/kPc2V52wDMH+TGCvd5v9PGAAAAAElFTkSuQmCC")
getimgProgramData = imgProgram.GetData
getimgProgramImage = imgProgram.GetImage
getimgProgramBitmap = imgProgram.GetBitmap

#----------------------------------------------------------------------
imgMachine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAoJJREFUeNqkU01oE1EQnk02iTFQE7QihUKRkKTF1iU9+FdQ"
    "CoWYgAcPegkIeiiIWiHgwUvpQXs1Ggo99OYlFwUhWAhYhZJWUmhMxJbYYk1LFDcmJraSv911"
    "vjQbevPgg9kZ5vu+eW9n3hM0TaP/WSI+gUCADAYDmUwmEgSBUNRoNJ5jaKjNSyuKsqRjjUaD"
    "VFWlWCy2X0BfDJ5nd5r9KxZI0Wh0BuRgMHibcznGrrD/wD6hawwHxBdcLte12dnZGYfDcYOF"
    "hkJBpnL5F3Y0IAcMHHB1nYAj+Xw+xHeZ8FSWf1BPTw+trqY2JElyAkilUhsej8dZKhWpu/s4"
    "jY+P3+P0s/n5+f0TVCoVqlarL0Oh0KTZbCZZlmlgoN+pqgrBEO/u/iZg4IALTecX+BQX6/X6"
    "9Xw+v8e7bYqiSMvLy+t+f2AGhhg5YOCAC43+7+T1eh+srCS1hYU32tJSQkun09rg4NA0TwLT"
    "IMTIAQMHXGigbU2hVqsZq9UaNZsKKYrKoxRZKDYwKizEyAEDB1xoOk3kzo6xP4PExMT9WyMj"
    "l/q2t7+npqYevkBucvLx1d7eE9Li4tutcPjJXEsoCO+z2WxcP0GcC3zmDt8ZHj7bVyyWyO32"
    "SLHYOwl4ufyTdna+ELCuriN2nlSEC2x1mshdRZGbkchcSJaLfCOtFI+//prLbRIMMXLAwAEX"
    "mk4T+ZLALo+Ojj1PJtc1t7s/bLfbHyUSGQ2GGDlg4IALTesd6Y8JY7JarX6bzTZtsVhOwq+t"
    "fdMymZx2MAcOuPrmrSYKaDHRUbZjbIcA8sM6xQ9sADFP4xNf54/t21tnk9kKrG3qBdCLw20T"
    "//GCFbY9tj+sVf8KMAACOoVxz9PPRwAAAABJRU5ErkJggg==")
getimgMachineData = imgMachine.GetData
getimgMachineImage = imgMachine.GetImage
getimgMachineBitmap = imgMachine.GetBitmap

#----------------------------------------------------------------------
imgAbort = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAntJREFUeNqkk99v0lAUxw9t6SjIwhgsiBlGYCJotixhM5lZ"
    "wl72svgyffWf4C/YX8CTfwCJyZ4MW+LD3syMv5bIi1kcwUHmNJmAgEKhLaUtnlMKgcU3b/Jt"
    "b3vP53vPvfdc22AwgP9pHD1e2GzA4ptkAwiidrG7gQpZcd9RH3CqHOpKxw/SM5ycu2b42C4I"
    "6fDycjS4tOQVZmcdlKHcbq9enZ9vXpyePlFlOYNxr6YyGMGCx7P3cGcnPuA4oadp0Gu1RmPO"
    "QDzu9IfD8/mjo73u8L9pwtAD0wqyDkd6dXs73pIkIZDNQqfTmZL5T1GEB6lUnJmZSRMzNsD1"
    "7IYSiehvURTu5nLmlPcOD0EURVPUpxY7OAARTRYikag+3KfhEjSAR26/31tvNuFlNApPSyVQ"
    "FAVC+/sgSRKU8JthGHidTILdbgff3JyXGESfM5bBosEwDg3X7Xa5IOvzQaFQgGq1ahrZ8JTe"
    "IMzTKfX7oEiSg5jJDEDDARXTlTALl2EAy7LmbDzPm7oxsdssxmpW38ygD/BDrNWUQb0Ogq5D"
    "7Ph4CuY4DlLFIjjpOAhQVYWYsQG6va9VKg03Bi5OwJ/X1uDTyoppQNool02Dtiw3iZk0yH1r"
    "NMq4U/Ll1pYJnyF8C8dIJ7GYme67SAQMw5ArvV6JmLGBgeXZ1fXMx3q94AWQv66vw238L1ii"
    "/gnCHoTznU5BMowMMcTaqFRplykoidV4h2HScZ6Pxnje62FZBwX90XWlqKrNgqqWLhDOYxVe"
    "UgESaxnQacyjfFhegQTA5gLAfbxcN61C+1kD+HIG8BanxS78QtWR1UYGjLXBzmv341+NLmIX"
    "JSFr/BVgAM8jHGX/y9T1AAAAAElFTkSuQmCC")
getimgAbortData = imgAbort.GetData
getimgAbortImage = imgAbort.GetImage
getimgAbortBitmap = imgAbort.GetBitmap

#----------------------------------------------------------------------
imgLog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCjQhZXhA0AAAAgZJREFUOMuNkU9rU0EU"
    "xX93mtQkNJJAKUTaTZqCpOimq+IuuhJciIhfwc9QKKHtxg8g2HWhK3VdpOBKt20WEoRKX3AT"
    "4qJNmj+v5s3MddGX2JJUvDDMcDnz4xyOEM/LavUZUODf8/n91taP64vE6OG9v7dXre4OnSNy"
    "jsh7nCqqCkCtVmPv8PD1i81N+bizczL6Z8YA58R7j4siXBQxvLwk7Pfp9Xp0u116vR4ftrd3"
    "vXOPn29srEwAnHMigBEhOTNDKplkNpEgYQwiwtnZGW/396mUy+++HR+/mozgnDEifDk6QlXJ"
    "5XIMBgPul0pgLZVKBVUlm83yqVY7Pzk4uAmwzomIUCqV8N6jquTzeVLJZCywWO/H2gkHzloR"
    "oFwo8LVe51G5PLWGn90uztqpAGNE+N5qoarUm82xk9Hx3jMjgrPWTACstUaARqOB956n6+tT"
    "nfwKQ+wtABERlpeXUdVbnSSNwV6L8LfGKDICBEFAu92m0WgQBAHlQoFOp8ODxUUeLi1dRYii"
    "WyKIUCwWAcjn86gqg+EQ7z0XYYhXRWLthAMbtxAEAaenp6zMz9NsNsnMzjKXSnE3nSaXyWBE"
    "bkQYOwj7/QTAk7U1VBXrHAr8tvaqgbgFuaYdAdJAtnN+fme0FBGMCKqKxLcBvDGIMcTaBaA7"
    "AixctFrtudXVN/zH+DBsxwD7B6PbNz1a3d2MAAAAAElFTkSuQmCC")
getimgLogData = imgLog.GetData
getimgLogImage = imgLog.GetImage
getimgLogBitmap = imgLog.GetBitmap


#----------------------------------------------------------------------
imgCli = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNqkUztuwkAQnf16ndihgjJFWh8gCgdBokfKBWhS"
    "QJuKiIYmt4AT0OYAER1FGioUBQtk8IfMjLFRFClSkpWeZi3ve/P27a44Ho/wn6E7nc4N1ltE"
    "+EtujHjReZ7f9fv9h1arFeV5BlmWI1JIU5pnUBQFlCYVCKEZWltYr9evz89PjxoXXG2322i5"
    "XPJiAooyfpojoul0eqmNMcVgMIBms8m+KJOy67GeE9I0hSQ5gJTkQLNLzgBtCiIPh0OYz+ew"
    "Wq3YOhEqbDYxYgeNRsj2CbvdhgUkLpbUaTweQ7vdBswCOyU13t8/II4TMMaB510wnPPx254F"
    "yGKv14PZbAaLxQK63S5EUYTELez3OZL8L7CWBEy5BbQolVIwmUwgCAK2PxqNMG2BgWnuWNo2"
    "3JWqUporCxwOB+V5Hvi+z5ZpzyRYFAo7uROpJFJ4UpKAxKpqAUk/iFyFR+fu3FUdWNWVQM5o"
    "VJUdOOdwr3sWoHO2NjhZPxOrjt+uMl4iY62tz70cBgNc10QpxamjqIlJEuOxNgIRhuE97vn6"
    "Lw8J3b6RpH96SPqX/IwelPjvc/4UYABrxgUeC3Nd3QAAAABJRU5ErkJggg==")
getimgCliData = imgCli.GetData
getimgCliImage = imgCli.GetImage
getimgCliBitmap = imgCli.GetBitmap

#----------------------------------------------------------------------
imgMove = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCjoyf0UsgAAAAqRJREFUOMttk89rHVUU"
    "xz937r2TxJdakhqNboSK9bXqarKqJMFFZNyYPhRciJuiduE6dPN2nUWgf0FqQSHiwiIlGx1w"
    "YSJUFGYWYlsKxYIbfzT1lfeeMZ17585xYV4aSL5wF/d7Dl843/M96qnFD4m0RhvN88srKKUw"
    "1qK1ToEM6IYQ8tp7RITfNi4T6kATAtubVzAnFj/AxjF2bIwDSEMI2duvP5t89d0f2R6XA8wu"
    "fYyvKrxzAEQcRlp7n51bmE2Gw4ZzC7NJ7X0GpEf0Yg5+hv0+93u9DsDqvXvlyvn5ZPWT78u9"
    "cufp6ek8tvZoARFJrTGdY63WheHODkDhvYzKc8daLawxayJyfTTOYwGRtHYuAxiPIqKJCfq7"
    "u3gfADg+MUEcRdTOJUCCyL4nkYik3vuss9ROvHOEEAqtVDFuzLUHvf6lcWNuaKWKEELhneON"
    "155LvPeZiKQA6uTFreLdt+aSXs8xNWWp6sDf//xL5euL/cGjtclWvCgiGyLQiHD/wQ4vnZxm"
    "a/Nu+evqwpzxleuuf3kje++ds8nn134oD/iz/eriK6d/3Lr5ArDPnzp7Ovk2v1kqpboARkTy"
    "2ns++2IzA9BazwGEEIqBjhPvXHmQu7X5c6mU6hpr830TRSSv/w9G55H3KKWItKYfjeGriioE"
    "RARjbQlcN3H8eAuDn9bRz5xBnTiVB+/zpmnWUCoJITDQY6PEFYiUtcgFbS3u91/Y/es2sIQa"
    "KdnZl9Fnlolm2qmIZE+cfz956OBJC9Wn66VSqtts38nD7Q38n7dG2TkczWimjZlfSW3najH5"
    "tYjtXC3M/EoazbQP9YoICtDAJDAFHB/5ErWXE1588yPufnOlubMx2kINDICHwFBEgto7qBgY"
    "33tHHdgIDVABu4ATkeY/CLRGm55hK9QAAAAASUVORK5CYII=")
getimgMoveData = imgMove.GetData
getimgMoveImage = imgMove.GetImage
getimgMoveBitmap = imgMove.GetBitmap

#----------------------------------------------------------------------
imgEye = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAdhJREFUeNrUk01LAlEUhu845QdRUxZBhIIWtFBso2AwRAVN"
    "LqKltHCb63b9A/9AixZCELhyYdAmEyYCBcOlNa1CSQoxog/DMY3x9p5B27Zw1YGH8XrO+557"
    "59wROOdsmLCwIWNoAwFh/ugfZQKsAQV4gbNf9woqIAeuQHOgGxgIMNix2Wx7iqIsxmKxWU3T"
    "xgqFgpWSsix3fT5fK5VKPedyuftOp5OE7oz60hHsYD8UCh3k83k5k8ksGYYx5XK5rK2WzgiI"
    "rPQf5aiGakljakVRjKDrZaPR6Oi6zglVVTlFMnnMZXmdK8o2x674IE+1pCHtCFx2w+GwE9u3"
    "drtd81yJRAKdDXZ4eGSuFxb87PHxjg3yVEsaNNolg5NSqTTVbDaX7Agq8Hg8TFWLbGVl0xTY"
    "7TY2Our5NfhCQPNAWtFisdSr1WqvWCwawWBwRpKkcZyXadoN83qXmSQ50V1jGxurpnGlUqnH"
    "4/FzvItTmoo5ApjQNMIOh2MrEon4o9Gov1arzZXL5XHKBwKBT7fbXU+n07fZbPa23W5f4BVd"
    "93o9TgYimATTMHHCbB5PN9ZSf0LmrsEHRDWInvB8w/oFvAv920iFDkBzF/64fHTjvoFOxsL/"
    "/5h+BBgAwjbgRLl5ImwAAAAASUVORK5CYII=")
getimgEyeData = imgEye.GetData
getimgEyeImage = imgEye.GetImage
getimgEyeBitmap = imgEye.GetBitmap

#----------------------------------------------------------------------
imgSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAzZJREFUeNpsU21Ik1EUPu/2OufHtrY5dJtoQlKGhKaTTcuP"
    "mZVhoG1TcAYJZv5cURqGoYIxhoFZSM38UaZYgxK0EtEfIn7PhdIPQaMCmebIj8myubm3c+cH"
    "Fl143vvec8/znHPPvYfS6XTw73A4HCASiQ7WLBZLRFFUCv5GkLXFYunHya7RaIBeWVm5HBYW"
    "JkXDEqKHOBCyz+fzk5Eo4vF4Or2+uDAu7mRyQkJCJbGrVKpd8aGhIanZbH4mFArjNjY2wG63"
    "w+LiIuzs7Pjh9XqVGs2VoqioKDXOzzG7HoVCYccgcuTLWCSyUqmsKisr02MmlYTkcrlgc3OT"
    "kAnkkZHy5Kampt7x8YlOkjoGk2OGBdvb27lEoGd+ft5UUlLSUVFRoZdIJJWEuLy8DG63Gzwe"
    "T5DH4+WVlpbmKRTJxeifFBt7rKq1tfWB0+nksPcLtbq6OjI8PMyvra3V22w2/tLS0khISAiF"
    "W6lqddYFp3MDtFqtiqZpmcFguGq1Tk/39fUNsg9Xf21tbWRsbMwvYrVa+ZhJeEBAQFhqampO"
    "aGgo0DQbEhMT5ZOTU59MJtOH9fX1txT8Z8TExFTez88vjTWbvYLrZfEFve/r8Uicve1fiG9s"
    "Nrs/MDDwB40fIOocDucAeO9fhS0tgrS6Oml3TY1dJxb//O12Nz+l6YMgKLA74zn9i30guSAi"
    "IiLl0tn0i5bHzct5ublHTthsTJLPF3nN6x31ImmGxfL7Yj2ATTI4RNZERx/NNBobb93uaH/o"
    "2nT2hc/MSE+Vl2c5bDYPAxAZ7/ON6PCWohFC8tj4fD6IxWLAqFq1+px5auozk5Z25olMJtPe"
    "EAigG6DhHYB1y2Bgxijq4yhF3R2kKHiDmXSQM+wJFGZnn38xO/uFSU/PbMMHVSiVSiGZywUk"
    "E+eG1yiyXV3NIHlggKLuHRYoysrKeTU3Z2cyMtTtAoGgKDg4+K9bIe3WjiIvUWSnvp5B8nAX"
    "QK1fAJ2NCwsOjKzu5HK55WiSIARkCxGI4CJ4pMfuADxqQxHGaGTMAFNm0mxYySIs3mmGYb7j"
    "sx1H2xbCtQcPaThEECKEiN4EKD8OoJwA6JoHaPwjwAC3pz/3riyFYwAAAABJRU5ErkJggg==")
getimgSettingsData = imgSettings.GetData
getimgSettingsImage = imgSettings.GetImage
getimgSettingsBitmap = imgSettings.GetBitmap

#----------------------------------------------------------------------
imgGeneralSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAY5JREFUeNqkk09qwlAQxr+XvKgFIyb+QUQqdmkvkK6KV+jK"
    "U7gRkS5EcJMDeAQ3rnqOXqBbBdGFilGsrhK1bwZjFSpUDHyZl5eZX74Z8sThcMA9l4Y7L6H0"
    "pOQomTfWfit9SnV76ff774VC4fm/7QghMB6Pv6rVqkstWPl8/nmz2aDb7YIg2+32z/VkMkGv"
    "18N0OgXVUC0B9CAIsNvtoOs6R8/zYNs2J57vL5dLNJtNzGYz7Pd7MqOfACQpJUdKbDQanEgw"
    "y7IYRqBWq4VYLIZjuwyQIcAwDI6apqHdbiMajWK1WqFer2M+nyOVSnFxLpcLAfIEoETTNDmR"
    "7MfjcWSzWR5Yp9NBJBJhOEXf98N5/gLW6zVqtRoWi8WFG7KfSCSQyWQu9gkcAgzaIEuu63Kf"
    "5/O4tj4CDHZAE00mk/y1dDrNEw8Tr61pPlQrFckfDAajYrH46DgOOyGblUqF12S/VCpxw/Rc"
    "LpcZMhwOR1SrJF7Vuzcl+8Zf2VP6oEYejudA3ggI6DyIe4/zjwADALUz7/8W+6CIAAAAAElF"
    "TkSuQmCC")
getimgGeneralSettingsData = imgGeneralSettings.GetData
getimgGeneralSettingsImage = imgGeneralSettings.GetImage
getimgGeneralSettingsBitmap = imgGeneralSettings.GetBitmap
#----------------------------------------------------------------------
imgFind = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCwkJO+fKowAAAn1JREFUOMuNkt9LU3EY"
    "xp/3Ped4th2nS0WxlSQRqUtIK9ZFZWlddFGQXXVbEBgEEXlXV11ImBP/gIIYFAj9EsmLTAyC"
    "EhPByKmlNWktnWtzc9vZcfueLnIx5i564cN78Xx5eN73/dL5G5+haaWwWq0NzNwNoB2AE0AA"
    "wJgQojeVSs0lEhsoVjIAmKa4kE6nPK1NltDRZqu/ppJX5pfTsSmf7ppfzIyYprgJ4HlRA8Mw"
    "GkyR9XSerfjSccReyYQyAGjea60sLxeJqh2Z+Vdv4p5MJusTQswVGkjV+y/da3FZ7edO1ZRY"
    "FJZzAhGIiM0Si0nh8EZ6yR/dZxjGkGEYyEeOxWLtLa49i4HfSTkA6MViNjeWRkff+tuLjqDr"
    "aWedUwvW12gqAMoXfYFYDAB21dosup52FjNgITgQ/JXMFBMbnWV2AAiupDaF4IAQjEJYUbSx"
    "iamoQwiTCg02M0JIzNLk9HqFomhjiqKhEFlVy3rHJ/SR44cTIfdBuyUrzH9pjKwJ/7ek7f1k"
    "3OlIv7yuGJ9Af7cLZgYzQ9rp6lpTSuzLEzNGZ0onUeVQDIddsv0IZtIvXsfVweGws/NEvHpx"
    "ZtBnmuZPIlrPmRARqOXiR6iqHaqqNTBL235iYPbBo8jXgTNe75PbHk/vnWQy8YyZZ3MJZLv+"
    "GOH1Vqi7T84RSVcK95AxoohEIsGurqtWr3fwbl9fj21tbXUIwAcUnq2+tXvbJb5P3wczg4gO"
    "NTUduOz1Pr3W398zsLS0MMrMw/jfIiLIsny6ra3j4cLCqul2u2/V1dWBADAAaQsZgJKHnNdl"
    "AJIsy8ccDkctEY2HQqF3tDUGF0Eq6Lz1NkcWQPgPoNkNgoXHVyQAAAAASUVORK5CYII=")
getimgFindData = imgFind.GetData
getimgFindImage = imgFind.GetImage
getimgFindBitmap = imgFind.GetBitmap

#----------------------------------------------------------------------
imgGotoLine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAh5JREFUeNqkU89rE0EUfrOzScxuthG0gkEtVA9GQYS13qsI"
    "ngRBQax4Elu8eBZ6lP4JgiL24kFRDHiQoPQgopc2BwXpRQSDENiwtpuQTXZ3fvieZtdGoz04"
    "8PFm3pv3zffmzTCtNfzPMNPJ7LJ3F42L8BDriEdSqVUlJWilRpLeLuzP5kY6QSXzmPBswjb2"
    "nDjiXHUs4wE6b2HI+peCXwR4ihJiqe2HrwucFU4e3lndN5m/hgpukgopRIaxBHEUQRLHtOFl"
    "s9X91g8FP1Sxp5wiu4y+mW0Jon4fEiKJoi9tv9eXUkGwmfCDFXuvSJJLfyPILpGSh8Pb2FCx"
    "1gqiSEDJMR2MVbftAskfjk5HJJIxBtRhgxl5jE1mSsNwPMFmuw25fB4KVlHghao4TiAIAhDC"
    "QHUD9rPMAWA54wloUFB1JRicg+e1wfc7wFgJ4kEE1An123sYIcB38OMhSWoZosdMCHM70ObS"
    "8taG+xpo5v8gkElSw6B7Zu6U2wpiaA4E9CwkAQ7Ts647UeSwWnvTwLupjX9IWtexhMUXy/UG"
    "K5egyUvgW2X4amIJjgPvHq80KE77thKw9DPRrReOXQBePXcWfbenFq64n7oaDtgMWvce0smL"
    "cv15PfrwFEY+IC2GDlJTROwyZ67P5c7fX6u80posrdG/G2EjeJpD2KqAoykTAcIxjl48DtOn"
    "b8DnlTvq45P36OshfOo45mS9/C7AAC/XRIWgonuzAAAAAElFTkSuQmCC")
getimgGotoLineData = imgGotoLine.GetData
getimgGotoLineImage = imgGotoLine.GetImage
getimgGotoLineBitmap = imgGotoLine.GetBitmap

#----------------------------------------------------------------------
imgOpen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAaFJREFUeNqkU88vA0EU/mZ2WiElfobERfwBLiIhcfA/OLki"
    "cXSU4OJQcSc9ceQiEkcu4ibiUhWkxKb1o6qyqVLbre7OerMqWqlkpS/59n2T9743M2/2Mdd1"
    "UY+JkxVWM8AZBsiN1wjtSBex730FYYrQ9zuLkjA4JxdzhQKypolpvQOGYWL9NMQpPETYUHns"
    "KIzw8OzuPBwHrivhyko4X17FypwxhujmzDJpF7wTOBKaEsuPYpVQVog9XvaaFoCnIQvQl6tF"
    "9c5/i79PojRB4fUJwqaFtG0Y8UMU354BVYw69AVJa/Lyh3PO1c6jpF2iQyQEFRVWLg2bknpG"
    "Jnw9Xe/Y5PB7Ru++2J5fFTZdK288QGtqg5VJw89/wRjHc/z43rJxrgqIbEpHV/8gbGqkH9OC"
    "DUjfnKVNC5eiJCHyuVf0sIDvAk7Jeksl9SeN415Q/wJaYztsy6ROS18FjFT8MVfANVFXEGkJ"
    "NXfSk3Bwjfu4P8OdfvVydovY2h49YzSB5OtW5OA/A6RncB3Zh060VU1SUJHyXPg1h2ARiqze"
    "cf4UYAAOUhKfHcZJBAAAAABJRU5ErkJggg==")
getimgOpenData = imgOpen.GetData
getimgOpenImage = imgOpen.GetImage
getimgOpenBitmap = imgOpen.GetBitmap

#----------------------------------------------------------------------
imgSave = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QMBCR0qtm4moQAAAkxJREFUOMudkc1LVGEU"
    "xp/rvNfGcVKbjy6D0x1jKEYcZGjCNkZBIQQSWLmLNgatopb9A6Lb0I2LFhFBNSW0Cfra1SJx"
    "iBaKUabI1FhK40h33jvnPfe+LRxdBIJ24IED55zf+QJ2sf6p0tmJJT06saQ7+6dKV3fLE7sF"
    "FFHf5qZq0hoBRVTbN4Bct1dKpX0fo+S6zQCm9weQMl7ZrLWSUgdIyo19T1CXMvrd5bznG6hL"
    "WdwTIHnr1ZRhGPkGAKtmKzx/yz9y+/UsAGiti6W7Aze2awwAGB4ePgkg/6W179SaaZ/rvX7F"
    "XvwD/K4DvtYImwYONQPrD5+uxNXK22POzAcAxUKhMGsMDQ3FEonEyNjY2LjrupieKeH+ux+o"
    "Dw7iY2WrSzoMRF48x+VcDOczMZhmEJOT43fW13/ea2LmeCaT6WZmVKtVnD7ajIs9LfCfPIYd"
    "AjpbgNCzRxhIC+QtoFLZgFKMVCrdzcxxwcxWIpGwt3eq1Wo4cVhhrdPBy8IDaA2cSUpkOwQc"
    "x0Qo1AYAiETiNjNbQillpVIpm5nhui6q1SrK5TKOt7vg6C/4vkb6YAirq2V0dDAMwwQzw7KS"
    "tlLKEkQUSyaT6Wg0ivb2NnR1pZDL5UBEuKAUPM9v3LoJQKDxOAFmL01EMUFEwWAwiMXFr1BK"
    "gYh2pBTD9/8FbEEikRiIKCiIKCClxMLCZ8zPz4GZd+R5PrRGo1jsqDK+jGvvb4KIAsJxHLNY"
    "LC5ns9mubLZnTxPINwpz3z4tO45jGuFw+JIQIo//MGYu/gWaSzpM3qF0jQAAAABJRU5ErkJg"
    "gg==")
getimgSaveData = imgSave.GetData
getimgSaveImage = imgSave.GetImage
getimgSaveBitmap = imgSave.GetBitmap


#----------------------------------------------------------------------
imgExit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAlhJREFUeNqkU71v01AQP3+okeOkjgVNREK/Ai1kYghlBVUs"
    "DGwdQCojylhWNv4E2OiGRAeYGbogJCaGKFWpiKqWCtokShNXadPKrf3s92zurKaK+Zg46efT"
    "3f3u53t+ZykMQ5h7+R0kWQZVVUE5hyRJywBQRtSQUxGcA4EjwiCA6rMZIJPhN+O+D0IIIpYX"
    "5rNl8lGM+b/ZsEAS3/Qc8dpnDLjngeuGkaeY8lQn3h8CAtUDzpdmxpMVbLg9aPK8AAZilC8W"
    "tArxxNA0kYDveXNmWlmcyKUKnuvCAIxxGI7Hx1IFQ5cXiR8XYOzRzelMfqPe7SFx9ULAjQms"
    "1resXrFg5IkfE8BiaTQ5kmm0rCMsvo3GxyZZEpGnmPJNrKcSSob4AwGVHsx1L9nHNhwenThC"
    "BHt4hZSuvXn/ha6zRgF+wD3fY47dtyN+TMBznB4XHNSQa2cOm4Qg2E7oeiXA65MVBdjpKc4q"
    "T47qCY15bsSPH4GxzUan308bmomjPmGOoxzu70PfsoA8xZTXRzWzaZ30iR8TwCt6t/51t50r"
    "TecSmfRjXJwXmJ5FJMhTTHmjOJ7b3G61iR87Am5btdOyVpRvPyr5e3euNes/nzqN1gI/PnZU"
    "w9C0iaumOTuV21nb2Ot1eit4rOpAQKJ/gT6afONhMrz+YCl5JbtolG/lw7FsSowkVFqGoGvZ"
    "9tp6m3UPVqSd1VfB1ocz6hsWoEkuI7IwdbcEU/P3QTMnQFIyEIo+OEcN2P30EXY/byHnAGFh"
    "nz8sIJ/vuI5Q4N8WIM4Qp9gnLgT+x34JMAAuBJ9VBPnzsgAAAABJRU5ErkJggg==")
getimgExitData = imgExit.GetData
getimgExitImage = imgExit.GetImage
getimgExitBitmap = imgExit.GetBitmap

#----------------------------------------------------------------------
imgAbout = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAmhJREFUeNqkk1trE1EQx2d3T67mhl0otVaoEQu9oFFpo6IU"
    "9C1CofSlxRu0VH3sF/DBj+BbRSgWGhGLKKIFESw1xRgJFTSRQKBqpaGbbRqSTdckm6wz624J"
    "6FsHfgs7s///mTN7DqfrOuwnmPFgDDiOs3IHkTDSg4hmTkYySBwpUIIW1jTtr0FLDHpE31h4"
    "4uLgwJUzPf6OQBsli5s7219eJTMfoysJRS4tYiphCThyMjsIi93tU9ce3BlxiQdEVVWNFawO"
    "nU4n7OYVeeH27At5fesh6uJUtwxET5v37mR0Zlx3c4b4f+FwOACUpjx3/f7jynb5HhrI1haG"
    "B8cvDDWculgs7ECjqmmpZ8l09m16g4rHLvd29Y2e7lUdKvN4POKpsbND72ffDGNp0TIIHb/U"
    "H5QkyRjO1yefvqWeJhcw/4iKn6PxG6VS6erRkb4BZmPQea47CLMQIgPenOgRwW8P0J7q9Tqs"
    "v8vkMD2PbJnM5z78yPF2HnSGvz3AB0iz9xsx7PVqDWq1GtD+m80m+2cAHDDBJQDPeNB4Y7h2"
    "elgd5AsbsqJWVcNy4NYQtTfdIp8+OXM+xNwMBLcAZamokGbPAGMtu5yWbC4bCA4BxP4OH34Q"
    "pnmYhMUT7T4SMxeDn8tZiTStBq/TL9eyellTaJV84hd9EGvpILa58l0SnAJUciUl+zyVJQ1Y"
    "R9I8xhHvIX98bGmq4e30r+J7sMUg6O3yr47GJhuewz46zhHSGFrTgIZGxzaCTJhnfg75bYwP"
    "wIncNO9IFFlC8qjVLAPaituEzBpIHdFaLp0NEczaLlJBbZPb73X+I8AAb+EUcaash1EAAAAA"
    "SUVORK5CYII=")
getimgAboutData = imgAbout.GetData
getimgAboutImage = imgAbout.GetImage
getimgAboutBitmap = imgAbout.GetBitmap

#----------------------------------------------------------------------
imgGCSBlack16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg0ngp9oXwAAAtNJREFUOMuNks9rHGUY"
    "xz/vOzPrbncTZJ0cGjB00RKdGkPbtQRJS+2CNw+yGD30Ku2/kMC2pIf0VIJEqKfeeqoIlh5q"
    "1SxJ448aMBGqNk3SZZUQ2mw2dXd2Z3Zm3nk9bAyaivg9Pg98+X4/zyPYp/cuXnwHOMh/a/bG"
    "5OTav25Onj078cvamt7pdPSTdltvuK7+rdnU1UZDVxsN/fn8vC6WSueKpdJhALnfwB4YqL84"
    "MIAKQ1QYEvg+XquF67o0m01c1+XTS5c+iZUqvDsxcfgZA6WUEIAUAsswSFoWCdPElBIhBPV6"
    "nY+vX+eM41y9v7T0vrnfIFZKSiGQQpBNp/fmlVqNQdsG4P7GBj09PXyxvLzzjwTFYjFvbG2N"
    "Vh494vkDB3jablNvtai5LknLolKrASCEACBSSkiA8fHx6ampqatBEJz47Nq1D1YfPuTmrVvM"
    "3rlDNp3GzmT26gB7dVQUCRPAMIz0+fPnPhwefn1tc3OT3kyaVwYH+ea772l4Hr2p1B4TgIRp"
    "YnQNpDkyMvJmuVx+4Divrh87dvzlTqdD/8F+FhcX8TyP/r4+2IX6F5OcbfPE84iiSErf90/O"
    "zMxcOXQo95JhpHjj9OmyYaSw7T5ecxyuTE/j+j5SCLbdLo+a62JJSRRFQnqe9+3Y2Fhpaemn"
    "ShAofv7hwVtBoFhfr3B3YYGhoSEyySRSCF7IdHnYmUy3QhhKubKycvfo0fyR0dFCrlz+qlqt"
    "rrKwMMfw8AlUFHM8n8cPQ6SUuL5Pw/N42m4jgCiKpAmwvb2tLlwYvzE39/XqvXu/Tjx+/Du3"
    "b98kDIMuPPOZd6EVhkS7V0jMzn45CfRalnVk5Ex+/qPLl085jkMikaDluoRKEWuN1ppYa+I4"
    "RgBeq2WagALqgArDcFlksz8WCoVTAKZpktztL4RAa40EYikRUvLHzs5z4m+pskB/Kpd7W6ZS"
    "ffwPxZ639ScTBkPH3uXMqwAAAABJRU5ErkJggg==")
getimgGCSBlack16x16Data = imgGCSBlack16x16.GetData
getimgGCSBlack16x16Image = imgGCSBlack16x16.GetImage
getimgGCSBlack16x16Bitmap = imgGCSBlack16x16.GetBitmap

