#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
imgGCSBlack32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIcBzAXW6G7pwAABvhJREFUWMPll3tsFNcZ"
    "xX93dtaPXbuxYRcbs2seAdsYJBOZVC6hreMAVUKUmJYILEAKaqtQ1LRSVFVqFCA8VKgatWqA"
    "JKZpBBJNY5oSZAdRBKmKRHkZB4OhRoTXWk6wvVtTs7tez8zOvf1jH13jRcVp/+tIV+fe0dyZ"
    "M9937vnuhf/3Szzsgy9s2rQVmPZffm/vHzdv/iTzhv6wM5VS0/du3LjKtm0UIJVKt9RYZfYT"
    "kxIImKbJz958UyzfuJEPt2xJk9DGQQBp25imiWkYaTQMg5FYjJFYjNjwMMPRKMPRKNFIhEgk"
    "QiQcJhwO09vby4HNm1cppdZ+Z8OGxV+GgCaEINU0QNM0HEKgaRpaJiZb+nkgEolgAr/fsmWV"
    "Umrtt197bfH4CEiZFs2XIXH37l1MwAT2bt3apKRcu+zVVxePRwMi9XGUApHQr6YUaBpIORaT"
    "l0xqYHdzc/reV8vLm/Z9/LHnoQlIKRN/LQQSONnRQYnXS9/AAJM8njT2B4PMr6kZQ2LBggXY"
    "tk08Hse2bXRd54Njx+LjjwCgCcHXa2tRSjHT70+jBGb4/dhKZY2EcDhwaBpKKQoKCyl/9NF7"
    "44mAICMFqUigFJ/dvMmZc+eIhMO43G4WPvEEZVOmpEn85fhx+vv7eWHFCmSGAUkpxbhEmFJ0"
    "CjUh+OLOHd5vaSESDlNVWUlffz9Hjh4FKQmHw7S2tnLx4kUGBwdHCRMhUFIyrgiMEaFSdF25"
    "glKKpU8/jdvtpqysDIcQSCnp7+tDCEFZWRmhUAhNiFEWPK4ISCm7EzPFqEjELQuA3JwcLl++"
    "zIeHDrG/pYXBwUHmVFezfNkyCgoKEivmviU63hQMpkSYSWL6tER5OHP2LJUVFdTMnZv+w5RP"
    "ZIo3RUIk3qk9VAqWL1/+/XgwuGb3zp1UVlVR39CASr6kZs4cenp7aT9/ngtdXeQ4nTxeW4vX"
    "600sW6XSOdcyfEIkI/DAatjY2PiSEKJeKfWGEOInLS0tKy3LYvdbb/HMs89yuK2Nqupqnlq0"
    "CKUUcdvGME3MZN1IFaZ0P9nycnORUpKXn8/KV175KGsKli5duq6iomJdc3PzyuLi4u2WZWmh"
    "UJChoX9iWRaH29pY++KL/P3KFd56910++/xzTl26RG8oxKXubvqTOBAM0tXdzUAolMaUbadE"
    "mDUF8Xj8qfXr188LBG6zbdvWxRcudFpSJgrrvJoaKisrCQRu07RiBb997z1KvV5KPR6UUpR6"
    "vaOwxOtFQQKVSqchJUJHNgI+n+/2yZMnZzY0NEyPRqP4fD6HEAKlFBMnTiAcDqPrOm/v2cPC"
    "RYsI3bsHwI2eHgCuBwKJcSCAAG7cvo0QgpuBAOWTJ4MQ6LrO+21t18YQqKur+5GUcm04HDZ9"
    "Pt8Mn8/n6OjoMH/ww5eDZ06fKZhQXExpaSmdnZ18caePm9euke90UltbS6nXS6HLRanXS4Hb"
    "PRpdLkomTSJX1xGAruvsb229NiYFpml+a8+e5mfC4TB5eXlIqdi+/RefuubV/Ongvn2/XLN6"
    "DdXVc5g1axZ+v5/CwkJ2vv0O/qoqSjwe+oJBSjwe7gwMpMepYlXi8VDo948yojEEDMPQR0YM"
    "4nEb25YIoeNw6Ja0bQ0gNzcXIXRsWxKP24yMGKAU82bPBkhoIYVZNJHyEQBp22M1UFRUNOXQ"
    "oUPi8OHDt6ZOnVbu803Vamu/NumvrR9VXOj4dEJj40oKCly0t59l/wd/4Nz580yZMYOZVVVc"
    "DwQQQvxbA1k0UT55MgAOXWfvwYPXs/qA3+9f6PVO+vWuXc3zY7EYPt90HnlkIgBDQ/+gt/cW"
    "+fn5/Gbnr/juupd4rLZ21Jr/Sl5e2ge43xOSm1an08k3Vq8+ktUHDMP4+a5dv5sfDA7idOZz"
    "7NiReE/PDXp6bnD8+J9xOvMJBgf58cs/Zevrr9MXCtGZXP8Xr14dVTHvrx0pS06mIHspKC4u"
    "3tDQsPhWe/tVVVk5u7OoqOhvp051qVOnutSSJUvUc881qvb2q6qpabXasWOHsmxbWfG4MuNx"
    "ZViWGrEsFTNNNWyaKmoYKmIYKjIyosKxmLoXi6mh4WEVtSw15/nnjz7Q/10u1ya3233a5XJ9"
    "0+12n+7uvqO6unpUfX29OnHihKqvr1fbtm1TtpQqbtvjJhG1LDVjyZJPsmlAByYCHiAPICcn"
    "Z5Wen/+9x+bOLayrq6OpqQkF5DideLxePB4PDodj1GFEPQBTmnDoOjOffPJENiuWQBRQqZOT"
    "aZpvuCorFx44cODxzAc1hwO3y5Xw9uQGRQmByNiw3I+pKioAY2REfxCBSLKlLxvssrKyB+8X"
    "Mg+bQiT++r7jmcroC03DNAzHf9oPTAVKgSnG0FAwr6rq7P/yZKxiseC/AKsV5rYw7NE2AAAA"
    "AElFTkSuQmCC")
getimgGCSBlack32x32Data = imgGCSBlack32x32.GetData
getimgGCSBlack32x32Image = imgGCSBlack32x32.GetImage
getimgGCSBlack32x32Bitmap = imgGCSBlack32x32.GetBitmap

