#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
imgPlayGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBx8mNXKb5QAAAGhJREFUOMtjYBhUwNfX"
    "/7yvr78BKXqY0PgGDAwM5319/RuINYARzQX/kbgXGBgYEjdv3niBFBeQ7Bp8LmAgxjVMRHoV"
    "p2uYKI05FiLV4fQCMQY0bt68sYEcFxAVjSzk2IrPAKJsHVwAAGz0KKANoy45AAAAAElFTkSu"
    "QmCC")
getimgPlayGrayData = imgPlayGray.GetData
getimgPlayGrayImage = imgPlayGray.GetImage
getimgPlayGrayBitmap = imgPlayGray.GetBitmap

#----------------------------------------------------------------------
imgStepGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBx82KMWLgQAAAHxJREFUOMvNkt0NgCAM"
    "hD+NA+EgxBmcBBmJMIhspC9ieLBW1EQvaUKg3F1/4DewdpitHUztv6YgWLajjzFMgsh+n3Pa"
    "gzx34sYVgUQAYIC5VJTQKu9O6013oU/Zjb/jgKclACSglyajlSCOVCNIwBhjSJq9rlLVv77K"
    "32MFUIMqDbGteEsAAAAASUVORK5CYII=")
getimgStepGrayData = imgStepGray.GetData
getimgStepGrayImage = imgStepGray.GetImage
getimgStepGrayBitmap = imgStepGray.GetBitmap

#----------------------------------------------------------------------
imgStopGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFByAHIcWhhwAAACtJREFUOMtjYBhowAhj"
    "+Pr6/ydF4+bNGxkZGBgYmCh1wagBowYMDgMGHgAA3pEEGCq7DsMAAAAASUVORK5CYII=")
getimgStopGrayData = imgStopGray.GetData
getimgStopGrayImage = imgStopGray.GetImage
getimgStopGrayBitmap = imgStopGray.GetBitmap

#----------------------------------------------------------------------
imgBreakGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFByATOx91+gAAAL9JREFUOMvNkr0NwjAQ"
    "Rh9BCEpGSBdKGCEDWHHLNFG2gS6RB2AEKCFVSkq3EQ3NBTmOA6GCTzrJvp93p7Ph15r5DqWy"
    "GMgBDazFbYESKIypmlGAUtkWODmFviyQGlNdBgDpfH5T7EJ23SSRE8gnFCM5eXdxATqQ/BDz"
    "pUMAv3sLLMTawBQDgK/lyLmnyFvOVNkQoPwCUIYAxcQprOT2AfKu6QdI95Fev3HuRuv6dk+S"
    "zVG2HAMrp/AA7I2prvyVnrpfMROzV4CSAAAAAElFTkSuQmCC")
getimgBreakGrayData = imgBreakGray.GetData
getimgBreakGrayImage = imgBreakGray.GetImage
getimgBreakGrayBitmap = imgBreakGray.GetBitmap

#----------------------------------------------------------------------
imgMapPinGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFByA54KS8LAAAALhJREFUOMulktENwjAM"
    "RF8rBoANOgKLWKEbsAITVExQsQEb0CgLdIN2hG4AI/DjIhQ5JBUnRbFs53x2XGFAxJ2AHmjU"
    "tQCXEPwQ51aJxw9stDFJbST1es9Aq2eOYh/sDIJV9nWtJuJQVU2cXPMnLAWLVuq0MkD3FcsS"
    "jMAZOBrDHEta8D8U++w36tCewD5yv0Lwh9IhDoW+JIEvba1KNRu1YcrP7cE9YRcT3BJ2OUTc"
    "JOKmrZvIlspvA94usHD55RcAAAAASUVORK5CYII=")
getimgMapPinGrayData = imgMapPinGray.GetData
getimgMapPinGrayImage = imgMapPinGray.GetImage
getimgMapPinGrayBitmap = imgMapPinGray.GetBitmap

#----------------------------------------------------------------------
imgGotoMapPinGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFByEMrwxJTgAAAM5JREFUOMvNkFsNAkEM"
    "RQ+TFYAEJCwOBgHNBAdIwAlBAYsCmFTArgPGASsBCfwU0mxYXj/QpEmf994Wfm2TdwdF0hQ4"
    "ANFKHbCsPiC7LRfLI3CoBiw7oAYWqvkyAIhAUc1zmz0BMbjlFbAygNYkv/6BSIou3xgAJvWu"
    "RCSdgZk7oQb6CmhHwGvrzS0/AmtHAHAMHzxx/6gWgIXz4prFagCo5gL0rt+r5hJUc6eaO7vv"
    "4f1e8jAOjqEBmifLANuR+H0TSa1Iuj+++gJjz1/ZFUNIRLiwZlGoAAAAAElFTkSuQmCC")
getimgGotoMapPinGrayData = imgGotoMapPinGray.GetData
getimgGotoMapPinGrayImage = imgGotoMapPinGray.GetImage
getimgGotoMapPinGrayBitmap = imgGotoMapPinGray.GetBitmap

#----------------------------------------------------------------------
imgLinkGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBx8XZKyb3wAAANFJREFUOMvNklERgzAQ"
    "RB8dBCABCdQBCMiAhFYCEqoACSChmRNAHRAJSKiE/lw6zE2g06/2fpJJdvd2L4FfV/YN2Lm2"
    "AGagEvEZQH4ALoEB6PToARRABYSIy3fIlXYqgBV4ArVeB6CJ2NMH8gScLUbEP5MCavtNFvFX"
    "jRBtB92zF2EwZID7Zl2sGyvQaebeubYGgtqdnGtHoNwIpmegA5vjc2m0EbjoXX/kYJsxAMGQ"
    "GxG/JgX0k9ha1HYkh6MZzOaTRCcTcLOdUwKR3Gzf+f/rBUsBSE7N9wI1AAAAAElFTkSuQmCC")
getimgLinkGrayData = imgLinkGray.GetData
getimgLinkGrayImage = imgLinkGray.GetImage
getimgLinkGrayBitmap = imgLinkGray.GetBitmap

#----------------------------------------------------------------------
imgProgramGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBxcW23IhQQAAASJJREFUOMtjZIACX1//"
    "/wwEwObNGxnRxZgYSADYLGFEl0S3BZsmZDUkuQCboVgN2HL0HL+vr///jYfOyhMyjAWb4MyO"
    "xg/VUxeKt2bHvyRkAE4vMDExsjIwMDBUTVmgxsDAwJDV0CeILRawuiC5pIq9OTPuZ2JRpcbn"
    "92/uMzAwMPz8+pGfgYHhA1EGyKlriTXMWsz77x8D4////3mrpy4U+P///x+ivWAkwfukIS32"
    "s6k03+f71y5ytmbHf3hw/ZIk0YEIA+defOavT415WjdjMV9TRuwn5HSD1wUHrt2Tg7rkIyRA"
    "GbhJisbXz55wMjAwMOy+eFPv9bOnwg1psW/DM/LEN2/eSJwBoS52NxkYGBiRNDBi04zVAGJy"
    "Jdm5ERsAAA6Saru9+a83AAAAAElFTkSuQmCC")
getimgProgramGrayData = imgProgramGray.GetData
getimgProgramGrayImage = imgProgramGray.GetImage
getimgProgramGrayBitmap = imgProgramGray.GetBitmap

#----------------------------------------------------------------------
imgMachineGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAPZJREFUeNqkU4ENgkAM5D8OgJu8G8AAxHcDmYARjCMwAW4g"
    "hgF0A38TfwTbpCWlqRq1yeXpc/1ev31XvLCm2e5hGchtp+lysnheBAQKYuusb+Qgl33HwbBc"
    "ASUgA26AqJKNgEpwalCVWEGgHwWt0VAbFSfMCkjFQxA+WYbs68UdkGwtuSaM6t/MdXRxHUvi"
    "YMiwU105q9ISoPfUqqAyHA3ZvfIxZvDFn4YHtCRH2sHgdsrHmNa9qXEk2ZkOjNYdrcRmZfQ9"
    "vlBeLUaZOlF+UXrJY+9FPZmHxOg7lyQ5SU8itiXwqwP/LtqbYH8j1KK/PODX5/wUYABloVE7"
    "jTdWswAAAABJRU5ErkJggg==")
getimgMachineGrayData = imgMachineGray.GetData
getimgMachineGrayImage = imgMachineGray.GetImage
getimgMachineGrayBitmap = imgMachineGray.GetBitmap

#----------------------------------------------------------------------
imgTargetGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAASdJREFUeNrEU1sRwkAMvDsFSAAHrQMqgIEqoEhAAYOCSgAU"
    "lA4CwEHrgDoAB7C52QyhPH74IDM7gSSb16XeGZlMpgOoApgDyeFQe9pvUC2wA7awX5UTDDmB"
    "aoBSyO5VEvoaxj4S0HAEhrRvgdyQc9ocY46axLPthg5pLUeLpzcdSKExVAUIpwPSwJm1ciQj"
    "sADOhngRGxPnppMicGGOy4lk/N6YpI4VNyaJjjMPZmE1dek+y6oXm7i/i+eR6AL3XF6cv3dI"
    "Ih1sI/yf8TXiHbR0TqnXXwque7Ft4HmKyNONUUE2vOBNqMibL8THWyho3/18SL53ygNzyrXs"
    "hP4Z29bKUiiDP44gy5I9ZMzqGFiZ4pUhd0p++hppSIGlWayVlr5UySJ3AQYA9a+ChGGMS8cA"
    "AAAASUVORK5CYII=")
getimgTargetGrayData = imgTargetGray.GetData
getimgTargetGrayImage = imgTargetGray.GetImage
getimgTargetGrayBitmap = imgTargetGray.GetBitmap

#----------------------------------------------------------------------
imgXGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAP9JREFUeNpiZEADvr7+CUAqHogd0KQOAPHCzZs3LkAWZETS"
    "qACk1gOxAQN+cAGIA4EGPYAbANV8HogFGIgDH4DYEGQIE1RgPQmaGaBqQXoYmKF+zkAzvRNL"
    "GDRCvccB5Uuoq2s8ZIIGGDKYCHRaA5BORBJLhIpNRFMbzwh0wX8sTgRpWAB1HQMSez66QhYc"
    "fpwP1MAAizJcmkGAiYFCgMsF2LzAgM0VTNAUhhLaaH4GeScB6p1G9NTJDIwKUGIKQBI0AIpx"
    "Aul+JLEAqLp8pGgEWwZLieeJSMIYSRroKkNYIAZCExADCUk5EB4L0IxhCM0oDERkJkOUzERJ"
    "dgYIMADRhV+mXJ7YiAAAAABJRU5ErkJggg==")
getimgXGrayData = imgXGray.GetData
getimgXGrayImage = imgXGray.GetImage
getimgXGrayBitmap = imgXGray.GetBitmap

#----------------------------------------------------------------------
imgLogGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBxY7h7ZMdQAAADZJREFUOMtjYKAQMPr6"
    "+v9nYGBg2Lx5IyMDAwMDjE8sYGIY8oARXYDUMBmOYUBqmIymg8EQBgCm0RetPdChKQAAAABJ"
    "RU5ErkJggg==")
getimgLogGrayData = imgLogGray.GetData
getimgLogGrayImage = imgLogGray.GetImage
getimgLogGrayBitmap = imgLogGray.GetBitmap

#----------------------------------------------------------------------
imgCliGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBxYQKwq1NQAAAJBJREFUOMvFU7sOgzAM"
    "PFeUCjp1YOeHrHyrdf+GaBe6JChEASUw4MmK5PM9HFF1Cy7UAxfrfoAm6t+kTaWDwbuVQc1w"
    "loGqawF8I0Cp8oC0X0qxJOKNiaRJ6eaciThzVLsxeiadquszCbS7EgA8SRNVN5A2x+lEYK/w"
    "JoH2kfZUml+wFF+iBx8BfNJFcvtv/AO6xzuPzHSN7wAAAABJRU5ErkJggg==")
getimgCliGrayData = imgCliGray.GetData
getimgCliGrayImage = imgCliGray.GetImage
getimgCliGrayBitmap = imgCliGray.GetBitmap

#----------------------------------------------------------------------
imgMoveGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAIZJREFUeNpiYMADfH3954MwPjXM+DQDqQQgNlBX11C4devm"
    "RqINQNIMA3gNweeF/yCMTw0TA4WACc3ZxLpsPrbQ/k+i18CGMGIJMDDYvHkjI7omLGYtoDgM"
    "KPYCA75AxBWNRAc4XdIBI5FJGRziwJhJJCovgNI8KO2D8gA+zcTGDt4AAwgwAJ/NRAADMlOh"
    "AAAAAElFTkSuQmCC")
getimgMoveGrayData = imgMoveGray.GetData
getimgMoveGrayImage = imgMoveGray.GetImage
getimgMoveGrayBitmap = imgMoveGray.GetBitmap

#----------------------------------------------------------------------
imgEyeGray = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIFBxYkCr5BgAAAANVJREFUOMvFkr0NwjAQ"
    "hT9CQ5ktSMkIYQArYQMyAWICYAJEBxVsQKwbADaAElIxQkagsSPrICkAiddYvnf39O4H/o2e"
    "DhiTxcAayIHYhWugBOYitm4VMCbLgX1QqFEDhYgtXwSMyaau2CdugLP7p8AsEC5E7KEReFM8"
    "FrFX5W4EnLRIzxGXIHclYpfGZEtg0REDGEfAUfXpbYeJC8V57CNn+VPUEVAokdTbDttSXLOR"
    "ziG6m4hF7KN1iD9Z4zeH1A/ZqrrfhsNkBwyAxL2+cAtM9H38H08G9Fx3i5i9IQAAAABJRU5E"
    "rkJggg==")
getimgEyeGrayData = imgEyeGray.GetData
getimgEyeGrayImage = imgEyeGray.GetImage
getimgEyeGrayBitmap = imgEyeGray.GetBitmap

