"""----------------------------------------------------------------------------
   icons.py

   Copyright (C) 2013-2014 Wilhelm Duembeg

   This file is part of gsat. gsat is a cross-platform GCODE debug/step for
   Grbl like GCODE interpreters. With features similar to software debuggers.
   Features such as breakpoint, change current program counter, inspection
   and modification of variables.

   gsat is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   (at your option) any later version.

   gsat is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with gsat.  If not, see <http://www.gnu.org/licenses/>.

   Embedded Images
   These images generated by /usr/bin/img2py

   some icons by http://somerandomdude.com/work/iconic/
   some icons by Yusuke Kamiyamane. All rights reserved.

   These icons are licensed under a Creative Commons
   Attribution 3.0 License.
   <http://creativecommons.org/licenses/by/3.0/>

   Attribution-ShareAlike 3.0 United States (CC BY-SA 3.0)
----------------------------------------------------------------------------"""

from wx.lib.embeddedimage import PyEmbeddedImage

#------------------------------------------------------------------------------
# imgGCS
#------------------------------------------------------------------------------
imgGCSBlack32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIcBzAXW6G7pwAABvhJREFUWMPll3tsFNcZ"
    "xX93dtaPXbuxYRcbs2seAdsYJBOZVC6hreMAVUKUmJYILEAKaqtQ1LRSVFVqFCA8VKgatWqA"
    "JKZpBBJNY5oSZAdRBKmKRHkZB4OhRoTXWk6wvVtTs7tez8zOvf1jH13jRcVp/+tIV+fe0dyZ"
    "M9937vnuhf/3Szzsgy9s2rQVmPZffm/vHzdv/iTzhv6wM5VS0/du3LjKtm0UIJVKt9RYZfYT"
    "kxIImKbJz958UyzfuJEPt2xJk9DGQQBp25imiWkYaTQMg5FYjJFYjNjwMMPRKMPRKNFIhEgk"
    "QiQcJhwO09vby4HNm1cppdZ+Z8OGxV+GgCaEINU0QNM0HEKgaRpaJiZb+nkgEolgAr/fsmWV"
    "Umrtt197bfH4CEiZFs2XIXH37l1MwAT2bt3apKRcu+zVVxePRwMi9XGUApHQr6YUaBpIORaT"
    "l0xqYHdzc/reV8vLm/Z9/LHnoQlIKRN/LQQSONnRQYnXS9/AAJM8njT2B4PMr6kZQ2LBggXY"
    "tk08Hse2bXRd54Njx+LjjwCgCcHXa2tRSjHT70+jBGb4/dhKZY2EcDhwaBpKKQoKCyl/9NF7"
    "44mAICMFqUigFJ/dvMmZc+eIhMO43G4WPvEEZVOmpEn85fhx+vv7eWHFCmSGAUkpxbhEmFJ0"
    "CjUh+OLOHd5vaSESDlNVWUlffz9Hjh4FKQmHw7S2tnLx4kUGBwdHCRMhUFIyrgiMEaFSdF25"
    "glKKpU8/jdvtpqysDIcQSCnp7+tDCEFZWRmhUAhNiFEWPK4ISCm7EzPFqEjELQuA3JwcLl++"
    "zIeHDrG/pYXBwUHmVFezfNkyCgoKEivmviU63hQMpkSYSWL6tER5OHP2LJUVFdTMnZv+w5RP"
    "ZIo3RUIk3qk9VAqWL1/+/XgwuGb3zp1UVlVR39CASr6kZs4cenp7aT9/ngtdXeQ4nTxeW4vX"
    "600sW6XSOdcyfEIkI/DAatjY2PiSEKJeKfWGEOInLS0tKy3LYvdbb/HMs89yuK2Nqupqnlq0"
    "CKUUcdvGME3MZN1IFaZ0P9nycnORUpKXn8/KV175KGsKli5duq6iomJdc3PzyuLi4u2WZWmh"
    "UJChoX9iWRaH29pY++KL/P3KFd56910++/xzTl26RG8oxKXubvqTOBAM0tXdzUAolMaUbadE"
    "mDUF8Xj8qfXr188LBG6zbdvWxRcudFpSJgrrvJoaKisrCQRu07RiBb997z1KvV5KPR6UUpR6"
    "vaOwxOtFQQKVSqchJUJHNgI+n+/2yZMnZzY0NEyPRqP4fD6HEAKlFBMnTiAcDqPrOm/v2cPC"
    "RYsI3bsHwI2eHgCuBwKJcSCAAG7cvo0QgpuBAOWTJ4MQ6LrO+21t18YQqKur+5GUcm04HDZ9"
    "Pt8Mn8/n6OjoMH/ww5eDZ06fKZhQXExpaSmdnZ18caePm9euke90UltbS6nXS6HLRanXS4Hb"
    "PRpdLkomTSJX1xGAruvsb229NiYFpml+a8+e5mfC4TB5eXlIqdi+/RefuubV/Ongvn2/XLN6"
    "DdXVc5g1axZ+v5/CwkJ2vv0O/qoqSjwe+oJBSjwe7gwMpMepYlXi8VDo948yojEEDMPQR0YM"
    "4nEb25YIoeNw6Ja0bQ0gNzcXIXRsWxKP24yMGKAU82bPBkhoIYVZNJHyEQBp22M1UFRUNOXQ"
    "oUPi8OHDt6ZOnVbu803Vamu/NumvrR9VXOj4dEJj40oKCly0t59l/wd/4Nz580yZMYOZVVVc"
    "DwQQQvxbA1k0UT55MgAOXWfvwYPXs/qA3+9f6PVO+vWuXc3zY7EYPt90HnlkIgBDQ/+gt/cW"
    "+fn5/Gbnr/juupd4rLZ21Jr/Sl5e2ge43xOSm1an08k3Vq8+ktUHDMP4+a5dv5sfDA7idOZz"
    "7NiReE/PDXp6bnD8+J9xOvMJBgf58cs/Zevrr9MXCtGZXP8Xr14dVTHvrx0pS06mIHspKC4u"
    "3tDQsPhWe/tVVVk5u7OoqOhvp051qVOnutSSJUvUc881qvb2q6qpabXasWOHsmxbWfG4MuNx"
    "ZViWGrEsFTNNNWyaKmoYKmIYKjIyosKxmLoXi6mh4WEVtSw15/nnjz7Q/10u1ya3233a5XJ9"
    "0+12n+7uvqO6unpUfX29OnHihKqvr1fbtm1TtpQqbtvjJhG1LDVjyZJPsmlAByYCHiAPICcn"
    "Z5Wen/+9x+bOLayrq6OpqQkF5DideLxePB4PDodj1GFEPQBTmnDoOjOffPJENiuWQBRQqZOT"
    "aZpvuCorFx44cODxzAc1hwO3y5Xw9uQGRQmByNiw3I+pKioAY2REfxCBSLKlLxvssrKyB+8X"
    "Mg+bQiT++r7jmcroC03DNAzHf9oPTAVKgSnG0FAwr6rq7P/yZKxiseC/AKsV5rYw7NE2AAAA"
    "AElFTkSuQmCC")

imgGCSBlack16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg0ngp9oXwAAAtNJREFUOMuNks9rHGUY"
    "xz/vOzPrbncTZJ0cGjB00RKdGkPbtQRJS+2CNw+yGD30Ku2/kMC2pIf0VIJEqKfeeqoIlh5q"
    "1SxJ448aMBGqNk3SZZUQ2mw2dXd2Z3Zm3nk9bAyaivg9Pg98+X4/zyPYp/cuXnwHOMh/a/bG"
    "5OTav25Onj078cvamt7pdPSTdltvuK7+rdnU1UZDVxsN/fn8vC6WSueKpdJhALnfwB4YqL84"
    "MIAKQ1QYEvg+XquF67o0m01c1+XTS5c+iZUqvDsxcfgZA6WUEIAUAsswSFoWCdPElBIhBPV6"
    "nY+vX+eM41y9v7T0vrnfIFZKSiGQQpBNp/fmlVqNQdsG4P7GBj09PXyxvLzzjwTFYjFvbG2N"
    "Vh494vkDB3jablNvtai5LknLolKrASCEACBSSkiA8fHx6ampqatBEJz47Nq1D1YfPuTmrVvM"
    "3rlDNp3GzmT26gB7dVQUCRPAMIz0+fPnPhwefn1tc3OT3kyaVwYH+ea772l4Hr2p1B4TgIRp"
    "YnQNpDkyMvJmuVx+4Divrh87dvzlTqdD/8F+FhcX8TyP/r4+2IX6F5OcbfPE84iiSErf90/O"
    "zMxcOXQo95JhpHjj9OmyYaSw7T5ecxyuTE/j+j5SCLbdLo+a62JJSRRFQnqe9+3Y2Fhpaemn"
    "ShAofv7hwVtBoFhfr3B3YYGhoSEyySRSCF7IdHnYmUy3QhhKubKycvfo0fyR0dFCrlz+qlqt"
    "rrKwMMfw8AlUFHM8n8cPQ6SUuL5Pw/N42m4jgCiKpAmwvb2tLlwYvzE39/XqvXu/Tjx+/Du3"
    "b98kDIMuPPOZd6EVhkS7V0jMzn45CfRalnVk5Ex+/qPLl085jkMikaDluoRKEWuN1ppYa+I4"
    "RgBeq2WagALqgArDcFlksz8WCoVTAKZpktztL4RAa40EYikRUvLHzs5z4m+pskB/Kpd7W6ZS"
    "ffwPxZ639ScTBkPH3uXMqwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgAbort
#------------------------------------------------------------------------------
imgAbort = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAntJREFUeNqkk99v0lAUxw9t6SjIwhgsiBlGYCJotixhM5lZ"
    "wl72svgyffWf4C/YX8CTfwCJyZ4MW+LD3syMv5bIi1kcwUHmNJmAgEKhLaUtnlMKgcU3b/Jt"
    "b3vP53vPvfdc22AwgP9pHD1e2GzA4ptkAwiidrG7gQpZcd9RH3CqHOpKxw/SM5ycu2b42C4I"
    "6fDycjS4tOQVZmcdlKHcbq9enZ9vXpyePlFlOYNxr6YyGMGCx7P3cGcnPuA4oadp0Gu1RmPO"
    "QDzu9IfD8/mjo73u8L9pwtAD0wqyDkd6dXs73pIkIZDNQqfTmZL5T1GEB6lUnJmZSRMzNsD1"
    "7IYSiehvURTu5nLmlPcOD0EURVPUpxY7OAARTRYikag+3KfhEjSAR26/31tvNuFlNApPSyVQ"
    "FAVC+/sgSRKU8JthGHidTILdbgff3JyXGESfM5bBosEwDg3X7Xa5IOvzQaFQgGq1ahrZ8JTe"
    "IMzTKfX7oEiSg5jJDEDDARXTlTALl2EAy7LmbDzPm7oxsdssxmpW38ygD/BDrNWUQb0Ogq5D"
    "7Ph4CuY4DlLFIjjpOAhQVYWYsQG6va9VKg03Bi5OwJ/X1uDTyoppQNool02Dtiw3iZk0yH1r"
    "NMq4U/Ll1pYJnyF8C8dIJ7GYme67SAQMw5ArvV6JmLGBgeXZ1fXMx3q94AWQv66vw238L1ii"
    "/gnCHoTznU5BMowMMcTaqFRplykoidV4h2HScZ6Pxnje62FZBwX90XWlqKrNgqqWLhDOYxVe"
    "UgESaxnQacyjfFhegQTA5gLAfbxcN61C+1kD+HIG8BanxS78QtWR1UYGjLXBzmv341+NLmIX"
    "JSFr/BVgAM8jHGX/y9T1AAAAAElFTkSuQmCC")

imgAbortDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMBh9N5HW4AAABdElEQVQoz32Rv0tbURzFP/e+"
    "++J7FhyeBTU0pWCW4CJ0U4xrl7dkFRw6VenSFAqFDqmgo/4nWd7iWoOunSRLMrQBK9qmVXm5"
    "eb/y7ZAgdOk54/lwhnOU8H8ZWEWh2CrTYIPnwHcuaHeuBKGPElZR1MNS80V1OZj3hNH4evit"
    "lx6fRY9APXzSellz/GJW65DZr924dRb10VAvl5rrtcTfxc68S+qv1dxmvQwaaDyrjvw3wD4W"
    "yz6wR+IvVWmABtlcCB74AKS8ZocrrtmjTxHI5hSoKK/A4y0D/pCiOEAzIfGkAgYgxxIDGgcX"
    "gwZgAkwbBvfjGHg/ix0O0WjysQymwPnwl+EdDi6HfMbB4QhFMpTzKdC+62t7gssRLi6fgI+I"
    "TXrSBiVU2A6dVlArfDMbKgd71y1aX6IBSlDMEYal5nzVD4wH+dgOR730OIoSBCW8Mizy1F12"
    "t8yaWgH5kV9mneyGW36e5gaYECPZ76z7z88FMRP4CxsClib1AuxPAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgAbout
#------------------------------------------------------------------------------
imgAbout = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAmhJREFUeNqkk1trE1EQx2d3T67mhl0otVaoEQu9oFFpo6IU"
    "9C1CofSlxRu0VH3sF/DBj+BbRSgWGhGLKKIFESw1xRgJFTSRQKBqpaGbbRqSTdckm6wz624J"
    "6FsHfgs7s///mTN7DqfrOuwnmPFgDDiOs3IHkTDSg4hmTkYySBwpUIIW1jTtr0FLDHpE31h4"
    "4uLgwJUzPf6OQBsli5s7219eJTMfoysJRS4tYiphCThyMjsIi93tU9ce3BlxiQdEVVWNFawO"
    "nU4n7OYVeeH27At5fesh6uJUtwxET5v37mR0Zlx3c4b4f+FwOACUpjx3/f7jynb5HhrI1haG"
    "B8cvDDWculgs7ECjqmmpZ8l09m16g4rHLvd29Y2e7lUdKvN4POKpsbND72ffDGNp0TIIHb/U"
    "H5QkyRjO1yefvqWeJhcw/4iKn6PxG6VS6erRkb4BZmPQea47CLMQIgPenOgRwW8P0J7q9Tqs"
    "v8vkMD2PbJnM5z78yPF2HnSGvz3AB0iz9xsx7PVqDWq1GtD+m80m+2cAHDDBJQDPeNB4Y7h2"
    "elgd5AsbsqJWVcNy4NYQtTfdIp8+OXM+xNwMBLcAZamokGbPAGMtu5yWbC4bCA4BxP4OH34Q"
    "pnmYhMUT7T4SMxeDn8tZiTStBq/TL9eyellTaJV84hd9EGvpILa58l0SnAJUciUl+zyVJQ1Y"
    "R9I8xhHvIX98bGmq4e30r+J7sMUg6O3yr47GJhuewz46zhHSGFrTgIZGxzaCTJhnfg75bYwP"
    "wIncNO9IFFlC8qjVLAPaituEzBpIHdFaLp0NEczaLlJBbZPb73X+I8AAb+EUcaash1EAAAAA"
    "SUVORK5CYII=")

#------------------------------------------------------------------------------
# imgBreak
#------------------------------------------------------------------------------
imgBreak = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNrEU01Lw0AQnU2TWGItpAexB6FVrF+oIC14VY/6"
    "DxT9K8V/ouhP8NCTRy9BD6Jgi6FoqWJbA9pskk2ycWKtBJOePLjwyGwy8/J25i0JggD+sgT4"
    "4xKHwRkhX2wpgAIBOMCwjJhEvCI01HniAzQ5bvYiqsVfhJuSolTnK5XSVLGoyooiO5SyF12v"
    "3Gvatk9pFXMuogVk2INTQgppRTne2NlZDyQp43neT1IqlQLfsvparXblWNbhfhA0YwpclL24"
    "tjZnmGbGdd3YWZEkk19YmGtcX4fHO4oR4P/KaVXNdXq9ASFjQCkFaprAMA4V5fC7N+gNJCmY"
    "9DiXUSKYhgE2Fg6PJ34jsG3ZHTQ2TsCw2x/dLmPt9pjo+5BJGFngOIwNppJIoHVbrXIOIM9H"
    "zPyZ0rcwL9FIKO2k3uk0OCH9LHpiAt9F4ft+/9G2G2Fe4hi3sCiPPpgVhOpyOl2akSR1XBBk"
    "k3Omu65xa9v1B86rl+gDPWKkHwJCiISP/DTA6grAbhZgCV2povuMd4C7G4DzJ4BbzGljjZ1E"
    "gPlfvVPC7Yg2WIgPrPFiBP92Gz8FGAAZJMfQcW0emQAAAABJRU5ErkJggg==")

imgBreakDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMCBqjDay5AAABDklEQVQoz6WRr07DYBTFf+1G"
    "m5AiNtGEYCo2BAIB9QuW8AxD8CJ9EQSTOARYMj8aDAgGSRUZDenYaNZ+XdeLYCmfAsG98pzc"
    "e/4Ywu9j/oHTBOgAPY8+Pi4xIwbDCJ4BMATo0Duyg86u27KsonibvjypYHirEc486+LwoOGs"
    "1l+L9D5cnp5HtQbpe93MmZGSkjKncHa60tc0iL/Z/gSWKHJKVmy1xdcJrliKBTnfpg2Wlrg6"
    "IZ4XM7vCwFibKwuJtRxklCQm+qpERnpQg2RM2qjhKs3GDDTCVZQF7+FiIsoUUdnkI8yDy4if"
    "HI432G7u2yfmHi2m1aO6Lh94vclrkVTMyrsy1CrIKLUL/2rzC/+ddkCtau6CAAAAAElFTkSu"
    "QmCC")

#------------------------------------------------------------------------------
# imgCli
#------------------------------------------------------------------------------
imgCli = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNqkUztuwkAQnf16ndihgjJFWh8gCgdBokfKBWhS"
    "QJuKiIYmt4AT0OYAER1FGioUBQtk8IfMjLFRFClSkpWeZi3ve/P27a44Ho/wn6E7nc4N1ltE"
    "+EtujHjReZ7f9fv9h1arFeV5BlmWI1JIU5pnUBQFlCYVCKEZWltYr9evz89PjxoXXG2322i5"
    "XPJiAooyfpojoul0eqmNMcVgMIBms8m+KJOy67GeE9I0hSQ5gJTkQLNLzgBtCiIPh0OYz+ew"
    "Wq3YOhEqbDYxYgeNRsj2CbvdhgUkLpbUaTweQ7vdBswCOyU13t8/II4TMMaB510wnPPx254F"
    "yGKv14PZbAaLxQK63S5EUYTELez3OZL8L7CWBEy5BbQolVIwmUwgCAK2PxqNMG2BgWnuWNo2"
    "3JWqUporCxwOB+V5Hvi+z5ZpzyRYFAo7uROpJFJ4UpKAxKpqAUk/iFyFR+fu3FUdWNWVQM5o"
    "VJUdOOdwr3sWoHO2NjhZPxOrjt+uMl4iY62tz70cBgNc10QpxamjqIlJEuOxNgIRhuE97vn6"
    "Lw8J3b6RpH96SPqX/IwelPjvc/4UYABrxgUeC3Nd3QAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgExit
#------------------------------------------------------------------------------
imgExit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAlhJREFUeNqkU71v01AQP3+okeOkjgVNREK/Ai1kYghlBVUs"
    "DGwdQCojylhWNv4E2OiGRAeYGbogJCaGKFWpiKqWCtokShNXadPKrf3s92zurKaK+Zg46efT"
    "3f3u53t+ZykMQ5h7+R0kWQZVVUE5hyRJywBQRtSQUxGcA4EjwiCA6rMZIJPhN+O+D0IIIpYX"
    "5rNl8lGM+b/ZsEAS3/Qc8dpnDLjngeuGkaeY8lQn3h8CAtUDzpdmxpMVbLg9aPK8AAZilC8W"
    "tArxxNA0kYDveXNmWlmcyKUKnuvCAIxxGI7Hx1IFQ5cXiR8XYOzRzelMfqPe7SFx9ULAjQms"
    "1resXrFg5IkfE8BiaTQ5kmm0rCMsvo3GxyZZEpGnmPJNrKcSSob4AwGVHsx1L9nHNhwenThC"
    "BHt4hZSuvXn/ha6zRgF+wD3fY47dtyN+TMBznB4XHNSQa2cOm4Qg2E7oeiXA65MVBdjpKc4q"
    "T47qCY15bsSPH4GxzUan308bmomjPmGOoxzu70PfsoA8xZTXRzWzaZ30iR8TwCt6t/51t50r"
    "TecSmfRjXJwXmJ5FJMhTTHmjOJ7b3G61iR87Am5btdOyVpRvPyr5e3euNes/nzqN1gI/PnZU"
    "w9C0iaumOTuV21nb2Ot1eit4rOpAQKJ/gT6afONhMrz+YCl5JbtolG/lw7FsSowkVFqGoGvZ"
    "9tp6m3UPVqSd1VfB1ocz6hsWoEkuI7IwdbcEU/P3QTMnQFIyEIo+OEcN2P30EXY/byHnAGFh"
    "nz8sIJ/vuI5Q4N8WIM4Qp9gnLgT+x34JMAAuBJ9VBPnzsgAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgEye
#------------------------------------------------------------------------------
imgEye = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAdhJREFUeNrUk01LAlEUhu845QdRUxZBhIIWtFBso2AwRAVN"
    "LqKltHCb63b9A/9AixZCELhyYdAmEyYCBcOlNa1CSQoxog/DMY3x9p5B27Zw1YGH8XrO+557"
    "59wROOdsmLCwIWNoAwFh/ugfZQKsAQV4gbNf9woqIAeuQHOgGxgIMNix2Wx7iqIsxmKxWU3T"
    "xgqFgpWSsix3fT5fK5VKPedyuftOp5OE7oz60hHsYD8UCh3k83k5k8ksGYYx5XK5rK2WzgiI"
    "rPQf5aiGakljakVRjKDrZaPR6Oi6zglVVTlFMnnMZXmdK8o2x674IE+1pCHtCFx2w+GwE9u3"
    "drtd81yJRAKdDXZ4eGSuFxb87PHxjg3yVEsaNNolg5NSqTTVbDaX7Agq8Hg8TFWLbGVl0xTY"
    "7TY2Our5NfhCQPNAWtFisdSr1WqvWCwawWBwRpKkcZyXadoN83qXmSQ50V1jGxurpnGlUqnH"
    "4/FzvItTmoo5ApjQNMIOh2MrEon4o9Gov1arzZXL5XHKBwKBT7fbXU+n07fZbPa23W5f4BVd"
    "93o9TgYimATTMHHCbB5PN9ZSf0LmrsEHRDWInvB8w/oFvAv920iFDkBzF/64fHTjvoFOxsL/"
    "/5h+BBgAwjbgRLl5ImwAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgFind
#------------------------------------------------------------------------------
imgFind = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCwkJO+fKowAAAn1JREFUOMuNkt9LU3EY"
    "xp/3Ped4th2nS0WxlSQRqUtIK9ZFZWlddFGQXXVbEBgEEXlXV11ImBP/gIIYFAj9EsmLTAyC"
    "EhPByKmlNWktnWtzc9vZcfueLnIx5i564cN78Xx5eN73/dL5G5+haaWwWq0NzNwNoB2AE0AA"
    "wJgQojeVSs0lEhsoVjIAmKa4kE6nPK1NltDRZqu/ppJX5pfTsSmf7ppfzIyYprgJ4HlRA8Mw"
    "GkyR9XSerfjSccReyYQyAGjea60sLxeJqh2Z+Vdv4p5MJusTQswVGkjV+y/da3FZ7edO1ZRY"
    "FJZzAhGIiM0Si0nh8EZ6yR/dZxjGkGEYyEeOxWLtLa49i4HfSTkA6MViNjeWRkff+tuLjqDr"
    "aWedUwvW12gqAMoXfYFYDAB21dosup52FjNgITgQ/JXMFBMbnWV2AAiupDaF4IAQjEJYUbSx"
    "iamoQwiTCg02M0JIzNLk9HqFomhjiqKhEFlVy3rHJ/SR44cTIfdBuyUrzH9pjKwJ/7ek7f1k"
    "3OlIv7yuGJ9Af7cLZgYzQ9rp6lpTSuzLEzNGZ0onUeVQDIddsv0IZtIvXsfVweGws/NEvHpx"
    "ZtBnmuZPIlrPmRARqOXiR6iqHaqqNTBL235iYPbBo8jXgTNe75PbHk/vnWQy8YyZZ3MJZLv+"
    "GOH1Vqi7T84RSVcK95AxoohEIsGurqtWr3fwbl9fj21tbXUIwAcUnq2+tXvbJb5P3wczg4gO"
    "NTUduOz1Pr3W398zsLS0MMrMw/jfIiLIsny6ra3j4cLCqul2u2/V1dWBADAAaQsZgJKHnNdl"
    "AJIsy8ccDkctEY2HQqF3tDUGF0Eq6Lz1NkcWQPgPoNkNgoXHVyQAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgGeneralSettings
#------------------------------------------------------------------------------
imgGeneralSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAY5JREFUeNqkk09qwlAQxr+XvKgFIyb+QUQqdmkvkK6KV+jK"
    "U7gRkS5EcJMDeAQ3rnqOXqBbBdGFilGsrhK1bwZjFSpUDHyZl5eZX74Z8sThcMA9l4Y7L6H0"
    "pOQomTfWfit9SnV76ff774VC4fm/7QghMB6Pv6rVqkstWPl8/nmz2aDb7YIg2+32z/VkMkGv"
    "18N0OgXVUC0B9CAIsNvtoOs6R8/zYNs2J57vL5dLNJtNzGYz7Pd7MqOfACQpJUdKbDQanEgw"
    "y7IYRqBWq4VYLIZjuwyQIcAwDI6apqHdbiMajWK1WqFer2M+nyOVSnFxLpcLAfIEoETTNDmR"
    "7MfjcWSzWR5Yp9NBJBJhOEXf98N5/gLW6zVqtRoWi8WFG7KfSCSQyWQu9gkcAgzaIEuu63Kf"
    "5/O4tj4CDHZAE00mk/y1dDrNEw8Tr61pPlQrFckfDAajYrH46DgOOyGblUqF12S/VCpxw/Rc"
    "LpcZMhwOR1SrJF7Vuzcl+8Zf2VP6oEYejudA3ggI6DyIe4/zjwADALUz7/8W+6CIAAAAAElF"
    "TkSuQmCC")

#------------------------------------------------------------------------------
# imgGotoLine
#------------------------------------------------------------------------------
imgGotoLine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAh5JREFUeNqkU89rE0EUfrOzScxuthG0gkEtVA9GQYS13qsI"
    "ngRBQax4Elu8eBZ6lP4JgiL24kFRDHiQoPQgopc2BwXpRQSDENiwtpuQTXZ3fvieZtdGoz04"
    "8PFm3pv3zffmzTCtNfzPMNPJ7LJ3F42L8BDriEdSqVUlJWilRpLeLuzP5kY6QSXzmPBswjb2"
    "nDjiXHUs4wE6b2HI+peCXwR4ihJiqe2HrwucFU4e3lndN5m/hgpukgopRIaxBHEUQRLHtOFl"
    "s9X91g8FP1Sxp5wiu4y+mW0Jon4fEiKJoi9tv9eXUkGwmfCDFXuvSJJLfyPILpGSh8Pb2FCx"
    "1gqiSEDJMR2MVbftAskfjk5HJJIxBtRhgxl5jE1mSsNwPMFmuw25fB4KVlHghao4TiAIAhDC"
    "QHUD9rPMAWA54wloUFB1JRicg+e1wfc7wFgJ4kEE1An123sYIcB38OMhSWoZosdMCHM70ObS"
    "8taG+xpo5v8gkElSw6B7Zu6U2wpiaA4E9CwkAQ7Ts647UeSwWnvTwLupjX9IWtexhMUXy/UG"
    "K5egyUvgW2X4amIJjgPvHq80KE77thKw9DPRrReOXQBePXcWfbenFq64n7oaDtgMWvce0smL"
    "cv15PfrwFEY+IC2GDlJTROwyZ67P5c7fX6u80posrdG/G2EjeJpD2KqAoykTAcIxjl48DtOn"
    "b8DnlTvq45P36OshfOo45mS9/C7AAC/XRIWgonuzAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgLog
#------------------------------------------------------------------------------
imgLog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCjQhZXhA0AAAAgZJREFUOMuNkU9rU0EU"
    "xX93mtQkNJJAKUTaTZqCpOimq+IuuhJciIhfwc9QKKHtxg8g2HWhK3VdpOBKt20WEoRKX3AT"
    "4qJNmj+v5s3MddGX2JJUvDDMcDnz4xyOEM/LavUZUODf8/n91taP64vE6OG9v7dXre4OnSNy"
    "jsh7nCqqCkCtVmPv8PD1i81N+bizczL6Z8YA58R7j4siXBQxvLwk7Pfp9Xp0u116vR4ftrd3"
    "vXOPn29srEwAnHMigBEhOTNDKplkNpEgYQwiwtnZGW/396mUy+++HR+/mozgnDEifDk6QlXJ"
    "5XIMBgPul0pgLZVKBVUlm83yqVY7Pzk4uAmwzomIUCqV8N6jquTzeVLJZCywWO/H2gkHzloR"
    "oFwo8LVe51G5PLWGn90uztqpAGNE+N5qoarUm82xk9Hx3jMjgrPWTACstUaARqOB956n6+tT"
    "nfwKQ+wtABERlpeXUdVbnSSNwV6L8LfGKDICBEFAu92m0WgQBAHlQoFOp8ODxUUeLi1dRYii"
    "WyKIUCwWAcjn86gqg+EQ7z0XYYhXRWLthAMbtxAEAaenp6zMz9NsNsnMzjKXSnE3nSaXyWBE"
    "bkQYOwj7/QTAk7U1VBXrHAr8tvaqgbgFuaYdAdJAtnN+fme0FBGMCKqKxLcBvDGIMcTaBaA7"
    "AixctFrtudXVN/zH+DBsxwD7B6PbNz1a3d2MAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgMachine
#------------------------------------------------------------------------------
imgMachine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAoJJREFUeNqkU01oE1EQnk02iTFQE7QihUKRkKTF1iU9+FdQ"
    "CoWYgAcPegkIeiiIWiHgwUvpQXs1Ggo99OYlFwUhWAhYhZJWUmhMxJbYYk1LFDcmJraSv911"
    "vjQbevPgg9kZ5vu+eW9n3hM0TaP/WSI+gUCADAYDmUwmEgSBUNRoNJ5jaKjNSyuKsqRjjUaD"
    "VFWlWCy2X0BfDJ5nd5r9KxZI0Wh0BuRgMHibcznGrrD/wD6hawwHxBdcLte12dnZGYfDcYOF"
    "hkJBpnL5F3Y0IAcMHHB1nYAj+Xw+xHeZ8FSWf1BPTw+trqY2JElyAkilUhsej8dZKhWpu/s4"
    "jY+P3+P0s/n5+f0TVCoVqlarL0Oh0KTZbCZZlmlgoN+pqgrBEO/u/iZg4IALTecX+BQX6/X6"
    "9Xw+v8e7bYqiSMvLy+t+f2AGhhg5YOCAC43+7+T1eh+srCS1hYU32tJSQkun09rg4NA0TwLT"
    "IMTIAQMHXGigbU2hVqsZq9UaNZsKKYrKoxRZKDYwKizEyAEDB1xoOk3kzo6xP4PExMT9WyMj"
    "l/q2t7+npqYevkBucvLx1d7eE9Li4tutcPjJXEsoCO+z2WxcP0GcC3zmDt8ZHj7bVyyWyO32"
    "SLHYOwl4ufyTdna+ELCuriN2nlSEC2x1mshdRZGbkchcSJaLfCOtFI+//prLbRIMMXLAwAEX"
    "mk4T+ZLALo+Ojj1PJtc1t7s/bLfbHyUSGQ2GGDlg4IALTesd6Y8JY7JarX6bzTZtsVhOwq+t"
    "fdMymZx2MAcOuPrmrSYKaDHRUbZjbIcA8sM6xQ9sADFP4xNf54/t21tnk9kKrG3qBdCLw20T"
    "//GCFbY9tj+sVf8KMAACOoVxz9PPRwAAAABJRU5ErkJggg==")

imgMachineDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsKGSg8jqKbAAABp0lEQVQoz32RPWhTUQCFv/ty"
    "i+FBIKAQLTEN+AaRohlctIOgiyLRrUKJFOrPUKxLwZ+hdPSHLkbJogWpZurQoEgEURDBLFkU"
    "sYKN7UscLJa2NHlp9L57r8NDR89wpjOc8x1h+b8knMahD4GleYSDwMdMTWBRGF4go9zyUXHI"
    "PhO5yyXN7PhyU5yxH9LvARwAfyg1XCi5o9rpsI123NFCKTXsDwEIy0m+TxSKbZI0l/Z60Fra"
    "4wUkeHo1ff8lDmyhFuanJW36PYul3+shmZ9WC1tRydVjHN4MWo2Bfd++VN/AqePp/X5jM+Dc"
    "ap23wjJw7fydHn3s4NHtHzdh962LN36hiPPkun9XQhhTGAzgqMjBYFCEMZAQ1h9PwYkLXvZs"
    "/rmCfN7QWnk9C9RBQvxV+2viSiYbkMpN5GCbDTLZeLL9ILECDvQIx0YmO0gW/XXWWfQlHUYm"
    "w7FeBEqha5VykrlipWwwVMpzxSSVsq6paOYGstoQMy39MHbJxaCdtXszXfPOVrsRSSHZyS7i"
    "EBsUB8B+1p+A3/xkzYbCIhxc3L+3/ZMmoGvNH8TKrfqjhKcGAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgMove
#------------------------------------------------------------------------------
imgMove = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsLAhXMEk8nAAABbUlEQVQoz1WRv0pcQRyFv7l3"
    "diNmQbOYOqBYWM8KxsI/KWQgkLD4DhHyAjZbzisEub6AhcKiEBkQFCy2umMeQG6RMiiKG4l4"
    "//0sVhdzqsPhK87hqI9EaCwKTWxx9CpfInhKagboJZo0AcBW7pM5dYCHFXJyIOJFtnRr5p41"
    "UzrsOH0B7si6GUl4QxIysu7dGNAAYnW3tXUPaQHQaaET6eOfAbGFg5hJ/lEAk8QUBiPgQYst"
    "3GfzM5BGNPZvjhtTUVpRsW7OnIBX39Mv5pZpSoYU28Pk7aocCsI1s5yHHx2d9/bdpjkIAFwt"
    "LwzmCAAdcxJUD7T4gj0HcQeqVEweRm4QVK/hRyV9Dt0SRYTwSI2gA/3maMUvZpj2pa8TZSqg"
    "gFSCbGn+cA3oC+A987T7Yr6aB6w5Cqp/wyVX/Kc2i3Yj3ZGNdNG2x6mgiGnxjik0zJkP337v"
    "ZgEoGXLLX6kUEU0mmHh1G0DNIw/kUj8B2jqZwW6x6egAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgOpen
#------------------------------------------------------------------------------
imgOpen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAaFJREFUeNqkU88vA0EU/mZ2WiElfobERfwBLiIhcfA/OLki"
    "cXSU4OJQcSc9ceQiEkcu4ibiUhWkxKb1o6qyqVLbre7OerMqWqlkpS/59n2T9743M2/2Mdd1"
    "UY+JkxVWM8AZBsiN1wjtSBex730FYYrQ9zuLkjA4JxdzhQKypolpvQOGYWL9NMQpPETYUHns"
    "KIzw8OzuPBwHrivhyko4X17FypwxhujmzDJpF7wTOBKaEsuPYpVQVog9XvaaFoCnIQvQl6tF"
    "9c5/i79PojRB4fUJwqaFtG0Y8UMU354BVYw69AVJa/Lyh3PO1c6jpF2iQyQEFRVWLg2bknpG"
    "Jnw9Xe/Y5PB7Ru++2J5fFTZdK288QGtqg5VJw89/wRjHc/z43rJxrgqIbEpHV/8gbGqkH9OC"
    "DUjfnKVNC5eiJCHyuVf0sIDvAk7Jeksl9SeN415Q/wJaYztsy6ROS18FjFT8MVfANVFXEGkJ"
    "NXfSk3Bwjfu4P8OdfvVydovY2h49YzSB5OtW5OA/A6RncB3Zh060VU1SUJHyXPg1h2ARiqze"
    "cf4UYAAOUhKfHcZJBAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgPlay
#------------------------------------------------------------------------------
imgPlay = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAXhJREFUeNpi/P//PwMlgAWZ4zDvJQMjI+NMIPPwnz9/lvz5"
    "/Zvh98+fYPzrxw+G6w2m+A34+/cviDKGYhBYQsgFTMgckI0gHOstZQykCxj+/48hyQCYc9+/"
    "/8MQ7ydv/PvXL4KGYDXg+/c/DJcvf2KI9VMBG/IfjyEoBoACCoR///4HNOQHw/HjjxiCXIEu"
    "+fkTpyFYDXjz7gPD46dPgfQ7hsNH7zC428qCDSEYjb++fwfTr379Z/jAzg1m6ygJMqzddP4s"
    "MHonEDYAaDsIvGTlZnjJzcagK8nBsG3lfrBmVnb2JYS9AEowQPyClYdBXFqQ4diiHWeBgTgB"
    "6P8lP59cIpwSQTEAFmRnYbg+cwnE2e9uL/lyaS3D7+dXgDIlGAYwIucFVu0ABiYNvzMg9v83"
    "Nyf8u7F5yd9X1+Hy2PINigv+XNvIwSSgco3hx4dL/87NBVmpAcQ/oPg9EP/E6wKgk0EGCkEN"
    "/gcyEwn/AKr9g9cAcgBAgAEACsnYjGRDfAUAAAAASUVORK5CYII=")

imgPlayDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJCTaOBTPwAAAA2klEQVQoz33Rv0oDQRDH8e+G"
    "80+TxlJSKUj6rW1TBZ/Ah7gXEbdNv5BGsMgjBAKC14QkCGIpguAl3e3EMWtxFsde4jS/5sMP"
    "ZsZE/p+sjnvMiKl6RRCEuxT8gMUCPm3o1KEoQ6t5vD0ABGHDjd22SANULPeQBvim4olBQv5A"
    "IFDyTsmMayt5a80AVHSASyaFcXtBJKPHY2HciW+BLQDnPBTGHfmP9iUFOGZcGLfxL3w2gKl/"
    "ccXFM6zdm/8CIKYNr6fdlcyXC/oEAmskaTAZZ2TsUBQlRE3A4fkFDI1aCaBdI4gAAAAASUVO"
    "RK5CYII=")

#------------------------------------------------------------------------------
# imgPlug
#------------------------------------------------------------------------------
imgPlugConnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NCNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NBNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8++VdpNwAAAYdJREFUeNqc0kFLAkEU"
    "AOC3lhlLS0SK2CWwpEOuf8EQhC10rSSlbQsiyFB/QH+hW/+ibhJ1CoSkg6eKCBFviyAs0UFR"
    "VklzehNjyJK2OPCxb2ffG2beDsDkQ0JPkxZvome2iOWCF/Ycji2NLfSayWQIfTK/xbYxRW/M"
    "RSqVCui6DqqqBlgNN0jkRhRr2Wy2ZBgGtFotaLfb0Ol0gBACgiBALpcrYY5/1JbL6XSabnc9"
    "kUgQv18kHo+HOJ0uIooinS+jyLgzVyKRKJFlmSYng8EN4vWuEJ9vjb5XzMXmHkTpXL3eBE2r"
    "QTgsXRcKD/tu9xLw/Nwg/27UAjK6TCYPVvt9Dmw2OzQaBoRC0lWx+CjyvPBn04ebqKnq8bKu"
    "f2DDPn8mHA47cByHzQPI52/pH/Cim1Fnj6GqopwQSdoj8fghPXN1SOy/C7ODapSinBIWb1u9"
    "bXH0jnaZQWxpHKEmOkMutIgW0DyinePRLJpB02jKfBO76Bzdoy/UY3M9U9xl3wf6dIFvAQYA"
    "XFKD1NmwcssAAAAASUVORK5CYII=")

imgPlugDisconnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NGNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NFNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+phlpSgAAAbVJREFUeNqU089LAkEU"
    "B/BnpkYQEUUIXQo6SBRmJB07xWo/UA9GYFJoehMh6xB16Fin/guhg3jI6OzJixCWdYjshxJo"
    "IHoINXSdviNTCGVbAx9m9u3u27dvZ9X0v2GBU8jCuFj/eVjhMhgMMj4L1i6FmxbhSjgOBALT"
    "xWKRvF7vNI7VoFIpJLgJhUITlUqFqtVqS61WI1mWSafTUSQSuVUrJMgmEolZs9k8WCqViCeq"
    "1+uk1WopGo3e4fyuUgJ+0XMymZwzmUwDvAIVio7FYg+Ib0OsUw8mYV+sz/jF4XA4y5/MGO8h"
    "dYv49y7DFhyIJO3DAXlJkniG/E9PTfn9fn4yBb4Ola1CVczfRtpmszOnc5UnScOSiE/BYacm"
    "fTZxGSS9fmTo5SVPRqNxOJO5n0FMhjmIwOtPCXgTV+DE7d40NBoMXe6mcvmN5ucXDIiHoADX"
    "nSrgG+nR4/GN5nIFbJT3VlCj4U1m1GwyiscvnnAw9tu3tkPO5fIyi8XJHI513oNcG7vST+IS"
    "ZRbW1nxMrDegH/qgF3pAK76/WlT+9Qo12GvVTHQEO3AODaHeNsttmjzBhwADANJmm8jvUXkB"
    "AAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgProgram
#------------------------------------------------------------------------------
imgProgram = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg86069mBAAAAdlJREFUOMuNk79OG0EQ"
    "h7/Zu4OzhXEKhOR0KdLAWzh1iiiK8gp5BiRkAU0eIFKokaiS1ChCyivgIqlIDaKxMXfHnW//"
    "pfDdBmILZaTVrnZnvp3f7KzQ2LvR6DUw4Gn78eXg4PfDjbhdOOeen4xGx7W1aGvRzmG9x3sP"
    "wHg85uT8/MPb/X35dnR02capALBWnHNYrbFaU1cVZVGQ5zlZlpHnOV8PD4+dta/e7O29XAJY"
    "a0UAJUISRaRJwlocEyuFiDCZTPh0espwZ+fzz4uL98sSrFVKBCUCQBJFf4Uaw3A4xHtPr9fj"
    "+3g8vTw7ewww1oo0gGfdboi9ns14sbUFwK+rq+C7lIE1RgTY7HS4K0uc92Fcz2YM+v0gxxqz"
    "EqDa9JUIm50OAJOiCHLW4phoAVBLRTTGqBarlCKvqgBrwWmSkEQR5gEgfgAQEWFuDOtx2H5U"
    "k0G/z3Q+x6yUoLVqn3FuDL6tgXNMi3s8i4aKRLBar8xAiQiJCmdUWtNNU/KqYiNNAcjq+gkJ"
    "i5bG+cV9znsqrXHek1cVznuUyGoJZVHEbQH/tWxe02syuNc6+LaADtCbTafrQPg8vlm3c20t"
    "zntEKRrfbSBrAdt3Nze3G7u7H/kPc2V52wDMH+TGCvd5v9PGAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgSave
#------------------------------------------------------------------------------
imgSave = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QMBCR0qtm4moQAAAkxJREFUOMudkc1LVGEU"
    "xp/rvNfGcVKbjy6D0x1jKEYcZGjCNkZBIQQSWLmLNgatopb9A6Lb0I2LFhFBNSW0Cfra1SJx"
    "iBaKUabI1FhK40h33jvnPfe+LRxdBIJ24IED55zf+QJ2sf6p0tmJJT06saQ7+6dKV3fLE7sF"
    "FFHf5qZq0hoBRVTbN4Bct1dKpX0fo+S6zQCm9weQMl7ZrLWSUgdIyo19T1CXMvrd5bznG6hL"
    "WdwTIHnr1ZRhGPkGAKtmKzx/yz9y+/UsAGiti6W7Aze2awwAGB4ePgkg/6W179SaaZ/rvX7F"
    "XvwD/K4DvtYImwYONQPrD5+uxNXK22POzAcAxUKhMGsMDQ3FEonEyNjY2LjrupieKeH+ux+o"
    "Dw7iY2WrSzoMRF48x+VcDOczMZhmEJOT43fW13/ea2LmeCaT6WZmVKtVnD7ajIs9LfCfPIYd"
    "AjpbgNCzRxhIC+QtoFLZgFKMVCrdzcxxwcxWIpGwt3eq1Wo4cVhhrdPBy8IDaA2cSUpkOwQc"
    "x0Qo1AYAiETiNjNbQillpVIpm5nhui6q1SrK5TKOt7vg6C/4vkb6YAirq2V0dDAMwwQzw7KS"
    "tlLKEkQUSyaT6Wg0ivb2NnR1pZDL5UBEuKAUPM9v3LoJQKDxOAFmL01EMUFEwWAwiMXFr1BK"
    "gYh2pBTD9/8FbEEikRiIKCiIKCClxMLCZ8zPz4GZd+R5PrRGo1jsqDK+jGvvb4KIAsJxHLNY"
    "LC5ns9mubLZnTxPINwpz3z4tO45jGuFw+JIQIo//MGYu/gWaSzpM3qF0jQAAAABJRU5ErkJg"
    "gg==")

imgSaveDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAwEJHh0l/tBtAAABN0lEQVQoz3WPO05CURiEvwuH"
    "x1WDyMMLqFcSGgnEBmLtBiw0sdLOwsINuAGivdHEwiXgSqQUiAkGGqOJCfhA4Jwfrg0FBUw3"
    "M18mGZhRdb9RaWxUT2czNWtkb+jz/PK3GNg13qQiQR4XACY5WB6HTG/hgo6PSh66Nge4vbdK"
    "IHh4CHdP4NUuzgH8cFwuHPhcVSznIxnDhHhmPdOR904mVbDqb9ZhIn12dT3khSY5foAlWmyR"
    "IsDN5eeDT5I7eeGLNVI8EyZEnSghuhiyeUkqcdIugCZClDoQwUYTAGKuOMo4264w5JcuQWzG"
    "KHrY2AiOaxylE5u5OKtoRmgM4+k9C5CcTigdDtPCoNFoDJMZIIYOK+0f0KSOIAhjvGkJJ3yj"
    "/aofqLWL2eKchQ9e2/2AtXKkSiyU1P4BlmV4dLjh4mYAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgSettings
#------------------------------------------------------------------------------
imgSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAzZJREFUeNpsU21Ik1EUPu/2OufHtrY5dJtoQlKGhKaTTcuP"
    "mZVhoG1TcAYJZv5cURqGoYIxhoFZSM38UaZYgxK0EtEfIn7PhdIPQaMCmebIj8myubm3c+cH"
    "Fl143vvec8/znHPPvYfS6XTw73A4HCASiQ7WLBZLRFFUCv5GkLXFYunHya7RaIBeWVm5HBYW"
    "JkXDEqKHOBCyz+fzk5Eo4vF4Or2+uDAu7mRyQkJCJbGrVKpd8aGhIanZbH4mFArjNjY2wG63"
    "w+LiIuzs7Pjh9XqVGs2VoqioKDXOzzG7HoVCYccgcuTLWCSyUqmsKisr02MmlYTkcrlgc3OT"
    "kAnkkZHy5Kampt7x8YlOkjoGk2OGBdvb27lEoGd+ft5UUlLSUVFRoZdIJJWEuLy8DG63Gzwe"
    "T5DH4+WVlpbmKRTJxeifFBt7rKq1tfWB0+nksPcLtbq6OjI8PMyvra3V22w2/tLS0khISAiF"
    "W6lqddYFp3MDtFqtiqZpmcFguGq1Tk/39fUNsg9Xf21tbWRsbMwvYrVa+ZhJeEBAQFhqampO"
    "aGgo0DQbEhMT5ZOTU59MJtOH9fX1txT8Z8TExFTez88vjTWbvYLrZfEFve/r8Uicve1fiG9s"
    "Nrs/MDDwB40fIOocDucAeO9fhS0tgrS6Oml3TY1dJxb//O12Nz+l6YMgKLA74zn9i30guSAi"
    "IiLl0tn0i5bHzct5ublHTthsTJLPF3nN6x31ImmGxfL7Yj2ATTI4RNZERx/NNBobb93uaH/o"
    "2nT2hc/MSE+Vl2c5bDYPAxAZ7/ON6PCWohFC8tj4fD6IxWLAqFq1+px5auozk5Z25olMJtPe"
    "EAigG6DhHYB1y2Bgxijq4yhF3R2kKHiDmXSQM+wJFGZnn38xO/uFSU/PbMMHVSiVSiGZywUk"
    "E+eG1yiyXV3NIHlggKLuHRYoysrKeTU3Z2cyMtTtAoGgKDg4+K9bIe3WjiIvUWSnvp5B8nAX"
    "QK1fAJ2NCwsOjKzu5HK55WiSIARkCxGI4CJ4pMfuADxqQxHGaGTMAFNm0mxYySIs3mmGYb7j"
    "sx1H2xbCtQcPaThEECKEiN4EKD8OoJwA6JoHaPwjwAC3pz/3riyFYwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgStep
#------------------------------------------------------------------------------
imgStep = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAeNJREFUeNqkUztLA0EQnou5i29sVPAVRBAtrK4XLUWxULBK"
    "GhvbVP6OVIrgowmiIFZiWkHExgODGBTLENSLUSImub1H1pnl9vSQWOjAx+7Ot/PtzOyuwjmH"
    "/1hUTmZ2n0FRlC2cnruum3EdByKKAmosJnif0xEGHrp2ttov/BEp4HkeYKCOSOEyQT5mWcIv"
    "ueXZPuJ1WksLBOhEQnJ+QMcxBZwLEataDbhazQvmPwQcxgRKJRuSCyO6Y9tCxMYsJGdZbjBv"
    "KsCYBzc3FUgujgkRrDfBajVfwGsuQCfZomYOjQaHXK4MK3MowlgKhUQmxeJjsO/HLUgnYw6Y"
    "pglVrL1Q4LAwG9ePs/cpkaXjhYLDGdTrAsW3dzCZC9VoDManRuDg+NpwLCtN3AeeJ/c1LeEl"
    "EoNyezfEJwfh6PDSwBLSWEJGcGr7LyX4jSlpHRAf7YLs3omBjyetalqGmkhmImd/a2BIQHY2"
    "2tkGFxv7IhheHzL15zy0TCwK7lXtCN2AMPoLhEjvBGhLO1cEdXo90dI3+VWnz3Wdck4jrWVc"
    "kEGjdDfkPuXzwCq5hrF9i64xxBu9cuR6kLt3N/E7lB/yuB5Gf0H8EfkbMeVuHFSE5mtSrtRu"
    "2tDqQ6FqCRhXCQn81T4FGAAo72Xu5YvuhAAAAABJRU5ErkJggg==")

imgStepDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJFwCV/pm2AAABG0lEQVQoz33Ov0oDQRDH8e/o"
    "JQQL8QEUhICN5ZIHsLGQ4BOktz2fxGtTWXiFkCKlYCtWcoVoAhZWQRDz18Lc7mYva5HLJWky"
    "xRS/+TAz4tleAcAN0uTJxQ6hDEgTReKvrpcgA4UCYs0ugDpXj/mGHQCHo65c6BswxeFIcbgV"
    "MBgG1JUNfUNjMCz6BjB0uFQ29I10AwQLABlz3rhQ7dAjfOXjHGjA8MMfPc7UQwgOvf6kRjNk"
    "inBKOzGRJkPnpABzAk5oJSaysc6z4oQFhGPuE4lKcQoIdv0HA+xxl0g0iQdUWWYFeKbGbTKO"
    "PuMh8E0NsLyswOiw37Wv7x2qjMlGB/2PFpPu6IgeiAdknxJlwJDiqVBBmDHzvznYVv8FwISP"
    "Lb8SGwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgStop
#------------------------------------------------------------------------------
imgStop = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAT1JREFUeNrEUztSwzAQfUIGjBNomAwFPRWdSwpKzpAWCg7A"
    "OThACug5AxUFJSUFVFAwJGRgxrHxR5Il1nZw0GCHzKRAM/qs9PbpaXfFjDFYpq1gyeYUw+Hl"
    "CIyxAS39BXzuSPXpzfHOjCBXqpj8/tGuL6X9pJ8vdByGq+uX3wpklpVGHOcIAtV6dbfLa6xF"
    "INK0NNJUYTIR9aGUElkmoJSE1hq9XqfGWgRZkpSGEJpIJKIoQhiG5JzBzpKosTZBHJdGlKR4"
    "eh1C0M1VjrgFTvQM26jg+VNg6Li06zYHga/NVzDiHsad1dYginU+X8Gb4+HDba9MQdyyScF3"
    "agzn2PQAbaYd1Wym9SBZhdXjB9rplz6siDJVIecHZxfY3tv/sw7fH+/z2/MT8lMWAa23qG8s"
    "UMqF3MAi+Nff+CXAADjrrYLxZ/nIAAAAAElFTkSuQmCC")

imgStopDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJGge+NHJYAAAAsklEQVQoz6XRMU7DUBCE4e/F"
    "oQAhKm7iS3ATak5CTckpkLhDOrgCJcIKSvxsy0sRR8mzJSjYcvef0exuCr/X6o+5NY/Sk3ox"
    "2cT9wwEYqO/qfurHpHs9OXTYawr5te4EtGhtQS8bjG61JdBpfdvKjludATvsfeiRJDDYlQ6N"
    "UXWWIeYOo4siZJo7RKGfZchYuRLG6Q6B7PMIvFT12/PikF/vm7WBFFLlxuWCyJo4AP/85g/B"
    "20B5o42C/AAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgPause
#------------------------------------------------------------------------------
imgPause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAU1JREFUeNrEk79OwzAQxs/ELQkRUiUGhu5dGDMysMErwAoD"
    "DwCPAQ/AAG/AMyAGRhYWpM6obcjfpjRpnETmnDRWraRl6MAnnc73i/PpcrEJ5xy20Q5sKVov"
    "Tp5sIIQ84NJaonfs7rqNvV4eNg2KPBfJujjrW4xxeH4Z1Y+s89O+lWUKaxpkaVrm+TyHIMhl"
    "LTSb5RBFKmsYsMWizHEsNjNZC7nuFMbjH4U1DNIkqYyY6CCUtZDnTcFxAmQbhpjGcZknfggj"
    "P5C1UFL0INMosujvDjzeAd/Yx9qWm3zNQEYUtrYDm+6BY3YgX+lg0jXBNXWFre3AQQNf57C7"
    "MoNvakKog8IaJ1H8IhGFpoFpUFmLYPj9Wrdi6deHYkDqu4AnjmrHN49wMDiqhjEcFm/3t8ju"
    "kA2W7BPZFb7DWg0w9TC6G45+gRG0GvzbbfwVYACMcsm3y4uD/AAAAABJRU5ErkJggg==")

imgPauseDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfeCREGORAW62QYAAAAsklEQVQoz6WRMQ6CQBBFHwgk"
    "dtZeYw+hN7H2JNbWdh6CG1gaE05gUAJBs9ldUCx2RV0SG6aZn8zLS2YGxlZg22aLAA7r1SfZ"
    "SWRbI5bCkAKNWIiGtDc4wCCpMIDhzg3jAwpJjQIUV86oHgjfgKF0QMFlCEgKCiQgaQmRQ0PL"
    "xBk6lzzDk9gZcMkzdP8NmpApGtAExGhvzSg/7oAqY55ne6A6kdhjBA6bkfy84EH5da1R9QKq"
    "KkucPaZRYAAAAABJRU5ErkJggg==")


#------------------------------------------------------------------------------
# imgMachineReset
#------------------------------------------------------------------------------
imgMachineReset = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVEzMIIPvpEQAAAz9JREFUOMulkF9oW2UY"
    "xp/vnJM0SZNS+ydb07RZTSmd1tU0cZhInG66UUOh1j8o1ospuF4I2xD0QtjFQASpNytuiJfK"
    "EGHDPwzWOdfIJDBtQd3somkzsiQNLkm7Jk1zzne+fK832zp263P3vrzPj+d5GRHh/0gDgN0n"
    "lqFZLNA0DYqqehhjEwAiAAbu3P0DIEFEZ6WUK6qqTgKIzh10H9IeAI5pKh3v73F0eDttbS0O"
    "zQEAlU2xM1fUo6lM7SVJlGgIceCuQblnJRqzN+Gj8afdj/e22bxMwFGvN2AYEhqYw9du88bC"
    "Hc8IIQ5MxjxBIcRWBZLSozJ5PBbZ9titlTrqXOhLhVo+V9y8DQB93c2tT+xs95eLOl7b3x1c"
    "X+MwOd9KIDif8HfbOwrZCsprG/rF33J/ZfK3j5GUIVPXQ6n06vnT51IL7i47MqlVCFNAGMZW"
    "Am4YT3W0WNpKqSRyS4vVZl1+W+uOnK5VKmCMTTLGnjz89kjw33wVre022Owa+P2AXfUre53p"
    "rCO7UsG5jw92jo+Pr8a2l05Vjap+RhlzEBGmP0ss3P9txtjCPYBKQjn8YhSzv8yjUChgaurQ"
    "0UAg0H/y5KkvSNI7UkqYnIMxFgwN+1zbtznph9lrGQBQwuFw5PfkjeyZ83EKDPhgGAb8/v7+"
    "eDy+PDc3l2y/9F5kvVSCqesjTqf1+ZqiDWWLG52mYVgAQNF1PfrlsTcDj+7oYqpqx3NHp4Wq"
    "2uHz7fDPzMx8qut6lIheMDl/1TPo66poTexmrsxNw9gAAKVerydefuOtT+JXrnLOG0h8Pq1x"
    "3sDlhUUzduTESr5n4nV3b+eRodHII3mLi2SzHTdT2ZrJeRkAlGQyeTk4NNgb2/us9bvZn8xM"
    "JoWvf4xjdM8ey3B42ON994M+PhLyJplLqVubsHj2QsWobS7KRoMDACMi7Nu3/yuXq8V66der"
    "mI///Epo6sPq0GCfowZVXRp9v6KsltO0nL5uplJ/yvy1b+Tf36flrSSICAyAFcDDAHpUVQ1p"
    "Nucu8dCATXbtdsHm8qDZvcaYMo/S9T9o6UKS1m5UARQBlIhIMAAqgDYArQDsd+a7agBYB2A+"
    "sKsB2CQi+R8GrIocunSMSAAAAABJRU5ErkJggg==")

imgMachineResetDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUTNxBX+7RDAAABzUlEQVQoz32Oz2uScQDGP9/3"
    "1TnfYdtEk3StUhsVOVi6KIeHoh8QSLGRh/DUoR+3+gPqsOoS1CVYh+5dBqMg2uhQ0WIUzUPQ"
    "Dwm2sJy6OXPT3N731fd9O+i55/QcPjzPR1j8Pza4ix0bkl+ME2cI+MGCNWMW5DSJG1dtHTAp"
    "Tw56vO4eBRoHy4nchLlgnO0sgJV03EtEahhsIyEUjxIYeO06H32eARuYfjE5Fimhq4WVtQ0I"
    "9B0KrXMmuoEOSKCPBzwrVNWPX/O3zZgaW557kfGxTBOtfaGP9bp/slTffuZ9WkekxbHL0SJu"
    "nOhtwDpZUEo89F74s/exqTYUi6lM21y0HZBSvKPItZsj4akn1hWTJiI67PJZr3IgHY9///3S"
    "OoBGKPx26U32U7yCeqTnNIfXvJodJDVxZyQoZK63ZPaEHj1QE9Y5PRXehcjr2l+Qe6WZsm80"
    "KF+SGrxv3l/tD+6PjPYb1e7qYqGVTRlSdj4yeKprtpljlhP2o/70vqEBTZKZq219M3SwQcW4"
    "Nf2B5MXp+hfFlOvUtHztV2l1frlYAQRdBNktxxzDO7p3uhx+Z1UsVj/nspt1yqxbLYGMmz6c"
    "yAAYbNLstAZblvkPcw20XZHI1vwAAAAASUVORK5CYII=")


#------------------------------------------------------------------------------
# imgCycleStart
#------------------------------------------------------------------------------
imgCycleStart = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVCTUMYH2sKAAAAiBJREFUOMul0j9oE3EU"
    "B/Dv9a6NRRLqUEQhTWpOgokk5q6CkQaiQTtEOjhbncTSQTIJBgddXPxXDEVdCkIQRTqoOLWS"
    "hhSKRVGMwQuNkWjk6GL8E8nd/X7pc1Go9NIiPnjDWz583/v9BCLC/5S0dohPr0AQhDsACpzz"
    "LGcMzDTBTBOWYeDdxf0bA+12GwDU3w0A2c0SdK0dOGPgjGEsuVPljKVAdOKfgD9xGw2OU6Me"
    "lVnWpogt0GpxFIvfMTYqq8yyUrQB8hew+8WlIVc93//jUwWtloHFxY84fsSjMtPsiEgAkE6n"
    "bzidzi2WZRXzNycGTl69jz5hFTAtFL7sw0jMrT6ZXU7ZHVUCAFEUt46PnzkdDocquq4jGexH"
    "XAni/N1ZuANuzDx+9VIQhEnbBNFo9KAoilogsOe9oqiyaZpQ5AHM5J6jzoDK9L0yc+2a7HY4"
    "bJ+0yzCMWCaTueb1DvpEsRfB5MSKKPZC8W7HlWMhOD4XXhNR1qy/sb+i3++PybJ8YWrqVrVU"
    "qpKu/6RSqUqXr9823MrIQ7/fH+vesRcAQETrukvTtEIkMhQcHk4M5nJztVptGQ8ePbWSicOO"
    "A75tvFwuF5j+tuM/EIgIicTRrNPp6pmfn/uwtKSdU+KHnsXCvtVms2ksLOTPAjAANIjIXAcA"
    "6AHgAeCSJCkkSVKEc17hnGsAWgCqAL4BMIiI2wEigD4ADpuEHMBXIrI6rfALn1AIEjDjE18A"
    "AAAASUVORK5CYII=")

imgCycleStartDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUKABWkYXgHAAABMElEQVQoz33RP0hCURTH8e/z"
    "PTKSoqXGMhSFgsxeDQVvzClaW1qDRqeGqK1VlKKhZmlxaGgsInhTRBBEomGGS2ZRGQTvD9du"
    "g6UP+3PucJYPv3MOV5H8X1qzpVF2MUVW4ODgkOoEDdDRgWxngq/ZBIJ5XSTl0h/AwaHOgu7+"
    "IB5gcf0L+QI3U08D91ickeggGqyle7vdq92hTTQcXjD0o2R7WQ3UwMpyrFRlgmn2iHB4oWQ8"
    "CTOzamH0djLsEOUYi/1iT8bvOdZnG9upYEglUVMJsUjtUmar3i2jRnh9p5yXDzIvU3YsFzUG"
    "Adl6voIZHzNGTioVDtw5f0QUzcfOv3hubORO785Xt0zz4z1AEJtXnG+g0MUwfdq4FhclUcCi"
    "zBu2FG2g0o+/lSioS9c74hMfVHn8Ak/RTAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgFeedHold
#------------------------------------------------------------------------------
imgFeedHold = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVCTUtLBS8dgAAAjlJREFUOMulkz9oU1EU"
    "xr/kvvxr0iJK6VA0qR2CaUFrUkskUSFQ0S5OQYcuDm2GCs6BgoODS6n4QG0HJxeHoqBgESFN"
    "BUFqDBZbU7RopBg1/0xe8m7ufS9cFxuSJp36Ted85/A7Bw7HIITAQWTEASXtBucf/YbBYFgA"
    "4P1vJYQQ0528+PW+dkBd1wHAe+1iv5dzgaXYz92S9+p4v1fTWrx2gMYYAKBa1VEs6o0cABRF"
    "R7nc6rUBeK0GAFBVHeUyb+QAkMuVkMlUWrw2AKMUXZUfXdn328jXD4NRa6Mpny8hmy2C0X2u"
    "EI1G5ydNrx6Qwle7PDWBfHoDfpE8dqW2NM9UFbQuoBEJTFXBVLUdQAixRyLTkZlLnr5MJoPJ"
    "gAu3py73EkLsjFIUiA0FWzcYpWC0dQ3J7/efJYSkPJ4T22dOewcZYxhzO/F0Oc5isVjKePTI"
    "uV/mMeTsVuh7pgOAsVarBWVZnnO5BgYJscEXfQhCbDjldlpkWZ4z5rYcfyQ7CtaejhsYKaVv"
    "w+HwbDL58RvndWzevQXO64i/W2fhcHi2RHornEggZgkaY2A7662AVCr1ZmTENxQIhAaev1yu"
    "ptNf8OTZCz4RClmGh0/6lIr6Qbm/mOALiwkt8+kzj98xNwMMQgiEQuOPHY5uy8rK6521ta2b"
    "o6Pue8HgheOKovDV1diNpv46gKIQgjcAAMwAnAB6TCbTkCRJHl3XNzVN2wDAAHwXQlT2eyYD"
    "AALgEABLh7oO4G/zxL36B81HGAnLxB/5AAAAAElFTkSuQmCC")

imgFeedHoldDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUKADYGBgl1AAABOklEQVQoz4WRPUvDABCGnyRN"
    "K6aIiOLmVxepm+miEEEcdOrYv2ApVHQV+hNKwQ7i4uTkD9BBULEgDlZxULuIQoUKKkYb03xJ"
    "HFqTuuhN79099x7cCT5/h/hPnwhACWELFaj6y6FaCwEP1CXV4RBAXVTdtgoBBzDRcQAwaHZU"
    "AFiAyQcWAC88dVQX0Oq9wu2UX3nuAkRYLw1svisr1OkZkUsmHiImZghISjabHm4wT25IUix8"
    "JKzAIzIzK9WSd9MJmyT79lFtcA7kYB5ESysXxxISeSQmY+WiHv/tILZOM4XLe5dtXM7sTAFD"
    "QMam8bOiVsnktPG9T005cNKxSqp+sWuAfluNto8h+CzsxGPHj+erqQ1toumc5AH44s1vA0QZ"
    "pU+eiiS9G/camwff6H6WgEQ/sSD30H2nG/gGqct2z+LvT7EAAAAASUVORK5CYII=")


#------------------------------------------------------------------------------
# imgGotoMapPin
#------------------------------------------------------------------------------
imgGotoMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAa9JREFUeNqMUz1Lw1AUvUljK9F2ET9nwUGKWpSOXVy69A+I"
    "Lv4MZycF/4NjRBQdHJzsJIWCOhRBC4V+Do1IkpqmNnnekyhE1MYHh8M5l3fefZf3JCEEfa2W"
    "LIOmGDuMFcY4o8+4Zxwz9AXPo/BS6PuaZ+xP5vPpiVxuKZZIJF3HMXs3N8vW1VWaa3uM9qiA"
    "rWShsJbMZFaFrhN6456SqWx2XRobU8yLiy22DsMb5LBwuW11Y2PRM03SOGC3VvMZGr4bXIv+"
    "DBjwnSVZVoXr0lmnQ23D8Bka/iCYyd8BDpHl6PorNmyqKsm27TM0fNRHBvC4bzvFYk3E47Qz"
    "O0tn6bTP0PBRjwo4bZfLjTfLMnDqF6Dhoz4ygIfUtYU4f76+fiJFIW84JDA0fNRHBhj8qPpC"
    "aK1qta43my84HQwN3wg9ul8D7AA9bvXksVSqkyQRGBq+TURRM/DB075sNho9l68AhoZ/FxWw"
    "zXgIQkzeFBMcAIaGvx8VgHXAqDDeuYYZgCufPv0jAHryiGgG4xL888Cs55hSv/ydHwYCJhjT"
    "3PI5aRr5HAR0g/HQMLzhQ4ABAFZU8nO4cMZ1AAAAAElFTkSuQmCC")

imgGotoMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJAP4nK08AAABKUlEQVQoz13Rz0sCQRTA8e+u"
    "C4lll0js0E3skD+wvHbw2N8g9I907h/pliIs+B8YgQgGebVYwUWDTJbVWTOcmQ5ugvMu83jv"
    "w7wZnqUBuIIT7iiT5Ic3Hvl+ZRtOfJ7xcFO8vjhIrxf9y+ci90y3DTsG9VqlVA3TX4TpUrVW"
    "oR7Xd6BcyAk8XvAQFHKU2R+hk1ZK8c4vEedYKZ00blDLIJBkWJNBEgRqaYJub+SQ55Y8Dr2R"
    "6hpAtwa+CCUSiQgHvm6ZYKbcztBB4tAZKlfPDLBBNrzxZC6ZzL2xbGww34ASqtkfW/THqqmE"
    "MoFGo9u+2OAL3dZEJvggQi10QqITahExMQFMWaFtibZX/2vYAzZHnxnQwGeW490Sd4nNIaeR"
    "+0TkkmXGmvgjf7x4ikuV35bbAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgResetMapPin
#------------------------------------------------------------------------------
imgResetMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVFAEtg8B/ogAAAoRJREFUOMt9k0tIVGEU"
    "x3/3zjjKNYMeZBG0EnJjDyczKDAoKCOsFi1Kc9NDiKCBlrVoY0FUVNii1yZqkRFGhS6khS5C"
    "rIkeBGZJUzPjDOQNm/v8pnvntFBDIf3gg+/AOb//Of/Dp7HAyWraMqAdWA9UAD7wHri/WsQE"
    "0BYoXgV0LmpurqtsalobKS+vCpWynIGBz3Zf30fg7GqRXHSBBlqrWlo2VtXXbxDTRAAdqhY3"
    "Nm7Sysqi1rNnrcBlfb7qENYbDQ01Jcui2zQ5mkrRbZqULAujoaEmnBqLeQFFqNB03ZAwpCef"
    "J1co0JPPI2GIputGccqT+QEKbGWakxKG7DQMdM9jp2EgYYgyzUkF9oIAH4byg4MpicVor66m"
    "p66O9upqJBYjPziY8mEIYI6JTffybWhaApFr/rFVT3LJ5J6l8XhNhaYtnsnxbLuQSyYzwJM5"
    "HWy5mWorKpU4vGtFvKhU4kzXt92eSM/X/v4vRKOUggCiUb7293/xRJ5uFZn4B9hw6VObct1E"
    "+7418bwPrS1r4sp1E+fOv9LHx8bSZjb7S8IQM5v9NT42lvZFumeE9brOd7ryvO2ebevXb79+"
    "m/ag687rpGfb/Kas0YdHI8PDaTSNkeHhtA+P94IzA4i6tsXpk9s6RgqUXtx7+ea7A65V4OCJ"
    "HZuv1GolBZXZTOZUGARkMxlHg+ezfYu6li0XLvYKYATFIj8VuAWLhzd6DcA+As4diEgQoCBy"
    "HKw5gFxXs0y/ncpDDyQQ8BwH5+4BeybpD0QkDPnzn7XPXmOtn343OnLVRczRUaAe+AHoAkip"
    "xLTSSsCdvsHs37gciM2KI0AJWNIBLetg/wd4egt6gQngJ6D+Ar5OOqnI2T7MAAAAAElFTkSu"
    "QmCC")

imgResetMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUUAiI4UjHwAAABiklEQVQoz12Rz0vTYRzHX98f"
    "uPGtDpKMlCSioR6mIwd2CMEugpCjP2BEtzx42DGoqwQd9CyoSHpIRQiCrh1EEXFaFkIj3Whj"
    "hal82ff7PDj1eR4PC3G+r+8X78+Pt0WDHt7mOUminPCN99tHYDXYrYz1d6c6I7dqQe7nynde"
    "b/9xrgKtI08GE70iIqlF7rbdtIr8XbMbJiQTcUGBVQoIEnGS4F71TdTyNL84RdKO5ZkoNCTo"
    "0PcVMWrEUPi+Dq8D6xtFlw6G6MBlo6jXL4HxzMTmeMYs75RFVaFQiOpO2SyDA/A2o7NPU7v3"
    "eg6/5v14vO2MJr788Od218CGNxmZTacEwymZHbYLpcqxonJcKKlFAPuVfTIg7KmtgOmcQD/S"
    "C7mSRa6kl/ICwA0ZeXmk5zerBLzoe6wf3CiPnlMW1qf6dm5o3hm8UyQBkx7hnrjvKIyzH/wH"
    "Zg0g0sYg+RACGEdhLs+vf7Krkp/Bz9PLb2wwAHeQSM7rbbbQBICDpjmW9p7JjwefOeQftQtj"
    "66mo8di9eAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgSetMapPin
#------------------------------------------------------------------------------
imgSetMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCC4PCgdjqgAAAk1JREFUOMuFk0FIU3Ec"
    "xz/v+ZzydF0kVuihg9Bpaa5hYCiBInaQuoQw2yUiqkOeuohHC6KDEBgjL0l4GIjDQJGdXCEi"
    "TDIvhS4Wbm6QT2Tvub033nv/DmtgpesHv8uP7+/z+/5+8JOoEVlJagHCQAfQCJjAFjDbKoQG"
    "INVovghMNg8N+Zv6+i7XNTR4HcvSj1dXvxnLy9vAeKsQOaWGgZB3ePiqt6urU2gaApDBe667"
    "+5pUX6/oi4sh4JV8VrcDHWow2O7qOlFN4346TVTTcHUdNRhsdyprcSagDI2SLKvCcVjI58kV"
    "Cizk8wjHQZJltVy5ydkACwxL046E49CvqsilEv2qinAcLE07ssCoCTBhPZ9IpIXHQ9jnY8Hv"
    "J+zzITwe8olE2oT1/wHmc8lkpmgYBeE4VLNoGIVcMpkxYf5UQO9MLtI7kxvtEeKgJERsNx7f"
    "QVFwbRsUhd14fKckRKxHiINTAWXTDJRNc6z79fdRU4jofiq1p2Wzh8Jx0LLZw/1Uas8UIlrV"
    "S/7JzxFJlgMnIY/C/sCb2e2kcN2pifFOt6Wt7dn1wcGO9ZWVLS2TeXkX5qpapWjogaePbwS+"
    "FkC3K8W1Axi44w/E3n0as+BmNpN54tg22UzmWIIPJ4cpRd1IPn+x9Mcal0K3AvHIUlKS5al7"
    "oL+FOmHbWFD3APRa/4M3NLfpHZ1LNg1MhKu1adg4GhkR07Dxt/6fXyj92NzCtT/aa1PvgWZA"
    "FYBwXURFcgEo/k5bqmFGAVqA8w9h+Arc/gKxCCwBB8BPwPoFY48c81fKVnwAAAAASUVORK5C"
    "YII=")

imgSetMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJC/KRMHfAAABaElEQVQoz12RvUsCcRzGP5dH"
    "ilhBgWQUKEQthtTNDkIEQUE1W3PQ4hg0twRBa2sFQS9g9B8UhQinVDRUloKHNpRIeldX/e7X"
    "0Ate3/F5PjwPfB8F1432sEAMH29csJV/BsVlh1iNj2jD3g67od+cXrGSr3pagdBiYiI6Znot"
    "bG9/X0Ap8Xje5mqIRQdNipxRxCQ6SAzUVl/6FL9DgXcsBlD80geuBKdZrwuC2AQR1OtO8z+Q"
    "yZZUhphkCJVsycn8A+ThpWG+CAQC8+XSkIctwPrmevL6yUmf3KkIVE7unPT1Uwtga3ZqNSn2"
    "iuVKTVCpFctiD0Bd3lQ0gAbz2nZqjoN9PTLerZed/YIJoDa1Re2ZD6DClLabkglj6RPDVI6/"
    "k9WmvvZTMq1t6W0b942IRyA9Dw33SszkZvX4AkA4uyzD2V/975PGhXOa2yGAHyRALxYWn39j"
    "VY6qeTx0EWyXt51W2qwieEV8Ab3lml4I+uMeAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# Joggin controls X Y Z Home
#------------------------------------------------------------------------------
imgHomeX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFxAdFFmldAAABpRJREFUaN7tWG1wVNUZ"
    "fs69ez927+5myWY3gUAAQ0giUJJ2oBK1RTsDIzW2SeMgkFRLNbQqxU4aFFqaUFSCoRBCcYZO"
    "UxUGQ0sRUKZEpFUsYpm21mlBVEqT7eYDWJLNbu7dj3vv3tMfC0gowhI2oNN9/t5zz3mf9znP"
    "+55zgBRSSCGFFP6fQYZr4lUrFxffMWNssyQJjj8d7qioqf35R58bAvv3PbfI5ZQ2cRzLUkrR"
    "5w91d/cMLJxXWf86ALz5RhPn7TzrVFWdpdQAALAsS/1+JViztFm+mQRM+15reNTplJosZo5Q"
    "SgEADEMwIEeVYDD6+Kw5S19s27tmodsltfC8CefHAEDPqYHXI5Hw/feV1w0kvOD1RvzartWk"
    "tGwZfaFlxeT8POdinmOrzWYOhvFJYIZBYZMEiePYF9r2rhmtaTGXIJgGjQGAkVm2GZGI+WsA"
    "dt8wAqVly+i2l+pmF+S7mgSBLaA0HjAhF4tLYVAKgWeR6bauCgajXZebi1KqAdCuSfLrJbBn"
    "5zNl2aPsv+J5Nv38bmAYAn9/OKYoagPLMBMdDvP9ohjfLiYTgxEjzNmXZn+oYIb6Y8nts9nt"
    "21Z+0+Wytooil37xN1lWAx0e/11tb3y0mWHJ5vfe7yxXNV2/YLwkOm9ICvzy+adG2uxixRcm"
    "ZzUbhjHIiIFg9Mjf3+9akjchY+b8ucVvEyA2ZVJWQ3dPsNLtsq2xmE1jKU0egWtWoLbmkdzC"
    "AvfWgomuZsMwKKUAIQS6bqCvL7TtnXc91ZMnZT00MsvWYBY5iKKJtVqFH1sl4bZjH5yeGwhG"
    "/8owJG6MywVEQIdNgcMHN9zLsqTJYuFy46YDYRgCVY2h3eOv6u8Pe4qmjnw6fYS5lGXJIGXS"
    "0sTv5+U6bwmHtWW6bjyc4bTMpZTiYjV0nXK+3hAzLH1g/+8bH3NlWNZxHMOfX5QQggE5Gj7j"
    "k2e1d/hNM6aPecVi4R2fNi8hgO9s6KTvrFIZ02OjJuRm7LSYORjnJiSEIBCMdB//8PTshxet"
    "Ppo0AocPNr3D82yJKHKDsqqqMV/PqeCDhJDC9HTzszarKNCrbHCGEMiKGo4ZxvNqNNZjt4sr"
    "OY6RLnxnCKLRGE6dHliUkSG9NL1kcXTIBN46sDZHVrTV48eOmP+/chv//tfJ3lqzmRuTPcq+"
    "juNYhiboTkIIVFWXT5zsXeh2WZ2SxD8q8OyU+Lb7ZIwsRw+1e/zl8yrrfddM4Dcv108al5O+"
    "Q5L4QnqRxOGIRs2iyTj8Z+/dUyZn/kDg2W9deiRIlEQkoumaFlv/l/e69hTkuSozM63fM5mY"
    "QR1aVtQj/X6l6p77lp9ImMCLv14xNe8W5y67XRh/SdYgK+oDsqwW2mzCVx1p4kxCgKGWRULi"
    "XTsc0f725duX3HmgrbHaZhOaJAs/KCHRqN5hGLR6WslXDhBSRK9YRnf9bq0py22dl5YmXhJ8"
    "TOnw9M8Jh/Ux2aPsP0yzizPPVaIh43wJtpj5Lx16a/0/9+3/+G2/P/RdVR3c9Agh4wDUdXUc"
    "Fa/aB8oqfqRrurElEIh0neuYsf5gpH3HK/+Y4XZZ8jPdUiPDEDtJ8jnWkWbOXTB36iElrJ85"
    "2d73iGHQAKVxITQt5untC39n9PjKcMIeaNm8vKgg310rK6qvqyu4oSA/Y5zFwv/RZGKuuN9X"
    "1G/B7lffxa2FOWjd+iQYhoFhGHigsgHHP/Si7Bsl+Fld1eUrFEMQCmlQtdj07u6gNSvT+hDH"
    "mYTgQGT9rDlLj1xXH2jb21AxOtux42pmjURULHjwOXx8ogt1P1mAivI7sP23B/FMw3ZMzMvG"
    "y1uehCBwVzS3psdqi6c9tjbZRwkjkUGiyGNdYzUkScSGX+yG5z9nsHHTq7BaRaxvrL5i8BeM"
    "QaFR+iaTbAIJY2yOGyt/Won+fgXzq9YgOBDCqrpvIyfHnfS1hoVA/HrYBwAQxHjGvZ2+YVln"
    "WAgc+8CDDRt3w+m0o3XrU3C50tC8aQ+OHvN89gmEQhHULmuBrhuoWVKGTLcDNU+UQ9cNLF3e"
    "AkWJfLYJrHq2FV6vD8VFuSi99zYAwNfvmY4vFk+A1+vD06tbb867UNvehvLR2Y6dNJnXqU8J"
    "SNONJ4qm3bqRkLuMm2biG4UUgc8NAUIIQ8gNiIgQEEK4RK/rCROQFbUzEIxo514UhiebDIGs"
    "REO+s8pBQu40EjV9wvhDW2OpJAmPEwI22cWIEEDTYr3ezkD9vKr640ghhRRSSCGFBPBfx9HO"
    "j7bf4yEAAAAASUVORK5CYII=")

imgHomeY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFxAr2+Mw7QAABoRJREFUaN7tWH1wVNUV"
    "/933/XbffpBNIkkqloAoEktL5CMpmIAd0kqZAYxoqRWbYrCBduSr2NJGaEQpJCGkE2ZsdbQ6"
    "jiOORWTsABOdwmCr1YKINjDWJBswoWY3JJvsvu93+weBZIVAErJ2Mt3fn+/ed8753XN/55y5"
    "QBJJJJFEEv/PIIky/PNHN39rfPbMWkF0+Rs/e7e4avvG06OGQFXN/pVuJVDHsjxLKUUs1tka"
    "6WorKd+0/CAA1NYd4EOhswHTNFlKHQAAy7A0Fu2M7Kx+rOd/SYDbXrW3zK0EagRBJpTSC04I"
    "A13viWpq9+r1axY+v6N6X4niSX2W4wRc3AMA3V3nDqq6du+vH1vaPWiH1xvx7ypfIxvX30PL"
    "t/whJy194s9Yli/leRkXTxYAKHUgim43y/LP7di572u2ZaZxnBi3BwA8vrF5sqXdBeD1r4zA"
    "xvX30C0Vzxel3zCxhuXEWwEKSh0QQvoRACilYFkBHk9ahaZ1f34lW5RSE4A5pJRfL4Gntu9Z"
    "7PNnPsNyQgrQd2VUtdM29Ng2hmEmSbL/Xp4XQSkFw3BwufxZXz794YIZ7o9F82ezFVtfXKR4"
    "Ul/meTGl/5quR7vC4TNzGz5562kQ5umzLSeWWJZpJUJ6wyLwq011Gfl3PlyWkXXbXknyiP2F"
    "qGmR984EjxUp7pT8adOLWyTJczAj67bcSFfbA5apBUe6bgyZQOnKdRNuyJj0YvrYm2sdx6GU"
    "UhBCYDsWYtHzLzU1/qN0bObkh7y+sdsEQQLHSawoujeJojLrXNup+zQt8gEhDHDxvl1eGGnC"
    "NFC7+63vMwxXIwjyhF7ZEUIY2LaJjlDLjzS1M5iVlfOEy+VfSAgTVyIl2fvT1LTsbNNQf+nY"
    "1gq3ErjvwnrfHsex+Wi0g0lIH6is2b/KrQSqWYYX+sRKoGs9and3aP75cJAbN376nwVB9g9s"
    "lyAWDX/W0xN6wLHtzNS07Nd4QUJfvyBQ1Ujrf9pOF22tKPt4xAj8fvfb77Acn8/zUtyp2pbR"
    "HomcW04IM1l2jXlSkpQ4PVzRISEw9KjqUGe3bRltkuTdwrCcu2+dgWXp6I58sdKtpPxp1coC"
    "fdgEqmsPjDON6FMpgZuWXZ5uqzHU3rSB56Ubff6MapblmWsF35+EZRk94fbGErcnNSAI7jKO"
    "E24nhEVcdvWeo+H2M0se/82D7QPZYgdaqNj6whTFE3jD40mb1z/FlqVThuWdlqZjS1LTs1fI"
    "Lt9ajhPIYIO/5JjlBFFSFhPCnG5pPlbF85IhiPIdDMP02yOME0X5zoJ5iw7XH3qlY9AZKN/8"
    "x6mp6dl7JckzPv7UTOhG9H5D75ksikqBLPsKL5igwyyCBIADw9D+ufqRgjlVu94slSSlRhBc"
    "cVfVsoxmSp3Swrlz6qdMiq9Slym+umYP5/Gm/0CWvXHB25YZPd/Rcrelqzf6fBlrZNlb2FuJ"
    "rqOKUwAEgiDn7qqrP3nqk/ojsWjnT77c9AjwdQCPn/zoU+mafWDto0stx7FeUNXIxXnFVtVI"
    "04ljr+e5ldRbFG/aDkIY70Dy2frb5SgtmYEP3q+P+/7xyb+htGQGtpQvu+J/LpdvwrTpxUdN"
    "U/0iHGp6mFKnq3eKgu2YQTUW/vH9xZPUQWmg/tCe9tzcvLdFSfHGoh1/Pd8RLLspe2amJLlf"
    "Ztmrtw6O5fDh8SOwLAMzZhZd+n7o4EsINjdgftEPMfHmqQPpghd41zJBdD3ZEQruZVieodQ+"
    "pWnd69avWfTRdfWB7VX7isekZL56LbGapo4NaxdA16Ko3HkAbsUHSil+sW4BIl1hbKvcjzFj"
    "0q9aoWzb2vDIirzKER0lCMGgxkeeFzF79kLYtn3pGjU3N6CrM4Rbbr3jqsH3jtQAqHnk7wYz"
    "ogSGgoK5xQCA9949AAA4cfwwAGBW3ndH3FdCCKSlZyHn9jz8+9MTCIVa8eHxw+B5EdNy540O"
    "AgBQ2JuFN994Fq2fN2LqN+dAkt2jh0DON76NQCAD7xzdf+H65N+dED8JI8AwDOYULgYAKB4/"
    "puTMGl0EdF1DsOlfAIB5dy3FtfrHsN9xEmG0escqnGp4H4rHj+/MX4bvLXgoYU+LCSGwdkPd"
    "V/Y2ymCUYwgECJPAt+C4UQIgPMfxI0vAMGJnNS1i9n9xG/ngGeh6NBaLhg/nTyeDGl2GFE31"
    "rr8sFETXaoCwiSBg22a4q7N1c/mmBxuQRBJJJJFEEoPAfwG1paCowC6UZAAAAABJRU5ErkJg"
    "gg==")

imgHomeZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFxEBGUPIegAABbVJREFUaN7tWGtsFFUU"
    "PvfOvfPYbvdRWohIaaXQFnwHIUB8EE2sIlVBEGkhQoUSy0NejbS7sC32YYTW2gT+gEIRaasi"
    "Pn4YEkOCKQQSTTTS8kiUoi0l3YXCdrvT3Tsz1x+00NaUvnYV4n4/59459/vmzHfOmQGIIIII"
    "Iojg/wwUrsCr8rIfH/3I6EqqUNuVX1oX7C7Ydf6eEeA86Fgl2aRdmGABOEDAG7isetSsHat3"
    "HgUA2F5bSNta2kZpTBM45wAAgAXMVW+nd0/hHt9/KACR/KotObJVriAyQd3kEEbA/KyD+dia"
    "oqXF+x0H8rNku/yxQAXo3gMAoHrUo2qnurBsZXn7YE8kI6Wc/0keKskq5RvLNzxkSbCsxRRn"
    "E5H0IsYNDlShUZjgfY4D+eMM3YgTRAG4wXvFUmKVmWJAfA4Avv7XBJRklfLNlZvSrInWCizi"
    "VOBwk3zP3HZdwxSDHCO/xzpYM/B/xuKcMwBgQzl/xAK27H13XtToqL2Y4phuUggjCHiDut6p"
    "vQ8YJYtmupBIN7OCBQxStHR/zwyNBMMW8NLsucKU11PTZbtcLYiC1JMQ87Mbvpb2dPc5T2PC"
    "k+OTPReuVselxn6OCSahdh4ezk3rPlh73+QFKTn2JPsRGkV7k+9gpz0NnjTZJs+amJb0JzXT"
    "ozFJ9ql+j3+JHtAvhbriDVnA8nXLkuyJ9k+tCdZKzjkHDoAQAkPnEPAGPrvya2u2Pcm+zBRr"
    "el+QBBBEQaAKdVATndF28foi1sF+Qgh1OaNvSUQACHjYXqGCw665CKMKIpOkLnMihBEYzID2"
    "y+1LmS94KTY5pki0iOmAelMUo8S3LfGWCVpAyzN0vkK2SYv6ViFDN2jQG8Rh6QPOg47Vkk0q"
    "xwSLt8yKEDA/U9Vr6vO+Kz4SNyXuK6IQW79xEUDn9c7fO9sCS7hhjLWMsxzuNnd3vKAvePna"
    "xba0ytzKMyETUHDYdUIgwixB6t14DGa4/R7/mwijyaJFLBFNojRQdUEIAVOZyjnfrTPeIppI"
    "ISY4que6znRQr6qrZLtcte0VV2DYApw1jvG6qpdGj43O6JturvM/vE3eXCKReFOcqRwTjAdb"
    "GrtI+rxN7VmKTR5FFJKDKX4YCQh6ZVdldd5m7/yyNeXu/mIJ/S1s3rXpQcWufKvYlWdvEUMA"
    "elDnmGDDXe+eb423rhCjxY0CFdBQ6zoWsEhNZB5gdN5T7ykTJCFIFPIExrctgAkeTxX69MwX"
    "Zhyv+6bu2qAzsLFiw6OWcZYjNIo+0HOnwQzQVO0NprLJxESfkczi7L5mHTI4gBbUfna9WvCU"
    "85Azm5poBZV7jyI6Mxq5wbNnvDzthzQ8h9+xjG7fV0iUGGWxaBb7ku/oaOmYowW0eFOsaYNk"
    "FmcDjJB8V2wikamuL12//XWy6ceAt/Mtnelaz3UEkIgAXOdOXZAH7APblrs0rvEDQV+wufsB"
    "BH3sYuOxxpmSTUpRYpQdCCNLqBuSaKZJE9Mm1Omdemt7c/tKzvkN4MCBAxiacSl4I7j8nVnr"
    "1UGbeH3Z+sdsCdZcpmpuf6vvI0uiLZHK5FhPo/UHx4vOfteKvy+6o7m1gAaGZkz3u/1mJUZZ"
    "himWmI99WLS0+PSI+kB+Vd4C8xjzF8MZws7U1UNtaS0gjGD7d4UDVihDM3Kdc7fuDO0ogcAY"
    "zqtRf+I2+Qzn4oE9zTlw4Ky2uWZQ3AiEEfUnGqCmtBaQgCDDmQGp01NCfkbYBDScbICa0hpA"
    "GEHm1kxImZYclnPCIuDsqbNQXVIDGGPIdGVC8tRJYctyWARUF98kv8SVCZPCSD5sAnRNBwCA"
    "/c6qIZXRu0ZAqEmG/JPybkJEwL0kAIfvV3DvUQIhRAkRQitAU7WmoC/Iuv4ohI08U5k/cD1w"
    "/LUxCwc1ugyJjfOQI53KdA0gEMIhwNCMq363v2BHzs6zEEEEEUQQQQSDwN9MZGX0uZaCAQAA"
    "AABJRU5ErkJggg==")

imgHomeXY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFyAfJRHyqwAABv1JREFUaN7tWG1QVNcZ"
    "ft5z7t69fC+gDYKISoIIaBKYiWIHowmFaSZxjGhJGxJhYaE1jq1t/NFpp01ipjWtUZOOdQwR"
    "IzbN2CTa2jGJMTGDTT/W1o9YLWJGvhoJ4wIuCy67e/ee0x8sdIOmXWAN0+k+M+fPOe89533e"
    "85zzvucCEUQQQQQR/D+DbtXE2yoq7v5qdPSLCYxZjrjdq22NjS3/MwTO1dbWpTK2UyXiEsBV"
    "w+hqMwxryZ49RwGgef16U+vAQLLXMLiUEgDAGZM9Pp+r5sCBwakjkJOjnF6yZF2KouyIIyIR"
    "6OZEcBrG9T4h1i+sr3/lrM1mTeN8j0YEGbARADr9/qMej2fNPfv3D4S6JJusz3abjQDgt1VV"
    "eR1FRTtTFeWFYOcBwJASCYzFpHC+96zN9kOvlHdGMQYBQAYaA5ChKIXpMTH3j2d9ZbIEFtXX"
    "y7et1tJ8Vd0RRZQ9Es2xWysAaESYqSibrxnGlRHpjEAO2+gYbl8cgT/X1Dw8R1Fe1oiSRlzi"
    "ABxCGC4htnCirGmMrYkhggBgAjCd8zQRJtVOWEIFq1bx963WlamcvxZDlBQ85pSyv8XrXf6a"
    "y7WbS7n7D273Ko+UfroFB29CBA48/viMLRbLusWadiiRMbMIcqxPCPv7Q0OlKSbTkm8nJnYm"
    "cn50UVRUQbuuVwxK2RHua2/cBH706KOZBZq2/25VfdGQw0omAD4p0W0Yr77tdtcuMpsrMxRl"
    "SwwRool4AmM/SOB88V99vvI+If7G/i37G65EdpP+sJ2Bjrq6BxWiHbFEmQEPiBHBKwRafL7H"
    "eqTs+LKmPXsb5w/xIA8JQDLn38ojmjso5fd1w6hJ4bxcjmGhS2n61DDYLckD52y2J1I536YS"
    "qTJo+65JOdSl6yXNuq58JSrqYBxjls+blwB0GcblLsOo8AuRusBsfjM2cLiDJNh1yuMpLdu3"
    "73zYCHTU1f3RTLQkJmgxAPBI6ejw+9dyYP50zn9iYcwsQ9BsvxBDguiXQ0J8msTY0ypRzOg4"
    "ETxC4J9+f91tnO9L273bO2ECl6qrZzmJfpqjqt8QUmJE73L4sm497/VuimYsfa6ibDMTMTGO"
    "bfdKOXhO160zOU+OY2ydRrRACcxNgeYU4sMWn29V8d69jnETeK+qKjdbVV9PYGx+8Ba7pZTR"
    "ROKdoaH7Cs3mDWaisuCSYDzadUvp90m5/bjH87t8Va1IV5RvKoGkN4J+Iew9uv5YfkPDxyET"
    "+H1V1Z15qnooibE5Y6IGlxCPOIWYb2Hs3mmcLyNg3M4HzykAXBfiVFpDQ9GFyspaC+c74m+U"
    "arshZe2M3Nz3aMMG+R+v0aaNG5V0Rfn6tLHOA9cv6voDg1KmzzGZNiZzvgyTcB5BcollrKDV"
    "av37rwcHTzj8/mqPlP4xEZ4Noh+js1P7r3ng3u3b/V6ixh4hrgSia/QK0bbL6SxM43zeTEX5"
    "OQfiw52QpjGW+R2L5cMB4Op5XbcJoF8CUg7nmI5uIapo69ahkM/Am2vX3lWgaZucQjhadf2F"
    "AlWdHcfYcWUCeh9PVh2UEl7gnla/PzaDsUqVMfM1IbYvfOkl+6TywNnq6tWZqvr62Jtm3fHj"
    "eLWlBXdNn44PysrAiCCkxLI33sBHPT2oyM7Ghd5enHE48EpJCR7OzBz99lhnJ1YfOYLcpCT8"
    "qbx81CEd2JS8a9fWcJcS4maRf37pUuQmJeGsw4HG5mYAwJ4LF/BRTw/ykpPxfFERbHl5wzXU"
    "pUuf+fattjYAQHlW1tizocvnnmPhJnBTRCkK9peWIs5kwtN2Oy47nXj25EnEqyoaS0uhKQrK"
    "br8diWYzjnV2os/jGXZSSrzV3g4CsOaOO774cjoYmRYLfrF8Ofo8Htx38CCcXi92Ll+OzIQE"
    "AICmKKjIzoZfCBy6fBkAcNrhQLfbjaVpaUiNjZ1aAgDwycDwM1bjHADQ1t//mfHqgIx+E5DR"
    "58lnSgiccTjwlN2OL0VF4YOyMqRER+OZkydx+urVUZs58fEonjULf+nuRofLhSPt7dA4x4q5"
    "c6eWwKCuw/ruu/ALgc2FhUiNjcXmwkL4hUD1sWMY8PlGbW25uQCAn506hea+PjwwezbiVHVq"
    "CWxsakKry4XFKSl4ZN48AMDXsrJQOGMGWl0ufPfEiVHbkowMzIqLw68uXgSAUfvJYNKP+vri"
    "YtQXF9/Q/87KlTdGiwiVOTl4xm5Hsqbh/vT0qXvUTwRuXceZwLmoW7AACmNTvwOhYsXhw2i6"
    "cgXJmoYnFi7E9/LzwzJvyAQIYIwIhpxYJXR4xYqQS2wCTAhcx2GTkEvKT3oNQ7+VmmNE6BfC"
    "3WUYTfTkkyJUwiHjHzU1D8Vzvp4AHu6KNPBrpvdjv/+pkoaGZkQQQQQRRBBBCPgXhC/Lzh0o"
    "p7EAAAAASUVORK5CYII=")

imgHomeXYZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFzQB8bAYnQAABLBJREFUaN7tWG1oHEUY"
    "npndnd3b3B2N+SjXkFL1R605G5fLx/Wo38RSidiGQqNpMVRJoYqgkF8qWsQqRNtYUOlPkSql"
    "1oL/KmqoVbgmuYBoEqsotmmaJodyH3t3sztf/mn1cjYll15ixX1gfs0y8zwzz/POzALgwYMH"
    "Dx7+z4DLNXBHR4c1Nzd3mFK6avXq1TuGhobO/WcEWJa1lxDyrhBCAQAAXdcvmaa5Jx6PnwIA"
    "gPb2dk0IUXO1HwAAIIQSIZQZHh62y5kLVZL4wMCAalnWc67rvl9MjhCyJpvNnrAsqxcAAFzX"
    "3W3b9oxt2xeL2rTrup+sX78+UM6cyo2SjkQicGZmBsRisfDw8PB+xthLnPN5OwshBJxzLITY"
    "1tjYyBFCtxFC2iGcbwDGWL2iKN8lk8kfFzu/eqMCEomEjEajW1Kp1CDn/I4FvQohEEIAQshr"
    "mqZNl5K/AnqlrZyFIpHI9kwm81ExeSklwBhz0zRf9/l8xxH6exohBHAcp6FStl2ygN7eXqWt"
    "rW2b4zgfc85vKe7TNC3t8/keqK+vPyKEOFJdXd2FEGLLUTCWJGDTpk2hiYmJfalU6iSlVC/u"
    "wxifra2t3UIpjU1NTV1gjJ1Kp9MRwzB2qap6/l8XsHXr1ttt2/4wk8kchhDKvwZCCOi6frSu"
    "rq4vlUr1FgqFNznngHOuMMZe5JxHq6urd2KMR6867VrjSynlslWhcDjcmU6nj1JKI8XnCEII"
    "mKa52zTNL7PZ7MuEkJ5SHlJKi1K6RlGUA4qi6IyxcGmQEULMMIyTly9f/qniB5llWc8QQg4K"
    "IXCJ3wsY44eDwaCaTCY/ZYytut64hmH8YhjGLinlmlwud4Kx+dHAGF+qqqraEo/Hf6iYgHA4"
    "/K0QIsY5L12xpGmaT0opN7iue6A0DwvWblUtQAjfQwjNUEr3CyGq5tlCUYBhGHsdx/lgfHzc"
    "WbKApqamtbquv5HL5Z74R3gQ+jUQCPRzzhvz+fxBIURZeUII2cFgcE+hUKhhjO0TQtxVajtN"
    "077Rdb0rkUgky85AS0tLE2PsM8dxHixZHSmlFDU1NV3ZbPZp13VfEEKUfaeSUmJK6XYp5bm6"
    "urq3Oecu57yl+BshxFop5b2hUOj07OzsH4vegWg02mzb9klK6a0lqwYURenGGG+glN5HKb2/"
    "zKKxkKUSx44du6enp6ePMTZYmguE0G8AgD6/3//FyMiIvG4Z7ezsVB3Hefwa5HN+v/8RTdMa"
    "8/n8867rVoT8lTtQpLu7+/tQKPQ1xvip0kMPQrgOQvgKIcRY1A60trbeSQj53HXdBgAA1zTt"
    "QkNDw2PT09MPMcYOVYr4NXKRDwQCOyGEtel0elBKGQQAQFVVz/t8vo7R0dGfFx3iWCx2dyaT"
    "6dc0LWma5jupVGod5/yr5SJfXIEURWnz+Xz+QqHQK6XUMcaHxsbGzt7QOdDc3LyDEHJ8JZ6J"
    "CKH+ycnJtyp6lZBSihV86tLNmzejigq4WeEJ8AR4AjwBngBPwE0nVkqpLfDja+mkMMYXNU2j"
    "y01eVdW8aZqnz5w5s6irS1kvqY0bNz7KOX9WSqksix0Q+t3v978aj8cngQcPHjx48LAI/Alj"
    "LDoY63Xt2QAAAABJRU5ErkJggg==")

imgPosX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFiEHLqQxiwAAA/xJREFUaN7tmW1MU1cY"
    "x3/nItKhazSyipWUFoW5l0ZpGOyLmTEh2bLLEk1QVPxKwqctccwyCoFQqgvJRN6FMslcwmYW"
    "w5bs0z4uwxICIYEpxggtNdkCE9gLjBm8dx8qExHZpW/apf+kSe+9PT3P75znf+65z4W44oor"
    "rrhCkIh0BwUFBSqA2Wymqakp7P1JkQZQVRVVVfF6vZSVlakxBwBg3KUnOTmRsbExysvL1ZgD"
    "MLz0Io6z+SQnJzI6OkplZaUaUwBSQiD1lyGGh4eprq5WYwYgQXrk3WWIwcFBampq1JgAENLj"
    "i89KiNraWjUaADnAq0F8TqyegZUQL+g2MTAwgNPpDBriP9fl4uJT6tzcbyHNwOFDmeQfzlrz"
    "mvP89/y1uERubi4Oh0OEG6BQluWrxl16TGnbQYAQIESgmRDi32Px8HjlbwSQuDmBQwf3rtvJ"
    "MkReXh4VFRUinADHZFn+KjfHxJH3rBH1SbAQmjygqmrEje6wBzzR399PXV2dGl4Tq0RFDns+"
    "ug1CSM9R/ABUbhBC0uIRLSlktZVitZU+Hkz151htpRw/dQ5FUQBQFIVjJ11YbaVU1VwJGSKi"
    "N7IKexFZmbu5cXOSa719AFz9+gdujvnJytxNhb1I00y4XC41RBMHB6DTbebT+hK2bNFxsbkX"
    "3+QUTS3fsnWrjgv1JSQlJWpKJ4/H81SITaGM8OqUWX1uZKiNdJOBmqpiPjzr5uTpT/j9jwUu"
    "1JdgMhk0e6K86jtGR0ee3V7o519mAEjSBUbcf3dac9vOy57Altywk7DPwMhQ2xMjv/IcwE83"
    "fFxs6mXHDj09V+ycOH2expZveCPnZV5/LX3d/3d3exifuEdGRgYNDQ0i6jOwsLBIWXkXS0sK"
    "Z94/wk7DNs58cJSlJYWPPu5ifn5x3eDvjAeCb2xsFM9kFap19eD3T5N9YA8F8psAvPtOLrbs"
    "vfj90zjP9YQUvJa90HFZlr+0HUij8Oj+qNzI3N393Bn/VVPwIXsg/MEHRt5isWgK/rkC6Lwc"
    "MKzFYtlQ/UgTwPz8fQaH/E/NQkkSCAnE8nchSEiQeGWfIaLBawH4U5Ikbt2e4tbtqaBH9+38"
    "fbx1cM+a1zo+8zDhvRd05U5Lg2IgNchNqU6WZed+q5Giwuw1gr/OhHcGs9lMc3NzUGVHLSn0"
    "RagPW4ryJPulrut4fTOkp6cHHXzUTKys2g1ecvfhnZzFZDLR0tISUsE3OgAPHgG0u/vwTc6S"
    "lpZGa2tryNXq6AA8fJhp7+zD55/FaDTS3t4ellJ7VAD+vv+Ato4fmbw7R2pqKh0dHWF7TxAV"
    "AK8vsJ1OSUnB7XaH9SVHVJ4HAPR6Pd3d3YK44oorrv+V/gF5y32EC6U7RwAAAABJRU5ErkJg"
    "gg==")


imgNegX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFiEWRBQReQAAA/RJREFUaN7tmV9MW1Uc"
    "xz+3G1LZZGRAh4x0o9t4I3E86HwwMSY8GOeDJipOTXRqDYGiycSBWxcI0MWQONbKH6HLiENx"
    "YiZCTUyWLJpFAkQQ0jIaDeW2JbAMBzoDQYR7fBgsdMNRub1sTfpNmrT33/l+zvn1/H7nXIgp"
    "pphiikmFJK0ebLFYhCzLAHR2dmrWjk6LhxYXFwtZlhFCIITQdAQiDlBaWiq8Xi8JCXGkP5yo"
    "eQhFFMBqtQqPx0NCQhzHj+ZiSH0oegDKysrEwMDALfMAuk1SdACUl5eLvr6+EPMAm3RRAFBR"
    "UbGqeQBpAwA2q7m5srJS9Pb28qB+8x3mbxuBl4HBdTSRAPysSR4IMV+Su+o1Fy/9yqUfflPV"
    "w0lJ22hp+VyK6AhUVVWJnp6eu5oHyH0qi7g4Hf/MLyJgKS8AYun7imPL+WLlNYGxacYn/gR4"
    "AWiLCEC45pf15BN7193733S4GZ+4cddI0WlpXq3CyeK6/2tev0HmbxJEaBpdad66UebD8782"
    "gBrz1rLPyM7J56VXTqIoCgCKovDiIRvZOfmcKD8Xbgit7z9gs9lU9fyxkjyy9u3kynCAC+1d"
    "AHz19WWGvUGy9u3kWEmedpnYZrOJ7u5uVWGj1z/Ax9VmtmzRc/qTdvyBazhqO9i6Vc+pajPx"
    "8XFrjICKTOzxuFEUJWzz2Tn5Ib/d/fUA7DIaKD/xKu8fdXLotY+48dcsp6rNGI0GbWshg2EH"
    "AE1nu1U3MnF1CoB4/c0eD45Nal/M1dTUSCaTCd/odZzNa0O4++tDPssauuLntKOd5OREWs+V"
    "kJq6DXvtt3iG/NpXo3a7XTKZTIz4woO4XbOzcxSXnmFhQeHIu8+xw5DEkfeeZ2FB4YMPzzAz"
    "M6d9Oa0GosLWSjA4yf5H9vDswQMAPPP0o+Ts30swOEnlydaN25UoKioSPp+PPaYU3nr9sQ1J"
    "ZG0XBukfGMPlcuUB51WVEna7XcrMzGTE9/u6wum+WJE5HI4liOsRmZ3uyYrM4XBIFotF+EZH"
    "aTrbzdtvHAjrvmHvNRYXFYQQKIpAIBAKKIr4z6pnZmZeu525wsJCIcsymbuTMR9eHeLHyyN8"
    "f9GrLkR0Ojo6Og4C30UUIBRiO+bDj99x/su2Xxh0j+NyuY4Dc+ucZK4CLREfgWUVFBQIv9/P"
    "7l3beefNUIgvzvfjHprA5XLdv3ujtbW1ktFoRPZP8amzK+ScovG+aMQ2turq6qSMjAzkwDQN"
    "KyCUxSgBAGhoaJDS09PxB6ZpaOq6tXiJGgCAxsZGKS0tDX9wmvrGn/h7fjG6AACcTqeUkpJC"
    "YOwPZP9U9AEANDc3S4mJ2r8biCmmmGK69/oXOn7ErfS+mBYAAAAASUVORK5CYII=")

imgPosY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFiEmYs0h1QAAA+VJREFUaN7tl0tMXGUY"
    "hp9/Zk6wtCAXrbFARRMUw1BSpQO0YBmKtYVYYkJcNAQLZAZIxYWjKd1IKNEhEdwpKFFqwq7R"
    "NDVeFi4oVRgulWlAWxf2xsBAoNAaTWzonN8FBaEw3GZOLel5k7P5/tv7zPf953wDunTp0uVP"
    "TqdTOp1OqeUZQquNi0s++PTPqV77nTvTxMXF0dTUpMlZBu3M99hVVRIW/gRDQ0NUVlbKDQHw"
    "n3l43pyHNbeciKjtmkEITcxLSErO5+lnUubGOtpPcnPyOrGxsTQ3N4sHDmC++eSUQzwVb140"
    "51z7SaaCDCGCaV5K2LGzgLjtSX7nzkIE62IHvMGbbzlPe653F0gJO1ML2Rbz7IprzrV/ydTk"
    "taBAiGCZ3511hMiobateGywIEQzz1pePEhr66Jr3mIUI5E6IwMwLDuS/g9GkrDuLgUKs+Ttw"
    "rLq+a9Z8fsHxgMwDhGyKJSw8Bo/HQ0VFhdQU4Fh1fdfvl1zps+bny15qwV5qWRB7/8Qb2Est"
    "9PX+uCA+ONCJvdRC7XuHsaTtw5pbRmRUPB6Ph/LycqkJwHLm/cmaUwhAd9f3C+Lu/g4A0jMO"
    "zsWysouJjIpneHgYu90ugwpQX18v12oeYFfafkI3hzM40Mnff90CQErJBXcHQggs6a8smD8L"
    "MTIysmqIFQGcTqd0ubqR+C+b+aUzP6YoIWRmvorP55sro6tXL3Lr5gTPJaYSGbl10XlZ2cVE"
    "Rc9A2Gw2GRBAXV2ddLm6Acg/dHxdl3Sv9W4ZuX4A4EL/2bvlc8Dvmsy9MxBer5eysrJlIUz+"
    "BmpqamRf33lU1UdaRuGScz77omfBL39vDODxrTGYkzMYHOhiYmIEd/9ZFCWEF17MWRbcnJLH"
    "+Z5TjI2NUVJSIltbW8WqARwOh3S73fh8PgBcnaeWPCT6sTj2vFSyYhayrYUMDnTx7ZnPGRm+"
    "TOquXB7ZtBmAy3/8wq8D3yFV1e/68fFxioqKZFtbm1gVQGNjo2hpaVFHR0eFqqos9Xi9Xm5M"
    "DK2qjMw79hAd/SQ///TNTPnszpsbuzF+BamqJCYmoigKJtOMJSEEBoMBo9GIoihUV1eLNZWQ"
    "zWZb9n7U1tbKycnJJctp0UUzGMjKfo3TX33ClrAIkszpi3qBhoaGdXUFmvylvFe3b//DtSu/"
    "AZCz73WMRtM8/4E1xCatzX/04VEuXexlS1gEufsPczD/SFAbes0B3n73Y033vy8ltGw7LMQG"
    "B9joGQgUwbDB/T8IJaRnQM/Aw56Bh/w1uu5WwmCYYT/z9Yn/9WscEL7D4ZDT09MBAyQkJFBV"
    "VSXQpUuXLl33W/8Cr8asVJrlwa8AAAAASUVORK5CYII=")

imgNegY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFiE0kXRQnQAABABJREFUaN7tmF1MU2cY"
    "x//vOT1ToBVK1/JVLiYhw8zsQ6C0m0ZxzjnNNCrbxUI044IbZUtWLsqNhJF59hG2uSzho1HY"
    "wpK53bCJmzOQITr1FDbaQASzsBY3sIprESGDEc67iyoLYGvPOW0c2fkn56Ln9HnP73+e533e"
    "c15AlSpVqlQpEFESbLfb6dzcnGKI3NxcVFRUyGLRyL1pbW0tFQQhJk/R6/XKjpVtQBRFAMDu"
    "fUcUwXt+OYURX5/seObhVzFVFM2sbPz/QgYoVnoGqJoBNQP/6wyobfShG6ArfQ6oC1mc9M7b"
    "B1FeZkFvT8ei8wP9F1FeZkHNkddi0kbDvo06nU7R7/cTURRxv2N4eDjiwMVbS9ByohbCpe9R"
    "ULht4by7rxsAYLW9tCgDlZWVlOM4aDQhJEIIGIYBy7LgOA4Oh4NEbcBut9P29nbMz89HhDQ8"
    "mh32WmHRdnx18hgG+i9ieuo2krTJoJTC4+4GIQQW64uhMYyPwe8fxNDQUMR7lZaW0tbWVhKV"
    "gbq6OlJdXU3dbg9EcR5FthKY0teFHby8zLLod9MJFzhuFTZufBlnf/gCvT0d2Fy8Hz7fIG5P"
    "3ELeukLo9SYAwNqcDVibs2HZmBMTt/Cz62tMT43DaDSiubmZSJoDNTU1pKAgHwzDotfVJqs+"
    "NxeXAACEy2dCHy995+6Wz44Hxg54vsP01DjS0tLCwkf1TczzPBUEFyiAXburJJv45KM3MdB/"
    "CUffb8Onx97C+M1R1H18BqsTksLGXDj3OQJ/+pCRkQGn00kUdaGqqipitRaBgOL0N7xkA1vu"
    "ZuH0t8cxNvobnnp6U0T4810h+MzMzAfCR91GHQ4HeTzPepkQ6SbWP/kcDIYM/HThVKh8nt0Z"
    "ET4YCME3NTWRmK4D773rsMkxwTAMNm3ZCwDQ6lLwxHprRPisrKyo4SUvZHJMzM7OYMR7BQCw"
    "9flXwbKLG59L6MSPHccRDPhgNpvR2NgoaX9I1mbS4Tf4tj+uCXsoJdixqxKshrvv/z784BCG"
    "Bnug1aXAatuJ/a8cXmbgfNdnCAZGYDab0dDQIJlH9s7cvyaA4hcOITExWfIYSuEBgJVrwCV0"
    "frlt+8Fn7kyO5nmHe2A05SAhQScZPjs7Wza8IgNLTfw+4oZWlwbdGoMk+Pr6ekX7s4oM3DNh"
    "sR3I/HtmNP/62BUkJKYiOdkUAb4FwcC1mMDHxAAAeNyd7fdM+K9fxarVeqSkmMLCK6n5uBhY"
    "auKG/yq4R9ZAr09fuN7d1YKJGMPH1MBSEzf9v4LV6JCamr4Ar3TCxrSNRtKB1482TgZd5aII"
    "JGkNuDN5I2Y1H9cMLMvE7Fj+zF+TcYOPu3iepzzPU6hSpUpVOP0DD0i3ytA92g8AAAAASUVO"
    "RK5CYII=")

imgPosZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFiIGco5S3gAAAv9JREFUaN7tl01PGlEY"
    "hc+9wlITv1Ip0rpB2WvQ/oSuumwV0qQxmUJbu2EhSW2IUTtsXDaKLKyJKbhzYdo/oBVkQz9Q"
    "XDSlggwJFZrarpC5XVhjJcMUmRkpyZxkNvN1n3Pf98ydC+jSpUtXNfE8z3ieZ1qOQbR68f0H"
    "LwI/ijHu5KQEi8WChYUFTcai2sHvcKLI0Np2Del0Gm63mzVFBc7hgWH3EABgL5TF98KBJpUg"
    "msAzYNg1dOHamYne3l4sLi6S/86AHPyZkqEsiiqboGrCMxl4ALCNXkd7xw1kMhnVMqHYwJOn"
    "/PoZvF0G/qKJm6oFmyiFzxxE79QKf7GdBBQLXxUHmzQCvtKEkkwQZfAEdtegohZQauLSGZj0"
    "+rfVgj/NhAmtbWZkMhm4XC6maQUmvf7t/WRkRAr+2e0pAMDc21nJ81L6+95kKIdiIQWz2YxA"
    "IFAzl0ENeDlVGvq0mcAavwZCSUUlepAMAYeHKXAcx5aWlohqLeT3+1k98JVKbJ3Dj02NSrRT"
    "D9o7+pDNZsFxHFOlhXieZ9HoDhgA+8PBmtujcvYTW7sI8+E/8GOw2QeqPrcfzqFwlILJZEIw"
    "GCR1V2BmZoZFIlFAAv4y2n13Du947pCFB4CBez3o6OyDIAgYHx9ndVXA5/OxePw9RLGMkUfD"
    "/4SsFuK9yB5ez4ZAKYXD50D/oLVm4x9WPuPXzzy6u7uxvLxMag6xx+Nh8Xgc5XIZALD9MiI5"
    "QGeXBf13zbIQobkwKKVw+hywSsAfb3Yh8fENmChWfUc+n4fT6WSrq6ukJgPz8/MkGAyKuVyO"
    "iKIIqUMQBBx9SwOQN1A+OZ2EV1Mrkhk5yn8BE0XYbDYYjUYYDKdIhBBQStHS0gKj0Qiv10tU"
    "/ZWYnp5msVgMtx6PKFrIUuvHEA4T2NjYqItFky3l5VZSZduChhtQuqVqvAE0uQFCmryFCJq+"
    "hfQQ659RvQJ6BfTPaAMtGOp2TqnsXuGqVmNF9j0eDyuVSooNWK1WTExMEOjSpUuXrqvWb1yb"
    "fuGUEfTyAAAAAElFTkSuQmCC")

imgNegZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAXgBeAF6UkbWcAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcbFiIXGD5yLAAAAvpJREFUaN7tmMtPE0Ec"
    "x78zbU96IAFC6MNbkXtrW/4ET3ozUkPiRYmKl5LYRkxDeCxejUlbeiBGYstNEx8nbqBswQhK"
    "eSQ0PIS1htiaAhEk3fFQGhWo7DNI2G+yp2Z2P9/5/n7TmQEMGTJkyJAKETWDA4EA293dVQ3h"
    "dDrR1tamiMWs9KNdXV2M53lNZnFxcVHxWMUGRFEEADTd9qmCF17tYHnpg+Lx9PirmKkaTU82"
    "/v+QAMNJT4AZCRgJnOoEjGX02A2wk94Dp/2PzKwn2/2LHRV/63nTrckyWtFAPB4Xs9ksEUUR"
    "hz2ZTObIl5chy5oeSWOIGwKh5EAC7e3tzGKxwGwuIRFCQCmFyWSCxWJBMBgkkg80gUCALSws"
    "oFgs/hOwusaBhis2STOVHk0j2VuCb+64ikZvIwBgY6QG6U+vwfa255VUVVWFwcFBIvlEFg6H"
    "2eTkFESxCN8tr6xS2T/z6dEZJLnkHnwzGj3nJZn++CSDrc111NbWYmBggMhq4s7OTuJ2u0Cp"
    "CeOx94prdObtb3j/A79k+PlkFlub66irq6sIL+lMzHEc4/kUGADPTZcs+NmxWTzrToBSCn/Y"
    "jwaXUzJ87tsS6uvrEY/HiaplNBQKEZ/PCwKGVFReEomeJCiluCYDfi5RgrdarUfCy7qVuBfs"
    "ezc/N+ZjjMDT6tJsGd0Pn8+V4Pv7+yWxybrKUGJCqsrwNpsNsVhMMpfsuxg9TEw//YyNwhrs"
    "djui0agsJtlbiYd9wSb7Oe8LQuT3xOEz/0UxvKIEyrpzl3u+usJfYgzwtLoVw+dzy4rhVW3m"
    "Hj8KXS4lAaSiE4rhHQ6HYnhVCahJ4k/4SCSiisGk1kCKH056mlqsP7fXXGsTAmxu6xHwAvK5"
    "FU3gNTEAAFOTwy/LJlYnBNgrmCjDq6l5XQxIMTGbEPBdY3hNDRwwMS7AfsH6F7zahtWliQ9T"
    "y/XeWCGfuiGKwJmz1dgofNWs5nVN4EASO4Jr+0dBN3jdxXEc4ziOwZAhQ4Yq6Re9P4GeJtgd"
    "ZgAAAABJRU5ErkJggg==")

imgSpindleCWOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgSACk3J1eMtgAACDlJREFUaN7tmV1sXEcV"
    "x38zc6+vd/fu2mubTUJonJCkH5QkFBVk0lIBFQgUqlZFSH3hIaBCxUMFCIiEeOXjKRK8gIoA"
    "9YkGBOKzJTiVEiU0KE2bNiYtcb4/bCfxZ2yvd3N37gwPHEurxXbsrB1RkSONbN871/f8Z/7n"
    "nP+ZC3fsjv1/m1qB/5cFUiAC1gABMCPjOlD5XwRQBDYD9wB54BSggceBgjh+HTgPvAqcAJLl"
    "eHHQ5PNZ4AHg48CDwHsBD/QCw8BngHcBVhy+BjwvO1SWMSx/33YArbLinweeAtqBUJzaCFSB"
    "FiBX94yWeY8AdwNjAvY1mX9bAGSB94sDbTIiGfVORsJ7J9cALgnADwOPyrW7gT3AfqHZksws"
    "cX4O+BjwxTp+XxUHuyWmUmBCqLEO6Kq7/g8B9SCwScCvA1YLsMtL3Ykl7YBSaq1S6knv/We9"
    "90UBMAn0AxvEGSOBXJDVn00UIwJqI3BX3eK1yaJEMv8lYGqxPuklAmgPgqA9iqIwCAKA9wBb"
    "JHD7lFI3lFItSqlYKRUHQZC0tLQQBAFKqQGJiQ2StVRDPH0EeEwWYdkplAPe573fGEWRymaz"
    "NgiCnPe+LU3TNiDRWg+HYRiFYZhRSl0BThQKhdFisRgZY65ba48554oS+G0NABwwLRQ6Cgws"
    "N4AtwJeAh5xzU1EUXYiiqKy1jr33Xc65dq31ZC6X68tms6e894estW9v2LDhQHd392ml1GuT"
    "k5N9QLfWepP3PlcHoKKUOqeUOqyUOiaBbCUm3HIA0MaYR40xX9Fa93jv11Sr1RowlMlkxsMw"
    "bNFa54CLYRjuWb9+/R8GBgaeSdM0Mzw8vOby5cvbx8bGdlar1XVxHL9gjFkltSECxrXWfUqp"
    "Q0Cf9z4LbJf75xYTC4sB0JrJZLbl8/l7MplMJgzDklKqO0mSIE3Ta3EcD8ZxfBL42/j4+J+H"
    "hoaGnHObgJ8CVefck2madgN/2rZt24+npqYqSqlOpZTy3v/TOXfUe1+RXd4hAd0OvCkgmgKg"
    "gM5cLlcqlUppZ2fneDabnQrD0Cil1llrSzMzM29prZ/ftWvXX3t7e2fkuQeAD0i6/ZAE+e8G"
    "Bgb2d3R0nM1ms5POuekkScoC7lPAQw3BfQo4LnS6ZQAtwEer1eonJiYm4nK5PKa1Hszn8yNx"
    "HN8IgsDVarUzY2NjB3t7e6/WPbca+KaAQILyOeDM5ORkraen50x/f/8qa+3jsuLFORbuPPD6"
    "zWh0szoQa617giDYaYzJVyqV4XK5fDUMw9FMJjNtjHkbOABcbHhusxQqpEYckEIHwN69exN5"
    "d36eRTRASYANNgPA5nK5a4VC4V/ZbLbNOddirS2maVpKksRVKhVXqVRqDRJZizxAXv5DUaBP"
    "yD1XJysGpbC1zAGgILKlqUpcLhaLr+RyOW2M6fTe57z3sVKq01qbCYKgP03TMWvtXNSbAr4P"
    "/BK4b453zQjw+VJluBilcLMJ0ZUrVzYYY3q01iWlVGKMIQxD5Zyz1WqVarU6V0/hgR8BP6mr"
    "tGoOkMECPUm6mDpwMwBBFEXFKIpKYRjmgNR7nzrnTJIkUa1Wa3fOFRqoMRu0e+qU6OdE1HWI"
    "WJuRQO+ax4fZylxpmkLGmCPOuc4kSe51zrVba03tP4ZzLgBWiTQYb3Dghvz+VeBZ4Feid+4S"
    "xx4G1tYFsa/LQKk0P+PNAkgrlcqEMUYppQre+6q1dsZaGzrnWqWabpLxan3wiyM7ge9ItqlJ"
    "hX1CfnZKlnF1js/SaVqCfGI55HTFGHPJOddpre2w1ha891ZokAHWS4MyIcXHAaPA14BPSmPv"
    "5N64ZJf7JAa8jHrna1KB+wRIcwDCMBwD+r339wtdyt77USCWTOGB+2XVW6UAXQK+LXIb4DRw"
    "UoTaeF2foOoAzNp14BUB4JvuB6anp2vOuWtKqVGl1FVpSloEwA1xZjXwQeDTwLuBrcJvgL8D"
    "L0hxG5U+OFngZGQCOCNzl6ehyWQyV40xLwPHhAIlyfMz4oCTjLJKKDBbdd8EfiAAivLM+EJH"
    "KkqpvNZ6q9Z6S12f3RyAkZGRmSRJTgHXjDE1pdSY6PVW2YUbkk2Oi6wIgAtSyP4iVDBCjxHJ"
    "Qr7OabTWBEFAGIa5IAi2KKW2yi4vW09cDYLgiLV2Rmv9sHPuXu99WZxfJdw/JLtRk0L2a3m2"
    "QwBUJT3OAGit0VpjjEmMMZPGmCGt9Qnp3o7PzlsWANLEnI2iqGKMuUspFTvntHNuneTtvcDZ"
    "ukL24qwgBL4gADYBQ1rraa21DcPQhmE4Yow5aYw5HATBEaXU6Wq1ei1JkunFnN4t+VwoCILh"
    "NE3/CLwF7NBaF7z3+9I0PShT1tYVpgD4FvA08AtAGWPO53K5E8YYp5Tq11ofNMa83traen7z"
    "5s0T+/btsyt6sFUuly1wKY7jaedcl3Nu0Dm3P03TydnNkpQaAt+QdDpLn8l8Pj8Ux/FzxpjI"
    "ez9grR0YHBwsA1y4cGHFTrD/a5RKpaCjo6Ojra2tq7W1tVEOPw38RlKhl5j48uzN3bt368W8"
    "YzGHzzebkJfTiLXzCK7fA4fnUJmPAT+T1OklnX4XeHmOk7dHZP5cNgD8fCkHXY1WAt4QZxuH"
    "BZ6ZZ1G+J3M88Fuh0rPzLNjX66Rz43hDdFPTMbCU7wheZMM5yfsvyUKcWUAaKG7xW0Wz3wcK"
    "oiob7UWh0g5p7I8KfboapDOLKVYrBcCI1n9qgTndQoXtQqG5rKuZL0XN7kB3/WnDAtbFCpnm"
    "HW7veACLodBF6Xn9bfZNzXFgdkvpcf0Sd8ovwzvri+V57tgdWzn7NyEUF1rTusl3AAAAAElF"
    "TkSuQmCC")

imgSpindleCCWOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgSACUoBurOTwAACHtJREFUaN7tmVlsnFcV"
    "x393+b5vxpPxMnadZmkT0tqolFRpS1DaB0C0RaBShOAB3iq2CvFQASqVQDxVYnmqxAtIIAQP"
    "SGxqVSK1VdSUEqm0UknlxF2SZulix3HsxPZ4dn/Lvbwco2Fw3EnGKVTkSFcazbfc+z/3f875"
    "3/PBVbtq/9+mrsA788AA0CcjBWaBFcAADcD/LwIIgZuBvcBOATEAVIC/AA4YA6rAG8BJYKnX"
    "SW2PzxvgGqAg427gfmBUAFngPPCO3HePOO1N4DDwHDAhu/KeA8gBt8uiSsAJYBC4Fhhuu28Z"
    "KAI3AB8QoOPAPmBEFn8MaF2uBy/HBsTbXwG+AHwIiIXr2wUEQpt54DSwS65F4rgUeFvWcIM4"
    "ZAlIrjSAQeAzwNeBTwo18jLxOaHIOKAlWOeBMxIXm4FA/n9JqHQLcK9crwFnLwXEpVKoCHwK"
    "eAC4Q7y26ojrxJPngQuyWCW70C/PrjpsWig3ANwG3KCU2qmUir33p7z3J7pdkL5EANcD93Us"
    "fjWbDQnHQ6XUjLWWMAyx1sZKqU0yQqXUCvCK7MJuYLu1liiKAmvtoFJq8EoG8SahS1OyjO5I"
    "o1uUUmeCIHi9WCz25/P5uF6vH61UKk2tddkYM+icm0rTtOycGwduCsMwyOfzZ621R5vN5mtx"
    "HO+QmnEKqG9UDATi/euVUiilGkqpQDJKAKCUwlrbNMYcD4Lg6dHR0dldu3Yd1Fr/dXFx8VQU"
    "RcuFQmFOa/1WkiTbgFujKCr29fVN5XK5F7Msm6zX633e+48DNwrNZjcKwBbgS8AngKpS6rRS"
    "alEpBbDJGJOz1laiKHo5DMPHarXa/c1mM52amopmZ2fvdc59zznXPz4+/nC5XF5yzu3J5XLb"
    "C4XCdBAEh+v1+ly1Wt0F3G2MuUNrPaqUes17/+q7Ve1uAXwUeLAtWyjv/TngrDEmC8OQKIom"
    "oyj67djY2BMzMzM70zT9eZZlTeCLwA7n3P7Z2dnftVqtmcHBQTM4ONjSWp+tVCppHMe7oyi6"
    "s6+vb6RQKCzlcrkp7/2RJEmOSbrtCUAe+LSkzn4J1g8LpWJjzHShUJgcGBjYb4x58tixY03g"
    "VmAP8FWRFh54HHgeWHnkkUdeO3To0Lnl5eUPKqXuKhQKO4aGhhaHh4ffKJVKk2EYTjabzdOt"
    "Vmv+3eKgGwCjwGelckYd9WDMe0+WZU/t3bv38YmJidVqei3wkIAAmAF+KQWNZ555JqvX632F"
    "QmFPqVS6tlQqnQnD8JVarXbq3Llzlbm5uWKj0dgm1fltIOslCw0JiLXAGu99MY5je+DAgbjt"
    "/zEJRCTfHwJ2dDw7BRxqNBqFarV6XbPZvC5Jkj1a681BEFyjta6maVp1zr0ALPYCoE+osxaA"
    "WCrndEdtGZffZ4GfAv8APi/XnFxr1uv1xDm3LZ/P3zo8PKyNMYm1tq61Xmo0GsuVSmW+Wq2m"
    "vdYBu5oq1zAnNaGxhrSuAj8GfgPctNZcYRguFovFE8ViUVtrm977BaVUTSlVt9YuGGNeqFar"
    "9V4BuHU4qOQdYcf/HvgZ8Is25fofZ49Wq6XK5TKtVstrrTclSVLIsgzvfeicm8+ybAZ4fT25"
    "3Q2Apogsd5HnRyRotdAtJ0H7R3lGSyod6ZQxzrn+JEkGrbWFXC6X5vP5VCllgEKSJKMrKytD"
    "cRzbXndgSRRl1ubdVe8bYBtwl2SovMSDEzkA8C2pIb9fQ5JvTtPU1uv1ahzHBEGgrLUrWuuz"
    "3vvjxpiX3i2NdgOgLIuqiRZSAsK1Zal7RFWeB/4gxUfJeeEHokQ7JfKNwI3e+yjLshXvfcs5"
    "l2RZ1qeU6vfeqyzLyuul0G4B1EQ9viUnraANhBf+b5dUuyI7VgC+LcC2CNiTbaDHpLrvFIo1"
    "vPdRmqZ5oBIEwRljzLRU8p7ltBcAL8jxsP3Z1bGq+5fkUDMNfE4WiijLN2QndstB6GaJlwDA"
    "e78g79jsvU+AE0EQLG7UeWBBqmh5na5GLAVnQU5Z2+T/vwutxoCtIktuk8BfjZVNspPnlVJz"
    "SqkF59x8rVZLNgJApLXerbW+RSlVXOe+WHag2lZ1jwI/EQBDEgebJSM5cUBDnhmVgjlhjHk2"
    "n8/PbdSJbJNS6hZr7e4gCArWWrTWiJRup1lTjpLLElvvSCF7Uq4bkQ+T8ntFRg6oK6UWjTEJ"
    "MB/H8ckLFy501WrpJogbSqnJIAj2W2unnXM3Z1m2Jcuy/izLQucczjnEk3MiwBIpZH+Sd5Rk"
    "0U5i6SMSwHNAoJTarrU+rrV+3lr7apZlXbdYulGjqTHmfD6ffzWfzx8OgmDCGDNrrXXW2kAp"
    "tVqFp733T0uP53aRzwvC74ckgI9LNtIiswe01vPGmGVjzEml1LPNZnM6TVO3oW0V51zWarWa"
    "tVrtwr59+96sVqtHvfcva61PWmvrYRgmQRC8nqbpAe+9EQCT0lb8vqTUCeBFATVnjNlpjLlJ"
    "KfWm1voJrfWL1tq5JEm6XvxldeYOHjyYCtcvbN269Zi19m9KqW1Zlq1orU+Xy+VAClkAfBd4"
    "WBzVEkAAFWPMfq11RWs9rbU+UqvVeu6TrtcAvtj4lz366KPtCeEbwJ/F215i4oF/60vmcuHA"
    "wMBIqVQqjY6O2m7muJzudBH4WltO71SpTwgtOqX0fcCvJHV6Sac/BJ5dowf6Mbl/LZsBfi1p"
    "9rJsFDgii+0cKfDNizjlR3KPBx4TKj14EYd9R/TOWnMckdZlzzFwKd8RvMiGt6QmPC2OOL1O"
    "i0Rxmd8qev0+0N/RSl+1p4RK98rB/rDQZ6RDkq92+/4rHziMaP0vr3PPDqHCnUKhtWykly9F"
    "ve7AjjW6DRdb5BUxzfvc3vcAuqHQlJxf/Xu8NiVz95wed17iTvkNmLO9WL7NVbtqV87+CY+Q"
    "Jk+tfg8hAAAAAElFTkSuQmCC")

imgSpindleOff = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgSACwrTiEkvAAAAmRJREFUaN7t2DtoVEEY"
    "BeBvN+ujSBQ1BiRgUkTt1ErBwkJRwReIhTYWooJYiAoK2ln4aLWxEi1VEGyMlYiF2FhEsDEa"
    "o4aoTcRHE0nctfkXlmXNa3cSL+6BhZnLZWfOvef/z5lLE0000UQT/zNyif43X+O/SyhmgUAe"
    "R9Edmy6v8xa3G02ikOgNrMQTDMR8DTamWKiQUJ6DeBfjBdiQSquzgRYJi202sB3tWSVwACdT"
    "yTUVgXKn2Y3z6MLvrBRxCd/iye/Eurg2lMIHUmEf+mPj5c3vyFIbXYWeGPfjacgoEzWQx+oY"
    "f8JVXEdHivVSFfF8/MRl3IoCzlQXKuEabsR8YargmKoGhnE3uk4e+7NmZEX8ivGJMLJclgiM"
    "x4YP4wLaMJYVCRUxglPYhhVx7U0KI0v1BoawN/xAHGZeZ0lCa9EZ42e4U0EmE0ZWdt2XuBIE"
    "lmTJyAr4EEb2MHyhJUsSGgsjuxfzpRUE8v86gWIYWW/MW3EoslBPoztRCgKdFXGigLM4luoz"
    "TgoCo2Fk83AG50I+o/gxF0aWmyS0VWMEX3ARWyLIjeMVPjdojSkTaMORCllUa/0BnteI0l+x"
    "NVpnKTY/HGRGq+7fjD0ThMKbEc1nhA70xWarf+M4/peneSnuKeF+SOlvge50nBdqrdGH5Y3I"
    "QtMpvlLEhkF8x6N4EAMTyCE30wKvN8wtwrIa13tDSruwHi/wuOJMUEmkda7SaEtk/YMT3NMV"
    "UtgUEqqF9nraa71voGuKXxuSnMZSRolZQ+YJTEVCH7F4MkNJgFysXXd77J7mmyo1YM1Ks3yv"
    "iSbS4Q9tbX/BUHhHgQAAAABJRU5ErkJggg==")

imgCoolantOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcfABwSvljVSwAACGJJREFUaN7tWH9MU0ke"
    "/07fK330tVDASq2l0KW0RTzCj67AmXMjiiKLsngqOTmEM17iZnOGnGduk8uFcJtc4gUvqHfJ"
    "xrhGY2JWT5e9NTEYZHfDpuepoCTiQmmphZbf8Aql7Svta+f+OLqpCAVdJVyOTzLJmzef+b75"
    "zMx33vc7AGtYwxreOLRa7W6BQMACAAYALBAIWJVK9XMAEC1WcnNzha/zLXKlREVFRbkAwLVY"
    "e0dHB6xqARhjHgCgpWirUgDHceTY2NivYmJiti/GSU9P7y4uLr5aX1/PrToBgUCAnJ6ePhiJ"
    "4/f7m/Py8q4BALcqtxBBECMIoUW3SDAYHFm1PiAQCLxJSUmfSCSStsU4Go3GU1JSMrtqnZgg"
    "iL729vauxdrb29tfyy7vbQyWoihyOe/eBBY0WldXF9PW1pYmkUh0UqlUwTCMnWXZnvLy8t5j"
    "x47NRDLY2dlJV1RUFGOMqbAjlPJ6vcWdnZ3fZmVluSP1v3jxoripqUkzMTGxcXJykk9RlFcq"
    "lY5s27bNVF9f75zPf+lcLioq+qi/v3/f6OhojtfrFREEQQUCAS9N0y6FQvFQpVI16fX6bxiG"
    "GYqJicFxcXGxtbW1o6H+27dv/83jx4//Oj09/cLkxMbGcnq9/retra3nQ+8aGxsTHQ7HtNPp"
    "RPHx8fKOjo5Ci8Xygd1u3+J2u0WBQAARBIEpinLJZLLHSqXyq5aWlr9HXBKhUGgKhQALFaFQ"
    "yMrlcrNKpfparVY3Z2RkNBUUFCQDAJw5cyZap9N9uVjfTZs2NdXV1VEAANnZ2ckZGRlNarW6"
    "WaVSfS2Xy800TXuX+LZpyS3k8XhImqY5mqb7aZq20TTtdblclNPpTPJ4PMkej4fyeDypAJA6"
    "J9ianJwMAABWq5Xv8/niFpscr9cbBwBR/330gtVqzWJZNmWer3A0TfeLxWKbSCTyut1uyu12"
    "J7nd7mS3200uKUCv199NSkp6qlAomqOiokZ27NjBXbt2jfT7/TK73V48Ojp6YHh4OJPjOJrP"
    "5wvmZg0AAPbv3+97+PDhc4vFsu2lvYoQSKVSa2Vl5Wx9fT2wLAtisdhLEAT4/f5ZkiRdcrn8"
    "6fr162+mpqY2B4PBkcOHD3Otra2kz+eT2e32YpvN9pMlT6vTp0+LI7U3NDSsy8/P31JeXn6k"
    "qqrqeFlZ2W6MMRFqr6ysfH/Dhg2985dfoVD0VldXvx/m2ERZWdnuqqqq4+Xl5Uf0ev27DQ0N"
    "637M2N4Ydu3aVZGamnqPoqhBiqIG1Wr1vT179lT8T+UEDQ0N6woLCzMLCwszl5rZH4NFw9u6"
    "ujpZT0/Pe3w+P8Xv91tjY2PbLly4MDyfd+PGDVFTU9NWjPFmlmWnSJL8982bN3sQQoF54TRR"
    "WlqazufzC4RCYQxBEF179+41HDp06KUc4ejRo/KZmZmfCQSCFL/fby0oKPg2/KheUgDGWHDg"
    "wIGGu3fvHuM4juLxeN6EhIQHKSkpV4uLi7/Kzs52trS08CwWy0+7urpqHA7HByzLijDGXHx8"
    "vF0ul3+em5t7KT8/3wYAYDAYlJ2dnUcHBwcrpqamFABA0jTtSkhI+HLz5s2XlUrlv4qKioJP"
    "njyJuXPnzj6r1XqEYZgtGGOKJElvSUnJxevXr/8OITS77FhIKBSqPR4PNRcpUh6P5z2Hw5E3"
    "NDT0oUQiGZ+eno5iGCaDYZhEAAAejwfBYJAcGhpKmZyc/HhgYGCfwWCwAQCMjY0pp6am0n0+"
    "H4S4LMuKJiYmfjk+Pl4UHx//rK2tzccwjHR8fDzD5XJRIZ7P56OEQqH6lYM5iUTSr9frW2Uy"
    "mX9gYIBvt9szJiYmZC6XKzecJxaLvTKZ7LFWq3U6nU7o6+tTjo2NbQqVsJQSNm7c+CwtLc1G"
    "0zR0d3fHjI6O5jAMkxiahBASExNHFArFM4VC4R8eHuaLxeL+VxKAEJq9ffv2Jzk5OZNbt27F"
    "BoMB3bp1a2t3d3fN5ORkMcuyoqioKJBIJA+USuXVnTt3/qOysnIWAODs2bPJ9+/fPzoyMlLB"
    "MIwMACAhIWFEJpN9npeX91ltba0NAOD8+fOCR48eHRwaGjricDi2+Hw+iI6Odkml0ubMzMzL"
    "paWlhpqaGnz58mVE03TCQtsHlpGjvuSw586d0zocjnVJSUmcTqf7vrGxcXgBHyKqq6t1JpNJ"
    "AQCQlpZmv3LlykuODQBw6tQp+dOnT9NtNhsZFxc3ceLECeNCjr2GNaz0j2yJm7cNGOOTCKES"
    "jHHyXLxjRQjdxhg39Pb2Ti7QJzyhP2g0Gm9G4hiNxmWNjfcagy/AGHchhE4CQDpCSIgQohFC"
    "GQDwMQA802g0mUtccn2q1Wo3vIkVeCUBOp0uHmP8BUIoftElRSgRIdSk1WpFETgJAPDZigvA"
    "GB9HCMnC6h3BYPAdjuPUANAZRn0HY/zrJczt0Wg0H660gNIXOvN4J00m0/O+vr6+ue0TPsv7"
    "I9jpDQWtOp0ubcUEAIAuvOLz+Z6EXR92zBtkRoRbuCMAEEAICTHGVwGAWCkBL2REFovlhz+m"
    "2Wx2zOPSixkxm80PAODPc9U8jUbzh5USMBFeUavVPwxSqVSKI3HnQyQS/QljHEpw/6jRaPQr"
    "IeD5C5EgSeaEnqOjo7PmcY2RDHV0dHAY4yoAYBFCJELo6lsXgBD6Yt5ePpOWlqbSaDQpAPCX"
    "efR/LmXPZDL1AMDvF/KvtyXgEsZ4KKyey+PxLAih5wDwbhh1MBgMXlqOTaPR+DcAuLciPtDT"
    "08MAwCGMMRPhiHQEg8FfmM3mmeWezoFAoAZj7FiR2+ne3l4Dx3FZGOMzAPA9xngGY+zBGBsB"
    "oBEAckwm03evYtNsNg8ihD5aC03XsIb/Q/wHV/e4+KT7Y5IAAAAASUVORK5CYII=")

imgCoolantOff = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcfABwn6OsRaAAAB/tJREFUaN7tWG1MU1ka"
    "fk/vbXvpbaEUK7WWQpdCi3UJHx2BNetEFK0MyuCqZGUR17iJm80asq7J/CNkfrmpu6jZP8ad"
    "aEzM6Op0dkwMhmF2lk3XHQUlEQekUAst5au9hdL2lrb07I8FU5EWcdyZbsKT3KSn5zn33ue8"
    "73Puew7AOtaxjncOjUazl8/nswCAAQDz+XxWpVL9DACE8a7S0lLB2zyL/L5E8Xg8HwD44vX3"
    "9PRAUgvAGHMAAK1GS0oBkUiEnJqa+mVqaurOeJyCgoJ+g8FwvbW1NZJ0AhYWFsjZ2dnDiTjh"
    "cLi9rKzsBgBEkjKFCIKYQAjFTZFoNDqRtB7g8/nBrKysj8VicVc8Tn5+fqC6uno+aU1MEMRw"
    "d3d3X7z+7u7ut7ov53/xshRFkW/y37vAijdtaWlJ7erqyhOLxVqpVKpgGMbBsuxAXV3d4MmT"
    "J+cS3bC3t5eur683YIypmCWUCgaDht7e3q+Lior8icZfuXJFZDKZ8l0u12a3282lKCoolUon"
    "duzYYWltbfUu57+2LldVVf1mZGTkwOTkZEkwGBQSBEEtLCwEaZr2KRSKhyqVyqTX6//OMIwz"
    "NTUVp6enpzU3N08ujd+5c+dvHz9+/MfZ2dlXJictLS2i1+t/19nZeWnpv7a2tkyPxzPr9XqR"
    "RCKR9/T0VFqt1g8dDsc2v98vXFhYQARBYIqifDKZ7LFSqfyio6PjzwlDIhAILEslwEqXQCBg"
    "5XL5kEql+kqtVrfrdDpTRUVFNgDA+fPnU7Ra7efxxm7ZssXU0tJCAQAUFxdn63Q6k1qtblep"
    "VF/J5fIhmqaDqzzbsmoKBQIBkqbpCE3TIzRN22maDvp8Psrr9WYFAoHsQCBABQKBXADIXRRs"
    "y87OBgAAm83GDYVC6fEmJxgMpgMA778/g2Cz2YpYls1Z5pUITdMjIpHILhQKg36/n/L7/Vl+"
    "vz/b7/eTqwrQ6/X3s7KynioUinYejzexa9euyI0bN8hwOCxzOByGycnJQ+Pj44WRSITmcrn8"
    "xVkDAICDBw+GHj58+MJqte54LVcRAqlUamtoaJhvbW0FlmVBJBIFCYKAcDg8T5KkTy6XP924"
    "cePt3Nzc9mg0OnH06NFIZ2cnGQqFZA6Hw2C323+86mp17tw5UaJ+o9G4oby8fFtdXd2xxsbG"
    "U7W1tXsxxsRSf0NDwwebNm0aXB5+hUIx2NTU9EGMsYna2tq9jY2Np+rq6o7p9fr3jEbjhu/y"
    "bu8Me/bsqc/Nzf2SoqgxiqLG1Gr1l/v27av/v9oTGI3GDZWVlYWVlZWFq83sd0Hc8ralpUU2"
    "MDDwPpfLzQmHw7a0tLSuy5cvjy/n3bp1S2gymbZjjLeyLDtDkuS/b9++PYAQWlhWThM1NTUF"
    "XC63QiAQpBIE0bd//37zkSNHXtsjnDhxQj43N/dTPp+fEw6HbRUVFV/HLtWrCsAY8w8dOmS8"
    "f//+yUgkQnE4nGBGRsY3OTk51w0GwxfFxcXejo4OjtVq/UlfX99xj8fzIcuyQoxxRCKROORy"
    "+aelpaWflJeX2wEAzGazsre398TY2Fj9zMyMAgBImqZ9GRkZn2/duvWqUqn8V1VVVfTJkyep"
    "9+7dO2Cz2Y4xDLMNY0yRJBmsrq6+cvPmzd8jhObfuBYSCATqQCBALVaKVCAQeN/j8ZQ5nc5f"
    "i8Xi6dnZWR7DMDqGYTIBADgcDkSjUdLpdOa43e6PRkdHD5jNZjsAwNTUlHJmZqYgFArBEpdl"
    "WaHL5frF9PR0lUQiedbV1RViGEY6PT2t8/l81BIvFApRAoFAveZiTiwWj+j1+k6ZTBYeHR3l"
    "OhwOncvlkvl8vtJYnkgkCspksscajcbr9XpheHhYOTU1tWXpitlSwubNm5/l5eXZaZqG/v7+"
    "1MnJyRKGYTKXJmEJmZmZEwqF4plCoQiPj49zRSLRyJoEIITm7969+3FJSYl7+/bt2Gw2ozt3"
    "7mzv7+8/7na7DSzLCnk8HojF4m+USuX13bt3/7WhoWEeAODChQvZDx48ODExMVHPMIwMACAj"
    "I2NCJpN9WlZW9pfm5mY7AMClS5f4jx49Oux0Oo95PJ5toVAIUlJSfFKptL2wsPBqTU2N+fjx"
    "4/jq1auIpumMldIH3mCP+pphL168qPF4PBuysrIiWq3227a2tvEVPEQ0NTVpLRaLAgAgLy/P"
    "ce3atdeMDQBw9uxZ+dOnTwvsdjuZnp7uOn369POVjL2OdXzfH7KYU7ZNGOMzCKFqjHH2Ym1j"
    "QwjdxRgbBwcH3SuMWfV85/nz5+ht+W+8pdRoNBUY4z6E0BkAKEAICRBCNEJIBwAfAcCz/Pz8"
    "wh8yAnEFaLVaCcb4M4SQJG74EMpECJk0Go3whxJAJjgKPIUQksW0ezDGh6PRKIckydsAULTY"
    "9SOM8a8A4E9rDf+74HMSCKh5hcjhnLFYLC+Gh4eHF9MnNhIHky4CAKCNbYRCoScxR4U9BEHE"
    "itWt4iW8lhleCz+RiV/Z/Vit1pdfx6GhIc8yLp10JgYAV2xDrVa/fEmlUilKxE2WFHoBAC9N"
    "TJJkCQD8AwAgJSWlaLnv3pUp18onEyyRnwFARczp8fm8vLzDiyfMf1hG/1vSpRBC6BOMsTOm"
    "XcrhcKwIoRcA8F4MdSwajX6SdAIGBgYYADiCMWYSLLWeaDT686GhoblkNDEMDg6aI5FIEcb4"
    "PAB8izGewxgHMMbPAaANAEosFss/10vKdaxjHW+N/wD55pKrRHVSqQAAAABJRU5ErkJggg==")

imgSetToZero = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgRFxYpjlqB8gAACTJJREFUaN7tmXtMW+cV"
    "wM/xC+PYxtgYzMuwEAiUhxMTRwZaoAkrNcVtuixUWf9oVynqP1tX7aGpatOH2rWq2KPTsj+a"
    "Smv2B41I0pKWUdKIEEjABhuDF5IYSINTAzUBX2xfHjZc+377p1Tt2sDlEappOZIlS/Z37/md"
    "853znXM+gHtyT+7J/7TgZjyEECJqbW2V1tTU0JcuXSqJi4s7s7CwkBgKhQARQSKRQFxc3O2Z"
    "mZmDpaWlPVarNc5oNM4h4tIPBkAIETidTmlPT098cnLy7yiKOnLlyhXBwMAAuFwuCAQCwDAM"
    "ICKIRCJISEgAnU4HxcXFsGvXLlatVr9P0/SrGRkZvoKCgkVEJFsCQAjB1tbW2GAwuGt2dvY3"
    "brf7J+fOnYOBgQHuL0WEffv2wf79++c0Gs3fkpKSGvLy8tzbt29fuKsAhBChw+HItdvtZqfT"
    "+XRvb2+20+n8+nc+nw9CoRBEIhERCoXAMAzOzs4CId8xLgEAIhKJeNXV1VBSUnIzLi7uxYSE"
    "hPN1dXU0IkY3HSAcDgvOnz+/59atW6/YbLaHW1pawO/3EwBAsVgMSqUSkpKSIlKp9LZGo1lM"
    "TU2NjI+Px1+4cEHt9/vvaBMAgOTkZCwpKRk1mUxnH3zwwVNZWVkDXONDwNHy/IaGBsPVq1df"
    "7O7ufthisUA0GiVisRg1Gg2bkpLypdFopPV6/ZRAIDhz3333UYWFhYvHjx+vvXbt2jMrACAA"
    "EK/XSzo6OrZLpdJfx8TEFIVCodcIIb2IyGwYgBAiPHv2bPHg4OBLnZ2dNXa7HaLRKKtUKnnZ"
    "2dkzpaWlQ4WFhZ8cOHBgMD4+nkLE3uW1dXV1Kj6f/wyXXTAzM0NOnjyJNE1XISKRyWQvEULs"
    "qwX3qgA2my3H4/G82t3dXW2z2YBlWTY9PZ1XXl4eMBgMjTU1NY3Z2dl2RPxOACoUijiWZbkG"
    "NjIMQ1paWlCpVP4YEf/t9XqHASC4boCPPvpI1Nvb+4jNZqu2WCzAsiyr1Wp5tbW1wdra2kaT"
    "yfQXRLyxgvfIGhIEAAAyDEM+/vhjDIfDj5lMpl6GYVqEQmHoTut4KzwwRqVS1Q4MDPy8paUF"
    "WJZl1Wo1r6qqKvD44483mkymP6+k/EbOJoqioKurKzsQCLzhdDozV/rzHQF8Pp+coqj6y5cv"
    "5wYCASKRSHhFRUX+ysrKk1VVVX9ExJG7WCEQj8dDrFbrzrGxsScCgYBszQDt7e2xfX192z//"
    "/HOCiJiRkRGtrq4ePnTo0Om7ZPn/DmxsamqCycnJ5wcHBxVrAnC5XCJCyO8//PBDAACUyWSg"
    "1+uD+/btOycWi3u2qlALhUJgs9nivvjii0JCCHIGqK+vZ27fvv3s8PAwICJoNBrWaDS6i4uL"
    "LYgY2spqs7m5GWJiYv7g8/kknAGee+65TLvdzgcAEIlEJDExcTolJeUMAFzY6nKZoijwer27"
    "+vv7YzinUUQ8brVaAQBAIpFgfn4++9BDD1GIyMIPIFeuXAGr1SrgDOD3+3d5PJ5lgKhWq52W"
    "SqXeNUcibkq7AaOjo9De3h7mvIUoioou1/IAMDsyMnIWEf+11hf7fL65paUN9ywwMTEBnZ2d"
    "v+XsAYqivv4eGxsr2rt3r+7EiRNPz8/Pq5cryNUsL5FI5j744AMTwzAgl8tBKBRy9lo0GoWJ"
    "iQmYmpqCSCQCXq8XlErlUQB4mRPAN60WCAQkFovlMZqmH5ubmwMej8dJkUgkAmq1Gsxmc7Pb"
    "7T4nFould0qF31R+dnaWrqioMHz66afm06dPq3w+H0ajUYhEItxd1tDQMLncdGzkYzabSVdX"
    "17Pr6PrMb731lislJYUFAKJSqYjL5eIeA4mJibzNCEBCCASDQek6loqnp6f5yzshPT0dpqam"
    "nuEMIJfLqfj4+A0D8Hg84PP5a17ncDjI6OgoLC4uAgCAVquFioqKRs4AsbGxx3Q63aakQK79"
    "wDeHBjabLX1sbGzbMkBeXh4cPXo0gTNAIBD4xwMPPLA5Vdnat2LZwsLCT2maTmIYBgEA8vPz"
    "4dChQ0ucAbRabWTPnj3zIpFoS09cQoior6+vpL+/P2t6eppPCCE6nQ4UCsU/CwsLQ5wB0tLS"
    "IDk5uf7RRx/d6qphd09Pz8PXrl1T0TRNAABMJhNMTU29gYjcs5BAIGAWFxePlZWVTchksq2y"
    "flpra+vBtra2ArfbLWBZFnJzczEnJ6fLaDQG1tzQaLVaWqPRvHnw4MFvzXDukvICh8Nhvnjx"
    "4hNOpzORpmkilUrRYDCMx8bGvp6fnx9cDwCTlZXVYjAYLLm5uZs2CP4e5WXt7e2PvPfeewea"
    "m5uTx8fHAQBw//79kJ+f//7S0lLXSvOhFesCg8HwpUqleqm8vNyRmZm56V4ghKR2dHQ839TU"
    "9HJbW1vpyMiIIBqNkoKCAtDpdFa9Xv/JU089tbDusQoiMuPj4z0SieSMQqEofvfddzEYDBKu"
    "3mBZFliWxe9RXDE0NFRcX19f43K5ftbd3a25desWsCwLOTk5sHv37m6VSvWK0Wgc3PBkLi0t"
    "LeTz+ZpEIlFBJBJ58tSpU/iVm1cFiYmJgdTU1MBXSusBILerqyv6zjvv7B0ZGano7e3N8Hg8"
    "CRRFASEEdu7cCTqdzpKenv56WlraZblcvmotzumcf/vttwMKheI6APjn5+eVfr8/gaZp3moQ"
    "arUapFLpUlFRUcKNGzd+0d7efrixsbH84sWLZQ6H40cej2fb7OwsAQDQ6XRYWlpq2bFjx2s7"
    "duzoOHz4MKdGAtewX3l2u11+6dIl4/T09Av9/f3lHR0dwDB3nr/Gx8dDamoqzTDMAsuy8QsL"
    "CzE0TZNwOIwMwxAAgG3btqHZbIaSkpI+tVr9QmpqamdFRQXDVa81Zxa32y24efNmocfj+eX1"
    "69ef/Oyzz0SDg4N3LCN4PB7weDyIRCLfuidARCgrK4P7779/KiMj46/FxcVNBoPh5lqvnXCd"
    "2QOdTqdseHg4LxwO/2psbKyura2Nb7VaYbUWUi6XQ2VlJVRWVoZUKtXfg8HgsbKystt6vX5d"
    "10y4wTTI8/l8YLfbFZmZmX+iKOrJoaEh4ejoKExOTsJyByeTySAlJQWys7NBq9VOCoXCN69e"
    "vXriyJEjIUSMwD25J/fk/1f+AxQ2R3rmDR6GAAAAAElFTkSuQmCC")

imgSetToZeroXY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgWBgAr/P+k9wAACvVJREFUaN7tmXtQU3cW"
    "x7+/kIQQA4RHMLwCCxLeBkHaAK2Aj2IoWFzU2vafbju2/aN0O+2uTuuj7bTbrmXXne3Wau3M"
    "6s6sokgr1SLWVUQkPBISsqIGXA0acEGSQAjI6yb3t/+A66NI0NbOznpm7tw7c3/33N/n/M75"
    "3XPOBR7JI3kk/9NCfgwllFJ+dXW1KD8/31FXV5fh6+tbMTIyEjQ6OgpCCIRCIXx9fa/39/cX"
    "Z2ZmNjU2NvoqlcphQsjEzwZAKeUaDAZRU1OTX3Bw8G9tNtu6s2fPcltbW2E0GmG328EwDAgh"
    "4PP5CAwMhEKhQFpaGlJSUliJRLLb4XC8HxERYU1KShonhNCHAkApJdXV1V6Dg4MpQ0NDb3d2"
    "dv7y2LFjaG1tdf+lhGDx4sVYsmTJsFQq/cvcuXP3xsfHd0ZFRY38pACUUp5Op4vTarWFBoPh"
    "xebm5hiDwXDzvoeHB3g8Hvh8PuXxeGAYhgwNDYHSu4xLAVA+n8/Jy8tDRkbGZV9f342BgYHH"
    "16xZ4yCEuH50gLGxMe7x48cXXrly5T2NRrO8qqoKAwMDFAARCATw9/fH3LlznSKR6LpUKh0P"
    "DQ11dnd3+508eVIyMDAwrU0AIDg4mGRkZJhUKlVlbm5ueXR0dKu78cF10/Iee/fuTT937txG"
    "tVq9vKGhAS6XiwoEAiKVStmQkJB/K5VKR2pqah+Xy61ISEiwJScnj+/atavg/PnzL90DgACg"
    "PT09tLa2NkokEr3l6ek5f3R09ANKaTMhhHlgAEopr7KyMq2trW3T6dOn87VaLVwuF+vv78+J"
    "iYnpz8zMbE9OTj5cVFTU5ufnZyOENE89u2bNmgAPD4+X3PGC/v5+WlZWRhwOx1JCCPX29t5E"
    "KdXOFNwzAmg0GrnZbH5frVbnaTQasCzLhoeHcxYtWmRPT08/kJ+ffyAmJkZLCLkrAMVisS/L"
    "su4GNmEYhlZVVRF/f/9lhJB/9vT0dAAYvG+Ab775ht/c3Py0RqPJa2hoAMuyrEwm4xQUFAwW"
    "FBQcUKlUfyKE/Oseq0dnsUEAAGEYhn777bdkbGzsGZVK1cwwTBWPxxud7jnOPRR6BgQEFLS2"
    "tv6qqqoKLMuyEomEs3TpUvvKlSsPqFSqbfea/IN8m2w2G+rr62PsdvtHBoMh8l6DpwWwWq0+"
    "Nput9MyZM3F2u50KhULO/PnzB3JycsqWLl36B0LIxZ8wQ6Bms5k2NjbGdnV1PWu3271nDVBT"
    "U+PV0tISdenSJUoIIREREa68vLyO1atXH/yJLH9nYJNDhw6ht7f3zba2NvGsAIxGI59SuuHr"
    "r78GAOLt7Y3U1NTBxYsXHxMIBE0PK1EbHR2FRqPxvXr1ajKllLgNUFpayly/fv3Vjo4OEEIg"
    "lUpZpVLZmZaW1kAIGX2Y2eaRI0fg6en5O6vVKnQb4I033ojUarUeAMDn82lQUJAlJCSkAsDJ"
    "h50u22w29PT0pOj1ek+3t1FCyK7GxkYAgFAoJImJiexTTz1lI4Sw+Bnk7NmzaGxs5LoNMDAw"
    "kGI2m6cAXDKZzCISiXpmHYnkRyk3YDKZUFNTM+a2C9lsNtdULg9g6OLFi5WEkO9m+2Kr1To8"
    "MfHANQuuXbuG06dP/8btFbDZbDevvby8+I899phiz549L964cUMylUHOZHmhUDi8b98+FcMw"
    "8PHxAY/Hc3vVXC4Xrl27hr6+PjidTvT09MDf338zgC1uAdxqNbvdLmxoaHjG4XA8Mzw8DA6H"
    "49ZEnE4nJBIJCgsLj3R2dh4TCASi6bbCWyc/NDTkyM7OTj969GjhwYMHA6xWK3G5XHA6ne4v"
    "2d69e3unio4HOQoLC2l9ff2r91H1FX7yySfGkJAQFgANCAigRqPR/RgICgrizBSAO3bsAKUU"
    "Fy5cuOkePB4PRqMRlFLs2LED4+PjePnll3fI5fJhmUx229c0ISHBTy6XM3K5fCIqKkpyh3qB"
    "xWLxmPKE8PBw9PX1veQ2gI+Pj83Pz++eACUlJThz5gzi4+Oxfv16AMCGDRsQFxeHuro6lJSU"
    "QCAQQCqVniOEzBEIBLetBMMwhYQQLiHkO5PJZLn1nk6noyaTCePj4wAAmUyG7OzsA24DeHl5"
    "fa5QKGb08eLiYpjNZmzcuBHLli3Du+++C7PZjFWrVt302dzc3JpJ/y5JSEi4GckcDmfl5OXu"
    "O5sGGo0mvKura84UQHx8PDZv3hzoNoDdbv/rk08+OaOvWiwWrFy5EpRSHD16FJRSFBUVwWL5"
    "r0Eff/zxLgA1AEKdTuezADB//nwhgDxK6XWRSFR9h9qskZGRVQ6HYy7DMAQAEhMTsXr16gm3"
    "AWQymXPhwoU3+Hz+jBB6vR5qtRpcLheHDx/+wfYKIeT3k+e3JpO0PABeAP6u0+mctzbIWlpa"
    "MvR6fbTFYvGglFKFQgGxWPy35OTkUbcBwsLCEBwcXLpixYoZAV577TUsW7YMvb29WLt2LYqK"
    "iu4a097e/g9KqR7AArlcnjvlPhwOZ/cdQxc0NTUtP3/+fIDD4aAAoFKp0NfX9xEhxP1diMvl"
    "MuPj459nZWVd8/aetpZAcnIytm3bhu7ubiiVSvT392P37t2Ijo7+oeFbJ88bKKUFlNKW9vb2"
    "87dYP6y6urr4xIkTSZ2dnVyWZREXF0fkcnm9Uqm0z7qgkclkDqlU+nFxcfFtPZwpEQqFKC8v"
    "h5eXF9avX4+rV69i06ZNEIvFqKiogKfn7cnjxYsXKyillwgheYQQv1uDl1LK1el0hadOnXrW"
    "YDAEORwOKhKJSHp6ereXl9eHiYmJg/cDwERHR1elp6c3xMXF3dUE++KLLxAXFwe1Wo2ysjIA"
    "wM6dO6HX65GSkoLt27ffqZIlhOycvB7ncrllk5P3rqmpefqrr74qOnLkSHB3dzcAkCVLliAx"
    "MXH3xMREvTv9oWl7Qvv378995ZVXWiIjIykAdjZf4hUrVtDq6uq3p/TJ5fI3Y2NjaWxs7P5J"
    "/aGnTp3a/Prrr+uio6OHOBwOC4BNSkqiW7ZsaTh+/PjCB2psEUKY7u7uJqFQWCEWi9O+/PJL"
    "Mjg4SN1tSbIsC5ZlyS36ZAAQGRm5r7KycklpaWm+0Wh8Xq1WS69cuQKWZSGXy7FgwQJ1QEDA"
    "e0qlsu2BO3NhYWGjVqv1EJ/PT3I6nS+Ul5eTyWWeEcTT0xOhoaF2ANi/f3/+p59++rxQKGxa"
    "vnx59meffZbd3NwcYTabA202GyiliI2NhUKhaAgPD/8wLCzsjI+Pz4y5uIc7lty6datdLBZf"
    "ADBw48YN/4GBgUCHw8GZCUIikUAkEk2YTKbyurq6tUFBQVyRSMTW1tZm6nS6X5jN5jlDQ0MU"
    "ABQKBcnMzGyYN2/eB/Pmzat97rnn3CokyCzigaPVan3q6uqUFovlHb1ev6i2thYMM318+fn5"
    "ITQ01MEwzAjLsn4jIyOeDoeDjo2NEYZhKADMmTOHFBYWIiMjo0UikbwTGhp6Ojs72+2gnXXN"
    "19nZyb18+XKy2WwuuXDhwgvff/89v62tbdr8nsPhgMPhwOl03vafgBCCrKwsPPHEE30RERF/"
    "TktLO5Senn55tr+dyH3uTsRgMHh3dHTEj42N/bqrq2vNiRMnPBobGzFTCenj44OcnBzk5OSM"
    "BgQEbB8cHPw8Kyvrempq6n39ZnqgqptSyrFardBqteLIyMg/2my2F9rb23kmkwm9vb2YquC8"
    "vb0REhKCmJgYyGSyXh6P9/G5c+f2rFu3bpQQ4sQjeSSP5P9X/gO4Qv/tqkyReQAAAABJRU5E"
    "rkJggg==")

imgSetToZeroZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgUFSEdC7PxLwAACb5JREFUaN7tmXtMW+cV"
    "wM+x8cU4trEBg3kZFmIe5eEEx5GBFmjCQk2hTZeFKks1dZGSadLWTXsoqtqsrdp1qtij2zpN"
    "SaU100YjktCkZZQ0SggkgMHm4QUSMEkwMVAI+GL78rDh2vfbH4OK0gZMoKmm5kiWfHVf53fO"
    "d853zrkAD+WhPJT/a8GNeAghhKqrqxOXlJQwV65cyQkNDT0zOzsb6fF4ABFBJBJBaGjo3cnJ"
    "yb25ubmtRqMxVK/XTyPi/NcGQAgJslgs4tbWVnl0dPSvaJo+dO3ataCuri7o7e0Fl8sFLMsC"
    "IgJFURAREQEajQa0Wi1s3bqVUygU7zEM82pCQoIjIyNjDhHJAwEghGBdXV2I2+3eOjU19Qub"
    "zfad8+fPQ1dXV+AvRYSdO3fCrl27ppVK5V+ioqIq09LSbJs3b579SgEIIYKOjo5Us9lcZrFY"
    "nm9ra1NbLJbPzvP5fBAIBEBRFBEIBMCyLE5NTQEhXzAuAQBCURSvuLgYcnJyboeGhr4UERFx"
    "oby8nEFE/4YDeL3eoAsXLmwfHBx8xWQyPVFbWwtOp5MAAAqFQggLC4OoqCifWCy+q1Qq52Jj"
    "Y33Dw8PyS5cuKZxO5z1tAgAQHR2NOTk5AwaD4dzjjz9+KikpqSvQ+AgK0PL8yspKXU9Pz0vN"
    "zc1PtLS0gN/vJ0KhEJVKJRcTE/OpXq9nsrOzx4OCgs488sgjdGZm5tzx48dLr1+/fnAFAAQA"
    "Mjo6ShoaGjaLxeKfBwcHZ3k8ntcIIW2IyK4bgBAiOHfunLa7u/vlxsbGErPZDH6/nwsLC+Op"
    "1erJ3NzcvszMzI/27NnTLZfLaURsW7y3vLw8nM/nHwxkFUxOTpKTJ08iwzBFiEgkEsnLhBDz"
    "asG9KoDJZEq22+2vNjc3F5tMJuA4jouPj+fl5+e7dDpdVUlJSZVarTYj4hcCUCaThXIcF2hg"
    "I8uypLa2FsPCwr6NiP8ZHR21AoD7vgE++OADqq2t7UmTyVTc0tICHMdxKpWKV1pa6i4tLa0y"
    "GAx/RMSbK3iPrCFBAAAgy7Lkww8/RK/X+7TBYGhjWbZWIBB47nUfb4UHBoeHh5d2dXX9oLa2"
    "FjiO4xQKBa+oqMj1zDPPVBkMhj+spPx69iaapqGpqUntcrnesFgsiStdfE8Ah8MhpWm64urV"
    "q6kul4uIRCJeVlaWs7Cw8GRRUdHvELH/K6wQiN1uJ0ajMWVoaOhZl8slWTNAfX19SHt7++Zb"
    "t24RRMSEhAR/cXGxdd++fae/IssvD2w8e/YsjI2N/ay7u1u2JoDe3l6KEHKkuroaAAAlEglk"
    "Z2e7d+7ceV4oFLY+qELN4/GAyWQKvXPnTiYhBAMGqKioYO/evftDq9UKiAhKpZLT6/U2rVbb"
    "goieB1lt1tTUQHBw8G8cDocoYIAXXngh0Ww28wEAKIoikZGREzExMWcA4NKDLpdpmobR0dGt"
    "nZ2dwQGnUUQ8bjQaAQBAJBJheno6t3v3bhoROfga5Nq1a2A0GoMCBnA6nVvtdvsigF+lUk2I"
    "xeLRNUcibki7AQMDA1BfX+8NeAnRNO1frOUBYKq/v/8cIv57rS92OBzT8/Pr7llgZGQEGhsb"
    "fxmwB2ia/ux/SEgItWPHDs2JEyeen5mZUSxWkKtZXiQSTb///vsGlmVBKpWCQCAI2Gt+vx9G"
    "RkZgfHwcfD4fjI6OQlhY2FEA+HVAAEut5nK5RC0tLU8zDPP09PQ08Hi8gBTx+XygUCigrKys"
    "xmaznRcKheJ7pcKlyk9NTTEFBQW6jz/+uOz06dPhDocD/X4/+Hy+wGshuVz+WX3icDigsrLy"
    "vlxfVlYGR44cqT18+PCxlJSUFT1ntVpxSRof7unpyaEoKhwAQCgUglAonAs4BiIjI3kbEYCE"
    "EHC73eIALr297Fg4MTHBX1wJ8fHxMD4+fjBgD0ilUloulysmJyfXBcDj8YDP53/BwgAAarX6"
    "SR6PV0MI8XMcd2DpuY6ODjIwMABzc/8zukqlgoKCgqqAPRASEvKORqPZkBT4Zf1AcnJyIiL+"
    "c6Hmee3WrVttS4cGJpMpfmhoaNMiQFpaGhw9ejQiYACXy/X3xx57bGOqsmVLMTExMRgAziCi"
    "HACa+vv7f7vslrzZ2dnvMgwTxbIsAgCkp6fDvn375gMGUKlUvu3bt89QFLXhuypFUX9GRC0A"
    "uBHxOQDwLx2Qtbe353R2diZNTEzwCSFEo9GATCb7R2ZmpidggLi4OIiOjq546qmnNlR5tVr9"
    "fUQ8vHD4o76+vjvLLtnW2tr6xPXr18MZhiEAAAaDAcbHx99AxMB34qCgIHZubu6dvLy8EYlE"
    "siHKp6SkZCDi3xYO/2W1Wk8uy1hxdXV1ey9evJhhs9mCOI6D1NRUTE5ObtLr9a41NzQqlYpR"
    "KpVv7t2793MznHWk1GpEXCyJn0tJSSFLfx0dHWWXL19+1mKxRDIMQ8RiMep0uuGQkJDX09PT"
    "3fcDwCYlJdXqdLqW1NTUdQ+CETF5pfPvvvvunpqamujh4WEAANy1axekp6e/Nz8/37TSfGjF"
    "qYROp/t0YGDg5fz8/Aqv16sdHBwk9wuyfB9Y8EpsQ0PDwerq6j11dXW5C0uHZGRkoEajMWZn"
    "Z3+0e/fu2fseqyAiOzw83CoSic7IZDLtsWPH0O12BwzBcRxwHPdlisv6+vq0FRUVJb29vd9r"
    "bm5WDg4OAsdxkJycDNu2bWsODw9/Ra/Xd697MhcXF+dxOBxnKYrK8Pl8B06dOoULbl4VJDg4"
    "GGJjY10LSmcDQGpTU5P/7bff3tHf31/Q1taWYLfbI2iaBkIIpKSkgEajaYmPj389Li7uqlQq"
    "XbUW5wdiybfeesslk8luAIBzZmYmzOl0RjAMw1sNQqFQgFgsns/Kyoq4efPmj+vr6/dXVVXl"
    "X758Oa+jo+Nbdrt909TUFAEA0Gg0mJub27Jly5bXtmzZ0rB///6AGglcQxbhmc1m6ZUrV/QT"
    "ExMvdnZ25jc0NADL3nv+KpfLITY2lmFZdpbjOPns7GwwwzDE6/Uiy7IEAGDTpk1YVlYGOTk5"
    "7QqF4sXY2NjGgoICNuDksNZgtNlsQbdv38602+0/uXHjxoFPPvmE6u7uvmcZwePxgMfjgc/n"
    "+9x3AkSEvLw8ePTRR8cTEhL+pNVqz+p0uttr/eyE95nT0WKxSKxWa5rX6/3p0NBQ+cWLF/lG"
    "oxFWayGlUikUFhZCYWGhJzw8/K9ut/udvLy8u9nZ2ff1mQnXuTnxHA4HmM1mWWJi4u9pmj7Q"
    "19cnGBgYgLGxMVjs4CQSCcTExIBarQaVSjUmEAje7OnpOXHo0CEPIvrgoTyUh/LNlf8CsTFq"
    "/8yuw2kAAAAASUVORK5CYII=")

imgGoToZeroXY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QgRFx40JYVnIwAABrlJREFUaN7tWX1IVFkU"
    "/715M5OfiWZfo7Oubo7S2I740WBWIOQH7YIYOeS6C4UUlmZBBG20VFDEEvtnLEu0Bi6xfUgk"
    "Yn41YDHEsLu248Z89NRhmEYnt7VN07Atz/7R9eUbRp0ZLXfBA493333vnnN+95577jnnAUu0"
    "REv0vyZuAXjIAESaTKYes9mMBw8eQBAEDA0NYXx8HAAQGRmJ1atXQ6PRICsrC3q9Hnq9PgPA"
    "SwCTiwbe4/FQfX09lZeXk1qtJqVSSRzHEQC/F8dxpFQqKSkpiSoqKqihoYG8Xi8t0EQGRdH1"
    "9fW0bds2Cg8Pn1Hhua7IyEjavn07XblyhQBEfBDNLRYL7du3j6KjoyXKyGQyio+Pp7y8PKqo"
    "qKAjR45QbW0txcTEzAkkNjaWamtryWaz0Xs1mZaWFiooKJAIl8vltHHjRjp9+jQZjcYpkwgH"
    "ILfb7aRWqwNaDY7jqKSkhIxG43sBwd28eZOysrIkQrVaLZ07d44EQSC2mSW27HA4AgYwdW3a"
    "tIlu3769oPuC6+jooJycHIm5GAwGunv3LgHgZxoYCgAAtHnzZrp3796CgOBsNhsVFxdLTObA"
    "gQPkdDrnXOpQAQCgsrKygGTMRWGHDx8WXaNMJqPq6moaHBwMiPF8APA8T8ePHycAinnZ/cqV"
    "K0WmpaWl1NvbG/CszAcAAEpMTKS2traQTSnGYDCIzFJSUqi9vT2oJZ0vAAC0Z88eAhAZtPZN"
    "TU0UFxcnms6JEyeCXs6FALB27Vq6c+cOzRbH+CNla2srhoeHAQBpaWkoLy8HgH8+9JE/ODiI"
    "9vZ2zOTt/AIQBMFx//598bmwsBA6nU65WEGXyWSC2+3uDRiAxWJBX1+fGElu2bIFAF4vFgC7"
    "3Q6bzRa4CT18+FAMhRMSEqDT6cBsclHo+fPnsFqtgQNwOBx4/frthCclJUGj0SxfzKTlzZs3"
    "cDgcgQPwer1ie9WqVQDwajEBTE5OwuPx+H0n99f54sWLd4F/dDRCzZpkMhlSUlKgVIa2/71e"
    "L8bGxgBAvAcEQHIcc6HHU6mpqXK73f6aKPjtMzExgZMnT+LWrVsAgJl4+AUQFRUltkdHR2c7"
    "L+Y03/T09FBnIKy0tPSlP53m3ANr1qwR20NDQwDwwc+A/v7+b58+fSqaokqlChxAWloa5PK3"
    "i+NyuSAIwsgMcn5k7vXXabxkAH5j/ZcA/MLa5T5jS1i/xR/j0dHROrfbDQDgeR4ajSZwABkZ"
    "GYiIeJtjP378GBaLZaYSTA2AHgDZAKpYXzWALKZYDYALrP9Ln7Gl7P6TPx16enqmVh/Lly+H"
    "VqsNfPkEQXBmZmaKAdWhQ4dolg2fCuA5gD9ZexjA3wDWTdkygL+YK46bVo/yAHgDIMGf/VdV"
    "VYny8/Pzye12O4MxQeX+/ftFBuvXr6eenp7ZXEk5+3aY3Xf4vD/P+qvZcy577vTHzGw2U3Jy"
    "sij/6NGjM07gTN7lVUlJCWJjY8WT+caNG7O53Y/YfcprfOLz/numTGUA5rPs+vXrcLlcokMp"
    "KioKPha7du1a5s6dO8VZWLduHXV2dvpbhWxmHoPMHDzsOcfnuxZ2IH4M4A8A4wCifY+dpqYm"
    "SkxMFOXu3r2bAESFlFI2NjZSfHy8JNHu6+ubDiIKgMDef8X6vmDPgo+Cn0/zTATgZ1+BVqtV"
    "UkBISEig1tbWeVUnwurq6iRJfU1NDXm93mfsfQMTds9n3F3W3+Bjrs5p2dZn0we43W6qqqoS"
    "ZfE8T8eOHZtXUg8AnNVqpaKiInFWFAoFHTx4kFwuVyjh9deMz9D0/SQIAu3du5d4npcUEPr7"
    "+xemNtTW1iapyvE8T7t27SKTyURBhBkRABoZj29YH280GqmsrIxkMpmkOtfV1bWw1bnGxkbS"
    "6XSShHvDhg10/vz5qZmSzSKwc9rMfwdgmcPhoLNnz1J6erqEp16vp+bm5vdScueam5tp69at"
    "EoEKhYLy8vLozJkz1NXVRR6P53d2ePFMCY61w71e7zOj0UinTp2i3NxcksvlkuJuYWEhdXR0"
    "BKV80Ci7u7vpwoULuHr1qiRv4HkeK1asgEajQXJyMlQqlRhBjoyMYGBgAE6nE48ePcLw8DAm"
    "J9+lGDExMaisrERNTQ20Wu0H+dkRc+nSJSooKKCwsLCQaz4RERFUXFxMDQ0NIfv6eZmU2+2m"
    "ixcv0o4dO0ilUpFCoZhTaaVSSWq1mgwGA12+fJkGBgbmZe8L8pPPbDZvm5iY+MFsNqO7uxuC"
    "IODJkyd+f/JlZ2dDr9cjPz//UwBjWMSffEu0REv0H6B/AWVdt+2jDAedAAAAAElFTkSuQmCC")
