"""----------------------------------------------------------------------------
   icons.py

   Copyright (C) 2013-2014 Wilhelm Duembeg

   This file is part of gsat. gsat is a cross-platform GCODE debug/step for
   Grbl like GCODE interpreters. With features similar to software debuggers.
   Features such as breakpoint, change current program counter, inspection
   and modification of variables.

   gsat is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   (at your option) any later version.

   gsat is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with gsat.  If not, see <http://www.gnu.org/licenses/>.

   Embedded Images
   These images generated by /usr/bin/img2py

   some icons by http://somerandomdude.com/work/iconic/
   some icons by Yusuke Kamiyamane. All rights reserved.

   These icons are licensed under a Creative Commons
   Attribution 3.0 License.
   <http://creativecommons.org/licenses/by/3.0/>

   Attribution-ShareAlike 3.0 United States (CC BY-SA 3.0)
----------------------------------------------------------------------------"""

from wx.lib.embeddedimage import PyEmbeddedImage

#------------------------------------------------------------------------------
# imgGCS
#------------------------------------------------------------------------------
imgGCSBlack32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIcBzAXW6G7pwAABvhJREFUWMPll3tsFNcZ"
    "xX93dtaPXbuxYRcbs2seAdsYJBOZVC6hreMAVUKUmJYILEAKaqtQ1LRSVFVqFCA8VKgatWqA"
    "JKZpBBJNY5oSZAdRBKmKRHkZB4OhRoTXWk6wvVtTs7tez8zOvf1jH13jRcVp/+tIV+fe0dyZ"
    "M9937vnuhf/3Szzsgy9s2rQVmPZffm/vHzdv/iTzhv6wM5VS0/du3LjKtm0UIJVKt9RYZfYT"
    "kxIImKbJz958UyzfuJEPt2xJk9DGQQBp25imiWkYaTQMg5FYjJFYjNjwMMPRKMPRKNFIhEgk"
    "QiQcJhwO09vby4HNm1cppdZ+Z8OGxV+GgCaEINU0QNM0HEKgaRpaJiZb+nkgEolgAr/fsmWV"
    "Umrtt197bfH4CEiZFs2XIXH37l1MwAT2bt3apKRcu+zVVxePRwMi9XGUApHQr6YUaBpIORaT"
    "l0xqYHdzc/reV8vLm/Z9/LHnoQlIKRN/LQQSONnRQYnXS9/AAJM8njT2B4PMr6kZQ2LBggXY"
    "tk08Hse2bXRd54Njx+LjjwCgCcHXa2tRSjHT70+jBGb4/dhKZY2EcDhwaBpKKQoKCyl/9NF7"
    "44mAICMFqUigFJ/dvMmZc+eIhMO43G4WPvEEZVOmpEn85fhx+vv7eWHFCmSGAUkpxbhEmFJ0"
    "CjUh+OLOHd5vaSESDlNVWUlffz9Hjh4FKQmHw7S2tnLx4kUGBwdHCRMhUFIyrgiMEaFSdF25"
    "glKKpU8/jdvtpqysDIcQSCnp7+tDCEFZWRmhUAhNiFEWPK4ISCm7EzPFqEjELQuA3JwcLl++"
    "zIeHDrG/pYXBwUHmVFezfNkyCgoKEivmviU63hQMpkSYSWL6tER5OHP2LJUVFdTMnZv+w5RP"
    "ZIo3RUIk3qk9VAqWL1/+/XgwuGb3zp1UVlVR39CASr6kZs4cenp7aT9/ngtdXeQ4nTxeW4vX"
    "600sW6XSOdcyfEIkI/DAatjY2PiSEKJeKfWGEOInLS0tKy3LYvdbb/HMs89yuK2Nqupqnlq0"
    "CKUUcdvGME3MZN1IFaZ0P9nycnORUpKXn8/KV175KGsKli5duq6iomJdc3PzyuLi4u2WZWmh"
    "UJChoX9iWRaH29pY++KL/P3KFd56910++/xzTl26RG8oxKXubvqTOBAM0tXdzUAolMaUbadE"
    "mDUF8Xj8qfXr188LBG6zbdvWxRcudFpSJgrrvJoaKisrCQRu07RiBb997z1KvV5KPR6UUpR6"
    "vaOwxOtFQQKVSqchJUJHNgI+n+/2yZMnZzY0NEyPRqP4fD6HEAKlFBMnTiAcDqPrOm/v2cPC"
    "RYsI3bsHwI2eHgCuBwKJcSCAAG7cvo0QgpuBAOWTJ4MQ6LrO+21t18YQqKur+5GUcm04HDZ9"
    "Pt8Mn8/n6OjoMH/ww5eDZ06fKZhQXExpaSmdnZ18caePm9euke90UltbS6nXS6HLRanXS4Hb"
    "PRpdLkomTSJX1xGAruvsb229NiYFpml+a8+e5mfC4TB5eXlIqdi+/RefuubV/Ongvn2/XLN6"
    "DdXVc5g1axZ+v5/CwkJ2vv0O/qoqSjwe+oJBSjwe7gwMpMepYlXi8VDo948yojEEDMPQR0YM"
    "4nEb25YIoeNw6Ja0bQ0gNzcXIXRsWxKP24yMGKAU82bPBkhoIYVZNJHyEQBp22M1UFRUNOXQ"
    "oUPi8OHDt6ZOnVbu803Vamu/NumvrR9VXOj4dEJj40oKCly0t59l/wd/4Nz580yZMYOZVVVc"
    "DwQQQvxbA1k0UT55MgAOXWfvwYPXs/qA3+9f6PVO+vWuXc3zY7EYPt90HnlkIgBDQ/+gt/cW"
    "+fn5/Gbnr/juupd4rLZ21Jr/Sl5e2ge43xOSm1an08k3Vq8+ktUHDMP4+a5dv5sfDA7idOZz"
    "7NiReE/PDXp6bnD8+J9xOvMJBgf58cs/Zevrr9MXCtGZXP8Xr14dVTHvrx0pS06mIHspKC4u"
    "3tDQsPhWe/tVVVk5u7OoqOhvp051qVOnutSSJUvUc881qvb2q6qpabXasWOHsmxbWfG4MuNx"
    "ZViWGrEsFTNNNWyaKmoYKmIYKjIyosKxmLoXi6mh4WEVtSw15/nnjz7Q/10u1ya3233a5XJ9"
    "0+12n+7uvqO6unpUfX29OnHihKqvr1fbtm1TtpQqbtvjJhG1LDVjyZJPsmlAByYCHiAPICcn"
    "Z5Wen/+9x+bOLayrq6OpqQkF5DideLxePB4PDodj1GFEPQBTmnDoOjOffPJENiuWQBRQqZOT"
    "aZpvuCorFx44cODxzAc1hwO3y5Xw9uQGRQmByNiw3I+pKioAY2REfxCBSLKlLxvssrKyB+8X"
    "Mg+bQiT++r7jmcroC03DNAzHf9oPTAVKgSnG0FAwr6rq7P/yZKxiseC/AKsV5rYw7NE2AAAA"
    "AElFTkSuQmCC")

imgGCSBlack16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg0ngp9oXwAAAtNJREFUOMuNks9rHGUY"
    "xz/vOzPrbncTZJ0cGjB00RKdGkPbtQRJS+2CNw+yGD30Ku2/kMC2pIf0VIJEqKfeeqoIlh5q"
    "1SxJ448aMBGqNk3SZZUQ2mw2dXd2Z3Zm3nk9bAyaivg9Pg98+X4/zyPYp/cuXnwHOMh/a/bG"
    "5OTav25Onj078cvamt7pdPSTdltvuK7+rdnU1UZDVxsN/fn8vC6WSueKpdJhALnfwB4YqL84"
    "MIAKQ1QYEvg+XquF67o0m01c1+XTS5c+iZUqvDsxcfgZA6WUEIAUAsswSFoWCdPElBIhBPV6"
    "nY+vX+eM41y9v7T0vrnfIFZKSiGQQpBNp/fmlVqNQdsG4P7GBj09PXyxvLzzjwTFYjFvbG2N"
    "Vh494vkDB3jablNvtai5LknLolKrASCEACBSSkiA8fHx6ampqatBEJz47Nq1D1YfPuTmrVvM"
    "3rlDNp3GzmT26gB7dVQUCRPAMIz0+fPnPhwefn1tc3OT3kyaVwYH+ea772l4Hr2p1B4TgIRp"
    "YnQNpDkyMvJmuVx+4Divrh87dvzlTqdD/8F+FhcX8TyP/r4+2IX6F5OcbfPE84iiSErf90/O"
    "zMxcOXQo95JhpHjj9OmyYaSw7T5ecxyuTE/j+j5SCLbdLo+a62JJSRRFQnqe9+3Y2Fhpaemn"
    "ShAofv7hwVtBoFhfr3B3YYGhoSEyySRSCF7IdHnYmUy3QhhKubKycvfo0fyR0dFCrlz+qlqt"
    "rrKwMMfw8AlUFHM8n8cPQ6SUuL5Pw/N42m4jgCiKpAmwvb2tLlwYvzE39/XqvXu/Tjx+/Du3"
    "b98kDIMuPPOZd6EVhkS7V0jMzn45CfRalnVk5Ex+/qPLl085jkMikaDluoRKEWuN1ppYa+I4"
    "RgBeq2WagALqgArDcFlksz8WCoVTAKZpktztL4RAa40EYikRUvLHzs5z4m+pskB/Kpd7W6ZS"
    "ffwPxZ639ScTBkPH3uXMqwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgAbort
#------------------------------------------------------------------------------
imgAbort = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAntJREFUeNqkk99v0lAUxw9t6SjIwhgsiBlGYCJotixhM5lZ"
    "wl72svgyffWf4C/YX8CTfwCJyZ4MW+LD3syMv5bIi1kcwUHmNJmAgEKhLaUtnlMKgcU3b/Jt"
    "b3vP53vPvfdc22AwgP9pHD1e2GzA4ptkAwiidrG7gQpZcd9RH3CqHOpKxw/SM5ycu2b42C4I"
    "6fDycjS4tOQVZmcdlKHcbq9enZ9vXpyePlFlOYNxr6YyGMGCx7P3cGcnPuA4oadp0Gu1RmPO"
    "QDzu9IfD8/mjo73u8L9pwtAD0wqyDkd6dXs73pIkIZDNQqfTmZL5T1GEB6lUnJmZSRMzNsD1"
    "7IYSiehvURTu5nLmlPcOD0EURVPUpxY7OAARTRYikag+3KfhEjSAR26/31tvNuFlNApPSyVQ"
    "FAVC+/sgSRKU8JthGHidTILdbgff3JyXGESfM5bBosEwDg3X7Xa5IOvzQaFQgGq1ahrZ8JTe"
    "IMzTKfX7oEiSg5jJDEDDARXTlTALl2EAy7LmbDzPm7oxsdssxmpW38ygD/BDrNWUQb0Ogq5D"
    "7Ph4CuY4DlLFIjjpOAhQVYWYsQG6va9VKg03Bi5OwJ/X1uDTyoppQNool02Dtiw3iZk0yH1r"
    "NMq4U/Ll1pYJnyF8C8dIJ7GYme67SAQMw5ArvV6JmLGBgeXZ1fXMx3q94AWQv66vw238L1ii"
    "/gnCHoTznU5BMowMMcTaqFRplykoidV4h2HScZ6Pxnje62FZBwX90XWlqKrNgqqWLhDOYxVe"
    "UgESaxnQacyjfFhegQTA5gLAfbxcN61C+1kD+HIG8BanxS78QtWR1UYGjLXBzmv341+NLmIX"
    "JSFr/BVgAM8jHGX/y9T1AAAAAElFTkSuQmCC")

imgAbortDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMBh9N5HW4AAABdElEQVQoz32Rv0tbURzFP/e+"
    "++J7FhyeBTU0pWCW4CJ0U4xrl7dkFRw6VenSFAqFDqmgo/4nWd7iWoOunSRLMrQBK9qmVXm5"
    "eb/y7ZAgdOk54/lwhnOU8H8ZWEWh2CrTYIPnwHcuaHeuBKGPElZR1MNS80V1OZj3hNH4evit"
    "lx6fRY9APXzSellz/GJW65DZr924dRb10VAvl5rrtcTfxc68S+qv1dxmvQwaaDyrjvw3wD4W"
    "yz6wR+IvVWmABtlcCB74AKS8ZocrrtmjTxHI5hSoKK/A4y0D/pCiOEAzIfGkAgYgxxIDGgcX"
    "gwZgAkwbBvfjGHg/ix0O0WjysQymwPnwl+EdDi6HfMbB4QhFMpTzKdC+62t7gssRLi6fgI+I"
    "TXrSBiVU2A6dVlArfDMbKgd71y1aX6IBSlDMEYal5nzVD4wH+dgOR730OIoSBCW8Mizy1F12"
    "t8yaWgH5kV9mneyGW36e5gaYECPZ76z7z88FMRP4CxsClib1AuxPAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgAbout
#------------------------------------------------------------------------------
imgAbout = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAmhJREFUeNqkk1trE1EQx2d3T67mhl0otVaoEQu9oFFpo6IU"
    "9C1CofSlxRu0VH3sF/DBj+BbRSgWGhGLKKIFESw1xRgJFTSRQKBqpaGbbRqSTdckm6wz624J"
    "6FsHfgs7s///mTN7DqfrOuwnmPFgDDiOs3IHkTDSg4hmTkYySBwpUIIW1jTtr0FLDHpE31h4"
    "4uLgwJUzPf6OQBsli5s7219eJTMfoysJRS4tYiphCThyMjsIi93tU9ce3BlxiQdEVVWNFawO"
    "nU4n7OYVeeH27At5fesh6uJUtwxET5v37mR0Zlx3c4b4f+FwOACUpjx3/f7jynb5HhrI1haG"
    "B8cvDDWculgs7ECjqmmpZ8l09m16g4rHLvd29Y2e7lUdKvN4POKpsbND72ffDGNp0TIIHb/U"
    "H5QkyRjO1yefvqWeJhcw/4iKn6PxG6VS6erRkb4BZmPQea47CLMQIgPenOgRwW8P0J7q9Tqs"
    "v8vkMD2PbJnM5z78yPF2HnSGvz3AB0iz9xsx7PVqDWq1GtD+m80m+2cAHDDBJQDPeNB4Y7h2"
    "elgd5AsbsqJWVcNy4NYQtTfdIp8+OXM+xNwMBLcAZamokGbPAGMtu5yWbC4bCA4BxP4OH34Q"
    "pnmYhMUT7T4SMxeDn8tZiTStBq/TL9eyellTaJV84hd9EGvpILa58l0SnAJUciUl+zyVJQ1Y"
    "R9I8xhHvIX98bGmq4e30r+J7sMUg6O3yr47GJhuewz46zhHSGFrTgIZGxzaCTJhnfg75bYwP"
    "wIncNO9IFFlC8qjVLAPaituEzBpIHdFaLp0NEczaLlJBbZPb73X+I8AAb+EUcaash1EAAAAA"
    "SUVORK5CYII=")

#------------------------------------------------------------------------------
# imgBreak
#------------------------------------------------------------------------------
imgBreak = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNrEU01Lw0AQnU2TWGItpAexB6FVrF+oIC14VY/6"
    "DxT9K8V/ouhP8NCTRy9BD6Jgi6FoqWJbA9pskk2ycWKtBJOePLjwyGwy8/J25i0JggD+sgT4"
    "4xKHwRkhX2wpgAIBOMCwjJhEvCI01HniAzQ5bvYiqsVfhJuSolTnK5XSVLGoyooiO5SyF12v"
    "3Gvatk9pFXMuogVk2INTQgppRTne2NlZDyQp43neT1IqlQLfsvparXblWNbhfhA0YwpclL24"
    "tjZnmGbGdd3YWZEkk19YmGtcX4fHO4oR4P/KaVXNdXq9ASFjQCkFaprAMA4V5fC7N+gNJCmY"
    "9DiXUSKYhgE2Fg6PJ34jsG3ZHTQ2TsCw2x/dLmPt9pjo+5BJGFngOIwNppJIoHVbrXIOIM9H"
    "zPyZ0rcwL9FIKO2k3uk0OCH9LHpiAt9F4ft+/9G2G2Fe4hi3sCiPPpgVhOpyOl2akSR1XBBk"
    "k3Omu65xa9v1B86rl+gDPWKkHwJCiISP/DTA6grAbhZgCV2povuMd4C7G4DzJ4BbzGljjZ1E"
    "gPlfvVPC7Yg2WIgPrPFiBP92Gz8FGAAZJMfQcW0emQAAAABJRU5ErkJggg==")

imgBreakDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMCBqjDay5AAABDklEQVQoz6WRr07DYBTFf+1G"
    "m5AiNtGEYCo2BAIB9QuW8AxD8CJ9EQSTOARYMj8aDAgGSRUZDenYaNZ+XdeLYCmfAsG98pzc"
    "e/4Ywu9j/oHTBOgAPY8+Pi4xIwbDCJ4BMATo0Duyg86u27KsonibvjypYHirEc486+LwoOGs"
    "1l+L9D5cnp5HtQbpe93MmZGSkjKncHa60tc0iL/Z/gSWKHJKVmy1xdcJrliKBTnfpg2Wlrg6"
    "IZ4XM7vCwFibKwuJtRxklCQm+qpERnpQg2RM2qjhKs3GDDTCVZQF7+FiIsoUUdnkI8yDy4if"
    "HI432G7u2yfmHi2m1aO6Lh94vclrkVTMyrsy1CrIKLUL/2rzC/+ddkCtau6CAAAAAElFTkSu"
    "QmCC")

#------------------------------------------------------------------------------
# imgCli
#------------------------------------------------------------------------------
imgCli = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNqkUztuwkAQnf16ndihgjJFWh8gCgdBokfKBWhS"
    "QJuKiIYmt4AT0OYAER1FGioUBQtk8IfMjLFRFClSkpWeZi3ve/P27a44Ho/wn6E7nc4N1ltE"
    "+EtujHjReZ7f9fv9h1arFeV5BlmWI1JIU5pnUBQFlCYVCKEZWltYr9evz89PjxoXXG2322i5"
    "XPJiAooyfpojoul0eqmNMcVgMIBms8m+KJOy67GeE9I0hSQ5gJTkQLNLzgBtCiIPh0OYz+ew"
    "Wq3YOhEqbDYxYgeNRsj2CbvdhgUkLpbUaTweQ7vdBswCOyU13t8/II4TMMaB510wnPPx254F"
    "yGKv14PZbAaLxQK63S5EUYTELez3OZL8L7CWBEy5BbQolVIwmUwgCAK2PxqNMG2BgWnuWNo2"
    "3JWqUporCxwOB+V5Hvi+z5ZpzyRYFAo7uROpJFJ4UpKAxKpqAUk/iFyFR+fu3FUdWNWVQM5o"
    "VJUdOOdwr3sWoHO2NjhZPxOrjt+uMl4iY62tz70cBgNc10QpxamjqIlJEuOxNgIRhuE97vn6"
    "Lw8J3b6RpH96SPqX/IwelPjvc/4UYABrxgUeC3Nd3QAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgExit
#------------------------------------------------------------------------------
imgExit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAlhJREFUeNqkU71v01AQP3+okeOkjgVNREK/Ai1kYghlBVUs"
    "DGwdQCojylhWNv4E2OiGRAeYGbogJCaGKFWpiKqWCtokShNXadPKrf3s92zurKaK+Zg46efT"
    "3f3u53t+ZykMQ5h7+R0kWQZVVUE5hyRJywBQRtSQUxGcA4EjwiCA6rMZIJPhN+O+D0IIIpYX"
    "5rNl8lGM+b/ZsEAS3/Qc8dpnDLjngeuGkaeY8lQn3h8CAtUDzpdmxpMVbLg9aPK8AAZilC8W"
    "tArxxNA0kYDveXNmWlmcyKUKnuvCAIxxGI7Hx1IFQ5cXiR8XYOzRzelMfqPe7SFx9ULAjQms"
    "1resXrFg5IkfE8BiaTQ5kmm0rCMsvo3GxyZZEpGnmPJNrKcSSob4AwGVHsx1L9nHNhwenThC"
    "BHt4hZSuvXn/ha6zRgF+wD3fY47dtyN+TMBznB4XHNSQa2cOm4Qg2E7oeiXA65MVBdjpKc4q"
    "T47qCY15bsSPH4GxzUan308bmomjPmGOoxzu70PfsoA8xZTXRzWzaZ30iR8TwCt6t/51t50r"
    "TecSmfRjXJwXmJ5FJMhTTHmjOJ7b3G61iR87Am5btdOyVpRvPyr5e3euNes/nzqN1gI/PnZU"
    "w9C0iaumOTuV21nb2Ot1eit4rOpAQKJ/gT6afONhMrz+YCl5JbtolG/lw7FsSowkVFqGoGvZ"
    "9tp6m3UPVqSd1VfB1ocz6hsWoEkuI7IwdbcEU/P3QTMnQFIyEIo+OEcN2P30EXY/byHnAGFh"
    "nz8sIJ/vuI5Q4N8WIM4Qp9gnLgT+x34JMAAuBJ9VBPnzsgAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgEye
#------------------------------------------------------------------------------
imgEye = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAdhJREFUeNrUk01LAlEUhu845QdRUxZBhIIWtFBso2AwRAVN"
    "LqKltHCb63b9A/9AixZCELhyYdAmEyYCBcOlNa1CSQoxog/DMY3x9p5B27Zw1YGH8XrO+557"
    "59wROOdsmLCwIWNoAwFh/ugfZQKsAQV4gbNf9woqIAeuQHOgGxgIMNix2Wx7iqIsxmKxWU3T"
    "xgqFgpWSsix3fT5fK5VKPedyuftOp5OE7oz60hHsYD8UCh3k83k5k8ksGYYx5XK5rK2WzgiI"
    "rPQf5aiGakljakVRjKDrZaPR6Oi6zglVVTlFMnnMZXmdK8o2x674IE+1pCHtCFx2w+GwE9u3"
    "drtd81yJRAKdDXZ4eGSuFxb87PHxjg3yVEsaNNolg5NSqTTVbDaX7Agq8Hg8TFWLbGVl0xTY"
    "7TY2Our5NfhCQPNAWtFisdSr1WqvWCwawWBwRpKkcZyXadoN83qXmSQ50V1jGxurpnGlUqnH"
    "4/FzvItTmoo5ApjQNMIOh2MrEon4o9Gov1arzZXL5XHKBwKBT7fbXU+n07fZbPa23W5f4BVd"
    "93o9TgYimATTMHHCbB5PN9ZSf0LmrsEHRDWInvB8w/oFvAv920iFDkBzF/64fHTjvoFOxsL/"
    "/5h+BBgAwjbgRLl5ImwAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgFind
#------------------------------------------------------------------------------
imgFind = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCwkJO+fKowAAAn1JREFUOMuNkt9LU3EY"
    "xp/3Ped4th2nS0WxlSQRqUtIK9ZFZWlddFGQXXVbEBgEEXlXV11ImBP/gIIYFAj9EsmLTAyC"
    "EhPByKmlNWktnWtzc9vZcfueLnIx5i564cN78Xx5eN73/dL5G5+haaWwWq0NzNwNoB2AE0AA"
    "wJgQojeVSs0lEhsoVjIAmKa4kE6nPK1NltDRZqu/ppJX5pfTsSmf7ppfzIyYprgJ4HlRA8Mw"
    "GkyR9XSerfjSccReyYQyAGjea60sLxeJqh2Z+Vdv4p5MJusTQswVGkjV+y/da3FZ7edO1ZRY"
    "FJZzAhGIiM0Si0nh8EZ6yR/dZxjGkGEYyEeOxWLtLa49i4HfSTkA6MViNjeWRkff+tuLjqDr"
    "aWedUwvW12gqAMoXfYFYDAB21dosup52FjNgITgQ/JXMFBMbnWV2AAiupDaF4IAQjEJYUbSx"
    "iamoQwiTCg02M0JIzNLk9HqFomhjiqKhEFlVy3rHJ/SR44cTIfdBuyUrzH9pjKwJ/7ek7f1k"
    "3OlIv7yuGJ9Af7cLZgYzQ9rp6lpTSuzLEzNGZ0onUeVQDIddsv0IZtIvXsfVweGws/NEvHpx"
    "ZtBnmuZPIlrPmRARqOXiR6iqHaqqNTBL235iYPbBo8jXgTNe75PbHk/vnWQy8YyZZ3MJZLv+"
    "GOH1Vqi7T84RSVcK95AxoohEIsGurqtWr3fwbl9fj21tbXUIwAcUnq2+tXvbJb5P3wczg4gO"
    "NTUduOz1Pr3W398zsLS0MMrMw/jfIiLIsny6ra3j4cLCqul2u2/V1dWBADAAaQsZgJKHnNdl"
    "AJIsy8ccDkctEY2HQqF3tDUGF0Eq6Lz1NkcWQPgPoNkNgoXHVyQAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgGeneralSettings
#------------------------------------------------------------------------------
imgGeneralSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAY5JREFUeNqkk09qwlAQxr+XvKgFIyb+QUQqdmkvkK6KV+jK"
    "U7gRkS5EcJMDeAQ3rnqOXqBbBdGFilGsrhK1bwZjFSpUDHyZl5eZX74Z8sThcMA9l4Y7L6H0"
    "pOQomTfWfit9SnV76ff774VC4fm/7QghMB6Pv6rVqkstWPl8/nmz2aDb7YIg2+32z/VkMkGv"
    "18N0OgXVUC0B9CAIsNvtoOs6R8/zYNs2J57vL5dLNJtNzGYz7Pd7MqOfACQpJUdKbDQanEgw"
    "y7IYRqBWq4VYLIZjuwyQIcAwDI6apqHdbiMajWK1WqFer2M+nyOVSnFxLpcLAfIEoETTNDmR"
    "7MfjcWSzWR5Yp9NBJBJhOEXf98N5/gLW6zVqtRoWi8WFG7KfSCSQyWQu9gkcAgzaIEuu63Kf"
    "5/O4tj4CDHZAE00mk/y1dDrNEw8Tr61pPlQrFckfDAajYrH46DgOOyGblUqF12S/VCpxw/Rc"
    "LpcZMhwOR1SrJF7Vuzcl+8Zf2VP6oEYejudA3ggI6DyIe4/zjwADALUz7/8W+6CIAAAAAElF"
    "TkSuQmCC")

#------------------------------------------------------------------------------
# imgGotoLine
#------------------------------------------------------------------------------
imgGotoLine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAh5JREFUeNqkU89rE0EUfrOzScxuthG0gkEtVA9GQYS13qsI"
    "ngRBQax4Elu8eBZ6lP4JgiL24kFRDHiQoPQgopc2BwXpRQSDENiwtpuQTXZ3fvieZtdGoz04"
    "8PFm3pv3zffmzTCtNfzPMNPJ7LJ3F42L8BDriEdSqVUlJWilRpLeLuzP5kY6QSXzmPBswjb2"
    "nDjiXHUs4wE6b2HI+peCXwR4ihJiqe2HrwucFU4e3lndN5m/hgpukgopRIaxBHEUQRLHtOFl"
    "s9X91g8FP1Sxp5wiu4y+mW0Jon4fEiKJoi9tv9eXUkGwmfCDFXuvSJJLfyPILpGSh8Pb2FCx"
    "1gqiSEDJMR2MVbftAskfjk5HJJIxBtRhgxl5jE1mSsNwPMFmuw25fB4KVlHghao4TiAIAhDC"
    "QHUD9rPMAWA54wloUFB1JRicg+e1wfc7wFgJ4kEE1An123sYIcB38OMhSWoZosdMCHM70ObS"
    "8taG+xpo5v8gkElSw6B7Zu6U2wpiaA4E9CwkAQ7Ts647UeSwWnvTwLupjX9IWtexhMUXy/UG"
    "K5egyUvgW2X4amIJjgPvHq80KE77thKw9DPRrReOXQBePXcWfbenFq64n7oaDtgMWvce0smL"
    "cv15PfrwFEY+IC2GDlJTROwyZ67P5c7fX6u80posrdG/G2EjeJpD2KqAoykTAcIxjl48DtOn"
    "b8DnlTvq45P36OshfOo45mS9/C7AAC/XRIWgonuzAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgLog
#------------------------------------------------------------------------------
imgLog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCjQhZXhA0AAAAgZJREFUOMuNkU9rU0EU"
    "xX93mtQkNJJAKUTaTZqCpOimq+IuuhJciIhfwc9QKKHtxg8g2HWhK3VdpOBKt20WEoRKX3AT"
    "4qJNmj+v5s3MddGX2JJUvDDMcDnz4xyOEM/LavUZUODf8/n91taP64vE6OG9v7dXre4OnSNy"
    "jsh7nCqqCkCtVmPv8PD1i81N+bizczL6Z8YA58R7j4siXBQxvLwk7Pfp9Xp0u116vR4ftrd3"
    "vXOPn29srEwAnHMigBEhOTNDKplkNpEgYQwiwtnZGW/396mUy+++HR+/mozgnDEifDk6QlXJ"
    "5XIMBgPul0pgLZVKBVUlm83yqVY7Pzk4uAmwzomIUCqV8N6jquTzeVLJZCywWO/H2gkHzloR"
    "oFwo8LVe51G5PLWGn90uztqpAGNE+N5qoarUm82xk9Hx3jMjgrPWTACstUaARqOB956n6+tT"
    "nfwKQ+wtABERlpeXUdVbnSSNwV6L8LfGKDICBEFAu92m0WgQBAHlQoFOp8ODxUUeLi1dRYii"
    "WyKIUCwWAcjn86gqg+EQ7z0XYYhXRWLthAMbtxAEAaenp6zMz9NsNsnMzjKXSnE3nSaXyWBE"
    "bkQYOwj7/QTAk7U1VBXrHAr8tvaqgbgFuaYdAdJAtnN+fme0FBGMCKqKxLcBvDGIMcTaBaA7"
    "AixctFrtudXVN/zH+DBsxwD7B6PbNz1a3d2MAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgMachine
#------------------------------------------------------------------------------
imgMachine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAoJJREFUeNqkU01oE1EQnk02iTFQE7QihUKRkKTF1iU9+FdQ"
    "CoWYgAcPegkIeiiIWiHgwUvpQXs1Ggo99OYlFwUhWAhYhZJWUmhMxJbYYk1LFDcmJraSv911"
    "vjQbevPgg9kZ5vu+eW9n3hM0TaP/WSI+gUCADAYDmUwmEgSBUNRoNJ5jaKjNSyuKsqRjjUaD"
    "VFWlWCy2X0BfDJ5nd5r9KxZI0Wh0BuRgMHibcznGrrD/wD6hawwHxBdcLte12dnZGYfDcYOF"
    "hkJBpnL5F3Y0IAcMHHB1nYAj+Xw+xHeZ8FSWf1BPTw+trqY2JElyAkilUhsej8dZKhWpu/s4"
    "jY+P3+P0s/n5+f0TVCoVqlarL0Oh0KTZbCZZlmlgoN+pqgrBEO/u/iZg4IALTecX+BQX6/X6"
    "9Xw+v8e7bYqiSMvLy+t+f2AGhhg5YOCAC43+7+T1eh+srCS1hYU32tJSQkun09rg4NA0TwLT"
    "IMTIAQMHXGigbU2hVqsZq9UaNZsKKYrKoxRZKDYwKizEyAEDB1xoOk3kzo6xP4PExMT9WyMj"
    "l/q2t7+npqYevkBucvLx1d7eE9Li4tutcPjJXEsoCO+z2WxcP0GcC3zmDt8ZHj7bVyyWyO32"
    "SLHYOwl4ufyTdna+ELCuriN2nlSEC2x1mshdRZGbkchcSJaLfCOtFI+//prLbRIMMXLAwAEX"
    "mk4T+ZLALo+Ojj1PJtc1t7s/bLfbHyUSGQ2GGDlg4IALTesd6Y8JY7JarX6bzTZtsVhOwq+t"
    "fdMymZx2MAcOuPrmrSYKaDHRUbZjbIcA8sM6xQ9sADFP4xNf54/t21tnk9kKrG3qBdCLw20T"
    "//GCFbY9tj+sVf8KMAACOoVxz9PPRwAAAABJRU5ErkJggg==")

imgMachineDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsKGSg8jqKbAAABp0lEQVQoz32RPWhTUQCFv/ty"
    "i+FBIKAQLTEN+AaRohlctIOgiyLRrUKJFOrPUKxLwZ+hdPSHLkbJogWpZurQoEgEURDBLFkU"
    "sYKN7UscLJa2NHlp9L57r8NDR89wpjOc8x1h+b8knMahD4GleYSDwMdMTWBRGF4go9zyUXHI"
    "PhO5yyXN7PhyU5yxH9LvARwAfyg1XCi5o9rpsI123NFCKTXsDwEIy0m+TxSKbZI0l/Z60Fra"
    "4wUkeHo1ff8lDmyhFuanJW36PYul3+shmZ9WC1tRydVjHN4MWo2Bfd++VN/AqePp/X5jM+Dc"
    "ap23wjJw7fydHn3s4NHtHzdh962LN36hiPPkun9XQhhTGAzgqMjBYFCEMZAQ1h9PwYkLXvZs"
    "/rmCfN7QWnk9C9RBQvxV+2viSiYbkMpN5GCbDTLZeLL9ILECDvQIx0YmO0gW/XXWWfQlHUYm"
    "w7FeBEqha5VykrlipWwwVMpzxSSVsq6paOYGstoQMy39MHbJxaCdtXszXfPOVrsRSSHZyS7i"
    "EBsUB8B+1p+A3/xkzYbCIhxc3L+3/ZMmoGvNH8TKrfqjhKcGAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgMove
#------------------------------------------------------------------------------
imgMove = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsLAhXMEk8nAAABbUlEQVQoz1WRv0pcQRyFv7l3"
    "diNmQbOYOqBYWM8KxsI/KWQgkLD4DhHyAjZbzisEub6AhcKiEBkQFCy2umMeQG6RMiiKG4l4"
    "//0sVhdzqsPhK87hqI9EaCwKTWxx9CpfInhKagboJZo0AcBW7pM5dYCHFXJyIOJFtnRr5p41"
    "UzrsOH0B7si6GUl4QxIysu7dGNAAYnW3tXUPaQHQaaET6eOfAbGFg5hJ/lEAk8QUBiPgQYst"
    "3GfzM5BGNPZvjhtTUVpRsW7OnIBX39Mv5pZpSoYU28Pk7aocCsI1s5yHHx2d9/bdpjkIAFwt"
    "LwzmCAAdcxJUD7T4gj0HcQeqVEweRm4QVK/hRyV9Dt0SRYTwSI2gA/3maMUvZpj2pa8TZSqg"
    "gFSCbGn+cA3oC+A987T7Yr6aB6w5Cqp/wyVX/Kc2i3Yj3ZGNdNG2x6mgiGnxjik0zJkP337v"
    "ZgEoGXLLX6kUEU0mmHh1G0DNIw/kUj8B2jqZwW6x6egAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgOpen
#------------------------------------------------------------------------------
imgOpen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAaFJREFUeNqkU88vA0EU/mZ2WiElfobERfwBLiIhcfA/OLki"
    "cXSU4OJQcSc9ceQiEkcu4ibiUhWkxKb1o6qyqVLbre7OerMqWqlkpS/59n2T9743M2/2Mdd1"
    "UY+JkxVWM8AZBsiN1wjtSBex730FYYrQ9zuLkjA4JxdzhQKypolpvQOGYWL9NMQpPETYUHns"
    "KIzw8OzuPBwHrivhyko4X17FypwxhujmzDJpF7wTOBKaEsuPYpVQVog9XvaaFoCnIQvQl6tF"
    "9c5/i79PojRB4fUJwqaFtG0Y8UMU354BVYw69AVJa/Lyh3PO1c6jpF2iQyQEFRVWLg2bknpG"
    "Jnw9Xe/Y5PB7Ru++2J5fFTZdK288QGtqg5VJw89/wRjHc/z43rJxrgqIbEpHV/8gbGqkH9OC"
    "DUjfnKVNC5eiJCHyuVf0sIDvAk7Jeksl9SeN415Q/wJaYztsy6ROS18FjFT8MVfANVFXEGkJ"
    "NXfSk3Bwjfu4P8OdfvVydovY2h49YzSB5OtW5OA/A6RncB3Zh060VU1SUJHyXPg1h2ARiqze"
    "cf4UYAAOUhKfHcZJBAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgPlay
#------------------------------------------------------------------------------
imgPlay = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAXhJREFUeNpi/P//PwMlgAWZ4zDvJQMjI+NMIPPwnz9/lvz5"
    "/Zvh98+fYPzrxw+G6w2m+A34+/cviDKGYhBYQsgFTMgckI0gHOstZQykCxj+/48hyQCYc9+/"
    "/8MQ7ydv/PvXL4KGYDXg+/c/DJcvf2KI9VMBG/IfjyEoBoACCoR///4HNOQHw/HjjxiCXIEu"
    "+fkTpyFYDXjz7gPD46dPgfQ7hsNH7zC428qCDSEYjb++fwfTr379Z/jAzg1m6ygJMqzddP4s"
    "MHonEDYAaDsIvGTlZnjJzcagK8nBsG3lfrBmVnb2JYS9AEowQPyClYdBXFqQ4diiHWeBgTgB"
    "6P8lP59cIpwSQTEAFmRnYbg+cwnE2e9uL/lyaS3D7+dXgDIlGAYwIucFVu0ABiYNvzMg9v83"
    "Nyf8u7F5yd9X1+Hy2PINigv+XNvIwSSgco3hx4dL/87NBVmpAcQ/oPg9EP/E6wKgk0EGCkEN"
    "/gcyEwn/AKr9g9cAcgBAgAEACsnYjGRDfAUAAAAASUVORK5CYII=")

imgPlayDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJCTaOBTPwAAAA2klEQVQoz33Rv0oDQRDH8e+G"
    "80+TxlJSKUj6rW1TBZ/Ah7gXEbdNv5BGsMgjBAKC14QkCGIpguAl3e3EMWtxFsde4jS/5sMP"
    "ZsZE/p+sjnvMiKl6RRCEuxT8gMUCPm3o1KEoQ6t5vD0ABGHDjd22SANULPeQBvim4olBQv5A"
    "IFDyTsmMayt5a80AVHSASyaFcXtBJKPHY2HciW+BLQDnPBTGHfmP9iUFOGZcGLfxL3w2gKl/"
    "ccXFM6zdm/8CIKYNr6fdlcyXC/oEAmskaTAZZ2TsUBQlRE3A4fkFDI1aCaBdI4gAAAAASUVO"
    "RK5CYII=")

#------------------------------------------------------------------------------
# imgPlug
#------------------------------------------------------------------------------
imgPlugConnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NCNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NBNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8++VdpNwAAAYdJREFUeNqc0kFLAkEU"
    "AOC3lhlLS0SK2CWwpEOuf8EQhC10rSSlbQsiyFB/QH+hW/+ibhJ1CoSkg6eKCBFviyAs0UFR"
    "VklzehNjyJK2OPCxb2ffG2beDsDkQ0JPkxZvome2iOWCF/Ycji2NLfSayWQIfTK/xbYxRW/M"
    "RSqVCui6DqqqBlgNN0jkRhRr2Wy2ZBgGtFotaLfb0Ol0gBACgiBALpcrYY5/1JbL6XSabnc9"
    "kUgQv18kHo+HOJ0uIooinS+jyLgzVyKRKJFlmSYng8EN4vWuEJ9vjb5XzMXmHkTpXL3eBE2r"
    "QTgsXRcKD/tu9xLw/Nwg/27UAjK6TCYPVvt9Dmw2OzQaBoRC0lWx+CjyvPBn04ebqKnq8bKu"
    "f2DDPn8mHA47cByHzQPI52/pH/Cim1Fnj6GqopwQSdoj8fghPXN1SOy/C7ODapSinBIWb1u9"
    "bXH0jnaZQWxpHKEmOkMutIgW0DyinePRLJpB02jKfBO76Bzdoy/UY3M9U9xl3wf6dIFvAQYA"
    "XFKD1NmwcssAAAAASUVORK5CYII=")

imgPlugDisconnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NGNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NFNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+phlpSgAAAbVJREFUeNqU089LAkEU"
    "B/BnpkYQEUUIXQo6SBRmJB07xWo/UA9GYFJoehMh6xB16Fin/guhg3jI6OzJixCWdYjshxJo"
    "IHoINXSdviNTCGVbAx9m9u3u27dvZ9X0v2GBU8jCuFj/eVjhMhgMMj4L1i6FmxbhSjgOBALT"
    "xWKRvF7vNI7VoFIpJLgJhUITlUqFqtVqS61WI1mWSafTUSQSuVUrJMgmEolZs9k8WCqViCeq"
    "1+uk1WopGo3e4fyuUgJ+0XMymZwzmUwDvAIVio7FYg+Ib0OsUw8mYV+sz/jF4XA4y5/MGO8h"
    "dYv49y7DFhyIJO3DAXlJkniG/E9PTfn9fn4yBb4Ola1CVczfRtpmszOnc5UnScOSiE/BYacm"
    "fTZxGSS9fmTo5SVPRqNxOJO5n0FMhjmIwOtPCXgTV+DE7d40NBoMXe6mcvmN5ucXDIiHoADX"
    "nSrgG+nR4/GN5nIFbJT3VlCj4U1m1GwyiscvnnAw9tu3tkPO5fIyi8XJHI513oNcG7vST+IS"
    "ZRbW1nxMrDegH/qgF3pAK76/WlT+9Qo12GvVTHQEO3AODaHeNsttmjzBhwADANJmm8jvUXkB"
    "AAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgProgram
#------------------------------------------------------------------------------
imgProgram = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg86069mBAAAAdlJREFUOMuNk79OG0EQ"
    "h7/Zu4OzhXEKhOR0KdLAWzh1iiiK8gp5BiRkAU0eIFKokaiS1ChCyivgIqlIDaKxMXfHnW//"
    "pfDdBmILZaTVrnZnvp3f7KzQ2LvR6DUw4Gn78eXg4PfDjbhdOOeen4xGx7W1aGvRzmG9x3sP"
    "wHg85uT8/MPb/X35dnR02capALBWnHNYrbFaU1cVZVGQ5zlZlpHnOV8PD4+dta/e7O29XAJY"
    "a0UAJUISRaRJwlocEyuFiDCZTPh0espwZ+fzz4uL98sSrFVKBCUCQBJFf4Uaw3A4xHtPr9fj"
    "+3g8vTw7ewww1oo0gGfdboi9ns14sbUFwK+rq+C7lIE1RgTY7HS4K0uc92Fcz2YM+v0gxxqz"
    "EqDa9JUIm50OAJOiCHLW4phoAVBLRTTGqBarlCKvqgBrwWmSkEQR5gEgfgAQEWFuDOtx2H5U"
    "k0G/z3Q+x6yUoLVqn3FuDL6tgXNMi3s8i4aKRLBar8xAiQiJCmdUWtNNU/KqYiNNAcjq+gkJ"
    "i5bG+cV9znsqrXHek1cVznuUyGoJZVHEbQH/tWxe02syuNc6+LaADtCbTafrQPg8vlm3c20t"
    "zntEKRrfbSBrAdt3Nze3G7u7H/kPc2V52wDMH+TGCvd5v9PGAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgSave
#------------------------------------------------------------------------------
imgSave = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QMBCR0qtm4moQAAAkxJREFUOMudkc1LVGEU"
    "xp/rvNfGcVKbjy6D0x1jKEYcZGjCNkZBIQQSWLmLNgatopb9A6Lb0I2LFhFBNSW0Cfra1SJx"
    "iBaKUabI1FhK40h33jvnPfe+LRxdBIJ24IED55zf+QJ2sf6p0tmJJT06saQ7+6dKV3fLE7sF"
    "FFHf5qZq0hoBRVTbN4Bct1dKpX0fo+S6zQCm9weQMl7ZrLWSUgdIyo19T1CXMvrd5bznG6hL"
    "WdwTIHnr1ZRhGPkGAKtmKzx/yz9y+/UsAGiti6W7Aze2awwAGB4ePgkg/6W179SaaZ/rvX7F"
    "XvwD/K4DvtYImwYONQPrD5+uxNXK22POzAcAxUKhMGsMDQ3FEonEyNjY2LjrupieKeH+ux+o"
    "Dw7iY2WrSzoMRF48x+VcDOczMZhmEJOT43fW13/ea2LmeCaT6WZmVKtVnD7ajIs9LfCfPIYd"
    "AjpbgNCzRxhIC+QtoFLZgFKMVCrdzcxxwcxWIpGwt3eq1Wo4cVhhrdPBy8IDaA2cSUpkOwQc"
    "x0Qo1AYAiETiNjNbQillpVIpm5nhui6q1SrK5TKOt7vg6C/4vkb6YAirq2V0dDAMwwQzw7KS"
    "tlLKEkQUSyaT6Wg0ivb2NnR1pZDL5UBEuKAUPM9v3LoJQKDxOAFmL01EMUFEwWAwiMXFr1BK"
    "gYh2pBTD9/8FbEEikRiIKCiIKCClxMLCZ8zPz4GZd+R5PrRGo1jsqDK+jGvvb4KIAsJxHLNY"
    "LC5ns9mubLZnTxPINwpz3z4tO45jGuFw+JIQIo//MGYu/gWaSzpM3qF0jQAAAABJRU5ErkJg"
    "gg==")

imgSaveDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAwEJHh0l/tBtAAABN0lEQVQoz3WPO05CURiEvwuH"
    "x1WDyMMLqFcSGgnEBmLtBiw0sdLOwsINuAGivdHEwiXgSqQUiAkGGqOJCfhA4Jwfrg0FBUw3"
    "M18mGZhRdb9RaWxUT2czNWtkb+jz/PK3GNg13qQiQR4XACY5WB6HTG/hgo6PSh66Nge4vbdK"
    "IHh4CHdP4NUuzgH8cFwuHPhcVSznIxnDhHhmPdOR904mVbDqb9ZhIn12dT3khSY5foAlWmyR"
    "IsDN5eeDT5I7eeGLNVI8EyZEnSghuhiyeUkqcdIugCZClDoQwUYTAGKuOMo4264w5JcuQWzG"
    "KHrY2AiOaxylE5u5OKtoRmgM4+k9C5CcTigdDtPCoNFoDJMZIIYOK+0f0KSOIAhjvGkJJ3yj"
    "/aofqLWL2eKchQ9e2/2AtXKkSiyU1P4BlmV4dLjh4mYAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgSettings
#------------------------------------------------------------------------------
imgSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAzZJREFUeNpsU21Ik1EUPu/2OufHtrY5dJtoQlKGhKaTTcuP"
    "mZVhoG1TcAYJZv5cURqGoYIxhoFZSM38UaZYgxK0EtEfIn7PhdIPQaMCmebIj8myubm3c+cH"
    "Fl143vvec8/znHPPvYfS6XTw73A4HCASiQ7WLBZLRFFUCv5GkLXFYunHya7RaIBeWVm5HBYW"
    "JkXDEqKHOBCyz+fzk5Eo4vF4Or2+uDAu7mRyQkJCJbGrVKpd8aGhIanZbH4mFArjNjY2wG63"
    "w+LiIuzs7Pjh9XqVGs2VoqioKDXOzzG7HoVCYccgcuTLWCSyUqmsKisr02MmlYTkcrlgc3OT"
    "kAnkkZHy5Kampt7x8YlOkjoGk2OGBdvb27lEoGd+ft5UUlLSUVFRoZdIJJWEuLy8DG63Gzwe"
    "T5DH4+WVlpbmKRTJxeifFBt7rKq1tfWB0+nksPcLtbq6OjI8PMyvra3V22w2/tLS0khISAiF"
    "W6lqddYFp3MDtFqtiqZpmcFguGq1Tk/39fUNsg9Xf21tbWRsbMwvYrVa+ZhJeEBAQFhqampO"
    "aGgo0DQbEhMT5ZOTU59MJtOH9fX1txT8Z8TExFTez88vjTWbvYLrZfEFve/r8Uicve1fiG9s"
    "Nrs/MDDwB40fIOocDucAeO9fhS0tgrS6Oml3TY1dJxb//O12Nz+l6YMgKLA74zn9i30guSAi"
    "IiLl0tn0i5bHzct5ublHTthsTJLPF3nN6x31ImmGxfL7Yj2ATTI4RNZERx/NNBobb93uaH/o"
    "2nT2hc/MSE+Vl2c5bDYPAxAZ7/ON6PCWohFC8tj4fD6IxWLAqFq1+px5auozk5Z25olMJtPe"
    "EAigG6DhHYB1y2Bgxijq4yhF3R2kKHiDmXSQM+wJFGZnn38xO/uFSU/PbMMHVSiVSiGZywUk"
    "E+eG1yiyXV3NIHlggKLuHRYoysrKeTU3Z2cyMtTtAoGgKDg4+K9bIe3WjiIvUWSnvp5B8nAX"
    "QK1fAJ2NCwsOjKzu5HK55WiSIARkCxGI4CJ4pMfuADxqQxHGaGTMAFNm0mxYySIs3mmGYb7j"
    "sx1H2xbCtQcPaThEECKEiN4EKD8OoJwA6JoHaPwjwAC3pz/3riyFYwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgStep
#------------------------------------------------------------------------------
imgStep = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAeNJREFUeNqkUztLA0EQnou5i29sVPAVRBAtrK4XLUWxULBK"
    "GhvbVP6OVIrgowmiIFZiWkHExgODGBTLENSLUSImub1H1pnl9vSQWOjAx+7Ot/PtzOyuwjmH"
    "/1hUTmZ2n0FRlC2cnruum3EdByKKAmosJnif0xEGHrp2ttov/BEp4HkeYKCOSOEyQT5mWcIv"
    "ueXZPuJ1WksLBOhEQnJ+QMcxBZwLEataDbhazQvmPwQcxgRKJRuSCyO6Y9tCxMYsJGdZbjBv"
    "KsCYBzc3FUgujgkRrDfBajVfwGsuQCfZomYOjQaHXK4MK3MowlgKhUQmxeJjsO/HLUgnYw6Y"
    "pglVrL1Q4LAwG9ePs/cpkaXjhYLDGdTrAsW3dzCZC9VoDManRuDg+NpwLCtN3AeeJ/c1LeEl"
    "EoNyezfEJwfh6PDSwBLSWEJGcGr7LyX4jSlpHRAf7YLs3omBjyetalqGmkhmImd/a2BIQHY2"
    "2tkGFxv7IhheHzL15zy0TCwK7lXtCN2AMPoLhEjvBGhLO1cEdXo90dI3+VWnz3Wdck4jrWVc"
    "kEGjdDfkPuXzwCq5hrF9i64xxBu9cuR6kLt3N/E7lB/yuB5Gf0H8EfkbMeVuHFSE5mtSrtRu"
    "2tDqQ6FqCRhXCQn81T4FGAAo72Xu5YvuhAAAAABJRU5ErkJggg==")

imgStepDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJFwCV/pm2AAABG0lEQVQoz33Ov0oDQRDH8e/o"
    "JQQL8QEUhICN5ZIHsLGQ4BOktz2fxGtTWXiFkCKlYCtWcoVoAhZWQRDz18Lc7mYva5HLJWky"
    "xRS/+TAz4tleAcAN0uTJxQ6hDEgTReKvrpcgA4UCYs0ugDpXj/mGHQCHo65c6BswxeFIcbgV"
    "MBgG1JUNfUNjMCz6BjB0uFQ29I10AwQLABlz3rhQ7dAjfOXjHGjA8MMfPc7UQwgOvf6kRjNk"
    "inBKOzGRJkPnpABzAk5oJSaysc6z4oQFhGPuE4lKcQoIdv0HA+xxl0g0iQdUWWYFeKbGbTKO"
    "PuMh8E0NsLyswOiw37Wv7x2qjMlGB/2PFpPu6IgeiAdknxJlwJDiqVBBmDHzvznYVv8FwISP"
    "Lb8SGwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgStop
#------------------------------------------------------------------------------
imgStop = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAT1JREFUeNrEUztSwzAQfUIGjBNomAwFPRWdSwpKzpAWCg7A"
    "OThACug5AxUFJSUFVFAwJGRgxrHxR5Il1nZw0GCHzKRAM/qs9PbpaXfFjDFYpq1gyeYUw+Hl"
    "CIyxAS39BXzuSPXpzfHOjCBXqpj8/tGuL6X9pJ8vdByGq+uX3wpklpVGHOcIAtV6dbfLa6xF"
    "INK0NNJUYTIR9aGUElkmoJSE1hq9XqfGWgRZkpSGEJpIJKIoQhiG5JzBzpKosTZBHJdGlKR4"
    "eh1C0M1VjrgFTvQM26jg+VNg6Li06zYHga/NVzDiHsad1dYginU+X8Gb4+HDba9MQdyyScF3"
    "agzn2PQAbaYd1Wym9SBZhdXjB9rplz6siDJVIecHZxfY3tv/sw7fH+/z2/MT8lMWAa23qG8s"
    "UMqF3MAi+Nff+CXAADjrrYLxZ/nIAAAAAElFTkSuQmCC")

imgStopDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJGge+NHJYAAAAsklEQVQoz6XRMU7DUBCE4e/F"
    "oQAhKm7iS3ATak5CTckpkLhDOrgCJcIKSvxsy0sRR8mzJSjYcvef0exuCr/X6o+5NY/Sk3ox"
    "2cT9wwEYqO/qfurHpHs9OXTYawr5te4EtGhtQS8bjG61JdBpfdvKjludATvsfeiRJDDYlQ6N"
    "UXWWIeYOo4siZJo7RKGfZchYuRLG6Q6B7PMIvFT12/PikF/vm7WBFFLlxuWCyJo4AP/85g/B"
    "20B5o42C/AAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgPause
#------------------------------------------------------------------------------
imgPause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAU1JREFUeNrEk79OwzAQxs/ELQkRUiUGhu5dGDMysMErwAoD"
    "DwCPAQ/AAG/AMyAGRhYWpM6obcjfpjRpnETmnDRWraRl6MAnnc73i/PpcrEJ5xy20Q5sKVov"
    "Tp5sIIQ84NJaonfs7rqNvV4eNg2KPBfJujjrW4xxeH4Z1Y+s89O+lWUKaxpkaVrm+TyHIMhl"
    "LTSb5RBFKmsYsMWizHEsNjNZC7nuFMbjH4U1DNIkqYyY6CCUtZDnTcFxAmQbhpjGcZknfggj"
    "P5C1UFL0INMosujvDjzeAd/Yx9qWm3zNQEYUtrYDm+6BY3YgX+lg0jXBNXWFre3AQQNf57C7"
    "MoNvakKog8IaJ1H8IhGFpoFpUFmLYPj9Wrdi6deHYkDqu4AnjmrHN49wMDiqhjEcFm/3t8ju"
    "kA2W7BPZFb7DWg0w9TC6G45+gRG0GvzbbfwVYACMcsm3y4uD/AAAAABJRU5ErkJggg==")

imgPauseDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfeCREGORAW62QYAAAAsklEQVQoz6WRMQ6CQBBFHwgk"
    "dtZeYw+hN7H2JNbWdh6CG1gaE05gUAJBs9ldUCx2RV0SG6aZn8zLS2YGxlZg22aLAA7r1SfZ"
    "SWRbI5bCkAKNWIiGtDc4wCCpMIDhzg3jAwpJjQIUV86oHgjfgKF0QMFlCEgKCiQgaQmRQ0PL"
    "xBk6lzzDk9gZcMkzdP8NmpApGtAExGhvzSg/7oAqY55ne6A6kdhjBA6bkfy84EH5da1R9QKq"
    "KkucPaZRYAAAAABJRU5ErkJggg==")


#------------------------------------------------------------------------------
# imgMachineReset
#------------------------------------------------------------------------------
imgMachineReset = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVEzMIIPvpEQAAAz9JREFUOMulkF9oW2UY"
    "xp/vnJM0SZNS+ydb07RZTSmd1tU0cZhInG66UUOh1j8o1ospuF4I2xD0QtjFQASpNytuiJfK"
    "EGHDPwzWOdfIJDBtQd3somkzsiQNLkm7Jk1zzne+fK832zp263P3vrzPj+d5GRHh/0gDgN0n"
    "lqFZLNA0DYqqehhjEwAiAAbu3P0DIEFEZ6WUK6qqTgKIzh10H9IeAI5pKh3v73F0eDttbS0O"
    "zQEAlU2xM1fUo6lM7SVJlGgIceCuQblnJRqzN+Gj8afdj/e22bxMwFGvN2AYEhqYw9du88bC"
    "Hc8IIQ5MxjxBIcRWBZLSozJ5PBbZ9titlTrqXOhLhVo+V9y8DQB93c2tT+xs95eLOl7b3x1c"
    "X+MwOd9KIDif8HfbOwrZCsprG/rF33J/ZfK3j5GUIVPXQ6n06vnT51IL7i47MqlVCFNAGMZW"
    "Am4YT3W0WNpKqSRyS4vVZl1+W+uOnK5VKmCMTTLGnjz89kjw33wVre022Owa+P2AXfUre53p"
    "rCO7UsG5jw92jo+Pr8a2l05Vjap+RhlzEBGmP0ss3P9txtjCPYBKQjn8YhSzv8yjUChgaurQ"
    "0UAg0H/y5KkvSNI7UkqYnIMxFgwN+1zbtznph9lrGQBQwuFw5PfkjeyZ83EKDPhgGAb8/v7+"
    "eDy+PDc3l2y/9F5kvVSCqesjTqf1+ZqiDWWLG52mYVgAQNF1PfrlsTcDj+7oYqpqx3NHp4Wq"
    "2uHz7fDPzMx8qut6lIheMDl/1TPo66poTexmrsxNw9gAAKVerydefuOtT+JXrnLOG0h8Pq1x"
    "3sDlhUUzduTESr5n4nV3b+eRodHII3mLi2SzHTdT2ZrJeRkAlGQyeTk4NNgb2/us9bvZn8xM"
    "JoWvf4xjdM8ey3B42ON994M+PhLyJplLqVubsHj2QsWobS7KRoMDACMi7Nu3/yuXq8V66der"
    "mI///Epo6sPq0GCfowZVXRp9v6KsltO0nL5uplJ/yvy1b+Tf36flrSSICAyAFcDDAHpUVQ1p"
    "Nucu8dCATXbtdsHm8qDZvcaYMo/S9T9o6UKS1m5UARQBlIhIMAAqgDYArQDsd+a7agBYB2A+"
    "sKsB2CQi+R8GrIocunSMSAAAAABJRU5ErkJggg==")
    
imgMachineResetDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUTNxBX+7RDAAABzUlEQVQoz32Oz2uScQDGP9/3"
    "1TnfYdtEk3StUhsVOVi6KIeHoh8QSLGRh/DUoR+3+gPqsOoS1CVYh+5dBqMg2uhQ0WIUzUPQ"
    "Dwm2sJy6OXPT3N731fd9O+i55/QcPjzPR1j8Pza4ix0bkl+ME2cI+MGCNWMW5DSJG1dtHTAp"
    "Tw56vO4eBRoHy4nchLlgnO0sgJV03EtEahhsIyEUjxIYeO06H32eARuYfjE5Fimhq4WVtQ0I"
    "9B0KrXMmuoEOSKCPBzwrVNWPX/O3zZgaW557kfGxTBOtfaGP9bp/slTffuZ9WkekxbHL0SJu"
    "nOhtwDpZUEo89F74s/exqTYUi6lM21y0HZBSvKPItZsj4akn1hWTJiI67PJZr3IgHY9///3S"
    "OoBGKPx26U32U7yCeqTnNIfXvJodJDVxZyQoZK63ZPaEHj1QE9Y5PRXehcjr2l+Qe6WZsm80"
    "KF+SGrxv3l/tD+6PjPYb1e7qYqGVTRlSdj4yeKprtpljlhP2o/70vqEBTZKZq219M3SwQcW4"
    "Nf2B5MXp+hfFlOvUtHztV2l1frlYAQRdBNktxxzDO7p3uhx+Z1UsVj/nspt1yqxbLYGMmz6c"
    "yAAYbNLstAZblvkPcw20XZHI1vwAAAAASUVORK5CYII=")


#------------------------------------------------------------------------------
# imgCycleStart
#------------------------------------------------------------------------------
imgCycleStart = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVCTUMYH2sKAAAAiBJREFUOMul0j9oE3EU"
    "B/Dv9a6NRRLqUEQhTWpOgokk5q6CkQaiQTtEOjhbncTSQTIJBgddXPxXDEVdCkIQRTqoOLWS"
    "hhSKRVGMwQuNkWjk6GL8E8nd/X7pc1Go9NIiPnjDWz583/v9BCLC/5S0dohPr0AQhDsACpzz"
    "LGcMzDTBTBOWYeDdxf0bA+12GwDU3w0A2c0SdK0dOGPgjGEsuVPljKVAdOKfgD9xGw2OU6Me"
    "lVnWpogt0GpxFIvfMTYqq8yyUrQB8hew+8WlIVc93//jUwWtloHFxY84fsSjMtPsiEgAkE6n"
    "bzidzi2WZRXzNycGTl69jz5hFTAtFL7sw0jMrT6ZXU7ZHVUCAFEUt46PnzkdDocquq4jGexH"
    "XAni/N1ZuANuzDx+9VIQhEnbBNFo9KAoilogsOe9oqiyaZpQ5AHM5J6jzoDK9L0yc+2a7HY4"
    "bJ+0yzCMWCaTueb1DvpEsRfB5MSKKPZC8W7HlWMhOD4XXhNR1qy/sb+i3++PybJ8YWrqVrVU"
    "qpKu/6RSqUqXr9823MrIQ7/fH+vesRcAQETrukvTtEIkMhQcHk4M5nJztVptGQ8ePbWSicOO"
    "A75tvFwuF5j+tuM/EIgIicTRrNPp6pmfn/uwtKSdU+KHnsXCvtVms2ksLOTPAjAANIjIXAcA"
    "6AHgAeCSJCkkSVKEc17hnGsAWgCqAL4BMIiI2wEigD4ADpuEHMBXIrI6rfALn1AIEjDjE18A"
    "AAAASUVORK5CYII=")

imgCycleStartDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUKABWkYXgHAAABMElEQVQoz33RP0hCURTH8e/z"
    "PTKSoqXGMhSFgsxeDQVvzClaW1qDRqeGqK1VlKKhZmlxaGgsInhTRBBEomGGS2ZRGQTvD9du"
    "g6UP+3PucJYPv3MOV5H8X1qzpVF2MUVW4ODgkOoEDdDRgWxngq/ZBIJ5XSTl0h/AwaHOgu7+"
    "IB5gcf0L+QI3U08D91ickeggGqyle7vdq92hTTQcXjD0o2R7WQ3UwMpyrFRlgmn2iHB4oWQ8"
    "CTOzamH0djLsEOUYi/1iT8bvOdZnG9upYEglUVMJsUjtUmar3i2jRnh9p5yXDzIvU3YsFzUG"
    "Adl6voIZHzNGTioVDtw5f0QUzcfOv3hubORO785Xt0zz4z1AEJtXnG+g0MUwfdq4FhclUcCi"
    "zBu2FG2g0o+/lSioS9c74hMfVHn8Ak/RTAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgFeedHold
#------------------------------------------------------------------------------
imgFeedHold = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVCTUtLBS8dgAAAjlJREFUOMulkz9oU1EU"
    "xr/kvvxr0iJK6VA0qR2CaUFrUkskUSFQ0S5OQYcuDm2GCs6BgoODS6n4QG0HJxeHoqBgESFN"
    "BUFqDBZbU7RopBg1/0xe8m7ufS9cFxuSJp36Ted85/A7Bw7HIITAQWTEASXtBucf/YbBYFgA"
    "4P1vJYQQ0528+PW+dkBd1wHAe+1iv5dzgaXYz92S9+p4v1fTWrx2gMYYAKBa1VEs6o0cABRF"
    "R7nc6rUBeK0GAFBVHeUyb+QAkMuVkMlUWrw2AKMUXZUfXdn328jXD4NRa6Mpny8hmy2C0X2u"
    "EI1G5ydNrx6Qwle7PDWBfHoDfpE8dqW2NM9UFbQuoBEJTFXBVLUdQAixRyLTkZlLnr5MJoPJ"
    "gAu3py73EkLsjFIUiA0FWzcYpWC0dQ3J7/efJYSkPJ4T22dOewcZYxhzO/F0Oc5isVjKePTI"
    "uV/mMeTsVuh7pgOAsVarBWVZnnO5BgYJscEXfQhCbDjldlpkWZ4z5rYcfyQ7CtaejhsYKaVv"
    "w+HwbDL58RvndWzevQXO64i/W2fhcHi2RHornEggZgkaY2A7662AVCr1ZmTENxQIhAaev1yu"
    "ptNf8OTZCz4RClmGh0/6lIr6Qbm/mOALiwkt8+kzj98xNwMMQgiEQuOPHY5uy8rK6521ta2b"
    "o6Pue8HgheOKovDV1diNpv46gKIQgjcAAMwAnAB6TCbTkCRJHl3XNzVN2wDAAHwXQlT2eyYD"
    "AALgEABLh7oO4G/zxL36B81HGAnLxB/5AAAAAElFTkSuQmCC")
    
imgFeedHoldDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUKADYGBgl1AAABOklEQVQoz4WRPUvDABCGnyRN"
    "K6aIiOLmVxepm+miEEEcdOrYv2ApVHQV+hNKwQ7i4uTkD9BBULEgDlZxULuIQoUKKkYb03xJ"
    "HFqTuuhN79099x7cCT5/h/hPnwhACWELFaj6y6FaCwEP1CXV4RBAXVTdtgoBBzDRcQAwaHZU"
    "AFiAyQcWAC88dVQX0Oq9wu2UX3nuAkRYLw1svisr1OkZkUsmHiImZghISjabHm4wT25IUix8"
    "JKzAIzIzK9WSd9MJmyT79lFtcA7kYB5ESysXxxISeSQmY+WiHv/tILZOM4XLe5dtXM7sTAFD"
    "QMam8bOiVsnktPG9T005cNKxSqp+sWuAfluNto8h+CzsxGPHj+erqQ1toumc5AH44s1vA0QZ"
    "pU+eiiS9G/camwff6H6WgEQ/sSD30H2nG/gGqct2z+LvT7EAAAAASUVORK5CYII=")
    

#------------------------------------------------------------------------------
# imgGotoMapPin
#------------------------------------------------------------------------------
imgGotoMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAa9JREFUeNqMUz1Lw1AUvUljK9F2ET9nwUGKWpSOXVy69A+I"
    "Lv4MZycF/4NjRBQdHJzsJIWCOhRBC4V+Do1IkpqmNnnekyhE1MYHh8M5l3fefZf3JCEEfa2W"
    "LIOmGDuMFcY4o8+4Zxwz9AXPo/BS6PuaZ+xP5vPpiVxuKZZIJF3HMXs3N8vW1VWaa3uM9qiA"
    "rWShsJbMZFaFrhN6456SqWx2XRobU8yLiy22DsMb5LBwuW11Y2PRM03SOGC3VvMZGr4bXIv+"
    "DBjwnSVZVoXr0lmnQ23D8Bka/iCYyd8BDpHl6PorNmyqKsm27TM0fNRHBvC4bzvFYk3E47Qz"
    "O0tn6bTP0PBRjwo4bZfLjTfLMnDqF6Dhoz4ygIfUtYU4f76+fiJFIW84JDA0fNRHBhj8qPpC"
    "aK1qta43my84HQwN3wg9ul8D7AA9bvXksVSqkyQRGBq+TURRM/DB075sNho9l68AhoZ/FxWw"
    "zXgIQkzeFBMcAIaGvx8VgHXAqDDeuYYZgCufPv0jAHryiGgG4xL888Cs55hSv/ydHwYCJhjT"
    "3PI5aRr5HAR0g/HQMLzhQ4ABAFZU8nO4cMZ1AAAAAElFTkSuQmCC")

imgGotoMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJAP4nK08AAABKUlEQVQoz13Rz0sCQRTA8e+u"
    "C4lll0js0E3skD+wvHbw2N8g9I907h/pliIs+B8YgQgGebVYwUWDTJbVWTOcmQ5ugvMu83jv"
    "w7wZnqUBuIIT7iiT5Ic3Hvl+ZRtOfJ7xcFO8vjhIrxf9y+ci90y3DTsG9VqlVA3TX4TpUrVW"
    "oR7Xd6BcyAk8XvAQFHKU2R+hk1ZK8c4vEedYKZ00blDLIJBkWJNBEgRqaYJub+SQ55Y8Dr2R"
    "6hpAtwa+CCUSiQgHvm6ZYKbcztBB4tAZKlfPDLBBNrzxZC6ZzL2xbGww34ASqtkfW/THqqmE"
    "MoFGo9u+2OAL3dZEJvggQi10QqITahExMQFMWaFtibZX/2vYAzZHnxnQwGeW490Sd4nNIaeR"
    "+0TkkmXGmvgjf7x4ikuV35bbAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgResetMapPin
#------------------------------------------------------------------------------
imgResetMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVFAEtg8B/ogAAAoRJREFUOMt9k0tIVGEU"
    "x3/3zjjKNYMeZBG0EnJjDyczKDAoKCOsFi1Kc9NDiKCBlrVoY0FUVNii1yZqkRFGhS6khS5C"
    "rIkeBGZJUzPjDOQNm/v8pnvntFBDIf3gg+/AOb//Of/Dp7HAyWraMqAdWA9UAD7wHri/WsQE"
    "0BYoXgV0LmpurqtsalobKS+vCpWynIGBz3Zf30fg7GqRXHSBBlqrWlo2VtXXbxDTRAAdqhY3"
    "Nm7Sysqi1rNnrcBlfb7qENYbDQ01Jcui2zQ5mkrRbZqULAujoaEmnBqLeQFFqNB03ZAwpCef"
    "J1co0JPPI2GIputGccqT+QEKbGWakxKG7DQMdM9jp2EgYYgyzUkF9oIAH4byg4MpicVor66m"
    "p66O9upqJBYjPziY8mEIYI6JTffybWhaApFr/rFVT3LJ5J6l8XhNhaYtnsnxbLuQSyYzwJM5"
    "HWy5mWorKpU4vGtFvKhU4kzXt92eSM/X/v4vRKOUggCiUb7293/xRJ5uFZn4B9hw6VObct1E"
    "+7418bwPrS1r4sp1E+fOv9LHx8bSZjb7S8IQM5v9NT42lvZFumeE9brOd7ryvO2ebevXb79+"
    "m/ag687rpGfb/Kas0YdHI8PDaTSNkeHhtA+P94IzA4i6tsXpk9s6RgqUXtx7+ea7A65V4OCJ"
    "HZuv1GolBZXZTOZUGARkMxlHg+ezfYu6li0XLvYKYATFIj8VuAWLhzd6DcA+As4diEgQoCBy"
    "HKw5gFxXs0y/ncpDDyQQ8BwH5+4BeybpD0QkDPnzn7XPXmOtn343OnLVRczRUaAe+AHoAkip"
    "xLTSSsCdvsHs37gciM2KI0AJWNIBLetg/wd4egt6gQngJ6D+Ar5OOqnI2T7MAAAAAElFTkSu"
    "QmCC")

imgResetMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUUAiI4UjHwAAABiklEQVQoz12Rz0vTYRzHX98f"
    "uPGtDpKMlCSioR6mIwd2CMEugpCjP2BEtzx42DGoqwQd9CyoSHpIRQiCrh1EEXFaFkIj3Whj"
    "hal82ff7PDj1eR4PC3G+r+8X78+Pt0WDHt7mOUminPCN99tHYDXYrYz1d6c6I7dqQe7nynde"
    "b/9xrgKtI08GE70iIqlF7rbdtIr8XbMbJiQTcUGBVQoIEnGS4F71TdTyNL84RdKO5ZkoNCTo"
    "0PcVMWrEUPi+Dq8D6xtFlw6G6MBlo6jXL4HxzMTmeMYs75RFVaFQiOpO2SyDA/A2o7NPU7v3"
    "eg6/5v14vO2MJr788Od218CGNxmZTacEwymZHbYLpcqxonJcKKlFAPuVfTIg7KmtgOmcQD/S"
    "C7mSRa6kl/ICwA0ZeXmk5zerBLzoe6wf3CiPnlMW1qf6dm5o3hm8UyQBkx7hnrjvKIyzH/wH"
    "Zg0g0sYg+RACGEdhLs+vf7Krkp/Bz9PLb2wwAHeQSM7rbbbQBICDpjmW9p7JjwefOeQftQtj"
    "66mo8di9eAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgSetMapPin
#------------------------------------------------------------------------------
imgSetMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCC4PCgdjqgAAAk1JREFUOMuFk0FIU3Ec"
    "xz/v+ZzydF0kVuihg9Bpaa5hYCiBInaQuoQw2yUiqkOeuohHC6KDEBgjL0l4GIjDQJGdXCEi"
    "TDIvhS4Wbm6QT2Tvub033nv/DmtgpesHv8uP7+/z+/5+8JOoEVlJagHCQAfQCJjAFjDbKoQG"
    "INVovghMNg8N+Zv6+i7XNTR4HcvSj1dXvxnLy9vAeKsQOaWGgZB3ePiqt6urU2gaApDBe667"
    "+5pUX6/oi4sh4JV8VrcDHWow2O7qOlFN4346TVTTcHUdNRhsdyprcSagDI2SLKvCcVjI58kV"
    "Cizk8wjHQZJltVy5ydkACwxL046E49CvqsilEv2qinAcLE07ssCoCTBhPZ9IpIXHQ9jnY8Hv"
    "J+zzITwe8olE2oT1/wHmc8lkpmgYBeE4VLNoGIVcMpkxYf5UQO9MLtI7kxvtEeKgJERsNx7f"
    "QVFwbRsUhd14fKckRKxHiINTAWXTDJRNc6z79fdRU4jofiq1p2Wzh8Jx0LLZw/1Uas8UIlrV"
    "S/7JzxFJlgMnIY/C/sCb2e2kcN2pifFOt6Wt7dn1wcGO9ZWVLS2TeXkX5qpapWjogaePbwS+"
    "FkC3K8W1Axi44w/E3n0as+BmNpN54tg22UzmWIIPJ4cpRd1IPn+x9Mcal0K3AvHIUlKS5al7"
    "oL+FOmHbWFD3APRa/4M3NLfpHZ1LNg1MhKu1adg4GhkR07Dxt/6fXyj92NzCtT/aa1PvgWZA"
    "FYBwXURFcgEo/k5bqmFGAVqA8w9h+Arc/gKxCCwBB8BPwPoFY48c81fKVnwAAAAASUVORK5C"
    "YII=")

imgSetMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJC/KRMHfAAABaElEQVQoz12RvUsCcRzGP5dH"
    "ilhBgWQUKEQthtTNDkIEQUE1W3PQ4hg0twRBa2sFQS9g9B8UhQinVDRUloKHNpRIeldX/e7X"
    "0Ate3/F5PjwPfB8F1432sEAMH29csJV/BsVlh1iNj2jD3g67od+cXrGSr3pagdBiYiI6Znot"
    "bG9/X0Ap8Xje5mqIRQdNipxRxCQ6SAzUVl/6FL9DgXcsBlD80geuBKdZrwuC2AQR1OtO8z+Q"
    "yZZUhphkCJVsycn8A+ThpWG+CAQC8+XSkIctwPrmevL6yUmf3KkIVE7unPT1Uwtga3ZqNSn2"
    "iuVKTVCpFctiD0Bd3lQ0gAbz2nZqjoN9PTLerZed/YIJoDa1Re2ZD6DClLabkglj6RPDVI6/"
    "k9WmvvZTMq1t6W0b942IRyA9Dw33SszkZvX4AkA4uyzD2V/975PGhXOa2yGAHyRALxYWn39j"
    "VY6qeTx0EWyXt51W2qwieEV8Ab3lml4I+uMeAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# Joggin controls X Y Z Home
#------------------------------------------------------------------------------
imgHomeX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFBsE21bVngAABRlJREFUWMPtV19sU1UY"
    "/32nt232P5kbA+aMRl7MmgWMidlDFYkLa3cBJ4Y/GnFqFre9SBjxReBh74SQyFziDBgewEgI"
    "rLurZSSARk00IgSWbCysZWwucfTWjd12W3vP54MtuZSNFSjTh/7ezj3f+b7f+f6d7xIyBDMT"
    "AFy+cp2mpqfsKytWJiIRXU5P37UJIezVLtfcs6vKJbIMkakgETERsWmanJeXZ05MTIjJyUm7"
    "othEYWGhOXD9mhi59Sdlm+BjKWRmCvRfsMXj8wKAEEKwlJJV78Y4EfF/4sF0b1ZXV5urVq82"
    "Y7GYNAyDSAg8DTy21qrKCn5lXY3pcDgSiqKYYJbffnf6/0MwBUVReHZ2NpFImOaObVsZOeTw"
    "lNpMslELADLbrSRbRbISwFoA5cvpQSUToXg87tq/f3/L4OBgvc1mCzJz265du9oikcirAEwA"
    "uhDivZ6enpllCXFLSwt1dXUxABw/fvzNwcHB94PBoKrreqmiKKiqqjoxPDzsZeaS/Px8MLMU"
    "QpT19PREFkuPP64O4OW1Ln5iD27ZsoW6urq4tbXVAWDj0NDQnqGhoddmZmaEoigMgEZHR3ca"
    "hgGHw8FERACmlspLu8NBADhrRdLU1NTIzKfD4TCYGf/yuO+5AwBIKcHMESJ6QdO0qXQ9qqqe"
    "ALAjuZwkIpfP5/srte/1eiuEENdSuc3MJzRNe/ehRbJp06bd4XD4tK7r95FJCxuICLFYDDdv"
    "3mRN02KL5G8bgLHkslxK+XXaRbsthTcGoG3RKmbmwg0bNhw0DGNfyjtLtB44nU5UVlYWe73e"
    "S8eOHXuLmZ1WmUAgEGHmplR4iUhVVbVlJpYgVVU/ISI1pQ7AB5qm/b1giA3DqNi7d+9nwWCw"
    "VUqZ53Q6OTWkZjAnkmmaKC8v/93lcnW1t7efIaI7aaE+BGB3ypzdbt8Rj8dPAihIXvaQpml7"
    "0vXbAODw4cMVZ8+ebR4ZGflcCGFXFOU+cswMZn4gvCmOyTVPT0+vjkajL4VCIT0QCFy2Giot"
    "Lb2Ul5fXSEQrADiklDsBOJLb1w3D2B4KhcwFCTqdztpwOHzUQoLSJpY5RVHmhRBxIcS8oigJ"
    "ZralyZEQAtFo9JlQKFR048aNb6w6xsbGEmvWrPmZiD4iontnmXmemT39/f3ji7YZl8uFWCyG"
    "4eFhmKYJYRk+pZRwu91H3W73QDgcZimlXlxcXNbd3f2prusv2my2e7LJMM9UVVVd8fl8Dxjz"
    "+/1XVFX9CcAb94pAiF98Pt/Vhz518/PzvxUXF3vq6+v3FRUVjVqLQwiB8fHxc7W1td11dXUn"
    "N2/e3Lt+/fqj0Wh0wnoRZkZNTc0pt9v9IREdXMiYqqpbreSS5173er1vL9qoDxw4QB0dHVMA"
    "vmfmXy9evNhARM9ZhQYGBiaJaBbAbOpbQ0PDbHr7KSkpOdPc3HxqIUMej6eMmTstZ3QApclC"
    "+9Lj8fzg9/vvPODBjo4OtlSkHo1GjXTD+fn59gWqV6Q37vPnz99aNFRCHEkWCJj5tpRyXao/"
    "EtEKIcQXGU0z6YYfBQUFBfaFvjc0NLxDRNssYW3u6+sbZeaPLXa3J1Mgu/8kS6Gurq6ciDot"
    "5Lr7+voCAKBp2jlm/sqy1+nxeMqWlaDT6TxieWdvz83NtVv3pZTtAG6lQm2z2TqXmgcLM5wb"
    "M5Lr7e3d9rAL+P3+uwCef5SB9cfku2gkm6kTwOQTyC0PGhsbKZtyOeSQQw455LA8+AcDiVF6"
    "OePF/AAAAABJRU5ErkJggg==")

imgHomeY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFB4p4/59rgAABJVJREFUWMPtV01oXFUU"
    "/s6dO/PIJE5AE9ImTjdtoZIhKAoSJC5CaGNmSq21RRED/kSSWFBscaPtIvsK6WoWhVa60JAY"
    "mp+piQkYK4hULAUTyA+ZyQ8x4GReyCRvXuZN3jtuZurLdJq02k4Lzre7737n3u+dc8+55xLy"
    "CGYmALh1e5zW4mvOPRV7tlZXVSseX3cIIZzVPl/y2b3llt1G5FMgETERsWmaXFRUZC4vL4to"
    "NOqU0iFKSkrMifE/RHj+T9pmg8cEZqbhkR8dqZQhAAghBFuWxYGmIyki4sfiwWxvVldXm3sr"
    "K01d1y1N04jE3XIem0AA8FZV8Esv1Jgul2tLSmmC2erq7n1yBGYgpeTNzc2trS3TfOvUCUYB"
    "/ydQvktL+txb9lKyE/KdJHsAPA+g/L4TKF/KUqmU79y5c62Tk5ONDocjwsztzc3N7aurqy8D"
    "MAGoQoh3+vv7N/IS4tbWVgoGgwwAV69ebZicnHw3EokEVFV9WkoJr9f7zczMTBMzl7rdbjCz"
    "JYQo6+/vX33kHjx27BgFg0Fua2tzATgyNTX12dTU1KsbGxtCSskAaGFh4W1N0+ByuZiICMBa"
    "rnO5TaDf7+8mojfTB3oxmUz6RkdH45n5hoYGj6Io40TkTX/qHhwcPJW9aF9fHwOArut+Zu5d"
    "XFwEM0NKeSdqRISysjIAINM0wcywLIt3TBLDMNqZeSW9gFdRlAv2eUVRvrKJiyaTyY/v5cWj"
    "R49+GovFelVVzdy9ubIaRARd1zE7O8uhUEjfUeDIyEgUwGnbhf6h3+8/nPbuYSL6wEY/neZn"
    "b1pSX19/QdO0LwHAsqzdSg8URUFVVZWnqanppytXrrzOzMqOSeL3+3uI6ER6gYVUKvWK0+n8"
    "JeM9Zu4JhUIns+00Tas4e/bs55FIpM2yrCJFUTjTpN5Hn0imaaK8vPx3n88XPHPmzDUiWnHk"
    "Mjh06NAYM79HRG4iKhVCNBPR3rS4FcMwmsLhcMJu09nZWdHX19cSDoe/EEI4pZTbxDEzmPmu"
    "8GY0psccj8crE4nEc3Nzc+rw8PCtnAKnp6e1gwcPLmYShojctun3h4aGbmbbKIpSG4vFLttE"
    "UFbHkpRSGkKIlBDCkFJuMbMji0dCCCQSiWfm5uaemp6e/vqeZeb69evfBgKBkwDesP31d6FQ"
    "qCsX3+fzQdd1zMzMwDRNCFvzaVkW6urqLtfV1U3EYjG2LEv1eDxlly5d+kRV1f0Oxz9+Sod5"
    "w+v13h4YGNi5DhJRGzPfESiEaL8X1zCM3zwez2uNjY0v3rhx46P19fV9GZFCCCwtLf1QW1v7"
    "fTKZLFYUxQDAFy9ePCWE2G8Pe01NTc+BAwe65ufnf921UA8MDPwVCAS2jXPxzp8/Tx0dHWsA"
    "hpj55tjYmJ+I9tk5ExMTUSLaBLBpS8bN7PJTWlp6raWlpeehNgsdHR1s87qaSCS07I3dbrcz"
    "R4RE1hijo6Pzj7ybyd74QVBcXOx84t4kT1I/+OAPqt0Ig4OD/6YlK7nPvXblPaqG9WcADEBL"
    "F2IFQPQ/8PKD48eP08PkFVBAAQUUUMDu+BuN6hIEZEZyzwAAAABJRU5ErkJggg==")

imgHomeZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFCASEzCP9wAABH5JREFUWMPtl11IW2cY"
    "x//Pe94k1TiF1WDbLb1YezMNbmMD54WD4UqNph92IBujemVRd7Exxm62Fubdrtb2Zl4I3fBi"
    "lJbSpDXqJix0DLqPlsIqGAW/ipWhifhxckxy3vPsJm6nafzq2rSw/O/OyXPO+eX5+J/nEPIo"
    "ZiYAuH3nLi0tLzn2VOwxFxfj1vLyiiaEcFT5fMkX93os+zUin4BExETESikuKipSc3NzYn5+"
    "3iGlJkpKStTI3T/FxPR9euAaPCUxMw39+JOWTqcEACGEYMuyONB4OE1E/FQymJ3NqqoqtXff"
    "PmUYhqXrOpF4GOepAQKA94UKfuO1auV0Ok0ppQKzdfHSlWcHcF1SSl5bWzNNU6n3Wt5lFPR/"
    "EuXbWjJ9b9mtZDPle0j2AHgVgGfbA5QvsnQ67Tt9+nTH6Ohog6Zpk8zc1dra2rW4uFgDQAGI"
    "CyE+CIVCq3kpcUdHB/X09DAA9PX1vTM6OnpycnIyEI/Hn5dSwuv1fj8+Pt7IzGXFxcVgZksI"
    "UR4KhRafeAaPHTtGPT093NnZ6QRwOBqNfhKNRt9aXV0VUkoGQDMzM+/rug6n08lERACWcvXl"
    "Q4CBQGDbRnn9+vWcFQgGgwwAhmE0MfOVe/fugZkhpfynakSE8vJyACClFJgZlmVx3nrwyJEj"
    "H8disa9t795cUw0hBAzDwOzsLEejUeORbaaxsfEVIcQvANyZm1/t7+9vzvHQkvr6+i8BtLnd"
    "7t2WZeWEs4ObpolkMmnu2rXrj5aWlq/a2toGiCi57QweOnTIQ0QhG9yIpmkns+N0Xa/o6ur6"
    "zOl0dlqWVQRgvb8280ZIKdnhcEil1JuRSOSLhYWFcma+SkQL2lZwlZWVDo/H009E1ZlTcdM0"
    "68Ph8F/2uHPnzlUEg8H2iYmJz4UQDiklr2/Q6yDM/ACYjZ0yx7y8vLwvkUi8PDU1FR8aGrq9"
    "JWBNTc03AE5kbqqY+fjg4OCt7DiXy1Ubi8Uu2CAoa2NJSilTQoi0ECIlpTSZWcuKIyEEEonE"
    "7qmpqefGxsa+27TETU1NHwI4ZfvXn4bD4eFcsT6fD4ZhYHx8HEopCNvyaVkW6urqLtTV1Y3E"
    "YjG2LCteWlpa3tvb+1E8Hj+gaf/mSSkFj8ez6vV671y7dm3jHvT7/W8T0Vkb3LfhcPjsRvGp"
    "VOr30tJSf0NDw+s3btw4tbKysn8dUgiB2dnZH2praweSyaTb5XKlAPD58+dbhBAH7GWvrq6+"
    "fPDgwYvT09M3NxwSv9//khDiku33X3Vd79gI7syZM9Td3b0EYJCZf4tEIk1EtN8eMzIyMk9E"
    "awDWbBVay56hsrKyq+3t7Zc3XBaOHj1aomlakIh2Z07NMfOJSCSS3Aiwu7ubbbYRTyQSevaD"
    "i4uLHTksRmRbzvDw8PSmRq2U6iMiX+YwqZRqHhgYuL/DD6JH3pLcbrdjU0AiOm4fTk3TbgYC"
    "gR296h6nnomPph3tg48pKyXb3D23jHtSy8LPABiAnjFiF4D5/xCXHzU3N9PjjCuooIIKKqig"
    "rfU3HkT/f4qKtQEAAAAASUVORK5CYII=")

imgHome = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFCEmK59KAwAABChJREFUWMPtV0tMXGUU"
    "/s5//7kMDIHEDgGq05gU00RGqI/UssANJsVS0hAN8RFhhQE2igtXQiJdGRcGViQl0UiMaWya"
    "Aov6QDqh0TTW2Bo7dsZRCS9ZMNwJMMM8mP8/LmQIjgIDDMhivuXNyTnf/c7jfpeQJTAzAcCP"
    "9+7T0vKSray0LBkKWXp5ecUQQtgq3e74I+Ulerd5RbYIEhETESulOD8/X83Pz4uFhQWblIYo"
    "LCxU3vs/iz+m/qRd58UBgJnpy69vGmtrCQFACCFYa80Xzp9bIyL+XxRMV7OyslKVHz+uotGo"
    "jkQiRGJvpQ6EIAC4Hi7lZ56sUqZpJqWUCsz6yufXjg7BFKSUHIvFksmkUi83v8jIIYcDOjPr"
    "h1oA0Ls9JYe1JGUATgMoyeqSZSPJ2tqau7u7u93n89UbhjHJzJ0tLS2doVDoWQAKgCWEeG1k"
    "ZCR8KC1ub2+ngYEBBoChoaHnfT7f65OTkxcsy3pISgmXy/VZIBA4z8zFBQUFYGYthHCOjIyE"
    "thqPuz958dRpN+9bwYsXL9LAwAB3dHSYAM75/f63/X7/c+FwWEgpGQBNT0+/EolEYJomExEB"
    "WNppLm2mSQD2T3B4eJgBIBqNNjDztZmZGTAzpJQbHSEiOJ1OACClFJgZWmve7tO4EkmAmSn9"
    "RfbU4sbGxrcAfLjenq03UAiEw2HMzc1Zfr+/HEBiu7zf3b5Ds7Oz1PxSk94TQWYurKurew9A"
    "q8PhOKa1xt8d3FIZJJNJxOPxpN1u/6G5ufn91tbWG0QU3+5c3Zz4Vpw5c1YX5kvOuMWRSKS0"
    "s7PzHdM0O7TW+QBS87XdC0FKyTabTSqlzno8nneDwaCTma8TUXCrdv82Oc0PfvEaH3/yaWYK"
    "9vX1lc7MzLT5fL5LqSQpB50iwswbajIzxL/tFSeTSSorKwtUV1d/0NXVdXm7mt94bpkhyzIy"
    "UnB8fPwJZr6Ubu83OZY4Ean1eWQiIqWUnZk3syQpJYLB4GPj4+OvAri8wzxpm2lmRtDtdiMa"
    "jSIQCEAp9Q91tNaora39qLa21ru4uMhaa6uoqMg5ODj4pmVZJw3D2IhVSqGkpCTscrnujY6O"
    "blvTbrezYUiVEcFEInGnqKjohfr6+qcnJibeWFlZOZEiKYTA3NzcVzU1NTfi8bgjLy8vAYD7"
    "+/ubhRAnN49BVVXV1YqKiitTU1O3d6p5zFnCsWhU70iwp6eHent7lwB8wczfezyeBiI6sTnG"
    "6/UuEFEMQCz1rKGhIZa+Q8XFxdfb2tquZiLKqYpH+cGvv6sdzUJvby9v2jBrdXU1kl64oKDA"
    "9h/bKNJPztjY2NRu/mseP1XBu3Yz6YV3A4fDYTty/yRHyQ8eGYKFGfrKTOOyblhvrduiyPq3"
    "PA/Awj7iDgdNTU2UzbgccsghhxxyyA7+AmDe4C30OMWcAAAAAElFTkSuQmCC")

imgHomeXY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFCcSXHEZMAAABkxJREFUWMPtWG1sU9cZ"
    "ft5zrz8SR0EaCQlbgzYRqLS60KqjK9KiqSJkYDtC9CNjbUdSrWmJW6llUzdVmhBJf01TW4Ha"
    "/RiRNg0hYHxVxDcZI0stKiS0TRlT45FAkypNWQTxRx3i2Nf2Pe/+XLOLSRwTW61U9f13z3nv"
    "Oc95P573PYdQpDAzAcDw5RGKz8Zt9XX12VgsKmdnbylCCNsDbrd+3+paiTKLKFaRiJiI2DAM"
    "rqioMKanp8XMzIxNVRVRVVVlhEY+EhOT/6VyA1zWgsxM585/oGQyaQFACCFYSsk+z48yRMTl"
    "BKgu61REPHX9hnHj5g2eGB8HAFHpci0IzOfzHQWwy/ycISJ3X1/fzdy8x+OpE0J8BKDWPPxR"
    "TdOeuWcX50vDt+r4ew9vMOx2e1ZVVQPM8viJ03fpZTIZP4DPzM9aKWVv3mF7c+BMPf+yYnBR"
    "F6gqp1KpbDZrGLvanrzLiufOnYsxcwcANgG1ejyeF03rvkREvlzkAGjXNO3zkmNwOeLz+d4B"
    "8Jr5mQDwNIATAFyma9/RNO3ny87iUiUcDr/BzCHz0wVAy4EDMJJIJN4oiWZKlUuXLqWklM8x"
    "c9rqPWZOSymfCwaDekkAmZmYWckR9nJkYGDgMhFdzEuSi/39/f8umagB1AN4yJJxy4nDJwE8"
    "njf8uMfjeaIkos5kMu7u7u49o6Oj2xRF+eTYsWP+3bt3+2Ox2PcBGACiQohnz549O7fYGtu3"
    "b68RQoSIaJU5FAXwDdM7N6WUDwwMDISLsuCePXtuAz98+HDz/v37X5+YmPjJ3Nzc2kQi0ez3"
    "+7unp6efTyaTm4noBwB8AGyFwkMI8V4OHDNPSSkfzvEjEa0SQry70L9K/sCOHTvoyJEj3NXV"
    "Zd+0aZNnfn7+V2NjY63xeLxSVVUGQPF4/MHZ2VknEbHT6SQAnwshDoyNjaUW2mR4ePhpAPst"
    "gH/c398/vG7duhAR/dQE6V6/fv3I1atXrxTl4o6Ojp3MfDoSiYCZQUT55Q4AIKUEM8eI6Dua"
    "psXz19m6dWutw+EIWUpZr6Zpnbl5r9f7eyLqXMzVC7q4tbX1tUgkcjoajd4BJs9tICIkk0mM"
    "j4+zpmnJhdZyOBzvWcBN2ez2163zUspfAJjMuVpRlN8takFmrtqyZUs3gHaXy7VSSrkgOKsV"
    "s9ksdF3POp3Of7a1tf2mvb19gIj0QvH4wYWL4tFHH5NVFeqSnc/tbiaRSNT5/f5f2u32Lill"
    "BQCmQuhMK6qqyjabTTUM47FgMPjrcDhcw8zvE1F4sU7o408+5Sv/CSl//NMRdOx+NrtkP3jg"
    "wIG6qampztHR0Tdzi1gJmZnviENmhhB3RQdns1mqr6+/tnHjxt/u3bv3UKGN/xb80B6LRpVY"
    "NKp3vvC8LGjBoaGhB5n5zfz23tKx6ERkMDNyljUMw8nMVpSkqirC4fC6oaGhZwAcWqI0SZvd"
    "rtSvXu0AkCwI0O12I5lM4tq1azAM4w7rSCnR1NT0h6amplAkEmEpZbS6urqmt7f31Wg0ulZR"
    "/s9UhmGgtrZ2rqGh4XJfX19BfE6nkxVFNXRdXzoG0+n0P6qrq7dv27btkQsXLrx469atNTmQ"
    "Qghcv379r5s3bx7Qdd3lcDjSAPjgwYNtQoi11jDYsGHDycbGxuOTk5OXlgr+lTW1nEom5aq6"
    "uoIXLXXfvn3U09MTB/AXZv57MBj0EtEaq1IoFJohohSAlIW/Uvk5tGLFivc7OztPFlM+72/8"
    "Nl+5Om58s25lwUwWPT09bMmw6Pz8fCJ/48rKStsC2SjyKWdwcHDyXu41372/sXiaWWzjexGX"
    "y3XXQbxe7wkieipH1LquuwcHB2dz883NzdUOh2OEiBrMoROBQKDtC2tY0+m0n5nD5uEbHA7H"
    "W3mV5m0LuBld11/+Qjvq8+fPzwB4xeKhF7xeb4tp3RYi+plF/RVTvyDAqiLvz8XqQdO048x8"
    "yjJ0qKWl5T4AvRYWOBkIBP5czIIfmlfAhFlpHABmStDL0ZVfSvlDIqohojU2m+1fRFRjggun"
    "02l/SU8fO3fupDNnznApeh6PZ5cQ4ugCNX2XpmnHy/Y2U+L9+BSAJyzgTmma9lQ5Lk3lea0i"
    "6sp3fdlft8pgxdshEAgEqCzvg1+WfA3wKw/wa/nKy/8AhdbdkoZA1W0AAAAASUVORK5CYII=")

imgPX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFC4qpbEa5wAAAhVJREFUWMPtmDtPG0EQ"
    "x/+zLhwpXYzJhyBNpBRuKVzc2mkgLyGkRIpIJCoUPghNcBP3FCnt3ZNTuUFykSJRyAcAUpEI"
    "KBwpxtIMzZ61YBPZBu9h4aluH7f67czOYxeYyUzSFZrk4uVyWZLver1OtwrQh7sOJIWCGxeS"
    "QsKNA0mh4UaFpDTgRoFUaYaQYTaVmomH1WQqTjIKJKVlumEhyVt0B8Ar1/xNRI9qtdpRMq61"
    "fqiU+gEgDwAismOMWZk0ZM9Jut3uOoBfrpln5uqFnRBVEzg3b/2mYt3/NtYDbDQaJyLyBoA4"
    "oKda63fup/dEVHZTBcBrY8zpTQbkqyBpwOAWgA3X/AvgOYDPAO47024ZYz6EOpN9gIVC4V4u"
    "l/tKRAuexpJ5e+12+0mz2eyEcpy+QN1qtf4x86qInPlaFpEzZl4dB+465h6YSeI4/kZEu5ec"
    "ZNda+z10tlFXmGMZwOKl7kWt9VLo2Nin9iiK5pRSP4lo3nUdA3jgzHzEzAtxHP8J5SR9GlRK"
    "bSdwInLIzI+T+EhE80qpjyGzygXAUqn0jIheJG0RWbPWHojIW+8svnRHIEjK6wEWi8U8EVU8"
    "uKq1tgEAxpgvIvLJG6tEUTQXIh/3ALPZ7LaXZw87nc6mP5GZNwHsJ6bOZDKVoMXCnSi3bnXB"
    "Ogm41O8kw6S/u3PtnIqL+1Q8fUzF49EgyHHrwZnMJG05B6HiD8KD/QCNAAAAAElFTkSuQmCC")

imgNX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFC4JB9ZrlQAAAglJREFUWMPtmL1OG0EQ"
    "x/+zLlzQRZg8RNLkEShc3HrTJORDEVKQUIJEhaDiKWjATdxTUNq7J6dyg+QyUcID8FERK6Sx"
    "FGNphmZPOmO7wLk9fIqnutnd0/1u/zOzH8DCFva4RrO+aIyR5LnVatFcAabhQkNSFnAhISkr"
    "uFCQlCVcCEjKGi5rSBUCLjeJZ4XLReJ5gJsKOC9wEwFDwBljjgG89+4vInrebDavk36t9VOl"
    "1A8AFQAQkWNr7YexJAk1c8PhcBvAlXcrzNwYmSWiRgLnx22PZXFIWdvt9o2IbAAQD/RSa/3Z"
    "f3eLiIwfKgA+Wmv/jEicV8wZYw4A7Hi3D+ANgBMAS17aA2vt7kgdzDMher3evoiceXcJgE3g"
    "APzs9/v7Dy7UWWZrt9v9y8zrInKbVlBEbpl5vdPpDDIB/BeL4/gbEZ3eS5JT59z3mZa6rJc/"
    "Y8xrAKv3mle11q+m1sG84jCKomWl1BkRrfim3wCeeJmvmflZHMe9sRmcNaYe+mNKqaMETkQu"
    "mflFUh+JaEUpdThV4tCQtVptjYjeJr6IfHLOXYjIZioW3/kQmByDoSCr1WqFiOopuIZzrg0A"
    "1tqvIvIl1VePomh5apKEgCyXy0epdfZyMBjspfuZeQ/AeSJ1qVSqF3u7VYgN67xAqrwl+z+P"
    "nYU4uBfi6qMQl0eTIB87kRa2sJB2ByDIE+Z7HSa8AAAAAElFTkSuQmCC")

imgPY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFC8GjnJHRQAAAYBJREFUWMPtmDFSwzAQ"
    "Rfd7xqOOijacgBvQetLIFQQuAA0hHAUukqSyXdk1LQ0ngI6korNdLI3NaGgSyyuJMNlOlmbn"
    "zX5599sgoUjTlM11nueQyAsXcJKQcAUnBQmXcBKQcA03FhI+4MZAwhecLSR8wtlAwjfcUEiE"
    "gBsCiVBw+0IiJNw+kAgNtwsSLvqcZJ+EqyYslSdyJY+U3YpcXnBndkvapYzJZ/0WD62ObT6r"
    "PmgrnU2+wZNk7L1y8u2SpilLNm7pfMc46LC+oFrrJYAZEREzf9R1fV5V1Ve/nyTJiVLqDcCk"
    "e7TM8/zG2yRpmmbOzFsiIgATpdSTua+UejbgNnVdP3gddWVZboho8SMFcKe1nnbVnQK4NY4v"
    "uvP+/yxorVcArjqp39u2vYjj+KWvHjOviqK4DmYWoigypT6L4/jVgNs2TTMP6mayLPtk5kdD"
    "6lMJacUkNqbDmogu+zUzr4uimAX3g0bl7n9LH7QP7jICf8ZRu44j4L8HPMbY+AY+NNABwNPv"
    "XgAAAABJRU5ErkJggg==")

imgNY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFC8enR7fEwAAAZ1JREFUWMPtmL9OwzAQ"
    "xu+zFHljYi1PwBuwRl2SCQovAAulPAq8SNspyZTMrCw8AWy0E1uS4VgSZCGQavucVlVuav74"
    "y6/+dHe2icYYY78Bl0FJkiwBzIiImPmjruvzqqq++udxHJ9ord8ATLpbyzzPb1y+pVwGNU0z"
    "Z+YtERGAidb6yXyutX424DZ1XT+4zqATYFmWGyJa/NgA3CVJMu1mdwrg1nh90b0/nMWG1SsA"
    "V53V723bXkRR9NLPHjOviqK49vmG8hqslGn1WRRFrwbctmmauW+SeAFmWfbJzI+G1adS1opY"
    "3EeapmsiuuyvmXldFMVMQluJ1Crg/rf1e62D/8wi97/zPBfTVXTgMQIePeBxRJqmbGbpkHrY"
    "Rcy89i0htnqwEfOFdNGDrZgrpKseXMRsIX304Cq2K6SvnpLISCm4YIX6LxCpsgTJf97b4zte"
    "JIulwyqLh4Z0qoNDQXp1ktCQu9RRSJSTUHDWexIpSJs2ad30fSFte7joqkQazmvbKd2zg+yL"
    "pVc9QTbu0uvGUGczHAIu2NGH5PHHN3D2zxn8oOkKAAAAAElFTkSuQmCC")

imgPZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFQE31WkkZAAAAY9JREFUaN7tmKFOxEAQ"
    "QGe2kApwBIuovJDwBQjEibs2JWBQCAy5BMun8AEkSEICpO3lCKIGwQcgseBQnLike4Npk+YM"
    "1+1st2Ke2xWTl9nd2dlFYCKKIqqPkyRBjrhoQ45TEm3JcUmiTTkOSbQt11YSu5BrI4ldyZlK"
    "YpdyJpLYtVxTSXQh10QSXcmtK4ku5daRRNdy/0mijTrHWSfRVhHmiqNsLQ9Xu6VsbnBr7RZ3"
    "l9ImnvEpbpod03hGddB06UziNb5J2u4rK2+XKIqIs3BzxxMEQRAEQegvnXxgtun7VN8zuGHj"
    "RTcejw+UUm8AsAUAQESPzp6dqwyHw11EfK7JfXied+4kg6sMBoNN3/cfAGCvnPopiuI4TdPf"
    "XggGQXADAIdl5jQRnc1ms0+nPwsVYRheAcBlNSai6yzLXp2WmYrRaHTked5LtSJEdJum6QVH"
    "bMUgFyil7mvb5X0+n096UWbiON5eLpdPALBTTn0T0Wme54teCGqt7xBxvxwutNYn0+n0S646"
    "QRAEQRA64w/5qcrxsgFdlAAAAABJRU5ErkJggg==")

imgNZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFQET6WrAtQAAAaNJREFUaN7tl71KA0EQ"
    "gGf2lBTaia3FlUHwCSwsUiR3nGhjZWEjgq2P4gMIliKo3A8nFmksfABLW+2svCKQzdjcQZAI"
    "t7uzyRXzdXdkJ192s/MDIAiCIAguoO3COI6p7WfTNLX+HtX1HVyzXfjfroxGoz2l1CsAbAAA"
    "ENGDiyDrDg4Gg21EfJqTew+C4HQlO/iXfr+/3uv17gFgp371PZ1OD7Ms++mEYBiG1wCwX++c"
    "JqKTsiw/XOOyHHEURZcAcN48E9FVnucvK00zDcPh8CAIgufmNIjoJsuyM66TUY5yoVLqbu6v"
    "8lZV1UUn0kySJJuz2ewRALbqV19EdDwejyedENRa3yLibv040VofFUXxKaVOEARBEARBEBY1"
    "pyYNKmc8bBOMqzu2iYc2bb2tpE08tJ05TCVt46HLQNRW0iUeukxrbSRd4ymOG8kl523sXCTC"
    "lZaQ85c3x+O6nuUWc2N0i5ctaZUHlyXpVEl8S7bJo8iRTnzJGQlySpqUSeOi7yppWsNZuxJu"
    "OWtBHzWbXdBH18Mu6KNvZBf00XmzC/qYXRp+AdlGygko3L6xAAAAAElFTkSuQmCC")

imgSpindleOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFQkLMt/S6wAAA9RJREFUaN7tmE1oXFUU"
    "x3/nZWjTaU0jLxgXokPQqARTqIITrZquZpE7K7vyY6MGFbEKamurEIqgUnd+7Botfi/MQrjD"
    "A/GD0layKKJVSB2wRPGr4NRUYqJh3j1u3tTnMAn5uCOzeH8Y5s29/3fu/5137jn3DGTIkGFF"
    "yBr5mz2tuwSob4EFYD/Qt0FxDpgEPloNObcGw1uMMQ/5cJ+19uPVcnPtjiFr7WHgNDBijHlk"
    "rfcHbRY3CRwA3gGettZWOkogUEtiDuBP4PdOE3gbMApcApSBm9dqoK0xaIwZAT7biI12e3Cl"
    "VLMqdK0luVar1csGBwd3bmDTUK1WTwBHgV98C/wb+KJarfasR6S1FuA4cAg42a5SB3AF8Diw"
    "o2l8xBizNSXoJLCYmv8VeAP4tN2b5EfgYNO924ApYFdq7CBwKvVbmwS3dRcvJZ+Wm81a+x5w"
    "BljolFPRtiS+NKkag512bGsIfBu4xqfhLk92NiUb7vXEixPAb8DPneTFHuBq4C1jjAI3+TDq"
    "s9T1AxPGmLt9PrWvUrcFeMK3OJ8Cu4ChpjHtJIFLwHdNY3GnpZrbgfeBT4DxrGFeR6JOI9/J"
    "Ynuz95WhAzbJek/rGby3sl2exUlSg/uT3reeva8MGTJ0OFZVjorFYndfX999wB5VHRaR7ap6"
    "QUROq+pUrVabnJ6e/qvBT9rOBr6P43gwiqL0XyX/4VhrZd1Zv1wuF8IwPAW8BuwWkRDIJd+7"
    "ReTVMAxPlcvlwjImrhKRB9tSlorFYrdzzorIEICqvluv16+N43gzcF3SgyAiQ845WywWu1u+"
    "JpFnRkdHt3pv3MMwfKAhDjheqVTSfe+3wF3GmCuBW0RkKAzD+xNP/9t7qp4QkV35fP4x4Hnf"
    "hX1PaqGXWswrcDjlqTubCc65/cncU6VS6VKvAkXkhpTAr1px6vX6lynOcPN8FEWfq+qHItKb"
    "y+X2+fZgT+NiYWHhXCvC3NzcudQDbW/Fcc4dUNUY2FsqlS73KfCPi31kPt/fsoXr7e1PefBC"
    "K04URTPAURHJ53K5Z30K/OYiMQiGWxoIgh0pD369nCHn3ISqLgLjK6SktQl0zn2Q8s6TrcNU"
    "9qU4U8vZiqLoJxF5WUQ2OecOeUkzQRAcAR4GrheRO8bGxt5U1edmZ2dnC4VCIQiCCeDWhD5T"
    "q9WOrGRPVV8UkXHgHi8etNYuxnFsVPVM4q57gyCoDgwMLAVBUAUaeXEmjmOTLnetUKlU5oAX"
    "RCTwFYNEUXRWRHaq6qOqegw4n/Qa51X1mHNuL3BjFEVnV7Pg/Pz8K6r6Q3YM+r/wD1dDRrrQ"
    "g6CvAAAAAElFTkSuQmCC")

imgSpindleOff = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFQkaWG/yGQAAA15JREFUaN7tl01oXFUU"
    "x3/nzqAm1jT0BbMpMg01IMEUYsGJH9Wuc2dlFlJxoxUqpSK0+NFNLO7iVneNih+tC7O7YUDU"
    "UmogiyBahdYHLUMp/YBOTARTDXnvdPMmPJ5jmEneDK/w/jDMm3vPPfN//3vPOfdAjhw5NoW0"
    "af9gSv+7BmjaBEvAu8DANsmFwAzwXSvGxTYc91hrj6Qhn3Pu+1Zti50+Q865aeAiMG6tPdru"
    "etNhcjPA+8DXwHvOublMEQTq0ZkD+Bv4M2sEnwdeBB4BKsDT7Tro6Bm01o4D57bjo9MKbpZq"
    "WkKhneTq+/6jw8PDY9sIGnzf/wn4HLiZNsF/gZ993+/bCknnHMAF4BQw36lSB7AbeBvYlxgf"
    "t9Y+HCM0D9yNzd8CPgN+7HSQXAdOJtbuAGaB52JjJ4HF2G9NEO5oFK9Fn6bB5pw7C1wGVrNy"
    "K9oRnS+NqsZw1q5tDYJfAY+n6biQkp8HooD7NFJxCrgD3MiSin3AXuBLa60C+9NwmmapGwSm"
    "rLWvpPnWaZW6HuB42uTSJFgARhJjmiWCa8CVxFiQtVRzAPgG+AF4I2+Yt5Co4+jNMtn+fL9y"
    "ZCBItnpbz5F6K1tImZxENXgw6n3X8/3KkSNHxtG0HJXL5YcGBgZeAyZVdVREdqrqiohcVNXZ"
    "er0+s7Cw8E/DPmozN4VzTlq12zTrVyqVkud5i8AnwEER8YBi9H1QRD72PG+xUqmUuqFgMalc"
    "GIZOREYAVPVMEASnRKRWKBT2AB8AL4vISBiGrlwu748r2UyBVpVqiaDneYcb5IALc3Nz8T73"
    "D+CQtfYx4BkRGfE87/VI6a4V9smNplb1oyb2CkxvHGCRl7q6xSLyZIzgr80WrK+v/1IsFhs2"
    "o8n5/wuE5Ja2apdUsK/xsLq6eruZg+Xl5duxF9rZVQWBv4BdAL29vYPAtf+0bP39gzGVV7Z6"
    "+Fu1Syr4+8aEMaNNFxizL6bgb129/YZh+G1MnRPNEruIvBOzme3qFhtjTgNvAk+IyAsTExNf"
    "qOqHtVqtViqVSsaYKeDZyPxSvV4/3VUFnXN3gyCwqno5kutVY4w/NDS0ZozxgUZevBQEgU0m"
    "6a40ONVq9aqIjKnqMVU9DyxFvcWSqp4Pw/At4KlqtXo1v8rcD7gHHRMWGwgBfZYAAAAASUVO"
    "RK5CYII=")

imgCoolantOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFQoHEETNAwAACNZJREFUaN7tmWtMk1ka"
    "x//nLbfSINgWbYUg4hawlYIzol0wTmWWy8QX3cjgZlTU7AxhvE5idsR10C7RgK7GCzteMxsV"
    "w150TXCD0xkxOoSRrSsqYKWCCLhcDVaKhYLQvme/tFrHeqGWyXzgSZrm9DznnN/5v+855zlP"
    "eXDPCABy+vTpCRaLJSswMHAnpXSHWq0+MDAwkBUdHf1hYmKi/7x58/Q3btygeAcj7rY7d+5c"
    "cEFBgUYqla59lVNPT8/e9evX78jKynriLiDPnUbHjh3zPnbs2Pbg4OAvHL/dv3//LqW0qa2t"
    "7YlYLA4GAIFAkHDt2rWhVatWVVZUVLilJONOo7t37yZ0dHSscJR7e3u3Z2dnL9y2bVvqokWL"
    "WLPZvLu2tpYCQGdn50qj0Rjj6mlRSt/4BL3cmVR9fX2SQqGQAEB3d/fXAoGgcNOmTRwACsBc"
    "XFy8o6ioSAzg08jIyOkPHz78EECdq1eFUgpCCPWYghqNBv39/TJHOTY2VltRUWEDQDMzMxkA"
    "WLlypUUmk2kdPo8ePYp01L1ARwj3Oji3ANVqtY9AIBA6yi0tLa0ASE5OTqbJZNq5bt26FADw"
    "8fHpcPg8efLE291FMmrAnp4e4vw+DQ4Ocrt27QrV6XRf+vr6brl169aGEydOBHp7v8gkl8tf"
    "UmrDhg2+HgcMDg5+YSA+n88MDw/z+/r6pgDA06dPwwYHB308tbUxeEfj8/mMr+9zIWw2Gx0Z"
    "GaEMw9A3QQqFQtubgL3gAXv69OnzGTNvnLMzOPeTsucVfBfLz8/nxvwRj7WNA44DjgOONeDg"
    "4CD3iwK0n8XPzGq10l+cgoQ8ZwwICHibqJzU19eTnw1waGiIjPIR/3zh1qlTpxa3tbXNeDay"
    "tzex2WwvqcNxHHG6EsyxWq2L3LmkjQaQrFix4rcGg0Ejl8tDAaCpqUm7YMGCPh+fl6OriIiI"
    "x21tbT/aY8FIvV7/p40bN37kuLJ6HPDIkSNTb968uU4ul0cDQHNz8z/T0tLytmzZ0uHKf+vW"
    "rY1JSUl59+7d+xYAoqKilFeuXPn84MGD4rFQkJSWln4SERHxGzvcD2vWrNl74MCBW/YYkDjF"
    "g2R4eJgAwP79+yvT0tJ2NjY26gCgvb39o/Ly8sw3hVijtj179kyKiYmpYlmWSiQSc0ZGxif2"
    "yTElJSWyuXPn7hYKhUMsy9KwsLCBlJSUgvLy8jCHT0ZGxueTJ08eYVmWxsXFfXf69OkJnlSQ"
    "NDc3K3p7e2MBYMqUKTeWLFnyHQBaXFws3rt3b/7t27c3JyQk+AKAUqn01+l0W3Jzc7/SaDT+"
    "ACjLsqVisfiGfR9V1tXV/cqTgNRkMk2Pi4vzt4fp/12+fLmJUorS0tKM1tbW3yUlJb3QYP78"
    "+aSrq2tlQ0NDOgAMDw8bJRJJDQDMmjVLWl9fH+oxQI1GwwiFwminPbAJAC0qKvLp6Oj4dWJi"
    "oss+jEajn8Vi+UCj0fBycnKsAQEBbU4ZBYFHF8nQ0JDV6Wiz2bcOP4ZhXrkiU1JSwOPxAhQK"
    "BeO4qzQ3N3t+o87Pz+ceP35c7yj7+vpOA4Dk5OQ+gUBw++LFiy7bXb58GTweT7906dKRM2fO"
    "ML29vVMiIiIcm3i/RxWUSCQPampqBgDAbDbPKykpmQgA8fHx306bNs3gqk1YWFh1fHz89wBw"
    "586die3t7bEAUFtb2zV79ux2jwKGhobWC4XCOgDo6uqaffbs2TQApLCwsFKpVBY0NTXdqKys"
    "5JqamnD16lWupaXlP3PmzNmdm5tbA4BUVVWxRqPxfQCQSqV3pk+f3uLpqIeXnp6+jWVZyrIs"
    "lclkl/bt2/ee49jKy8uLWrx48WdqtXr7smXLsnfv3h1lzz0yGo1GLZPJqliWpWKx2JqZmblx"
    "TALl48ePT1MoFJcckDExMefy8/MT7YMRV5+1a9fOnzlz5veONkqlsvTw4cOTRnMWjyq6WL16"
    "9ZKqqqpdkZGRMntWVR8SElKiUqm0U6dObbt+/bpZKpUGWCyW8Orq6oWdnZ3LZDJZNAAYDIbq"
    "5OTk3KNHj/5gzyh4HhAAyczMXF5TU5MbFRU10/GjXq/vnDhxYjefzzeazeYgk8kUGhsbK3XU"
    "NzQ0XJfL5QXnz5//92jgADdy1IcOHarn8XgP9Hq9v8FgmBoSEuI9adKkgAkTJkj5fP70oKCg"
    "EIlEEmBfsYMjIyN/T0tLKzx58uSl0cK5oyAA4MyZM7y+vr7AS5cupd2/fz95YGAgrru7Oygx"
    "MTFcp9O1SqXSPj8/v2szZswoT05OvpiVlWV2kTgat3EbN0/YW61ilUrlJxaLfw/gY0qpkhAS"
    "SCntI4TUUUrPGY3Gv+p0uiGHP8uyzqv1gc1mi9RqtcPOfTr7lJWVEbeDhfT09HCRSFQN4BCA"
    "BYQQEQAv+/cCQsjXIpGoOj09PfwVXUwlhOSMycVdpVL5cRxXRghR2CPhv1mt1iibzeYLIBrA"
    "P+ypEAXHcWUqlcrvFamSr9RqtcAdwNdm+UUi0WcOOACVFy5cWO5U3QBgGcuyYQASCCEKkUj0"
    "qV1pOIX3PxJC5vn7+38BoMDTEfXHTgPtcXWhAvBnJ6UyXKRAcu11X6ampk70KCAhJMYJsNaV"
    "j9VqrXHyUf60XqvVVlFKzxNCgry8vDZ7WsFnF2yLxfLQlYPJZHroNKFAVz4cx/2RUmoDsDE1"
    "NVXiScBnf+X7+/tPduUQFBQ02UnBPlc+Wq3WAOAkIcTfy8srz5OA+meODKN02QHDxDopePtV"
    "HXEcp6GUDgLIfs2WNDpAjuP+5aTOH1y/pmSzk8+5V/Wl1Wo7CCFFhBAfjuPyPbLNMAzzDYA1"
    "AGYQQj5YuHBhMaV0R2tra2t4eHg4wzAaAIl2d4PRaPzmtTkUSncRQrIBrPCIgmVlZYM2m42l"
    "lN61y5XFMExjRETEMMMwjQAc+6LBZrOxzsedK7tw4YIJQCEhhPHUOwitVttMCHmPUrqBUloB"
    "4DEAK4DHlNIKjuM2Anhfq9W+VV6jv7//L5TS/42HQT+X/R+yG5KEcoHH7gAAAABJRU5ErkJg"
    "gg==")

imgCoolantOff = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXFQoV4/28SwAACFhJREFUaN7tWHtMk1kW"
    "/92vvEqDYFu0FYJQtoBUCs6IsmAcZAaWiR+6kcHdUVGzM4bxuYnZHYyrdogGZTU+yPjAzEaF"
    "sJvFJcENDjNCdAgrW1dQwFoEec3yNFgoVMqr7d1/Wq1YB6iFzCacpGnud8/57u/+7nfOPedw"
    "YJ8QACQvL2+eXq9P9fT0PEYpPRobG3t2aGgoNSQk5MOYmBj3VatWqaqrqyneQYi9doWFhd6Z"
    "mZkKsVi8621Kvb29p/bs2XM0NTV10F6AHHuMcnJynHNyco54e3v/3vKsubn5CaW0qb29fVAo"
    "FHoDAI/Hi753797Itm3bKsrLy+1ikrHH6MmTJ9GdnZ1bLOP+/v4jO3bsWHv48OFfrVu3jtXp"
    "dFm1tbUUALq6urZqNJowW6dFKZ30BJ3s2ZRarY6TyWQiAOjp6fmax+Md379/vwkABaDLzc09"
    "mp2dLQTwWVBQUOCzZ88+BFBn61OhlIIQQh3GoEKhwIsXL6SWcXh4eEl5ebkRAE1JSWEAYOvW"
    "rXqpVFpi0Xn+/HmQZe41dISYfgqcXQBjY2NdeDwe3zJubW1tA0DS0tJStFrtsd27dycAgIuL"
    "S6dFZ3Bw0NleJ5k2wN7eXmL9PQ0PD5tOnDjhq1Qq/+jq6nrg4cOHe69cueLp7Pw6ptDQ0DeY"
    "2rt3r6vDAXp7e7+2EJfLZcbGxrgDAwOLAGB0dNRveHjYxVGhjcE7CpfLZVxdXxFhNBrp+Pg4"
    "ZRiGTgaSz+cbJwPsBAfI6Ojoqx0zk+7ZGrhpwtjxDL6LZGRkmGb8iGda5gDOAZwDONMAh4eH"
    "TT8rgOa7+KUYDAb6s2OQkFcYPTw8ppKVE7VaTWYN4MjICJnmEc9eunXt2rX17e3tS16u7OxM"
    "jEbjG+yYTCZiVRKsMBgM6+wp0qYDkGzZsuXX9fX1itDQUF8AaGpqKlmzZs2Ai8ub2ZVEIulr"
    "b2//lzkXDFKpVF/t27fvY0vJ6nCAFy9eXPzgwYPdoaGhIQDQ0tLy98TExEMHDhzotKV/8ODB"
    "xri4uENPnz79FgCCg4Pld+7c+eLcuXPCmWCQFBUVfSqRSD4yg/th586dp86ePfvQnAMSq3yQ"
    "jI2NEQA4c+ZMRWJi4rHGxkYlAHR0dHxcWlqaMlmKNW05efLkgrCwsEqWZalIJNIlJyd/at4c"
    "k5+fL125cmUWn88fYVmW+vn5DSUkJGSWlpb6WXSSk5O/WLhw4TjLsjQiIuK7vLy8eY5kkLS0"
    "tMj6+/vDAWDRokXVGzZs+A4Azc3NFZ46dSrj0aNHX0ZHR7sCgFwud1cqlQfS09P/pFAo3AFQ"
    "lmWLhEJhtTmOyuvq6n7hSIBUq9UGRkREuJvT9P9s3rxZSylFUVFRcltb22/i4uJeM1i9ejXp"
    "7u7e2tDQkAQAY2NjGpFIVAMAy5YtE6vVal+HAVQoFAyfzw+xioFNAGh2drZLZ2fnL2NiYmy+"
    "Q6PRuOn1+g8UCgUnLS3N4OHh0W7VUeA51ElGRkYMVleb0Rw63BiGeatHJiQkgMPheMhkMsZS"
    "q7S0tDg+UGdkZJj6+vrUlrGrq2sAAMTHxw/weLxHt27dsml3+/ZtcDgc1caNG8cLCgqY/v7+"
    "RRKJxBLEXziUQZFI9GNNTc0QAOh0ulX5+fnzASAyMvLbgICAels2fn5+VZGRkd8DwOPHj+d3"
    "dHSEA0BtbW338uXLOxwK0NfXV83n8+sAoLu7e/n169cTAZDjx49XyOXyzKampuqKigpTU1MT"
    "7t69a2ptbf33ihUrstLT02sAkMrKSlaj0bwPAGKx+HFgYGCro7MeTlJS0mGWZSnLslQqlZad"
    "Pn36Pcu1dejQoeD169d/Hhsbe2TTpk07srKygs29R0ahUMRKpdJKlmWpUCg0pKSk7JuRRPny"
    "5csBMpmszAIyLCysMCMjI8a8GLH127Vr1+qlS5d+b7GRy+VFFy5cWDCdu3ha2cX27ds3VFZW"
    "nggKCpKau6oqHx+f/KioqJLFixe3379/XycWiz30er1/VVXV2q6urk1SqTQEAOrr66vi4+PT"
    "L1269IO5o+B4gABISkrK5pqamvTg4OCllocqlapr/vz5PVwuV6PT6by0Wq1veHi42DLf0NBw"
    "PzQ0NPPGjRv/nA44wI4e9fnz59UcDudHlUrlXl9fv9jHx8d5wYIFHvPmzRNzudxALy8vH5FI"
    "5GH22OHx8fG/JSYmHr969WrZdMHZwyAAoKCggDMwMOBZVlaW2NzcHD80NBTR09PjFRMT469U"
    "KtvEYvGAm5vbvSVLlpTGx8ffSk1N1dloHM3JnMyJI8SmF0dFRbkJhcLfAfiEUionhHhSSgcI"
    "IXWU0kKNRvMXpVI5YtFnWXZS7ywuLiZT1fvJZCEpKclfIBBUATgPYA0hRADAyfy/hhDytUAg"
    "qEpKSvKfDQadJjJnMpmKCSEyc+b7V6PRmEEIaeNwOAEAvgLwW0KIzGQyFUdFRS23ZtIWA1Nl"
    "akoABQLB5xZwACpu3ry52Wq6AcAmlmX9AEQTQmQCgeAzM9Oz1jz6xKpuOGmrgALwZ6smUvKs"
    "HjEhJMwKYK0tA4PBUOPk5GTRkU+cf5sjTDzSqepNZPBlQa3X65/ZeoFWq31mtSHPWWUQwCAA"
    "PgC4u7svBPDfiQZeXl4LrVgesPfjn6reRAZVLycYRm7TgGHCrRh8NNMMMhN6ev+wYucPtpur"
    "5EsrncJZPWKGYb4BsBPAEkLIB2vXrs2llB5ta2tr8/f392cYRgEgxqxer9FovplVBouLi4eN"
    "RiNLKX1ipiuVYZhGiUQyxjBMIwBLXKw3Go3sxCA9G3EQJSUlLYSQ9yileyml5QD6ABgA9FFK"
    "y00m0z4A75eUlLRgTv4P5H9362HlfKp4oAAAAABJRU5ErkJggg==")
