"""----------------------------------------------------------------------------
   icons.py

   Copyright (C) 2013-2014 Wilhelm Duembeg

   This file is part of gsat. gsat is a cross-platform GCODE debug/step for
   Grbl like GCODE interpreters. With features similar to software debuggers.
   Features such as breakpoint, change current program counter, inspection
   and modification of variables.

   gsat is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   (at your option) any later version.

   gsat is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with gsat.  If not, see <http://www.gnu.org/licenses/>.

   Embedded Images
   These images generated by /usr/bin/img2py

   some icons by http://somerandomdude.com/work/iconic/
   some icons by Yusuke Kamiyamane. All rights reserved.

   These icons are licensed under a Creative Commons
   Attribution 3.0 License.
   <http://creativecommons.org/licenses/by/3.0/>

   Attribution-ShareAlike 3.0 United States (CC BY-SA 3.0)
----------------------------------------------------------------------------"""

from wx.lib.embeddedimage import PyEmbeddedImage

#------------------------------------------------------------------------------
# imgGCS
#------------------------------------------------------------------------------
imgGCSBlack32x32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIcBzAXW6G7pwAABvhJREFUWMPll3tsFNcZ"
    "xX93dtaPXbuxYRcbs2seAdsYJBOZVC6hreMAVUKUmJYILEAKaqtQ1LRSVFVqFCA8VKgatWqA"
    "JKZpBBJNY5oSZAdRBKmKRHkZB4OhRoTXWk6wvVtTs7tez8zOvf1jH13jRcVp/+tIV+fe0dyZ"
    "M9937vnuhf/3Szzsgy9s2rQVmPZffm/vHzdv/iTzhv6wM5VS0/du3LjKtm0UIJVKt9RYZfYT"
    "kxIImKbJz958UyzfuJEPt2xJk9DGQQBp25imiWkYaTQMg5FYjJFYjNjwMMPRKMPRKNFIhEgk"
    "QiQcJhwO09vby4HNm1cppdZ+Z8OGxV+GgCaEINU0QNM0HEKgaRpaJiZb+nkgEolgAr/fsmWV"
    "Umrtt197bfH4CEiZFs2XIXH37l1MwAT2bt3apKRcu+zVVxePRwMi9XGUApHQr6YUaBpIORaT"
    "l0xqYHdzc/reV8vLm/Z9/LHnoQlIKRN/LQQSONnRQYnXS9/AAJM8njT2B4PMr6kZQ2LBggXY"
    "tk08Hse2bXRd54Njx+LjjwCgCcHXa2tRSjHT70+jBGb4/dhKZY2EcDhwaBpKKQoKCyl/9NF7"
    "44mAICMFqUigFJ/dvMmZc+eIhMO43G4WPvEEZVOmpEn85fhx+vv7eWHFCmSGAUkpxbhEmFJ0"
    "CjUh+OLOHd5vaSESDlNVWUlffz9Hjh4FKQmHw7S2tnLx4kUGBwdHCRMhUFIyrgiMEaFSdF25"
    "glKKpU8/jdvtpqysDIcQSCnp7+tDCEFZWRmhUAhNiFEWPK4ISCm7EzPFqEjELQuA3JwcLl++"
    "zIeHDrG/pYXBwUHmVFezfNkyCgoKEivmviU63hQMpkSYSWL6tER5OHP2LJUVFdTMnZv+w5RP"
    "ZIo3RUIk3qk9VAqWL1/+/XgwuGb3zp1UVlVR39CASr6kZs4cenp7aT9/ngtdXeQ4nTxeW4vX"
    "600sW6XSOdcyfEIkI/DAatjY2PiSEKJeKfWGEOInLS0tKy3LYvdbb/HMs89yuK2Nqupqnlq0"
    "CKUUcdvGME3MZN1IFaZ0P9nycnORUpKXn8/KV175KGsKli5duq6iomJdc3PzyuLi4u2WZWmh"
    "UJChoX9iWRaH29pY++KL/P3KFd56910++/xzTl26RG8oxKXubvqTOBAM0tXdzUAolMaUbadE"
    "mDUF8Xj8qfXr188LBG6zbdvWxRcudFpSJgrrvJoaKisrCQRu07RiBb997z1KvV5KPR6UUpR6"
    "vaOwxOtFQQKVSqchJUJHNgI+n+/2yZMnZzY0NEyPRqP4fD6HEAKlFBMnTiAcDqPrOm/v2cPC"
    "RYsI3bsHwI2eHgCuBwKJcSCAAG7cvo0QgpuBAOWTJ4MQ6LrO+21t18YQqKur+5GUcm04HDZ9"
    "Pt8Mn8/n6OjoMH/ww5eDZ06fKZhQXExpaSmdnZ18caePm9euke90UltbS6nXS6HLRanXS4Hb"
    "PRpdLkomTSJX1xGAruvsb229NiYFpml+a8+e5mfC4TB5eXlIqdi+/RefuubV/Ongvn2/XLN6"
    "DdXVc5g1axZ+v5/CwkJ2vv0O/qoqSjwe+oJBSjwe7gwMpMepYlXi8VDo948yojEEDMPQR0YM"
    "4nEb25YIoeNw6Ja0bQ0gNzcXIXRsWxKP24yMGKAU82bPBkhoIYVZNJHyEQBp22M1UFRUNOXQ"
    "oUPi8OHDt6ZOnVbu803Vamu/NumvrR9VXOj4dEJj40oKCly0t59l/wd/4Nz580yZMYOZVVVc"
    "DwQQQvxbA1k0UT55MgAOXWfvwYPXs/qA3+9f6PVO+vWuXc3zY7EYPt90HnlkIgBDQ/+gt/cW"
    "+fn5/Gbnr/juupd4rLZ21Jr/Sl5e2ge43xOSm1an08k3Vq8+ktUHDMP4+a5dv5sfDA7idOZz"
    "7NiReE/PDXp6bnD8+J9xOvMJBgf58cs/Zevrr9MXCtGZXP8Xr14dVTHvrx0pS06mIHspKC4u"
    "3tDQsPhWe/tVVVk5u7OoqOhvp051qVOnutSSJUvUc881qvb2q6qpabXasWOHsmxbWfG4MuNx"
    "ZViWGrEsFTNNNWyaKmoYKmIYKjIyosKxmLoXi6mh4WEVtSw15/nnjz7Q/10u1ya3233a5XJ9"
    "0+12n+7uvqO6unpUfX29OnHihKqvr1fbtm1TtpQqbtvjJhG1LDVjyZJPsmlAByYCHiAPICcn"
    "Z5Wen/+9x+bOLayrq6OpqQkF5DideLxePB4PDodj1GFEPQBTmnDoOjOffPJENiuWQBRQqZOT"
    "aZpvuCorFx44cODxzAc1hwO3y5Xw9uQGRQmByNiw3I+pKioAY2REfxCBSLKlLxvssrKyB+8X"
    "Mg+bQiT++r7jmcroC03DNAzHf9oPTAVKgSnG0FAwr6rq7P/yZKxiseC/AKsV5rYw7NE2AAAA"
    "AElFTkSuQmCC")

imgGCSBlack16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg0ngp9oXwAAAtNJREFUOMuNks9rHGUY"
    "xz/vOzPrbncTZJ0cGjB00RKdGkPbtQRJS+2CNw+yGD30Ku2/kMC2pIf0VIJEqKfeeqoIlh5q"
    "1SxJ448aMBGqNk3SZZUQ2mw2dXd2Z3Zm3nk9bAyaivg9Pg98+X4/zyPYp/cuXnwHOMh/a/bG"
    "5OTav25Onj078cvamt7pdPSTdltvuK7+rdnU1UZDVxsN/fn8vC6WSueKpdJhALnfwB4YqL84"
    "MIAKQ1QYEvg+XquF67o0m01c1+XTS5c+iZUqvDsxcfgZA6WUEIAUAsswSFoWCdPElBIhBPV6"
    "nY+vX+eM41y9v7T0vrnfIFZKSiGQQpBNp/fmlVqNQdsG4P7GBj09PXyxvLzzjwTFYjFvbG2N"
    "Vh494vkDB3jablNvtai5LknLolKrASCEACBSSkiA8fHx6ampqatBEJz47Nq1D1YfPuTmrVvM"
    "3rlDNp3GzmT26gB7dVQUCRPAMIz0+fPnPhwefn1tc3OT3kyaVwYH+ea772l4Hr2p1B4TgIRp"
    "YnQNpDkyMvJmuVx+4Divrh87dvzlTqdD/8F+FhcX8TyP/r4+2IX6F5OcbfPE84iiSErf90/O"
    "zMxcOXQo95JhpHjj9OmyYaSw7T5ecxyuTE/j+j5SCLbdLo+a62JJSRRFQnqe9+3Y2Fhpaemn"
    "ShAofv7hwVtBoFhfr3B3YYGhoSEyySRSCF7IdHnYmUy3QhhKubKycvfo0fyR0dFCrlz+qlqt"
    "rrKwMMfw8AlUFHM8n8cPQ6SUuL5Pw/N42m4jgCiKpAmwvb2tLlwYvzE39/XqvXu/Tjx+/Du3"
    "b98kDIMuPPOZd6EVhkS7V0jMzn45CfRalnVk5Ex+/qPLl085jkMikaDluoRKEWuN1ppYa+I4"
    "RgBeq2WagALqgArDcFlksz8WCoVTAKZpktztL4RAa40EYikRUvLHzs5z4m+pskB/Kpd7W6ZS"
    "ffwPxZ639ScTBkPH3uXMqwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgAbort
#------------------------------------------------------------------------------
imgAbort = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAntJREFUeNqkk99v0lAUxw9t6SjIwhgsiBlGYCJotixhM5lZ"
    "wl72svgyffWf4C/YX8CTfwCJyZ4MW+LD3syMv5bIi1kcwUHmNJmAgEKhLaUtnlMKgcU3b/Jt"
    "b3vP53vPvfdc22AwgP9pHD1e2GzA4ptkAwiidrG7gQpZcd9RH3CqHOpKxw/SM5ycu2b42C4I"
    "6fDycjS4tOQVZmcdlKHcbq9enZ9vXpyePlFlOYNxr6YyGMGCx7P3cGcnPuA4oadp0Gu1RmPO"
    "QDzu9IfD8/mjo73u8L9pwtAD0wqyDkd6dXs73pIkIZDNQqfTmZL5T1GEB6lUnJmZSRMzNsD1"
    "7IYSiehvURTu5nLmlPcOD0EURVPUpxY7OAARTRYikag+3KfhEjSAR26/31tvNuFlNApPSyVQ"
    "FAVC+/sgSRKU8JthGHidTILdbgff3JyXGESfM5bBosEwDg3X7Xa5IOvzQaFQgGq1ahrZ8JTe"
    "IMzTKfX7oEiSg5jJDEDDARXTlTALl2EAy7LmbDzPm7oxsdssxmpW38ygD/BDrNWUQb0Ogq5D"
    "7Ph4CuY4DlLFIjjpOAhQVYWYsQG6va9VKg03Bi5OwJ/X1uDTyoppQNool02Dtiw3iZk0yH1r"
    "NMq4U/Ll1pYJnyF8C8dIJ7GYme67SAQMw5ArvV6JmLGBgeXZ1fXMx3q94AWQv66vw238L1ii"
    "/gnCHoTznU5BMowMMcTaqFRplykoidV4h2HScZ6Pxnje62FZBwX90XWlqKrNgqqWLhDOYxVe"
    "UgESaxnQacyjfFhegQTA5gLAfbxcN61C+1kD+HIG8BanxS78QtWR1UYGjLXBzmv341+NLmIX"
    "JSFr/BVgAM8jHGX/y9T1AAAAAElFTkSuQmCC")

imgAbortDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMBh9N5HW4AAABdElEQVQoz32Rv0tbURzFP/e+"
    "++J7FhyeBTU0pWCW4CJ0U4xrl7dkFRw6VenSFAqFDqmgo/4nWd7iWoOunSRLMrQBK9qmVXm5"
    "eb/y7ZAgdOk54/lwhnOU8H8ZWEWh2CrTYIPnwHcuaHeuBKGPElZR1MNS80V1OZj3hNH4evit"
    "lx6fRY9APXzSellz/GJW65DZr924dRb10VAvl5rrtcTfxc68S+qv1dxmvQwaaDyrjvw3wD4W"
    "yz6wR+IvVWmABtlcCB74AKS8ZocrrtmjTxHI5hSoKK/A4y0D/pCiOEAzIfGkAgYgxxIDGgcX"
    "gwZgAkwbBvfjGHg/ix0O0WjysQymwPnwl+EdDi6HfMbB4QhFMpTzKdC+62t7gssRLi6fgI+I"
    "TXrSBiVU2A6dVlArfDMbKgd71y1aX6IBSlDMEYal5nzVD4wH+dgOR730OIoSBCW8Mizy1F12"
    "t8yaWgH5kV9mneyGW36e5gaYECPZ76z7z88FMRP4CxsClib1AuxPAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgAbout
#------------------------------------------------------------------------------
imgAbout = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAmhJREFUeNqkk1trE1EQx2d3T67mhl0otVaoEQu9oFFpo6IU"
    "9C1CofSlxRu0VH3sF/DBj+BbRSgWGhGLKKIFESw1xRgJFTSRQKBqpaGbbRqSTdckm6wz624J"
    "6FsHfgs7s///mTN7DqfrOuwnmPFgDDiOs3IHkTDSg4hmTkYySBwpUIIW1jTtr0FLDHpE31h4"
    "4uLgwJUzPf6OQBsli5s7219eJTMfoysJRS4tYiphCThyMjsIi93tU9ce3BlxiQdEVVWNFawO"
    "nU4n7OYVeeH27At5fesh6uJUtwxET5v37mR0Zlx3c4b4f+FwOACUpjx3/f7jynb5HhrI1haG"
    "B8cvDDWculgs7ECjqmmpZ8l09m16g4rHLvd29Y2e7lUdKvN4POKpsbND72ffDGNp0TIIHb/U"
    "H5QkyRjO1yefvqWeJhcw/4iKn6PxG6VS6erRkb4BZmPQea47CLMQIgPenOgRwW8P0J7q9Tqs"
    "v8vkMD2PbJnM5z78yPF2HnSGvz3AB0iz9xsx7PVqDWq1GtD+m80m+2cAHDDBJQDPeNB4Y7h2"
    "elgd5AsbsqJWVcNy4NYQtTfdIp8+OXM+xNwMBLcAZamokGbPAGMtu5yWbC4bCA4BxP4OH34Q"
    "pnmYhMUT7T4SMxeDn8tZiTStBq/TL9eyellTaJV84hd9EGvpILa58l0SnAJUciUl+zyVJQ1Y"
    "R9I8xhHvIX98bGmq4e30r+J7sMUg6O3yr47GJhuewz46zhHSGFrTgIZGxzaCTJhnfg75bYwP"
    "wIncNO9IFFlC8qjVLAPaituEzBpIHdFaLp0NEczaLlJBbZPb73X+I8AAb+EUcaash1EAAAAA"
    "SUVORK5CYII=")

#------------------------------------------------------------------------------
# imgBreak
#------------------------------------------------------------------------------
imgBreak = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNrEU01Lw0AQnU2TWGItpAexB6FVrF+oIC14VY/6"
    "DxT9K8V/ouhP8NCTRy9BD6Jgi6FoqWJbA9pskk2ycWKtBJOePLjwyGwy8/J25i0JggD+sgT4"
    "4xKHwRkhX2wpgAIBOMCwjJhEvCI01HniAzQ5bvYiqsVfhJuSolTnK5XSVLGoyooiO5SyF12v"
    "3Gvatk9pFXMuogVk2INTQgppRTne2NlZDyQp43neT1IqlQLfsvparXblWNbhfhA0YwpclL24"
    "tjZnmGbGdd3YWZEkk19YmGtcX4fHO4oR4P/KaVXNdXq9ASFjQCkFaprAMA4V5fC7N+gNJCmY"
    "9DiXUSKYhgE2Fg6PJ34jsG3ZHTQ2TsCw2x/dLmPt9pjo+5BJGFngOIwNppJIoHVbrXIOIM9H"
    "zPyZ0rcwL9FIKO2k3uk0OCH9LHpiAt9F4ft+/9G2G2Fe4hi3sCiPPpgVhOpyOl2akSR1XBBk"
    "k3Omu65xa9v1B86rl+gDPWKkHwJCiISP/DTA6grAbhZgCV2povuMd4C7G4DzJ4BbzGljjZ1E"
    "gPlfvVPC7Yg2WIgPrPFiBP92Gz8FGAAZJMfQcW0emQAAAABJRU5ErkJggg==")

imgBreakDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsMCBqjDay5AAABDklEQVQoz6WRr07DYBTFf+1G"
    "m5AiNtGEYCo2BAIB9QuW8AxD8CJ9EQSTOARYMj8aDAgGSRUZDenYaNZ+XdeLYCmfAsG98pzc"
    "e/4Ywu9j/oHTBOgAPY8+Pi4xIwbDCJ4BMATo0Duyg86u27KsonibvjypYHirEc486+LwoOGs"
    "1l+L9D5cnp5HtQbpe93MmZGSkjKncHa60tc0iL/Z/gSWKHJKVmy1xdcJrliKBTnfpg2Wlrg6"
    "IZ4XM7vCwFibKwuJtRxklCQm+qpERnpQg2RM2qjhKs3GDDTCVZQF7+FiIsoUUdnkI8yDy4if"
    "HI432G7u2yfmHi2m1aO6Lh94vclrkVTMyrsy1CrIKLUL/2rzC/+ddkCtau6CAAAAAElFTkSu"
    "QmCC")

#------------------------------------------------------------------------------
# imgCli
#------------------------------------------------------------------------------
imgCli = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAbNJREFUeNqkUztuwkAQnf16ndihgjJFWh8gCgdBokfKBWhS"
    "QJuKiIYmt4AT0OYAER1FGioUBQtk8IfMjLFRFClSkpWeZi3ve/P27a44Ho/wn6E7nc4N1ltE"
    "+EtujHjReZ7f9fv9h1arFeV5BlmWI1JIU5pnUBQFlCYVCKEZWltYr9evz89PjxoXXG2322i5"
    "XPJiAooyfpojoul0eqmNMcVgMIBms8m+KJOy67GeE9I0hSQ5gJTkQLNLzgBtCiIPh0OYz+ew"
    "Wq3YOhEqbDYxYgeNRsj2CbvdhgUkLpbUaTweQ7vdBswCOyU13t8/II4TMMaB510wnPPx254F"
    "yGKv14PZbAaLxQK63S5EUYTELez3OZL8L7CWBEy5BbQolVIwmUwgCAK2PxqNMG2BgWnuWNo2"
    "3JWqUporCxwOB+V5Hvi+z5ZpzyRYFAo7uROpJFJ4UpKAxKpqAUk/iFyFR+fu3FUdWNWVQM5o"
    "VJUdOOdwr3sWoHO2NjhZPxOrjt+uMl4iY62tz70cBgNc10QpxamjqIlJEuOxNgIRhuE97vn6"
    "Lw8J3b6RpH96SPqX/IwelPjvc/4UYABrxgUeC3Nd3QAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgExit
#------------------------------------------------------------------------------
imgExit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAlhJREFUeNqkU71v01AQP3+okeOkjgVNREK/Ai1kYghlBVUs"
    "DGwdQCojylhWNv4E2OiGRAeYGbogJCaGKFWpiKqWCtokShNXadPKrf3s92zurKaK+Zg46efT"
    "3f3u53t+ZykMQ5h7+R0kWQZVVUE5hyRJywBQRtSQUxGcA4EjwiCA6rMZIJPhN+O+D0IIIpYX"
    "5rNl8lGM+b/ZsEAS3/Qc8dpnDLjngeuGkaeY8lQn3h8CAtUDzpdmxpMVbLg9aPK8AAZilC8W"
    "tArxxNA0kYDveXNmWlmcyKUKnuvCAIxxGI7Hx1IFQ5cXiR8XYOzRzelMfqPe7SFx9ULAjQms"
    "1resXrFg5IkfE8BiaTQ5kmm0rCMsvo3GxyZZEpGnmPJNrKcSSob4AwGVHsx1L9nHNhwenThC"
    "BHt4hZSuvXn/ha6zRgF+wD3fY47dtyN+TMBznB4XHNSQa2cOm4Qg2E7oeiXA65MVBdjpKc4q"
    "T47qCY15bsSPH4GxzUan308bmomjPmGOoxzu70PfsoA8xZTXRzWzaZ30iR8TwCt6t/51t50r"
    "TecSmfRjXJwXmJ5FJMhTTHmjOJ7b3G61iR87Am5btdOyVpRvPyr5e3euNes/nzqN1gI/PnZU"
    "w9C0iaumOTuV21nb2Ot1eit4rOpAQKJ/gT6afONhMrz+YCl5JbtolG/lw7FsSowkVFqGoGvZ"
    "9tp6m3UPVqSd1VfB1ocz6hsWoEkuI7IwdbcEU/P3QTMnQFIyEIo+OEcN2P30EXY/byHnAGFh"
    "nz8sIJ/vuI5Q4N8WIM4Qp9gnLgT+x34JMAAuBJ9VBPnzsgAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgEye
#------------------------------------------------------------------------------
imgEye = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAdhJREFUeNrUk01LAlEUhu845QdRUxZBhIIWtFBso2AwRAVN"
    "LqKltHCb63b9A/9AixZCELhyYdAmEyYCBcOlNa1CSQoxog/DMY3x9p5B27Zw1YGH8XrO+557"
    "59wROOdsmLCwIWNoAwFh/ugfZQKsAQV4gbNf9woqIAeuQHOgGxgIMNix2Wx7iqIsxmKxWU3T"
    "xgqFgpWSsix3fT5fK5VKPedyuftOp5OE7oz60hHsYD8UCh3k83k5k8ksGYYx5XK5rK2WzgiI"
    "rPQf5aiGakljakVRjKDrZaPR6Oi6zglVVTlFMnnMZXmdK8o2x674IE+1pCHtCFx2w+GwE9u3"
    "drtd81yJRAKdDXZ4eGSuFxb87PHxjg3yVEsaNNolg5NSqTTVbDaX7Agq8Hg8TFWLbGVl0xTY"
    "7TY2Our5NfhCQPNAWtFisdSr1WqvWCwawWBwRpKkcZyXadoN83qXmSQ50V1jGxurpnGlUqnH"
    "4/FzvItTmoo5ApjQNMIOh2MrEon4o9Gov1arzZXL5XHKBwKBT7fbXU+n07fZbPa23W5f4BVd"
    "93o9TgYimATTMHHCbB5PN9ZSf0LmrsEHRDWInvB8w/oFvAv920iFDkBzF/64fHTjvoFOxsL/"
    "/5h+BBgAwjbgRLl5ImwAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgFind
#------------------------------------------------------------------------------
imgFind = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCwkJO+fKowAAAn1JREFUOMuNkt9LU3EY"
    "xp/3Ped4th2nS0WxlSQRqUtIK9ZFZWlddFGQXXVbEBgEEXlXV11ImBP/gIIYFAj9EsmLTAyC"
    "EhPByKmlNWktnWtzc9vZcfueLnIx5i564cN78Xx5eN73/dL5G5+haaWwWq0NzNwNoB2AE0AA"
    "wJgQojeVSs0lEhsoVjIAmKa4kE6nPK1NltDRZqu/ppJX5pfTsSmf7ppfzIyYprgJ4HlRA8Mw"
    "GkyR9XSerfjSccReyYQyAGjea60sLxeJqh2Z+Vdv4p5MJusTQswVGkjV+y/da3FZ7edO1ZRY"
    "FJZzAhGIiM0Si0nh8EZ6yR/dZxjGkGEYyEeOxWLtLa49i4HfSTkA6MViNjeWRkff+tuLjqDr"
    "aWedUwvW12gqAMoXfYFYDAB21dosup52FjNgITgQ/JXMFBMbnWV2AAiupDaF4IAQjEJYUbSx"
    "iamoQwiTCg02M0JIzNLk9HqFomhjiqKhEFlVy3rHJ/SR44cTIfdBuyUrzH9pjKwJ/7ek7f1k"
    "3OlIv7yuGJ9Af7cLZgYzQ9rp6lpTSuzLEzNGZ0onUeVQDIddsv0IZtIvXsfVweGws/NEvHpx"
    "ZtBnmuZPIlrPmRARqOXiR6iqHaqqNTBL235iYPbBo8jXgTNe75PbHk/vnWQy8YyZZ3MJZLv+"
    "GOH1Vqi7T84RSVcK95AxoohEIsGurqtWr3fwbl9fj21tbXUIwAcUnq2+tXvbJb5P3wczg4gO"
    "NTUduOz1Pr3W398zsLS0MMrMw/jfIiLIsny6ra3j4cLCqul2u2/V1dWBADAAaQsZgJKHnNdl"
    "AJIsy8ccDkctEY2HQqF3tDUGF0Eq6Lz1NkcWQPgPoNkNgoXHVyQAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgGeneralSettings
#------------------------------------------------------------------------------
imgGeneralSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAY5JREFUeNqkk09qwlAQxr+XvKgFIyb+QUQqdmkvkK6KV+jK"
    "U7gRkS5EcJMDeAQ3rnqOXqBbBdGFilGsrhK1bwZjFSpUDHyZl5eZX74Z8sThcMA9l4Y7L6H0"
    "pOQomTfWfit9SnV76ff774VC4fm/7QghMB6Pv6rVqkstWPl8/nmz2aDb7YIg2+32z/VkMkGv"
    "18N0OgXVUC0B9CAIsNvtoOs6R8/zYNs2J57vL5dLNJtNzGYz7Pd7MqOfACQpJUdKbDQanEgw"
    "y7IYRqBWq4VYLIZjuwyQIcAwDI6apqHdbiMajWK1WqFer2M+nyOVSnFxLpcLAfIEoETTNDmR"
    "7MfjcWSzWR5Yp9NBJBJhOEXf98N5/gLW6zVqtRoWi8WFG7KfSCSQyWQu9gkcAgzaIEuu63Kf"
    "5/O4tj4CDHZAE00mk/y1dDrNEw8Tr61pPlQrFckfDAajYrH46DgOOyGblUqF12S/VCpxw/Rc"
    "LpcZMhwOR1SrJF7Vuzcl+8Zf2VP6oEYejudA3ggI6DyIe4/zjwADALUz7/8W+6CIAAAAAElF"
    "TkSuQmCC")

#------------------------------------------------------------------------------
# imgGotoLine
#------------------------------------------------------------------------------
imgGotoLine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAh5JREFUeNqkU89rE0EUfrOzScxuthG0gkEtVA9GQYS13qsI"
    "ngRBQax4Elu8eBZ6lP4JgiL24kFRDHiQoPQgopc2BwXpRQSDENiwtpuQTXZ3fvieZtdGoz04"
    "8PFm3pv3zffmzTCtNfzPMNPJ7LJ3F42L8BDriEdSqVUlJWilRpLeLuzP5kY6QSXzmPBswjb2"
    "nDjiXHUs4wE6b2HI+peCXwR4ihJiqe2HrwucFU4e3lndN5m/hgpukgopRIaxBHEUQRLHtOFl"
    "s9X91g8FP1Sxp5wiu4y+mW0Jon4fEiKJoi9tv9eXUkGwmfCDFXuvSJJLfyPILpGSh8Pb2FCx"
    "1gqiSEDJMR2MVbftAskfjk5HJJIxBtRhgxl5jE1mSsNwPMFmuw25fB4KVlHghao4TiAIAhDC"
    "QHUD9rPMAWA54wloUFB1JRicg+e1wfc7wFgJ4kEE1An123sYIcB38OMhSWoZosdMCHM70ObS"
    "8taG+xpo5v8gkElSw6B7Zu6U2wpiaA4E9CwkAQ7Ts647UeSwWnvTwLupjX9IWtexhMUXy/UG"
    "K5egyUvgW2X4amIJjgPvHq80KE77thKw9DPRrReOXQBePXcWfbenFq64n7oaDtgMWvce0smL"
    "cv15PfrwFEY+IC2GDlJTROwyZ67P5c7fX6u80posrdG/G2EjeJpD2KqAoykTAcIxjl48DtOn"
    "b8DnlTvq45P36OshfOo45mS9/C7AAC/XRIWgonuzAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgLog
#------------------------------------------------------------------------------
imgLog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCjQhZXhA0AAAAgZJREFUOMuNkU9rU0EU"
    "xX93mtQkNJJAKUTaTZqCpOimq+IuuhJciIhfwc9QKKHtxg8g2HWhK3VdpOBKt20WEoRKX3AT"
    "4qJNmj+v5s3MddGX2JJUvDDMcDnz4xyOEM/LavUZUODf8/n91taP64vE6OG9v7dXre4OnSNy"
    "jsh7nCqqCkCtVmPv8PD1i81N+bizczL6Z8YA58R7j4siXBQxvLwk7Pfp9Xp0u116vR4ftrd3"
    "vXOPn29srEwAnHMigBEhOTNDKplkNpEgYQwiwtnZGW/396mUy+++HR+/mozgnDEifDk6QlXJ"
    "5XIMBgPul0pgLZVKBVUlm83yqVY7Pzk4uAmwzomIUCqV8N6jquTzeVLJZCywWO/H2gkHzloR"
    "oFwo8LVe51G5PLWGn90uztqpAGNE+N5qoarUm82xk9Hx3jMjgrPWTACstUaARqOB956n6+tT"
    "nfwKQ+wtABERlpeXUdVbnSSNwV6L8LfGKDICBEFAu92m0WgQBAHlQoFOp8ODxUUeLi1dRYii"
    "WyKIUCwWAcjn86gqg+EQ7z0XYYhXRWLthAMbtxAEAaenp6zMz9NsNsnMzjKXSnE3nSaXyWBE"
    "bkQYOwj7/QTAk7U1VBXrHAr8tvaqgbgFuaYdAdJAtnN+fme0FBGMCKqKxLcBvDGIMcTaBaA7"
    "AixctFrtudXVN/zH+DBsxwD7B6PbNz1a3d2MAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgMachine
#------------------------------------------------------------------------------
imgMachine = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAoJJREFUeNqkU01oE1EQnk02iTFQE7QihUKRkKTF1iU9+FdQ"
    "CoWYgAcPegkIeiiIWiHgwUvpQXs1Ggo99OYlFwUhWAhYhZJWUmhMxJbYYk1LFDcmJraSv911"
    "vjQbevPgg9kZ5vu+eW9n3hM0TaP/WSI+gUCADAYDmUwmEgSBUNRoNJ5jaKjNSyuKsqRjjUaD"
    "VFWlWCy2X0BfDJ5nd5r9KxZI0Wh0BuRgMHibcznGrrD/wD6hawwHxBdcLte12dnZGYfDcYOF"
    "hkJBpnL5F3Y0IAcMHHB1nYAj+Xw+xHeZ8FSWf1BPTw+trqY2JElyAkilUhsej8dZKhWpu/s4"
    "jY+P3+P0s/n5+f0TVCoVqlarL0Oh0KTZbCZZlmlgoN+pqgrBEO/u/iZg4IALTecX+BQX6/X6"
    "9Xw+v8e7bYqiSMvLy+t+f2AGhhg5YOCAC43+7+T1eh+srCS1hYU32tJSQkun09rg4NA0TwLT"
    "IMTIAQMHXGigbU2hVqsZq9UaNZsKKYrKoxRZKDYwKizEyAEDB1xoOk3kzo6xP4PExMT9WyMj"
    "l/q2t7+npqYevkBucvLx1d7eE9Li4tutcPjJXEsoCO+z2WxcP0GcC3zmDt8ZHj7bVyyWyO32"
    "SLHYOwl4ufyTdna+ELCuriN2nlSEC2x1mshdRZGbkchcSJaLfCOtFI+//prLbRIMMXLAwAEX"
    "mk4T+ZLALo+Ojj1PJtc1t7s/bLfbHyUSGQ2GGDlg4IALTesd6Y8JY7JarX6bzTZtsVhOwq+t"
    "fdMymZx2MAcOuPrmrSYKaDHRUbZjbIcA8sM6xQ9sADFP4xNf54/t21tnk9kKrG3qBdCLw20T"
    "//GCFbY9tj+sVf8KMAACOoVxz9PPRwAAAABJRU5ErkJggg==")

imgMachineDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsKGSg8jqKbAAABp0lEQVQoz32RPWhTUQCFv/ty"
    "i+FBIKAQLTEN+AaRohlctIOgiyLRrUKJFOrPUKxLwZ+hdPSHLkbJogWpZurQoEgEURDBLFkU"
    "sYKN7UscLJa2NHlp9L57r8NDR89wpjOc8x1h+b8knMahD4GleYSDwMdMTWBRGF4go9zyUXHI"
    "PhO5yyXN7PhyU5yxH9LvARwAfyg1XCi5o9rpsI123NFCKTXsDwEIy0m+TxSKbZI0l/Z60Fra"
    "4wUkeHo1ff8lDmyhFuanJW36PYul3+shmZ9WC1tRydVjHN4MWo2Bfd++VN/AqePp/X5jM+Dc"
    "ap23wjJw7fydHn3s4NHtHzdh962LN36hiPPkun9XQhhTGAzgqMjBYFCEMZAQ1h9PwYkLXvZs"
    "/rmCfN7QWnk9C9RBQvxV+2viSiYbkMpN5GCbDTLZeLL9ILECDvQIx0YmO0gW/XXWWfQlHUYm"
    "w7FeBEqha5VykrlipWwwVMpzxSSVsq6paOYGstoQMy39MHbJxaCdtXszXfPOVrsRSSHZyS7i"
    "EBsUB8B+1p+A3/xkzYbCIhxc3L+3/ZMmoGvNH8TKrfqjhKcGAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgMove
#------------------------------------------------------------------------------
imgMove = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsLAhXMEk8nAAABbUlEQVQoz1WRv0pcQRyFv7l3"
    "diNmQbOYOqBYWM8KxsI/KWQgkLD4DhHyAjZbzisEub6AhcKiEBkQFCy2umMeQG6RMiiKG4l4"
    "//0sVhdzqsPhK87hqI9EaCwKTWxx9CpfInhKagboJZo0AcBW7pM5dYCHFXJyIOJFtnRr5p41"
    "UzrsOH0B7si6GUl4QxIysu7dGNAAYnW3tXUPaQHQaaET6eOfAbGFg5hJ/lEAk8QUBiPgQYst"
    "3GfzM5BGNPZvjhtTUVpRsW7OnIBX39Mv5pZpSoYU28Pk7aocCsI1s5yHHx2d9/bdpjkIAFwt"
    "LwzmCAAdcxJUD7T4gj0HcQeqVEweRm4QVK/hRyV9Dt0SRYTwSI2gA/3maMUvZpj2pa8TZSqg"
    "gFSCbGn+cA3oC+A987T7Yr6aB6w5Cqp/wyVX/Kc2i3Yj3ZGNdNG2x6mgiGnxjik0zJkP337v"
    "ZgEoGXLLX6kUEU0mmHh1G0DNIw/kUj8B2jqZwW6x6egAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgOpen
#------------------------------------------------------------------------------
imgOpen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAaFJREFUeNqkU88vA0EU/mZ2WiElfobERfwBLiIhcfA/OLki"
    "cXSU4OJQcSc9ceQiEkcu4ibiUhWkxKb1o6qyqVLbre7OerMqWqlkpS/59n2T9743M2/2Mdd1"
    "UY+JkxVWM8AZBsiN1wjtSBex730FYYrQ9zuLkjA4JxdzhQKypolpvQOGYWL9NMQpPETYUHns"
    "KIzw8OzuPBwHrivhyko4X17FypwxhujmzDJpF7wTOBKaEsuPYpVQVog9XvaaFoCnIQvQl6tF"
    "9c5/i79PojRB4fUJwqaFtG0Y8UMU354BVYw69AVJa/Lyh3PO1c6jpF2iQyQEFRVWLg2bknpG"
    "Jnw9Xe/Y5PB7Ru++2J5fFTZdK288QGtqg5VJw89/wRjHc/z43rJxrgqIbEpHV/8gbGqkH9OC"
    "DUjfnKVNC5eiJCHyuVf0sIDvAk7Jeksl9SeN415Q/wJaYztsy6ROS18FjFT8MVfANVFXEGkJ"
    "NXfSk3Bwjfu4P8OdfvVydovY2h49YzSB5OtW5OA/A6RncB3Zh060VU1SUJHyXPg1h2ARiqze"
    "cf4UYAAOUhKfHcZJBAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgPlay
#------------------------------------------------------------------------------
imgPlay = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAXhJREFUeNpi/P//PwMlgAWZ4zDvJQMjI+NMIPPwnz9/lvz5"
    "/Zvh98+fYPzrxw+G6w2m+A34+/cviDKGYhBYQsgFTMgckI0gHOstZQykCxj+/48hyQCYc9+/"
    "/8MQ7ydv/PvXL4KGYDXg+/c/DJcvf2KI9VMBG/IfjyEoBoACCoR///4HNOQHw/HjjxiCXIEu"
    "+fkTpyFYDXjz7gPD46dPgfQ7hsNH7zC428qCDSEYjb++fwfTr379Z/jAzg1m6ygJMqzddP4s"
    "MHonEDYAaDsIvGTlZnjJzcagK8nBsG3lfrBmVnb2JYS9AEowQPyClYdBXFqQ4diiHWeBgTgB"
    "6P8lP59cIpwSQTEAFmRnYbg+cwnE2e9uL/lyaS3D7+dXgDIlGAYwIucFVu0ABiYNvzMg9v83"
    "Nyf8u7F5yd9X1+Hy2PINigv+XNvIwSSgco3hx4dL/87NBVmpAcQ/oPg9EP/E6wKgk0EGCkEN"
    "/gcyEwn/AKr9g9cAcgBAgAEACsnYjGRDfAUAAAAASUVORK5CYII=")

imgPlayDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJCTaOBTPwAAAA2klEQVQoz33Rv0oDQRDH8e+G"
    "80+TxlJSKUj6rW1TBZ/Ah7gXEbdNv5BGsMgjBAKC14QkCGIpguAl3e3EMWtxFsde4jS/5sMP"
    "ZsZE/p+sjnvMiKl6RRCEuxT8gMUCPm3o1KEoQ6t5vD0ABGHDjd22SANULPeQBvim4olBQv5A"
    "IFDyTsmMayt5a80AVHSASyaFcXtBJKPHY2HciW+BLQDnPBTGHfmP9iUFOGZcGLfxL3w2gKl/"
    "ccXFM6zdm/8CIKYNr6fdlcyXC/oEAmskaTAZZ2TsUBQlRE3A4fkFDI1aCaBdI4gAAAAASUVO"
    "RK5CYII=")

#------------------------------------------------------------------------------
# imgPlug
#------------------------------------------------------------------------------
imgPlugConnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NCNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NBNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8++VdpNwAAAYdJREFUeNqc0kFLAkEU"
    "AOC3lhlLS0SK2CWwpEOuf8EQhC10rSSlbQsiyFB/QH+hW/+ibhJ1CoSkg6eKCBFviyAs0UFR"
    "VklzehNjyJK2OPCxb2ffG2beDsDkQ0JPkxZvome2iOWCF/Ycji2NLfSayWQIfTK/xbYxRW/M"
    "RSqVCui6DqqqBlgNN0jkRhRr2Wy2ZBgGtFotaLfb0Ol0gBACgiBALpcrYY5/1JbL6XSabnc9"
    "kUgQv18kHo+HOJ0uIooinS+jyLgzVyKRKJFlmSYng8EN4vWuEJ9vjb5XzMXmHkTpXL3eBE2r"
    "QTgsXRcKD/tu9xLw/Nwg/27UAjK6TCYPVvt9Dmw2OzQaBoRC0lWx+CjyvPBn04ebqKnq8bKu"
    "f2DDPn8mHA47cByHzQPI52/pH/Cim1Fnj6GqopwQSdoj8fghPXN1SOy/C7ODapSinBIWb1u9"
    "bXH0jnaZQWxpHKEmOkMutIgW0DyinePRLJpB02jKfBO76Bzdoy/UY3M9U9xl3wf6dIFvAQYA"
    "XFKD1NmwcssAAAAASUVORK5CYII=")

imgPlugDisconnect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOkE2MjE5N0NGNkEwODExREZCNTNEQUZBMkQxQTMwNkZBIiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkE2MjE5N0NFNkEwODExREZCNTNEQUZBMkQxQTMw"
    "NkZBIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+phlpSgAAAbVJREFUeNqU089LAkEU"
    "B/BnpkYQEUUIXQo6SBRmJB07xWo/UA9GYFJoehMh6xB16Fin/guhg3jI6OzJixCWdYjshxJo"
    "IHoINXSdviNTCGVbAx9m9u3u27dvZ9X0v2GBU8jCuFj/eVjhMhgMMj4L1i6FmxbhSjgOBALT"
    "xWKRvF7vNI7VoFIpJLgJhUITlUqFqtVqS61WI1mWSafTUSQSuVUrJMgmEolZs9k8WCqViCeq"
    "1+uk1WopGo3e4fyuUgJ+0XMymZwzmUwDvAIVio7FYg+Ib0OsUw8mYV+sz/jF4XA4y5/MGO8h"
    "dYv49y7DFhyIJO3DAXlJkniG/E9PTfn9fn4yBb4Ola1CVczfRtpmszOnc5UnScOSiE/BYacm"
    "fTZxGSS9fmTo5SVPRqNxOJO5n0FMhjmIwOtPCXgTV+DE7d40NBoMXe6mcvmN5ucXDIiHoADX"
    "nSrgG+nR4/GN5nIFbJT3VlCj4U1m1GwyiscvnnAw9tu3tkPO5fIyi8XJHI513oNcG7vST+IS"
    "ZRbW1nxMrDegH/qgF3pAK76/WlT+9Qo12GvVTHQEO3AODaHeNsttmjzBhwADANJmm8jvUXkB"
    "AAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgProgram
#------------------------------------------------------------------------------
imgProgram = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCg86069mBAAAAdlJREFUOMuNk79OG0EQ"
    "h7/Zu4OzhXEKhOR0KdLAWzh1iiiK8gp5BiRkAU0eIFKokaiS1ChCyivgIqlIDaKxMXfHnW//"
    "pfDdBmILZaTVrnZnvp3f7KzQ2LvR6DUw4Gn78eXg4PfDjbhdOOeen4xGx7W1aGvRzmG9x3sP"
    "wHg85uT8/MPb/X35dnR02capALBWnHNYrbFaU1cVZVGQ5zlZlpHnOV8PD4+dta/e7O29XAJY"
    "a0UAJUISRaRJwlocEyuFiDCZTPh0espwZ+fzz4uL98sSrFVKBCUCQBJFf4Uaw3A4xHtPr9fj"
    "+3g8vTw7ewww1oo0gGfdboi9ns14sbUFwK+rq+C7lIE1RgTY7HS4K0uc92Fcz2YM+v0gxxqz"
    "EqDa9JUIm50OAJOiCHLW4phoAVBLRTTGqBarlCKvqgBrwWmSkEQR5gEgfgAQEWFuDOtx2H5U"
    "k0G/z3Q+x6yUoLVqn3FuDL6tgXNMi3s8i4aKRLBar8xAiQiJCmdUWtNNU/KqYiNNAcjq+gkJ"
    "i5bG+cV9znsqrXHek1cVznuUyGoJZVHEbQH/tWxe02syuNc6+LaADtCbTafrQPg8vlm3c20t"
    "zntEKRrfbSBrAdt3Nze3G7u7H/kPc2V52wDMH+TGCvd5v9PGAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgSave
#------------------------------------------------------------------------------
imgSave = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QMBCR0qtm4moQAAAkxJREFUOMudkc1LVGEU"
    "xp/rvNfGcVKbjy6D0x1jKEYcZGjCNkZBIQQSWLmLNgatopb9A6Lb0I2LFhFBNSW0Cfra1SJx"
    "iBaKUabI1FhK40h33jvnPfe+LRxdBIJ24IED55zf+QJ2sf6p0tmJJT06saQ7+6dKV3fLE7sF"
    "FFHf5qZq0hoBRVTbN4Bct1dKpX0fo+S6zQCm9weQMl7ZrLWSUgdIyo19T1CXMvrd5bznG6hL"
    "WdwTIHnr1ZRhGPkGAKtmKzx/yz9y+/UsAGiti6W7Aze2awwAGB4ePgkg/6W179SaaZ/rvX7F"
    "XvwD/K4DvtYImwYONQPrD5+uxNXK22POzAcAxUKhMGsMDQ3FEonEyNjY2LjrupieKeH+ux+o"
    "Dw7iY2WrSzoMRF48x+VcDOczMZhmEJOT43fW13/ea2LmeCaT6WZmVKtVnD7ajIs9LfCfPIYd"
    "AjpbgNCzRxhIC+QtoFLZgFKMVCrdzcxxwcxWIpGwt3eq1Wo4cVhhrdPBy8IDaA2cSUpkOwQc"
    "x0Qo1AYAiETiNjNbQillpVIpm5nhui6q1SrK5TKOt7vg6C/4vkb6YAirq2V0dDAMwwQzw7KS"
    "tlLKEkQUSyaT6Wg0ivb2NnR1pZDL5UBEuKAUPM9v3LoJQKDxOAFmL01EMUFEwWAwiMXFr1BK"
    "gYh2pBTD9/8FbEEikRiIKCiIKCClxMLCZ8zPz4GZd+R5PrRGo1jsqDK+jGvvb4KIAsJxHLNY"
    "LC5ns9mubLZnTxPINwpz3z4tO45jGuFw+JIQIo//MGYu/gWaSzpM3qF0jQAAAABJRU5ErkJg"
    "gg==")

imgSaveDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAwEJHh0l/tBtAAABN0lEQVQoz3WPO05CURiEvwuH"
    "x1WDyMMLqFcSGgnEBmLtBiw0sdLOwsINuAGivdHEwiXgSqQUiAkGGqOJCfhA4Jwfrg0FBUw3"
    "M18mGZhRdb9RaWxUT2czNWtkb+jz/PK3GNg13qQiQR4XACY5WB6HTG/hgo6PSh66Nge4vbdK"
    "IHh4CHdP4NUuzgH8cFwuHPhcVSznIxnDhHhmPdOR904mVbDqb9ZhIn12dT3khSY5foAlWmyR"
    "IsDN5eeDT5I7eeGLNVI8EyZEnSghuhiyeUkqcdIugCZClDoQwUYTAGKuOMo4264w5JcuQWzG"
    "KHrY2AiOaxylE5u5OKtoRmgM4+k9C5CcTigdDtPCoNFoDJMZIIYOK+0f0KSOIAhjvGkJJ3yj"
    "/aofqLWL2eKchQ9e2/2AtXKkSiyU1P4BlmV4dLjh4mYAAAAASUVORK5CYII=")

#------------------------------------------------------------------------------
# imgSettings
#------------------------------------------------------------------------------
imgSettings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAzZJREFUeNpsU21Ik1EUPu/2OufHtrY5dJtoQlKGhKaTTcuP"
    "mZVhoG1TcAYJZv5cURqGoYIxhoFZSM38UaZYgxK0EtEfIn7PhdIPQaMCmebIj8myubm3c+cH"
    "Fl143vvec8/znHPPvYfS6XTw73A4HCASiQ7WLBZLRFFUCv5GkLXFYunHya7RaIBeWVm5HBYW"
    "JkXDEqKHOBCyz+fzk5Eo4vF4Or2+uDAu7mRyQkJCJbGrVKpd8aGhIanZbH4mFArjNjY2wG63"
    "w+LiIuzs7Pjh9XqVGs2VoqioKDXOzzG7HoVCYccgcuTLWCSyUqmsKisr02MmlYTkcrlgc3OT"
    "kAnkkZHy5Kampt7x8YlOkjoGk2OGBdvb27lEoGd+ft5UUlLSUVFRoZdIJJWEuLy8DG63Gzwe"
    "T5DH4+WVlpbmKRTJxeifFBt7rKq1tfWB0+nksPcLtbq6OjI8PMyvra3V22w2/tLS0khISAiF"
    "W6lqddYFp3MDtFqtiqZpmcFguGq1Tk/39fUNsg9Xf21tbWRsbMwvYrVa+ZhJeEBAQFhqampO"
    "aGgo0DQbEhMT5ZOTU59MJtOH9fX1txT8Z8TExFTez88vjTWbvYLrZfEFve/r8Uicve1fiG9s"
    "Nrs/MDDwB40fIOocDucAeO9fhS0tgrS6Oml3TY1dJxb//O12Nz+l6YMgKLA74zn9i30guSAi"
    "IiLl0tn0i5bHzct5ublHTthsTJLPF3nN6x31ImmGxfL7Yj2ATTI4RNZERx/NNBobb93uaH/o"
    "2nT2hc/MSE+Vl2c5bDYPAxAZ7/ON6PCWohFC8tj4fD6IxWLAqFq1+px5auozk5Z25olMJtPe"
    "EAigG6DhHYB1y2Bgxijq4yhF3R2kKHiDmXSQM+wJFGZnn38xO/uFSU/PbMMHVSiVSiGZywUk"
    "E+eG1yiyXV3NIHlggKLuHRYoysrKeTU3Z2cyMtTtAoGgKDg4+K9bIe3WjiIvUWSnvp5B8nAX"
    "QK1fAJ2NCwsOjKzu5HK55WiSIARkCxGI4CJ4pMfuADxqQxHGaGTMAFNm0mxYySIs3mmGYb7j"
    "sx1H2xbCtQcPaThEECKEiN4EKD8OoJwA6JoHaPwjwAC3pz/3riyFYwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgStep
#------------------------------------------------------------------------------
imgStep = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAeNJREFUeNqkUztLA0EQnou5i29sVPAVRBAtrK4XLUWxULBK"
    "GhvbVP6OVIrgowmiIFZiWkHExgODGBTLENSLUSImub1H1pnl9vSQWOjAx+7Ot/PtzOyuwjmH"
    "/1hUTmZ2n0FRlC2cnruum3EdByKKAmosJnif0xEGHrp2ttov/BEp4HkeYKCOSOEyQT5mWcIv"
    "ueXZPuJ1WksLBOhEQnJ+QMcxBZwLEataDbhazQvmPwQcxgRKJRuSCyO6Y9tCxMYsJGdZbjBv"
    "KsCYBzc3FUgujgkRrDfBajVfwGsuQCfZomYOjQaHXK4MK3MowlgKhUQmxeJjsO/HLUgnYw6Y"
    "pglVrL1Q4LAwG9ePs/cpkaXjhYLDGdTrAsW3dzCZC9VoDManRuDg+NpwLCtN3AeeJ/c1LeEl"
    "EoNyezfEJwfh6PDSwBLSWEJGcGr7LyX4jSlpHRAf7YLs3omBjyetalqGmkhmImd/a2BIQHY2"
    "2tkGFxv7IhheHzL15zy0TCwK7lXtCN2AMPoLhEjvBGhLO1cEdXo90dI3+VWnz3Wdck4jrWVc"
    "kEGjdDfkPuXzwCq5hrF9i64xxBu9cuR6kLt3N/E7lB/yuB5Gf0H8EfkbMeVuHFSE5mtSrtRu"
    "2tDqQ6FqCRhXCQn81T4FGAAo72Xu5YvuhAAAAABJRU5ErkJggg==")

imgStepDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJFwCV/pm2AAABG0lEQVQoz33Ov0oDQRDH8e/o"
    "JQQL8QEUhICN5ZIHsLGQ4BOktz2fxGtTWXiFkCKlYCtWcoVoAhZWQRDz18Lc7mYva5HLJWky"
    "xRS/+TAz4tleAcAN0uTJxQ6hDEgTReKvrpcgA4UCYs0ugDpXj/mGHQCHo65c6BswxeFIcbgV"
    "MBgG1JUNfUNjMCz6BjB0uFQ29I10AwQLABlz3rhQ7dAjfOXjHGjA8MMfPc7UQwgOvf6kRjNk"
    "inBKOzGRJkPnpABzAk5oJSaysc6z4oQFhGPuE4lKcQoIdv0HA+xxl0g0iQdUWWYFeKbGbTKO"
    "PuMh8E0NsLyswOiw37Wv7x2qjMlGB/2PFpPu6IgeiAdknxJlwJDiqVBBmDHzvznYVv8FwISP"
    "Lb8SGwAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgStop
#------------------------------------------------------------------------------
imgStop = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAT1JREFUeNrEUztSwzAQfUIGjBNomAwFPRWdSwpKzpAWCg7A"
    "OThACug5AxUFJSUFVFAwJGRgxrHxR5Il1nZw0GCHzKRAM/qs9PbpaXfFjDFYpq1gyeYUw+Hl"
    "CIyxAS39BXzuSPXpzfHOjCBXqpj8/tGuL6X9pJ8vdByGq+uX3wpklpVGHOcIAtV6dbfLa6xF"
    "INK0NNJUYTIR9aGUElkmoJSE1hq9XqfGWgRZkpSGEJpIJKIoQhiG5JzBzpKosTZBHJdGlKR4"
    "eh1C0M1VjrgFTvQM26jg+VNg6Li06zYHga/NVzDiHsad1dYginU+X8Gb4+HDba9MQdyyScF3"
    "agzn2PQAbaYd1Wym9SBZhdXjB9rplz6siDJVIecHZxfY3tv/sw7fH+/z2/MT8lMWAa23qG8s"
    "UMqF3MAi+Nff+CXAADjrrYLxZ/nIAAAAAElFTkSuQmCC")

imgStopDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJGge+NHJYAAAAsklEQVQoz6XRMU7DUBCE4e/F"
    "oQAhKm7iS3ATak5CTckpkLhDOrgCJcIKSvxsy0sRR8mzJSjYcvef0exuCr/X6o+5NY/Sk3ox"
    "2cT9wwEYqO/qfurHpHs9OXTYawr5te4EtGhtQS8bjG61JdBpfdvKjludATvsfeiRJDDYlQ6N"
    "UXWWIeYOo4siZJo7RKGfZchYuRLG6Q6B7PMIvFT12/PikF/vm7WBFFLlxuWCyJo4AP/85g/B"
    "20B5o42C/AAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgPause
#------------------------------------------------------------------------------
imgPause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAU1JREFUeNrEk79OwzAQxs/ELQkRUiUGhu5dGDMysMErwAoD"
    "DwCPAQ/AAG/AMyAGRhYWpM6obcjfpjRpnETmnDRWraRl6MAnnc73i/PpcrEJ5xy20Q5sKVov"
    "Tp5sIIQ84NJaonfs7rqNvV4eNg2KPBfJujjrW4xxeH4Z1Y+s89O+lWUKaxpkaVrm+TyHIMhl"
    "LTSb5RBFKmsYsMWizHEsNjNZC7nuFMbjH4U1DNIkqYyY6CCUtZDnTcFxAmQbhpjGcZknfggj"
    "P5C1UFL0INMosujvDjzeAd/Yx9qWm3zNQEYUtrYDm+6BY3YgX+lg0jXBNXWFre3AQQNf57C7"
    "MoNvakKog8IaJ1H8IhGFpoFpUFmLYPj9Wrdi6deHYkDqu4AnjmrHN49wMDiqhjEcFm/3t8ju"
    "kA2W7BPZFb7DWg0w9TC6G45+gRG0GvzbbfwVYACMcsm3y4uD/AAAAABJRU5ErkJggg==")

imgPauseDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfeCREGORAW62QYAAAAsklEQVQoz6WRMQ6CQBBFHwgk"
    "dtZeYw+hN7H2JNbWdh6CG1gaE05gUAJBs9ldUCx2RV0SG6aZn8zLS2YGxlZg22aLAA7r1SfZ"
    "SWRbI5bCkAKNWIiGtDc4wCCpMIDhzg3jAwpJjQIUV86oHgjfgKF0QMFlCEgKCiQgaQmRQ0PL"
    "xBk6lzzDk9gZcMkzdP8NmpApGtAExGhvzSg/7oAqY55ne6A6kdhjBA6bkfy84EH5da1R9QKq"
    "KkucPaZRYAAAAABJRU5ErkJggg==")


#------------------------------------------------------------------------------
# imgMachineReset
#------------------------------------------------------------------------------
imgMachineReset = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVEzMIIPvpEQAAAz9JREFUOMulkF9oW2UY"
    "xp/vnJM0SZNS+ydb07RZTSmd1tU0cZhInG66UUOh1j8o1ospuF4I2xD0QtjFQASpNytuiJfK"
    "EGHDPwzWOdfIJDBtQd3somkzsiQNLkm7Jk1zzne+fK832zp263P3vrzPj+d5GRHh/0gDgN0n"
    "lqFZLNA0DYqqehhjEwAiAAbu3P0DIEFEZ6WUK6qqTgKIzh10H9IeAI5pKh3v73F0eDttbS0O"
    "zQEAlU2xM1fUo6lM7SVJlGgIceCuQblnJRqzN+Gj8afdj/e22bxMwFGvN2AYEhqYw9du88bC"
    "Hc8IIQ5MxjxBIcRWBZLSozJ5PBbZ9titlTrqXOhLhVo+V9y8DQB93c2tT+xs95eLOl7b3x1c"
    "X+MwOd9KIDif8HfbOwrZCsprG/rF33J/ZfK3j5GUIVPXQ6n06vnT51IL7i47MqlVCFNAGMZW"
    "Am4YT3W0WNpKqSRyS4vVZl1+W+uOnK5VKmCMTTLGnjz89kjw33wVre022Owa+P2AXfUre53p"
    "rCO7UsG5jw92jo+Pr8a2l05Vjap+RhlzEBGmP0ss3P9txtjCPYBKQjn8YhSzv8yjUChgaurQ"
    "0UAg0H/y5KkvSNI7UkqYnIMxFgwN+1zbtznph9lrGQBQwuFw5PfkjeyZ83EKDPhgGAb8/v7+"
    "eDy+PDc3l2y/9F5kvVSCqesjTqf1+ZqiDWWLG52mYVgAQNF1PfrlsTcDj+7oYqpqx3NHp4Wq"
    "2uHz7fDPzMx8qut6lIheMDl/1TPo66poTexmrsxNw9gAAKVerydefuOtT+JXrnLOG0h8Pq1x"
    "3sDlhUUzduTESr5n4nV3b+eRodHII3mLi2SzHTdT2ZrJeRkAlGQyeTk4NNgb2/us9bvZn8xM"
    "JoWvf4xjdM8ey3B42ON994M+PhLyJplLqVubsHj2QsWobS7KRoMDACMi7Nu3/yuXq8V66der"
    "mI///Epo6sPq0GCfowZVXRp9v6KsltO0nL5uplJ/yvy1b+Tf36flrSSICAyAFcDDAHpUVQ1p"
    "Nucu8dCATXbtdsHm8qDZvcaYMo/S9T9o6UKS1m5UARQBlIhIMAAqgDYArQDsd+a7agBYB2A+"
    "sKsB2CQi+R8GrIocunSMSAAAAABJRU5ErkJggg==")
    
imgMachineResetDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUTNxBX+7RDAAABzUlEQVQoz32Oz2uScQDGP9/3"
    "1TnfYdtEk3StUhsVOVi6KIeHoh8QSLGRh/DUoR+3+gPqsOoS1CVYh+5dBqMg2uhQ0WIUzUPQ"
    "Dwm2sJy6OXPT3N731fd9O+i55/QcPjzPR1j8Pza4ix0bkl+ME2cI+MGCNWMW5DSJG1dtHTAp"
    "Tw56vO4eBRoHy4nchLlgnO0sgJV03EtEahhsIyEUjxIYeO06H32eARuYfjE5Fimhq4WVtQ0I"
    "9B0KrXMmuoEOSKCPBzwrVNWPX/O3zZgaW557kfGxTBOtfaGP9bp/slTffuZ9WkekxbHL0SJu"
    "nOhtwDpZUEo89F74s/exqTYUi6lM21y0HZBSvKPItZsj4akn1hWTJiI67PJZr3IgHY9///3S"
    "OoBGKPx26U32U7yCeqTnNIfXvJodJDVxZyQoZK63ZPaEHj1QE9Y5PRXehcjr2l+Qe6WZsm80"
    "KF+SGrxv3l/tD+6PjPYb1e7qYqGVTRlSdj4yeKprtpljlhP2o/70vqEBTZKZq219M3SwQcW4"
    "Nf2B5MXp+hfFlOvUtHztV2l1frlYAQRdBNktxxzDO7p3uhx+Z1UsVj/nspt1yqxbLYGMmz6c"
    "yAAYbNLstAZblvkPcw20XZHI1vwAAAAASUVORK5CYII=")


#------------------------------------------------------------------------------
# imgCycleStart
#------------------------------------------------------------------------------
imgCycleStart = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVCTUMYH2sKAAAAiBJREFUOMul0j9oE3EU"
    "B/Dv9a6NRRLqUEQhTWpOgokk5q6CkQaiQTtEOjhbncTSQTIJBgddXPxXDEVdCkIQRTqoOLWS"
    "hhSKRVGMwQuNkWjk6GL8E8nd/X7pc1Go9NIiPnjDWz583/v9BCLC/5S0dohPr0AQhDsACpzz"
    "LGcMzDTBTBOWYeDdxf0bA+12GwDU3w0A2c0SdK0dOGPgjGEsuVPljKVAdOKfgD9xGw2OU6Me"
    "lVnWpogt0GpxFIvfMTYqq8yyUrQB8hew+8WlIVc93//jUwWtloHFxY84fsSjMtPsiEgAkE6n"
    "bzidzi2WZRXzNycGTl69jz5hFTAtFL7sw0jMrT6ZXU7ZHVUCAFEUt46PnzkdDocquq4jGexH"
    "XAni/N1ZuANuzDx+9VIQhEnbBNFo9KAoilogsOe9oqiyaZpQ5AHM5J6jzoDK9L0yc+2a7HY4"
    "bJ+0yzCMWCaTueb1DvpEsRfB5MSKKPZC8W7HlWMhOD4XXhNR1qy/sb+i3++PybJ8YWrqVrVU"
    "qpKu/6RSqUqXr9823MrIQ7/fH+vesRcAQETrukvTtEIkMhQcHk4M5nJztVptGQ8ePbWSicOO"
    "A75tvFwuF5j+tuM/EIgIicTRrNPp6pmfn/uwtKSdU+KHnsXCvtVms2ksLOTPAjAANIjIXAcA"
    "6AHgAeCSJCkkSVKEc17hnGsAWgCqAL4BMIiI2wEigD4ADpuEHMBXIrI6rfALn1AIEjDjE18A"
    "AAAASUVORK5CYII=")

imgCycleStartDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUKABWkYXgHAAABMElEQVQoz33RP0hCURTH8e/z"
    "PTKSoqXGMhSFgsxeDQVvzClaW1qDRqeGqK1VlKKhZmlxaGgsInhTRBBEomGGS2ZRGQTvD9du"
    "g6UP+3PucJYPv3MOV5H8X1qzpVF2MUVW4ODgkOoEDdDRgWxngq/ZBIJ5XSTl0h/AwaHOgu7+"
    "IB5gcf0L+QI3U08D91ickeggGqyle7vdq92hTTQcXjD0o2R7WQ3UwMpyrFRlgmn2iHB4oWQ8"
    "CTOzamH0djLsEOUYi/1iT8bvOdZnG9upYEglUVMJsUjtUmar3i2jRnh9p5yXDzIvU3YsFzUG"
    "Adl6voIZHzNGTioVDtw5f0QUzcfOv3hubORO785Xt0zz4z1AEJtXnG+g0MUwfdq4FhclUcCi"
    "zBu2FG2g0o+/lSioS9c74hMfVHn8Ak/RTAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgFeedHold
#------------------------------------------------------------------------------
imgFeedHold = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVCTUtLBS8dgAAAjlJREFUOMulkz9oU1EU"
    "xr/kvvxr0iJK6VA0qR2CaUFrUkskUSFQ0S5OQYcuDm2GCs6BgoODS6n4QG0HJxeHoqBgESFN"
    "BUFqDBZbU7RopBg1/0xe8m7ufS9cFxuSJp36Ted85/A7Bw7HIITAQWTEASXtBucf/YbBYFgA"
    "4P1vJYQQ0528+PW+dkBd1wHAe+1iv5dzgaXYz92S9+p4v1fTWrx2gMYYAKBa1VEs6o0cABRF"
    "R7nc6rUBeK0GAFBVHeUyb+QAkMuVkMlUWrw2AKMUXZUfXdn328jXD4NRa6Mpny8hmy2C0X2u"
    "EI1G5ydNrx6Qwle7PDWBfHoDfpE8dqW2NM9UFbQuoBEJTFXBVLUdQAixRyLTkZlLnr5MJoPJ"
    "gAu3py73EkLsjFIUiA0FWzcYpWC0dQ3J7/efJYSkPJ4T22dOewcZYxhzO/F0Oc5isVjKePTI"
    "uV/mMeTsVuh7pgOAsVarBWVZnnO5BgYJscEXfQhCbDjldlpkWZ4z5rYcfyQ7CtaejhsYKaVv"
    "w+HwbDL58RvndWzevQXO64i/W2fhcHi2RHornEggZgkaY2A7662AVCr1ZmTENxQIhAaev1yu"
    "ptNf8OTZCz4RClmGh0/6lIr6Qbm/mOALiwkt8+kzj98xNwMMQgiEQuOPHY5uy8rK6521ta2b"
    "o6Pue8HgheOKovDV1diNpv46gKIQgjcAAMwAnAB6TCbTkCRJHl3XNzVN2wDAAHwXQlT2eyYD"
    "AALgEABLh7oO4G/zxL36B81HGAnLxB/5AAAAAElFTkSuQmCC")
    
imgFeedHoldDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUKADYGBgl1AAABOklEQVQoz4WRPUvDABCGnyRN"
    "K6aIiOLmVxepm+miEEEcdOrYv2ApVHQV+hNKwQ7i4uTkD9BBULEgDlZxULuIQoUKKkYb03xJ"
    "HFqTuuhN79099x7cCT5/h/hPnwhACWELFaj6y6FaCwEP1CXV4RBAXVTdtgoBBzDRcQAwaHZU"
    "AFiAyQcWAC88dVQX0Oq9wu2UX3nuAkRYLw1svisr1OkZkUsmHiImZghISjabHm4wT25IUix8"
    "JKzAIzIzK9WSd9MJmyT79lFtcA7kYB5ESysXxxISeSQmY+WiHv/tILZOM4XLe5dtXM7sTAFD"
    "QMam8bOiVsnktPG9T005cNKxSqp+sWuAfluNto8h+CzsxGPHj+erqQ1toumc5AH44s1vA0QZ"
    "pU+eiiS9G/camwff6H6WgEQ/sSD30H2nG/gGqct2z+LvT7EAAAAASUVORK5CYII=")
    

#------------------------------------------------------------------------------
# imgGotoMapPin
#------------------------------------------------------------------------------
imgGotoMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAa9JREFUeNqMUz1Lw1AUvUljK9F2ET9nwUGKWpSOXVy69A+I"
    "Lv4MZycF/4NjRBQdHJzsJIWCOhRBC4V+Do1IkpqmNnnekyhE1MYHh8M5l3fefZf3JCEEfa2W"
    "LIOmGDuMFcY4o8+4Zxwz9AXPo/BS6PuaZ+xP5vPpiVxuKZZIJF3HMXs3N8vW1VWaa3uM9qiA"
    "rWShsJbMZFaFrhN6456SqWx2XRobU8yLiy22DsMb5LBwuW11Y2PRM03SOGC3VvMZGr4bXIv+"
    "DBjwnSVZVoXr0lmnQ23D8Bka/iCYyd8BDpHl6PorNmyqKsm27TM0fNRHBvC4bzvFYk3E47Qz"
    "O0tn6bTP0PBRjwo4bZfLjTfLMnDqF6Dhoz4ygIfUtYU4f76+fiJFIW84JDA0fNRHBhj8qPpC"
    "aK1qta43my84HQwN3wg9ul8D7AA9bvXksVSqkyQRGBq+TURRM/DB075sNho9l68AhoZ/FxWw"
    "zXgIQkzeFBMcAIaGvx8VgHXAqDDeuYYZgCufPv0jAHryiGgG4xL888Cs55hSv/ydHwYCJhjT"
    "3PI5aRr5HAR0g/HQMLzhQ4ABAFZU8nO4cMZ1AAAAAElFTkSuQmCC")

imgGotoMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJAP4nK08AAABKUlEQVQoz13Rz0sCQRTA8e+u"
    "C4lll0js0E3skD+wvHbw2N8g9I907h/pliIs+B8YgQgGebVYwUWDTJbVWTOcmQ5ugvMu83jv"
    "w7wZnqUBuIIT7iiT5Ic3Hvl+ZRtOfJ7xcFO8vjhIrxf9y+ci90y3DTsG9VqlVA3TX4TpUrVW"
    "oR7Xd6BcyAk8XvAQFHKU2R+hk1ZK8c4vEedYKZ00blDLIJBkWJNBEgRqaYJub+SQ55Y8Dr2R"
    "6hpAtwa+CCUSiQgHvm6ZYKbcztBB4tAZKlfPDLBBNrzxZC6ZzL2xbGww34ASqtkfW/THqqmE"
    "MoFGo9u+2OAL3dZEJvggQi10QqITahExMQFMWaFtibZX/2vYAzZHnxnQwGeW490Sd4nNIaeR"
    "+0TkkmXGmvgjf7x4ikuV35bbAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# imgResetMapPin
#------------------------------------------------------------------------------
imgResetMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcVFAEtg8B/ogAAAoRJREFUOMt9k0tIVGEU"
    "x3/3zjjKNYMeZBG0EnJjDyczKDAoKCOsFi1Kc9NDiKCBlrVoY0FUVNii1yZqkRFGhS6khS5C"
    "rIkeBGZJUzPjDOQNm/v8pnvntFBDIf3gg+/AOb//Of/Dp7HAyWraMqAdWA9UAD7wHri/WsQE"
    "0BYoXgV0LmpurqtsalobKS+vCpWynIGBz3Zf30fg7GqRXHSBBlqrWlo2VtXXbxDTRAAdqhY3"
    "Nm7Sysqi1rNnrcBlfb7qENYbDQ01Jcui2zQ5mkrRbZqULAujoaEmnBqLeQFFqNB03ZAwpCef"
    "J1co0JPPI2GIputGccqT+QEKbGWakxKG7DQMdM9jp2EgYYgyzUkF9oIAH4byg4MpicVor66m"
    "p66O9upqJBYjPziY8mEIYI6JTffybWhaApFr/rFVT3LJ5J6l8XhNhaYtnsnxbLuQSyYzwJM5"
    "HWy5mWorKpU4vGtFvKhU4kzXt92eSM/X/v4vRKOUggCiUb7293/xRJ5uFZn4B9hw6VObct1E"
    "+7418bwPrS1r4sp1E+fOv9LHx8bSZjb7S8IQM5v9NT42lvZFumeE9brOd7ryvO2ebevXb79+"
    "m/ag687rpGfb/Kas0YdHI8PDaTSNkeHhtA+P94IzA4i6tsXpk9s6RgqUXtx7+ea7A65V4OCJ"
    "HZuv1GolBZXZTOZUGARkMxlHg+ezfYu6li0XLvYKYATFIj8VuAWLhzd6DcA+As4diEgQoCBy"
    "HKw5gFxXs0y/ncpDDyQQ8BwH5+4BeybpD0QkDPnzn7XPXmOtn343OnLVRczRUaAe+AHoAkip"
    "xLTSSsCdvsHs37gciM2KI0AJWNIBLetg/wd4egt6gQngJ6D+Ar5OOqnI2T7MAAAAAElFTkSu"
    "QmCC")

imgResetMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfhBxUUAiI4UjHwAAABiklEQVQoz12Rz0vTYRzHX98f"
    "uPGtDpKMlCSioR6mIwd2CMEugpCjP2BEtzx42DGoqwQd9CyoSHpIRQiCrh1EEXFaFkIj3Whj"
    "hal82ff7PDj1eR4PC3G+r+8X78+Pt0WDHt7mOUminPCN99tHYDXYrYz1d6c6I7dqQe7nynde"
    "b/9xrgKtI08GE70iIqlF7rbdtIr8XbMbJiQTcUGBVQoIEnGS4F71TdTyNL84RdKO5ZkoNCTo"
    "0PcVMWrEUPi+Dq8D6xtFlw6G6MBlo6jXL4HxzMTmeMYs75RFVaFQiOpO2SyDA/A2o7NPU7v3"
    "eg6/5v14vO2MJr788Od218CGNxmZTacEwymZHbYLpcqxonJcKKlFAPuVfTIg7KmtgOmcQD/S"
    "C7mSRa6kl/ICwA0ZeXmk5zerBLzoe6wf3CiPnlMW1qf6dm5o3hm8UyQBkx7hnrjvKIyzH/wH"
    "Zg0g0sYg+RACGEdhLs+vf7Krkp/Bz9PLb2wwAHeQSM7rbbbQBICDpjmW9p7JjwefOeQftQtj"
    "66mo8di9eAAAAABJRU5ErkJggg==")

#------------------------------------------------------------------------------
# imgSetMapPin
#------------------------------------------------------------------------------
imgSetMapPin = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QIbCC4PCgdjqgAAAk1JREFUOMuFk0FIU3Ec"
    "xz/v+ZzydF0kVuihg9Bpaa5hYCiBInaQuoQw2yUiqkOeuohHC6KDEBgjL0l4GIjDQJGdXCEi"
    "TDIvhS4Wbm6QT2Tvub033nv/DmtgpesHv8uP7+/z+/5+8JOoEVlJagHCQAfQCJjAFjDbKoQG"
    "INVovghMNg8N+Zv6+i7XNTR4HcvSj1dXvxnLy9vAeKsQOaWGgZB3ePiqt6urU2gaApDBe667"
    "+5pUX6/oi4sh4JV8VrcDHWow2O7qOlFN4346TVTTcHUdNRhsdyprcSagDI2SLKvCcVjI58kV"
    "Cizk8wjHQZJltVy5ydkACwxL046E49CvqsilEv2qinAcLE07ssCoCTBhPZ9IpIXHQ9jnY8Hv"
    "J+zzITwe8olE2oT1/wHmc8lkpmgYBeE4VLNoGIVcMpkxYf5UQO9MLtI7kxvtEeKgJERsNx7f"
    "QVFwbRsUhd14fKckRKxHiINTAWXTDJRNc6z79fdRU4jofiq1p2Wzh8Jx0LLZw/1Uas8UIlrV"
    "S/7JzxFJlgMnIY/C/sCb2e2kcN2pifFOt6Wt7dn1wcGO9ZWVLS2TeXkX5qpapWjogaePbwS+"
    "FkC3K8W1Axi44w/E3n0as+BmNpN54tg22UzmWIIPJ4cpRd1IPn+x9Mcal0K3AvHIUlKS5al7"
    "oL+FOmHbWFD3APRa/4M3NLfpHZ1LNg1MhKu1adg4GhkR07Dxt/6fXyj92NzCtT/aa1PvgWZA"
    "FYBwXURFcgEo/k5bqmFGAVqA8w9h+Arc/gKxCCwBB8BPwPoFY48c81fKVnwAAAAASUVORK5C"
    "YII=")

imgSetMapPinDisabled = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfdAhsJJC/KRMHfAAABaElEQVQoz12RvUsCcRzGP5dH"
    "ilhBgWQUKEQthtTNDkIEQUE1W3PQ4hg0twRBa2sFQS9g9B8UhQinVDRUloKHNpRIeldX/e7X"
    "0Ate3/F5PjwPfB8F1432sEAMH29csJV/BsVlh1iNj2jD3g67od+cXrGSr3pagdBiYiI6Znot"
    "bG9/X0Ap8Xje5mqIRQdNipxRxCQ6SAzUVl/6FL9DgXcsBlD80geuBKdZrwuC2AQR1OtO8z+Q"
    "yZZUhphkCJVsycn8A+ThpWG+CAQC8+XSkIctwPrmevL6yUmf3KkIVE7unPT1Uwtga3ZqNSn2"
    "iuVKTVCpFctiD0Bd3lQ0gAbz2nZqjoN9PTLerZed/YIJoDa1Re2ZD6DClLabkglj6RPDVI6/"
    "k9WmvvZTMq1t6W0b942IRyA9Dw33SszkZvX4AkA4uyzD2V/975PGhXOa2yGAHyRALxYWn39j"
    "VY6qeTx0EWyXt51W2qwieEV8Ab3lml4I+uMeAAAAAElFTkSuQmCC")

#------------------------------------------------------------------------------
# Joggin controls X Y Z Home
#------------------------------------------------------------------------------
imgHomeX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXAxY1Jk8eHAAAAylJREFUWMPtVk1IFGEY"
    "fr6f2fnZnVnXcd1VNgTB8OAliLyWohTRQRMvQYcl1C79XDpEnSKwLgpdu9UhxDJwwIsdgghP"
    "gijYxUKEToFBQaIz83b5dhtnZy3KrMM+MMy83/PN9z7zve9878twAGZm5xgApswUgF31bADY"
    "GR0ZCvGH4AeRoyNDBKBy+QCkEuIDEDgEyJ9NUCIwMzsXKCFQzsPDEMB/daISEgLYUzsQHKmA"
    "6G4cpoDfgkrOBo4GGxsbZzY3N7v+iXPP8265rvu1paXl0/Ly8un+/n7inFNfXx/9dedTU1PP"
    "pJQkpaRUKkX5fJ46OztJSkkDAwNJAl5EDi0CMBzjL8T4l3Wdl8tlMgyDNE0jXddJSkmGYZCu"
    "66TrOg0ODiYJaAPwOeLgI4AmxZkAPkS4LwCOJTrv7e0l0zQpnU6TaZpkGAal02myLKt67+7u"
    "rheCsdhXPlbj92LjN2veXF9fP9HT00O2bZPjOGRZFuVyueqzbduUzWYpk8mQbdtUKpVodXX1"
    "XGwZBuB1zNk4gJ2IvVxTR5aWlk6VSiVyHIccx6Hm5mZqamoiy7LIdV3KZrNVLpfLVfmOjg7y"
    "PO9KTMRxAN9iIipXAOBkXDHy+Tz5vg/GGBhjCIIAjDEIIbC7uwspf9QsIkIYhlU+DENsb2/H"
    "T8bbAO4nhOgRgGs1taBcLsM0TQghIISApmngnL/zPG98YWFhzPO88/Pz81eFEOCcw7KsqoCJ"
    "iYnFBEeLdXLked3MX1lZGS4UCuS6LhWLRWpra6tJtMp4a2srFYtFWltbu1hnuTd1QvA20uD8"
    "CEEF7e3tJIRAEAQQQmBra2sfXygUiHMOIoKmaTW8wiUATyO2H+s7LgN4kliOpZQgIkgpsbe3"
    "V7OyrusQQsAwDARBYjXOAHgYsXcAnFX3Ch6oebUCgiCAlBKcc6RSqdrmgfNqogqR2JHdAdAe"
    "sScBvFJOowfW3UQBmUwGjDFwzvdlfvQPME0Tvu/Dsqw43RU7YN5HHE+qk7CCG2r+fgFhGELT"
    "NDDGoOt6YgjCMIRpmkkhmlYNawXXI1u/o2xEOuzpRq/RQAMN/Bf4DvjRHVH1Ue8KAAAAAElF"
    "TkSuQmCC")

imgHomeY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXAxc72OwCWgAAAsNJREFUWMPtVk1P1FAU"
    "Pa/vdfoxbYehzAfjJCQkJizYuJGtQCAxrlBCdMGGGMU/4N9gp3t1YcQEE2rY+ANYkRBIcINK"
    "WIqyMTEybY+bzqRTOriZkc2c5KavPff2nt53X24FBoB377dEspQACsk6TExfWV760/bVBiFg"
    "ZXmJyTUE8DuxVpKvK+dABKRFJGhXhEkVBi8gI4QpIfyvAjLViBK7HqSac4jB4/j4ePbk5OTm"
    "tSQPguC57/u/xsbGzvb29u7Mz89T0zTOzc2xV8xmcjza9hWAk+IdAN8yPpt5L9rY2HirlKJS"
    "ioVCgZVKhZOTk1RKcWFhoaeAKoCzTIIXKf5lhvuexHRhbW2NpmlS13UahkGlFE3TpGEYNAyD"
    "i4uLvKpyjzJJYgCzicUZ7mE2eGZmhpZlsVgs0rIsmqbJYrFI27Y716mpKf5r+z5kEn1JLP1s"
    "Kx1wdHR0a3p6mq7r0vM82rbNcrncWbuuy1KpRMdx6Loum80mDw4O7vYSUAfwM5MwbT8SHwDA"
    "7u7u7WazSc/z6HkeR0dHOTIyQtu26fs+S6VShyuXyx1+YmKCQRA8Tg+JNFYBvOohcBXAm/ZN"
    "pVJhGIYQQkAIgSiKIISAlBIXFxdQSnUCSSKO4w4fxzHOz89F3ix4DeBj3ulKJ0+aDpZlQUoJ"
    "KSV0XYemaZ+DIHi6s7PzJAiCe9vb28+klNA0DbZtdwSsr69/uqoXbuSUv5HnuL+/f79Wq9H3"
    "fdbrdY6Pj19qtPbzarXKer3Ow8PDB9k5nYfsi3r6NhoNSikRRRGklDg9Pe3yrdVq1DQNJKHr"
    "ehffl3GslAJJKKXQarUu8YZhQEoJ0zQRRd3TWPVDQBRF0HUdAFAoFC7x7a9v73/ff0gcx4EQ"
    "ApqmdXV++gRYloUwDGHbdv8FxHEMXdchhIBhGLlbEMcxLMvK3aIhhhhiiGvFXwZBEFdulUGi"
    "AAAAAElFTkSuQmCC")
    
imgHomeZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXAxgWGqtC4AAAAshJREFUWMPtVs9rE0EU"
    "/ubXzsympm22adIaKBSEHgrixeJNW1oUQaiWgich+KP6Bwj+AYK33v0LVAQPXcnFo2C9FEpL"
    "q4ccSulJoSBCsdnd52U3bjZpLWrsJR885rFvZ75v3ns7swxdwKvXb1jsCgBO7AexqcWF+R/J"
    "u7wbAhYX5ikeAwAHsTVivhbOrghIi4iRZITiLHRfQEYIpYTQfxWQyUYY2+kg1Zw9dB/1ev3K"
    "zs7OuVMh933/sed534eGhr6ura1dnpmZIc45TU9P0+/m0gnsWCwvL7+QUpKUkhzHoWKxSOPj"
    "4ySlpNnZ2e4KqFarZIwhpRRprUlKScYY0lqT1prm5ub+WkBw1MSpqSmy1lIulyNrLRljKJfL"
    "keu6zXFiYqJNQPYgYhm7miF9lF1ge3v7wuTkJG1tbUEpBSKCMQaO44CIIISAlBKcc+zt7aFS"
    "qdDGxsa1k/TSeQDfUrt/ln1hdXX1YqVSoXw+T/l8ngqFAg0MDJDruuR5HvX39zdjg4ODzfjY"
    "2Bj5vn83fUlkcRbAx3gEgJcAbmd7oFgsUhAEYIyBMYYwDMEYgxACh4eHkFL+qi0RoihqxqMo"
    "wv7+Put0F5wB8DZF/h7AnU4NWK1WYa2FEAJCCCilwDn/5Pv+g1qtdt/3/esrKysPhRDgnMN1"
    "3aaApaWld512LgHUUmn/DKBwXJ3W19dvlkol8jyPyuUyjYyMtAlNng8PD1O5XKbNzc1b2Xs6"
    "wXMA92L/C4BLAOq/a5bR0VESQiAMQwghsLu727JuqVQizjmICEqplni6BE9S5AcAbpyEHACk"
    "lCAiSCnRaDTa4lprCCFgjEEYhm0pT/A05VsAH47ga2vcMAyhlAIAOI7TNiHZfVL/o86BP76r"
    "+/r6wBgD57yl89NfgLUWQRDAdV388z+iKIqglAJjDFrrjiWIogjW2o4l6qGHHno4VfwEhNoL"
    "GYRVUnMAAAAASUVORK5CYII=")

imgHome = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXAxgs3KebUgAAAoZJREFUWMPtVjFLHFEQ"
    "/t7MvN19e4KFHlhYCQGLA0kT20RRCLExHKYXkpg/EPBXWNnlBwQxsXDB5n6AaQQRNI2FxWET"
    "EDSY5G73TQpvjxPN3XIxmuK+Zou3O/PtfPPNG4M+sbG5ZQAQAAFgAfwEoAAiALpUXbwsEof6"
    "JbBUXVQAHkADwI9Wcm4d26Jx+iaQk+ggkkMA/LoXArdUowngEkB6rwQ6SKCVPMNDodWcA9wP"
    "jo+Pn52cnDx6kORJkrwfGRn5Pjo6+m1vb+/p7OysEpHOzMzoP0++trb2UURURDQIAi2Xyzox"
    "MaEionNzc9qlQfmvbbi8vKyrq6uvjDFgZnjvcXFxgXq9DmaGMV1N4Dc2t/q3/vT0tDrntFQq"
    "qXNOoyjSUqmkcRy3n5OTk9rLpp0kqIiHj46OHlcqFT08PIS1FqqKKIoQBAFUFcwMEQERoV6v"
    "Y3x8XA8ODp53GVi6sbllAaDn0Njd3X1SrVa/nJ+fXw16EXjv0Wg04JxDmqZQvfrpXALvPYaH"
    "h7G+vv56YWHhwx8qQQCingTK5bKmaQpjDIwxyLIMuf6NRgMi0n5XVeG9R2d/nJ2dmS4TM6QC"
    "TQfnHJgZzAxrLYjoa5Ikb3d2dt4kSfJie3v7HTODiBDHcZvAyspKrUd4X2hu7+/vv5yfn/+U"
    "pimstTDG4PT09Nq3Y2NjmleIiFCr1aqVSuVTjzuDC1liamrqMzMjjmMQ0bWyd5YfAIgI1lp0"
    "S97RkGlhT4oIVBUigmazeeM8DEMwM6IoQpb1vo3z61uKEsiyDNZebVpBENxcLIigqm3973wh"
    "GRoagjGmqwS5LeM4vnsC3vt2A4ZheKsE3ns4526VaIABBhjgv8Vv9Cb4MBH+vxoAAAAASUVO"
    "RK5CYII=")
        
imgHomeXY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXAxUIVQoBzgAAA7ZJREFUWMPtlj1oHEcU"
    "x387M3v7cbd3OkmHFEUgR+CgQikCwSoTS0gQggsZoSZxc4RYxrh14SJJmS8QmLSpYxw7dtAa"
    "NWoCIagSCAWURiZCJILgRARMbEu3+9ysjr3V7Ul2bKnJHx47b9/MvP/MezNvLDrg5q07FmAl"
    "agHYTdou8Hh2ZjrmP0J1Ms7OTAuwLw3AJEQagOYFQB3WYXZmWhIiUSJx4rzd2O9ThAU4n7Gf"
    "y9jvqqMyTUjEwF6yA1GbbpeBf1L610BX0vaA6ynbQ+CKepbtSkjQgcA2cDWlvwJ8lbSvAadS"
    "to+BreeKW5KcebCAHzNbfRF4nNJXXlQO5eF14FGGxL5EwFscA67lELj+TLNsbGyc3dzcPP0c"
    "BM7kEHj7yDOEYXi1p6fnYW9v74OVlZV3JiYmRCkl4+PjcoThP+UQ+Dl1ueVjfn7+hjFGjDFS"
    "KBSkVqvJ8PCwGGNkcnJSOiSoBt7PON3L6Bc6Oq/X6+K6rti2LY7jiDFGXNcVx3HEcRyZmprK"
    "JRAEQQD8nnL2CJjIJOUfQKntBGNjY+J5nhSLRfE8T1zXlWKxKL7vN78jIyOdQvBZZrWfJP8/"
    "zfz/vGXU+vr6m6OjoxIEgZTLZfF9X6rVarMdBIFUKhUplUoSBIEMDg7K2trauxnnp4EnKSf3"
    "k8K1X8Dup2xPkv6wvLx8ZnBwUMrlspTLZenu7pauri7xfV96enqkUqk0bdVqtWkfGhqSMAw/"
    "TBG4l16lUurczVt3/A614J4FUKvVpNFoYFkWlmURRRGWZaG1Znd3F2NMcwYRIY7jpj2OY3Z2"
    "dqwON6YDqNmZ6X9zq2G9XsfzPLTWaK2xbRul1K9hGF5cXFz8KAzD9xYWFi5prVFK4ft+k8Dc"
    "3NzSIQcqzqkbzXsbgNXV1fNTU1O3G40Gtm1jWRbb29stK+vv75f9HVJKsbS0NDM6Onr7kJqh"
    "gTjv8dLiYGBgQLTWRFGE1pqtra0We19fnyilEBFs2z5gB74DZlL6b8AbSeklOXq/AENtHyTG"
    "GEQEYwx7e3sH2DqOg9Ya13WJora7ehn4K6WfAr5I6V+mnQMPWghEUYQxBqUUhULhYMIo1UxU"
    "rdtW0z+BK5l/c8DZRC5mbK0PklKphGVZKKVaMj99AjzPo9Fo4Pt+Xui/BX7IhPmbRNIhuwvc"
    "aCEQx3EzAR3HaRuCOI7xPK9tiDKr3knpryWyj7+BSy/7PXAhpxoK8AHHhLCN8wWOEa+2ITCQ"
    "ew+8JEinu0dxwvifwIkTOHE8BcFpaECgbFe2AAAAAElFTkSuQmCC")
    
imgPX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCCodbFwg+AAAAVJJREFUWMPtmL1OwzAQ"
    "x39mgQVUJD42XgGeASQQK+UZ4G1gh52PjmXvjsQGD4DoVCQ2li4NiyOdTlTE6eFLICdFse7+"
    "8v3iiy3b0FlnvhZ+uf9i0VwhE1ztfCEjXK2cITNcct7gAJeUOzjBVc6/5LyKFE0ucSUOr0lS"
    "mSV4la4qpPwHb2PHBfAObCntdvSXmpsfEj1Zf9g6MBYAQxV/ELEx0KuQUH5QyjPXDoCZEJ5F"
    "/7nwzYD9hFExh7wUok/gOL5L30WN0j1aQq4AL2rEyvYzsFxzApiO5B4wVcIpsGswu81KPVLC"
    "kdHyYwLYnyM+yQz3LeAGMBGCD9GexLgbHMC9ELwBO2p9vPOEO1Wio+g/VP6+B9ymWgquVfwq"
    "sdSF9awdqNKuqfgq8Co0gxxw/2671egNqzlcE84kYWHBXzp2tuLg3oqrj1ZcHpldv3XWmbd9"
    "AeCSD7Csem9UAAAAAElFTkSuQmCC")

imgNX = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCCoIAYHEEwAAAVBJREFUWMPtmDtOw0AQ"
    "hj/SQBMEEo8uV4AzgASiJZwBbkP6pCchZdKnR6KDAyBSJRIdTZoszToajZSH7X14hX/JsjXj"
    "+fXZs7bXC7VqxdVeiVrjyMcLoHF8sU4BjaeOODE0nodNKTMTaGwXMjKBH8CVGp7ggrXYBH47"
    "5DKKDrfJrBJw68ZgEbj3LXB962uAOXCm8uc2np3zsqmtebf5DhdwDExFzUjlxyI3BY5CwmW6"
    "Bpai9tHGn0RsCVy5gnsrMBQ6ov4XuLP7LPYc485JHQCf6o5lxx/AvivAMroEFspvAVy4fDDK"
    "aqL8Jtu+FiEh22v87qsAeQLMRP2POJ7ZfFTIV1H3DbTU+3Gwy8zFF+SDqrm18RsVb8eAPFWf"
    "sp7Kd/O02gfkULX2UOWbwJc4Z5j8dCuJCWslIBuhW/ZvfzuT+HFPYukjicWjoMtvtWrF1h+y"
    "zw+w+XZJcwAAAABJRU5ErkJggg==")

imgPY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCCotSoUQVAAAARVJREFUWMPtl00OgjAQ"
    "hedxAHZ05Xk4gng3PYHgRfQUupRD4KYkZKJS6OtPlElIoG3mfWXamRbCs0F9g+EUgeBo/hEQ"
    "jqKBwHDeOogA56WFSHCr9RARbpUmIsMt1kUCuEXaSATnrI+EcE4MSAw3y4EM4L6yFES43opQ"
    "c2tBgruKiAlRAEAA7BWc72ThEmIGHPM493bmc8+N7G9g72J2mQQzD7JPQfD5C+y7RpC7y0BO"
    "3Gx/m/2ntZO19BCRUvWXtn0cc44NWNlKMgIcVf9p0ve046NboypBbdtr1b5PGepuAnIXkZ0K"
    "bZt6LRoVav1e5bBhDh+Kf5PTrr4ouC63tGMUoIl6w19xEKD4LiRz2wB/HnAzX3sBnppmeggG"
    "FSwAAAAASUVORK5CYII=")

imgNY = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCQM38mMc8gAAAR5JREFUWMPtmE0OwiAQ"
    "hR89QHftyvP0CNa76QlsPYjxFLqshxg3NCETowIPik0nIWmAPL4U5geAzTb7TxsAiG0PALUa"
    "r23/POecG7AB8HQAjmr85IxNdn526x0IAdDZ/k7175fc6tEBuQPYqa0dlj6Lrdpq/d2U4DAH"
    "taVz60vy6ouCG0sLO60CbFnChggpKXSr0jPCBrh6wNWYKC/Npmd+FGOGJi894ykWC+mtZwLE"
    "QiGD9KpAMXieyRtTTzzbN5ti9CqSR36Ci6oJK2LY0HZlFKyGcL7e6YX+OcP0YrYZZhzMAhea"
    "SbLB+QRbWQLONxtIbrgU6Yp+FwpJ+pILLkVVQl8vpraTHGuxi0/6OowLtqRcg/UCIKn0Uz19"
    "0LRfgvlqbILUMHsAAAAASUVORK5CYII=")

imgPZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCSMJpoYl+wAAASdJREFUaN7tmC1OxUAU"
    "Rs/XhGCeBYGEBSDRJOwGw3ZQLOHtAUVAwgYwmAcOQQJJMYhJQ3h97TfTm3BPUlFzvzN30vmp"
    "8NEP3uUoqkpytvqqKGfJUGW52TlqIDcrS43kJuepodykTDWW2zlXC8jtlK2F5Ebna0G5UQ5a"
    "WG6rhwLI/enSGeU2PyHWtbUzyd0DhzU2ABkENwO5uYPVmCl2yDmPc7+OfNvzYK7Xu79i9zYp"
    "5zroPgVpThfcd40qd5fevHC76yVJkiRJkgSl1Q/MyVndf52ZU+C9OJiuI8kdAM+F3BOwiiK3"
    "B9wWcm/ASaTuXRdyX8BFJLnLwSX8KpLcOfBZyN1EkjsGXgu5O2A/itwKeCzkXoCjSN1bF3If"
    "wFludUmSJEmSNOUb5FNZM86MbmQAAAAASUVORK5CYII=")

imgNZ = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCSMWK44oDgAAAS9JREFUaN7tmDFOxDAQ"
    "Rd9EQjTbbrMlHICSGonb0HCdrTjC3oEKRAkXoKFA0FEggTQ0FBZFwJmx1xL/SSnz58mxPXZA"
    "CCGEiGCBd71Hnek/fpUT4O17hB3YjSS3Bh4LuQdgNYrcAXBdyL0CxyON3raQ+wTOR5K7KOQc"
    "uBxJ7gz4KOSuRpI7Al4KuRvgcBS5FXBfyD0Bm5FGb1fIvQOnanVCCCGEEELMHE59H3n2x7Cs"
    "U3h1nlWGRSWr8yxw57Akudm8KXAhqpmTd5l5Xvn8xnMkb0pakXNy60j4lLht/OQ2Kjc30T2Y"
    "t3TkLHMVZ2OZ+2AXuaWdpJtczWbr+5Cr7QbeW65Fu0qVW9r0vZdci1NJer1ef1gX18o+fKbX"
    "sYQJ7y1rWNKq9Fb5WYIt7i4AfAGuvF0lxKaSFAAAAABJRU5ErkJggg==")

imgSpindleOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCRcsVqgCSwAAAqtJREFUaN7tmb9rFFEQ"
    "xz930dxtjBJBVFCSIEYJFjaCRFAEW6N/hYUmAQtBsLHUXgvBqMQf2FqooMV5/kotEqKNoIUa"
    "9M5U8cedl7XYWXxZdveyd7PykPeFx96P2Znvzps3894sODg4pKKQUb6kZLcB+NoEh4GzwKYu"
    "yS0D14DH2t4eBT7Lk2cZy8BPufpACzixWqNrcg6hH8Al4DUwBpzM01gnHpwGinJ/P3A/qweL"
    "OT6QD9RlagGWgMWsSoo5Z4iDwGFgPTAO7M+qJO8YHANmJDSGgK2GR60gCDAoI5pq1Kf4I/BA"
    "gfAs8Covb2wHrnaQC8PxDDiSZ6kLSZ4G9sbE2zpjBc9KHgyxANwAKv+ihvcCfcbYDDw3PFUH"
    "DkVkvE4MdbpIGjKSYvkR8Bb4bsuuqN/w4B1gl23btpDgbWBEU3GPYkwWgOvixfNADfhkkxc3"
    "ADuBW7JI9tk2zSMyxb6NBD3gSiTNqBAsKsbynpjtljUEG8A74/tX2Zhas4pbwDepGF+kXj90"
    "h+aMidpEn81kB9x8OViwSDrdrTuoNwN6lMkVpAZvkbPvbzdfDg4O/wnKwCmCxk8NaMq1AkzI"
    "/9HzSDjey7mZFJmuMAzMkd5WmxO5OOM+MJUXwXKEXNh36QV2A3cjJMsJBBf425pTJTjJyuZj"
    "XGl7achMxBgPm0rn8iBYNZSMJ8gcN2QqMcYPyHUR2KhNsG4oGUyQGTJkagnG78nnC9oEm4aS"
    "UkqchjLNBOOjsrNZIngVYZ0HIXgt5gOXNQk+NZQcTZA5Zsg8STG+jaAl/EtSkgrBKUNJNWEV"
    "vzBkJtt456L8NqNF0APmDUU3CfqAa1nZD/RFrtyG4ICETUuzkuwA3rSpJPMit5oVeibm/q7h"
    "yfRVxQNNuVYlDLwMSbgEfNAm6JCEP534Lb2mn4fbAAAAAElFTkSuQmCC")

imgSpindleOff = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCRc4THLWNgAAAnFJREFUaN7tmctqFEEU"
    "hr+ZaDITo7gQ40KSEIwigm4EySJBcB18CheaCbhzmYdwI3jDG3kBFZLFEMxlLXGIblx6QacV"
    "A1GZMWkXOQ0nbfdMuq0uS6gfiu6e+afq71PnnKo6Ax4eHh1RysjvMzRuCwhNCxwBbgBH/lLc"
    "NnAXWDBt7dPAB3nzLG0b+CnXENgCrux10H0Fu9AP4CawBowDV4scLI8F7wBl+f0A8DSrBcsF"
    "vlAIBDK1AJvA16ydlAvOEBPAReAgMAVcyNpJ0T44DjwQ1xgGjimLOiEQYEhaPNUYn+J3wDMD"
    "gleBl0VZ4zhwO0cujNoL4FKRS10k8jpwLsHfDqgIXpU8GOEjcB+o21jDe4F+1Y4CS8pSATAZ"
    "41TzDJQ3SFrS0nx5HngDfHdlVzSgLPgEOOnati0S+BgYM9lxj0GfLAH3xIqzQBN475IVDwEn"
    "gEcSJOddm+YxmeLQRYFV4FYszRgRWDboy2cStlvOCGwBb9XzZ9mYOhPFW8AXWTE+yXr93B+a"
    "MyZqjX6XxR728+XhQJDk3a17GC8G9BgWV5I1eFDOvr/8fHl4ePynqADX2Cn0NIG2XOvAtHwf"
    "P390a1l4HTECNLp00hCedYGVmLioztILnALmYiIrCQN3QiZLJaHG7mJj0lK2ojjTtgUuqg6m"
    "UjiXFaduW2CgOhhK4QwrTtO2D7YVsa+Dn0acdtEC43u3DXU/mCJQf/4txU+TWi5eXGBD3Z9N"
    "EaiL569sJ+gZZerFlLdeVpya7SCpAuuqk4fs1P32s7v+FwrPeh4EGAVed3HkdeHxLwRGlqzJ"
    "NAcSrYE8z/Dnfx7WBXrsFb8B/jIxn8V55CYAAAAASUVORK5CYII=")

imgCoolantOn = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCRgTZ1YzuQAACCVJREFUaN7tWHtMlNkV"
    "/937zVMchpmCMDzGBf1kYAQUB9GVVLQZZdN1NaVj44v4RxsWWUxjStcYu1NS3WJsfG3rK5sQ"
    "peymJKbYP9ZuUcFuS23FR7oI2gCOgUETGYEZmQcz893+0W/WAUEWHKx/cJKbO3DPPef3nXvu"
    "eVwO0yMCgNTW1ka73e4darX6AGPsVx6P56eJiYkVBoPhe6tWrZpTUFDQdvPmTYb/A5ELFy7M"
    "W7Zs2e9iY2M9hBBGCGGU0m9GSkqKJz8//3BtbW30a0d35swZaUFBwWG1Ws0IIUytVvszMjI6"
    "Vq5c+Q+e5++q1WqBUsri4uKChYWFH1mtVjpdXZLpbLp3797bdrt9u8vlQnJysluv11cXFxfX"
    "GQyG/itXrnyntbW1tLu7++d2u5329fWVOByOiwD+DWDUcTPGCCEk4i5A169fX6VQKASZTMZM"
    "JtMnq1evlgCgId88f/58lMlk+lQqlTKVShW0WCx7xDWMAUgZY+SlyqaKzmq14tmzZ7zP5yPR"
    "0dGunJycS9euXQsCYBaLhQJASUmJm+f5SyqVyjc8PEz7+/sXhdZGOTIhwmQWnDLAwsJCWVRU"
    "lBYAfD6f68GDBzYApLS01DI4OHigvLx8HQDIZDI7x3FeAHA6ndJpH9dUNzx58oSEjosxxjwe"
    "j1BdXZ18/fr1yqampr23b9+uqKmpUUulUjD23DiZmZkvWKqiokIecYBxcXEs7IioUqmkIyMj"
    "yqGhocRgMAifz6f3eDyyMD8bL4bOnAXH+BBRKpVULn9uiGAwyPx+P6OUskkCPbRabXAywJJI"
    "XGufz/f8i+mk3xwOXBgbeiJqwVelqqoqYUaP+HXQLMBZgLMAZxJgKNW9UQDFXPwNwEAgwN44"
    "CxJCQAgBx3FUpVJx32ZLe3s7eW0AvV4vAQBBEITJjpgQAgCvr9w6d+7cxp6engzGGCilVCqV"
    "kmAw+IJ1BEEghBAwxjAwMLA8EAi8N9VKZqoAyfbt2zd1dHRYbTZbMqUUOp3u9po1a4ZkMtkL"
    "zGlpaU8TExO/JoTg4cOHi9ra2n65e/fud0JtQcQBnjp1av6tW7fKbTabQSKRID09/Q9FRUX7"
    "9+7dax+Pf9++ff9Zu3btfp7nvwCArq6u7KampvePHz8eOxMWJA0NDVt6enrWAsDChQuby8rK"
    "fnPs2LHbYg1IwupBMjIyQgDg6NGjXxUVFR1YsGDBdQDo7e19p7Gx0TJZiTVlOnz48LysrKwW"
    "QghLSEhwFRcXbxE/jtbV1fH5+fmHtFqtlxDC9Hr98Lp16z5ubGzUh3iKi4vfj4+P91NK2ZIl"
    "S/4c6WaelJWVrUlOTh4mhLDc3Nzmuro6jdhezlu6dOlnc+bMYWJ3xgghLDo6WsjNzT1jtVrn"
    "AiA1NTUJRqPxOqWUJSUl9VVWVuZG8ojZ4ODggoGBAZlMJmNarfZf27ZtG2SMoaGhodhms/3I"
    "4/GM6j1cLhd59OhRyf379zcAwMjIiCMhIeEOx3FwOp3a9vb25IgBtFqtVKvVGhhjEgCC1+vt"
    "BMBOnDghs9vtK51OJx2T/gAADodD4Xa7V1utVq60tDSgUql6KKVCIBAgjLGoiF4Sr9cbYP97"
    "p0AgEAiKbaSCUhorCMILnRtjDMFgEBzHqYxGIw31KoQQGvE4WFVVJTx9+rSd47ggY4zK5fJU"
    "ADCbzUNRUVFfS6XjJwm5XA6O49o2b97sr6+vpwMDA4mCIEAikTBBEJ5F1IIJCQkPY2JifH6/"
    "n7hcrgLxkiAvL++L1NTUDjGdjUpver2+NS8v70sAuHv3rqa3tzcnEAggJibmqclk6o1omDl4"
    "8GBcdnZ2C8dxTKfTPdu0adMWMRtQi8Wy3WAwtKrV6qBUKmUajSZoNBpbSkpKfhgKM2azeadW"
    "q/VwHMeWL1/eWFNTExPpqofbsGHDL6KjowVKKeN5/vKRI0dyQ2lr//796Rs3bvxxYWHhR1u3"
    "bv3JoUOH0gFwAKjVai3keb6FUspiY2MDFotl94wUymfPnk01Go2XOY5jEomEZWVlXaiqqloV"
    "/uw2duzateu7ixcv/pJSyjiOY9nZ2Q0nT56cN5VcPKXqYufOnT9oaWmp7uzs5Cml4Hm+LSkp"
    "qW7FihWX5s+f33Pjxg2XTqdTud3ut1pbW7/f19e3tbOz08AYQ2pqaqvZbP7w9OnTzeKLQuQB"
    "AiAWi2XbnTt3Puzu7l7MGMPcuXOZVqt9pNFoHiuVSofL5YoZHBxMdjgc8V6vlxJCkJaWdiMz"
    "M/Pjixcv/mkq4KZFTU1NksrKyndNJtMf4+Pj3RzHjXo8Dz2mSyQSlpKS4s7JyTm3Z8+egmlX"
    "79PZVF9fzw0NDakvX75c1NXVZR4eHl7y+PHjGKfTCY1GA51ON6RQKP6ZkZHRaDab/7Jjxw7X"
    "OA9HszRLs/Q6SQFgF4CrAPoB+MX5KoBycX1UxRU2bABk4xXCYeOV6C0AbWMEjh1tIt94yhmA"
    "ipkCqBgDrg7AItEi6QA+HwNSMQHAxwCiZgLgB2FC/jpBoP97GE/5OMq/Eud9MwGwOUzIhgl4"
    "NobxXB1H+dviPABAE2mAjjAh+gl45ofx9E+gvEH8/etIA/SHCZG/xE9DPP4JlGcACAAYBpDw"
    "JloQAD4V//5tJAFeCxPy7gQ874XxNL1EeRIANwCfGJIiArAiTEjzBLf4b2E8H0xinWrxf+ci"
    "BVAJoD1M0HkAvPhiygP4fdha+wRxMJxiRLcJRjKTpAHomCSTtIt83+aG/myc/a9MSvH4mkUL"
    "+MW5WXQD5RSCsBzAw0gDnKWJ6L8755p04l4IxwAAAABJRU5ErkJggg==")

imgCoolantOff = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QcXCRgfbuB/kgAAB+lJREFUaN7tWH1Mk9sZ"
    "/53ztqUV29IOhPJRL+grhQooFtFJJrpUudkcZqwuKhL/2MJFxCwm7BrjbkemNxoXv27mV5YQ"
    "ZdybkZjh/rjuDhTdB3MTxUwEXQAxUDSR8tFCP2j7nv2x9loQxLKC9w+e5IS3nN857+99nuc8"
    "H4fD7IQAIDU1NQqHw7FHqVQeZYz9yul0/iw+Pr5Cp9N9d8OGDYvy8vLa7t+/z/AehFy7dm3J"
    "mjVrfhMdHe0khDBCCKOUfj2SkpKcubm5J2tqahTzzu7SpUvivLy8k0qlkhFCmFKp9KSlpXWs"
    "X7/+HzzPP1YqlQKllMXExPjy8/M/MZvNdLbvEs1m0ZMnT75tsViK7XY7EhMTHVqt9nhRUVGt"
    "TqcbuHnz5rdaWlpKu7u7f26xWGh/f3+J1Wq9DuDfACaYmzFGCCFhdwG6devWKqlUKkgkEmYw"
    "GD7buHGjCAAN+ObVq1cjDQbDb8ViMZPL5T6TyXTQP4dJBCljjLz1ZaGyM5vNGB0d5d1uN1Eo"
    "FPasrKwbd+7c8QFgJpOJAkBJSYmD5/kbcrncPTY2RgcGBlYE5iY4MiHCTBoMmWB+fr4kMjJS"
    "DQBut9v+7NmzHgCktLTUNDw8fLS8vHwLAEgkEgvHcS4AsNls4lmbK9QFr169IgFzMcaY0+kU"
    "jh8/nnj37t3KpqamQ62trRXV1dVKsVgMxl4rJz09/Q1NVVRURISdYExMDAsyEZXJZHR8fFw2"
    "MjIS7/P54Ha7tU6nUxLkZ1PF0LnT4CQfIjKZjEZEvFaEz+djHo+HUUrZDIEearXaNxNhUTiO"
    "tdvtfv3FdMZvDiYuTA49YdXg/ytVVVXCnJp4PmSB4ALBBYJzSTCQ6r5RBP25+GuCXq+XfeM0"
    "SAgBIQQcx1G5XM69y5L29nYybwRdLhcBAEEQhJlMTAgBgPkrt65cuVLY29ubxhgDpZSKxWLi"
    "8/ne0I4gCIQQAsYYhoaG1nq93h+EWsmESpAUFxdv7+joMPf09CRSSqHRaFo3bdo0IpFI3gCn"
    "pKQMxsfHPyKE4Pnz5yva2tp+eeDAgQ8DbUHYCV64cGHpgwcPynt6enQikQipqam/LygoOHLo"
    "0CHLVPjDhw//Z/PmzUd4nv8SALq6ujKbmpo+Onv2bPRcaJDU19fv7O3t3QwAy5cvv11WVvbr"
    "M2fOtPprQBJUD5Lx8XECAKdPn/5rQUHB0WXLlt0FgL6+vg8bGhpMM5VYIcvJkyeXZGRkNBNC"
    "WFxcnL2oqGin/+NobW0tn5ube0KtVrsIIUyr1Y5t2bLl04aGBm0AU1RU9FFsbKyHUspWrVr1"
    "p3A386SsrGxTYmLiGCGEZWdn366trVX528slq1ev/nzRokXM350xQghTKBRCdnb2JbPZvBgA"
    "qa6ujtPr9XcppSwhIaG/srIyO5wmZsPDw8uGhoYkEomEqdXqf+3evXuYMYb6+vqinp6eHzud"
    "zgm9h91uJy9evCh5+vTpNgAYHx+3xsXFPeQ4DjabTd3e3p4YNoJms5mq1WodY0wEQHC5XJ0A"
    "2Llz5yQWi2W9zWajk9IfAMBqtUodDsdGs9nMlZaWeuVyeS+lVPB6vYQxFhnWQ+Jyubzsf/cU"
    "8Hq9Pn8bKaWURguC8EbnxhiDz+cDx3FyvV5PA70KIYSGPQ5WVVUJg4OD7RzH+RhjNCIiIhkA"
    "jEbjSGRk5COxeOokERERAY7j2nbs2OGpq6ujQ0ND8YIgQCQSMUEQRsOqwbi4uOdRUVFuj8dD"
    "7HZ7nv+QICcn58vk5OQOfzqbkN60Wm1LTk7OVwDw+PFjVV9fX5bX60VUVNSgwWDoC2uYOXbs"
    "WExmZmYzx3FMo9GMbt++fac/G1CTyVSs0+lalEqlTywWM5VK5dPr9c0lJSU/CoQZo9G4V61W"
    "OzmOY2vXrm2orq6OCnfVw23btu0XCoVCoJQynucbT506lR1IW0eOHEktLCz8SX5+/ie7du36"
    "6YkTJ1IBcACo2WzO53m+mVLKoqOjvSaT6cCcFMqXL19O1uv1jRzHMZFIxDIyMq5VVVVtCL52"
    "mzz27dv3nZUrV35FKWUcx7HMzMz68+fPLwklF4dUXezdu/eHzc3Nxzs7O3lKKXieb0tISKhd"
    "t27djaVLl/beu3fPrtFo5A6H44OWlpbv9ff37+rs7NQxxpCcnNxiNBo/vnjx4m3/jUL4CQIg"
    "JpNp98OHDz/u7u5eyRjD4sWLmVqtfqFSqV7KZDKr3W6PGh4eTrRarbEul4sSQpCSknIvPT39"
    "0+vXr/8xFHKzkqamJlFlZeX3DQbDH2JjYx0cx024PA9cpotEIpaUlOTIysq6cvDgwbxZV++z"
    "WVRXV8eNjIwoGxsbC7q6uoxjY2OrXr58GWWz2aBSqaDRaEakUuk/09LSGoxG45/37Nljn+Li"
    "aEEWZEHmUqQA9gG4BWAAgMf/9xaAcv/8hArrHUYouLfKBwDaZtikzY+bd4LSSeRqAawAIAGQ"
    "CuCLSSSlU7z4re1DKJqaSvYHbfCXaQL734Mw5fNN8HbQBtumwRQGYW7NN0Fr0AbaaTBLgzAD"
    "8+2DniBgxFv8NIDxzDXByRWGLeg5dhqCwf8fmcZPpxqzwk0m2Bb0nDkNwayg50fzHaArglR9"
    "e5qv/lsQZv98HxIZgPagTa4C4P03pDyA3wXNtb+POAgAKQA6ZnDkdj8O74NgQJP7/Wa2+k+r"
    "1f+7wj+P90lwQd5V/gucIZ5WcwNLdwAAAABJRU5ErkJggg==")
